local GameEvent = {}

-- [流程]
----------------------------------------
GameEvent.EV_ON_LOGIN = 10001
GameEvent.EV_ON_LOGIN_SERVER_DONE = 10002
GameEvent.EV_ON_LOGIN_NAME = 10003
GameEvent.EV_ON_RESUME_GAME = "EV_ON_RESUME_GAME"
GameEvent.EV_ON_LOGIN_TIMEOUT = "EV_ON_LOGIN_TIMEOUT"
GameEvent.EV_ON_SDK_LOGIN_SUCCESS = "EV_ON_SDK_LOGIN_SUCCESS"
GameEvent.EV_ON_GET_PALTINFO = "EV_ON_GET_PALTINFO"
GameEvent.EV_ON_LOGIN_DONE = "EV_ON_LOGIN_DONE"
GameEvent.EV_ON_NET_SHOW_CIRCLE = "EV_ON_NET_SHOW_CIRCLE"

GameEvent.EV_ON_SDK_PLATFORM_LOGIN = "EV_ON_SDK_PLATFORM_LOGIN"
GameEvent.EV_ON_SDK_USER_CREATE = "EV_ON_SDK_PLATFORM_LOGIN"
GameEvent.EV_ON_SDK_USER_LOGIN = "EV_ON_SDK_USER_LOGIN"

--GAME STATE
GameEvent.EV_ON_GAME_PAUSE = "EV_ON_GAME_PAUSE"
GameEvent.EV_ON_GAME_RESUME = "EV_ON_GAME_RESUME"
GameEvent.EV_ON_GAME_ONENTER = "EV_ON_GAME_ONENTER"

--mission data
GameEvent.EV_ON_TASK_COMPELETE     	= "EV_ON_TASK_COMPELETE" 	--任务完成
GameEvent.EV_ON_TASK_UPDATE_MAIN     	= "EV_ON_TASK_UPDATE_MAIN" 	--任务完成

--daily mission data
GameEvent.EV_ON_DAILY_TASK_FLUSH = "EV_ON_DAILY_TASK_FLUSH"
GameEvent.EV_ON_DAILY_TASK_ITEM_FLUSH = "EV_ON_DAILY_TASK_ITEM_FLUSH"
GameEvent.EV_ON_DAILY_REGISTER = "EV_ON_DAILY_REGISTER"	-- 七天签到

-- talking data
GameEvent.EV_ON_TALKING_DATA_FIRST_OPEN     = "EV_ON_TALKING_DATA_FIRST_OPEN" 	--0 第一次打开游戏
GameEvent.EV_ON_TALKING_DATA_REGISTER     	= "EV_ON_TALKING_DATA_REGISTER" 	--1 注册
GameEvent.EV_ON_TALKING_DATA_ENTER_LOGIN   	= "EV_ON_TALKING_DATA_ENTER_LOGIN" 	--2 进入登录界面
GameEvent.EV_ON_TALKING_DATA_SELECT_SVR    	= "EV_ON_TALKING_DATA_SELECT_SVR" 	--3 完成选服步骤
GameEvent.EV_ON_TALKING_DATA_ENTER_GAME    	= "EV_ON_TALKING_DATA_ENTER_GAME" 	--4 进入游戏
GameEvent.EV_ON_TALKING_DATA_GUIDE_OUT    	= "EV_ON_TALKING_DATA_GUIDE_OUT" 	--5 完成开场引导对话，点击出城
GameEvent.EV_ON_TALKING_DATA_NANYANG_1  	= "EV_ON_TALKING_DATA_NANYANG_1" 	--6 完成南阳第一关战斗
GameEvent.EV_ON_TALKING_DATA_NANYANG_2     	= "EV_ON_TALKING_DATA_NANYANG_2" 	--7 完成南阳第二关战斗
GameEvent.EV_ON_TALKING_DATA_NANYANG_3     	= "EV_ON_TALKING_DATA_NANYANG_3" 	--8 完成南阳第三关战斗
GameEvent.EV_ON_TALKING_DATA_NANYANG_END   	= "EV_ON_TALKING_DATA_NANYANG_END" 	--9 完成第一章南阳
GameEvent.EV_ON_TALKING_DATA_PVP_END     	= "EV_ON_TALKING_DATA_PVP_END" 		--10 完成第一场PVP

GameEvent.EV_ON_PANEL_OPEN = "EV_ON_PANEL_OPEN"--打开panel
GameEvent.EV_ON_PANEL_CLOSE = "EV_ON_PANEL_CLOSE"--顶层界面发生变化才需要发消息
--city
GameEvent.EV_ON_CITY_BUILD = "EV_ON_CITY_BUILD"
GameEvent.EV_ON_CITY_UPDATE_BUILDINGS_STATE = "EV_ON_CITY_UPDATE_BUILDINGS_STATE" --刷新主城内所有建筑的状态信息
GameEvent.EV_ON_CITY_SOLDIERS_REFRESH = "EV_ON_CITY_SOLDIERS_REFRESH"--刷新校场士兵数量
GameEvent.EV_ON_USER_FLUSHUSEMSG = "EV_ON_USER_FLUSHUSEMSG"	--	 刷新用户基本信息(头像等)
GameEvent.EV_ON_UPDATE_USERNAME = "EV_ON_UPDATE_USERNAME"	--　 名字修改刷新
GameEvent.EV_ON_UPGRADE_CITY = "EV_ON_UPGRADE_CITY"	--　 建筑升级

GameEvent.EV_ON_CITY_BUFF_UPDATE = "EV_ON_CITY_BUFF_UPDATE"--内城buff状态更新


--union
GameEvent.EV_ON_REFRESH_UNION_PANEL = "EV_ON_REFRESH_UNION_PANEL"
GameEvent.EV_ON_UNION_MEMBER_REFRESH = "EV_ON_UNION_MEMBER_REFRESH"
GameEvent.EV_ON_REFRESH_UNION_FOREIGN_PANEL = "EV_ON_REFRESH_UNION_FOREIGN_PANEL"
GameEvent.EV_ON_UNION_WAR_REFRESH = "EV_ON_UNION_WAR_REFRESH"
GameEvent.EV_ON_REFRESH_UNION_PANEL_RED_NUM = "EV_ON_REFRESH_UNION_PANEL_RED_NUM"
GameEvent.EV_ON_REFRESH_UNION_DONATE = "EV_ON_REFRESH_UNION_DONATE"
GameEvent.EV_ON_REFRESH_UNION_TASK = "EV_ON_REFRESH_UNION_TASK"
GameEvent.EV_ON_UNION_JOIN = "EV_ON_UNION_JOIN"
GameEvent.EV_ON_REFRESH_UNION_BUILD_DOING = "EV_ON_REFRESH_UNION_BUILD_DOING"
GameEvent.EV_ON_REFRESH_UNION_POWER = "EV_ON_REFRESH_UNION_POWER"
GameEvent.EV_ON_REFRESH_UNION_SHOP = "EV_ON_REFRESH_UNION_SHOP"
GameEvent.EV_ON_GPSBUILID = "EV_ON_GPSBUILID"
GameEvent.GOTOHEROMODE4 = "GOTOHEROMODE4"

-- chat
GameEvent.EV_ON_CHAT_NEWMESSAGE = "EV_ON_CHAT_NEWMESSAGE"
GameEvent.EV_ON_CHAT_BOTTOM = "EV_ON_CHAT_BOTTOM"
GameEvent.EV_ON_UNION_QUITUNION = "EV_ON_UNION_QUITUNION"
GameEvent.EV_ON_UNION_SELECTUSER = "EV_ON_UNION_SELECTUSER"
GameEvent.EV_ON_CHAT_SHIELD = "EV_ON_CHAT_SHIELD"
GameEvent.EV_ON_NEW_CHAT = "EV_ON_NEW_CHAT"

--ui
GameEvent.EV_ON_UI_RES_NUM_UPDATE = "EV_ON_UI_RES_NUM_UPDATE"
GameEvent.EV_ON_UI_RES_NUM_UPDATE_ACTION = "EV_ON_UI_RES_NUM_UPDATE_ACTION"
GameEvent.EV_ON_UI_USER_UPDATE = "EV_ON_UI_USER_UPDATE"
GameEvent.EV_ON_UI_EFFECT_PLAY = "EV_ON_UI_EFFECT_PLAY"
GameEvent.EV_ON_UI_BAGEFFECT_PLAY = "EV_ON_UI_BAGEFFECT_PLAY"
GameEvent.EV_ON_UI_TROOP_REFERSH = "EV_ON_UI_TROOP_REFERSH"
GameEvent.EV_ON_UI_MAIL_UNREADNUM	 = "EV_ON_UI_MAIL_UNREADNUM"
GameEvent.EV_ON_UI_OCCUPY_FLUSH	 = "EV_ON_UI_OCCUPY_FLUSH"
GameEvent.EV_ON_UI_REWARDBAG_FLUSHSTATE	 = "EV_ON_UI_REWARDBAG_FLUSHSTATE"
GameEvent.EV_ON_UI_HERO_FLUSH	 = "EV_ON_UI_HERO_FLUSH"
GameEvent.EV_ON_UI_HERO_KNOW	 = "EV_ON_UI_HERO_KNOW"
GameEvent.EV_ON_UI_NOTICE_FLUSH	 = "EV_ON_UI_NOTICE_FLUSH"
GameEvent.EV_ON_UI_CITY_FEATURE	 = "EV_ON_UI_CITY_FEATURE"
GameEvent.EV_ON_UI_BUILD_RED_FLUSH	 = "EV_ON_UI_BUILD_RED_FLUSH"
GameEvent.EV_ON_UI_UNION_RED_FLUSH	 = "EV_ON_UI_UNION_RED_FLUSH"
GameEvent.EV_ON_UI_EQUIP_FLUSH	 = "EV_ON_UI_EQUIP_FLUSH"
GameEvent.EV_ON_UI_TECH_FLUSH	 = "EV_ON_UI_TECH_FLUSH"
GameEvent.EV_ON_UI_TECH_FINISH	 = "EV_ON_UI_TECH_FINISH"
GameEvent.EV_ON_UI_TECH_BUFF	 = "EV_ON_UI_TECH_BUFF"
GameEvent.EV_ON_UI_HEAD_FLUSH	 = "EV_ON_UI_HEAD_FLUSH"
GameEvent.EV_ON_UI_ACTIVITY_UPDATE	 = "EV_ON_UI_ACTIVITY_UPDATE"
GameEvent.EV_ON_UI_BOSS_FLUSH	 = "EV_ON_UI_BOSS_FLUSH" 
GameEvent.EV_ON_UI_BOSS_MISS	 = "EV_ON_UI_BOSS_MISS"  
GameEvent.EV_ON_UI_BOSS_REFERSHITEM	 = "EV_ON_UI_BOSS_REFERSHITEM" 
GameEvent.EV_ON_UI_BOSS_PLAY	 = "EV_ON_UI_BOSS_PLAY"
GameEvent.EV_ON_UI_RED_TURNTABLE_HERO_FREE_TIMES = "EV_ON_UI_RED_TURNTABLE_HERO_FREE_TIMES"
GameEvent.EV_ON_UI_RECHARGE	 = "EV_ON_UI_RECHARGE"
GameEvent.EV_ON_UI_RECHARGE_SUCCESS	 = "EV_ON_UI_RECHARGE_SUCCESS"
GameEvent.EV_ON_UI_TRAINCARD_FINISH	 = "EV_ON_UI_TRAINCARD_FINISH"
GameEvent.EV_ON_UI_BUILD_FLUSH	 = "EV_ON_UI_BUILD_FLUSH"
GameEvent.EV_ON_UI_HP_UPDATE	 = "EV_ON_UI_HP_UPDATE"
GameEvent.EV_ON_UI_ACM_UPDATE	 = "EV_ON_UI_ACM_UPDATE"
GameEvent.EV_ON_UI_CHOOSE_CITY = "EV_ON_UI_CHOOSE_CITY"
GameEvent.EV_ON_UI_GOT_GOV_HERO = "EV_ON_UI_GOT_GOV_HERO"
GameEvent.EV_ON_UI_LEISURE = "EV_ON_UI_LEISURE"
GameEvent.EV_ON_UI_ADUPDATE = "EV_ON_UI_ADUPDATE"
GameEvent.EV_ON_UI_ADSOLDOUT = "EV_ON_UI_ADSOLDOUT"
GameEvent.EV_ON_UI_VIPUPDATE = "EV_ON_UI_VIPUPDATE"
GameEvent.EV_ON_UI_TRAINCLICK = "EV_ON_UI_TRAINCLICK"
GameEvent.EV_ON_UI_SCENECALL = "EV_ON_UI_SCENECALL"
GameEvent.EV_ON_GUIDE_START = "EV_ON_GUIDE_START"
GameEvent.EV_ON_GUIDE_END = "EV_ON_GUIDE_END"
GameEvent.EV_ON_GUIDE_MAIN_END = "EV_ON_GUIDE_MAIN_END"
GameEvent.EV_ON_UNION_CHATUNREAD = "EV_ON_UNION_CHATUNREAD"
GameEvent.EV_ON_RES_BUILDLISTNODE = "EV_ON_RES_BUILDLISTNODE"
GameEvent.EV_ON_RES_WIDELIST = "EV_ON_RES_WIDELIST"
GameEvent.EV_ON_WILD_REFRESH = "EV_ON_WILD_REFRESH"
GameEvent.EV_ON_REFRESH_STORE = "EV_ON_REFRESH_STORE"
GameEvent.EV_ON_REFRESH_SALARY = "EV_ON_REFRESH_SALARY"
GameEvent.EV_ON_MONTHCARD = "EV_ON_MONTHCARD"
GameEvent.EV_ON_HEROHEADLIST = "EV_ON_HEROHEADLIST"
GameEvent.EV_ON_RESWAREHOUSE = "EV_ON_RESWAREHOUSE"
GameEvent.EV_ON_CASTINFOGUIDE = "EV_ON_CASTINFOGUIDE"
GameEvent.EV_ON_UNIONHINT = "EV_ON_UNIONHINT"
GameEvent.EV_ON_GARRISON_BUILD = "EV_ON_GARRISON_BUILD"
GameEvent.EV_ON_CHAT_TRANSLATE = "EV_ON_CHAT_TRANSLATE"
GameEvent.EV_ON_CHAT_TRANSLATEING = "EV_ON_CHAT_TRANSLATEING"
GameEvent.EV_ON_GARRISON_GARRISONUI = "EV_ON_GARRISON_GARRISONUI"
GameEvent.EV_ON_EQUIP_FORGIN_POINT = "EV_ON_EQUIP_FORGIN_POINT"
GameEvent.EV_ON_SOLDIER_HARVEST = "EV_ON_SOLDIER_HARVEST"
GameEvent.EV_ON_CITYSCROLLSCALECHANGE = "EV_ON_CITYSCROLLSCALECHANGE"

GameEvent.EV_ON_UI_REPLAY_START ="EV_ON_UI_REPLAY_START" 
GameEvent.EV_ON_UI_REPLAY_STOP ="EV_ON_UI_REPLAY_STOP" 
GameEvent.EV_ON_UI_REPLAY_PAUSE ="EV_ON_UI_REPLAY_PAUSE" 
GameEvent.EV_ON_UI_REPLAY_UNSPEED ="EV_ON_UI_REPLAY_UNSPEED" 
GameEvent.EV_ON_UI_REPLAY_SPEED ="EV_ON_UI_REPLAY_SPEED" 
GameEvent.EV_ON_UI_REPLAY_RESUME ="EV_ON_UI_REPLAY_RESUME" 
GameEvent.EV_ON_UI_REPLAY_CLEANWIDGET ="EV_ON_UI_REPLAY_CLEANWIDGET" 
GameEvent.EV_ON_TASK_NORMAL_COMPELETE = "EV_ON_TASK_NORMAL_COMPELETE"
GameEvent.EV_ON_HEAMFREAM_UPDATE = "EV_ON_HEAMFREAM_UPDATE"
GameEvent.EV_ON_APPROVECOUNT_UPDATE = "EV_ON_APPROVECOUNT_UPDATE"
GameEvent.EV_ON_UICHESTPANEL_UPDATE = "EV_ON_UICHESTPANEL_UPDATE"
GameEvent.EV_ON_RECONNECT_UPDATE = "EV_ON_RECONNECT_UPDATE"
GameEvent.EV_ON_FRIEND_UPDATE = "EV_ON_FRIEND_UPDATE"
GameEvent.EV_ON_BUILDIERS_UPDATE = "EV_ON_BUILDIERS_UPDATE"
GameEvent.EV_ON_FIRECODE_UPDATE = "EV_ON_FIRECODE_UPDATE"
GameEvent.EV_ON_SKINPANDECT_UPDATE = "EV_ON_SKINPANDECT_UPDATE"
GameEvent.EV_ON_LORDE_EQUIP_BUFF_UPDATE = "EV_ON_LORDE_EQUIP_BUFF_UPDATE"
GameEvent.EV_ON_BOSS_POINT = "EV_ON_BOSS_POINT"
GameEvent.EV_ON_BATTLEERRORCODE_SHOW = "EV_ON_BATTLEERRORCODE_SHOW"
GameEvent.EV_ON_CHATTOP_UNIONRECRUIT = "EV_ON_CHATTOP_UNIONRECRUIT"
GameEvent.EV_ON_SOLDIER_GET = "EV_ON_SOLDIER_GET"
GameEvent.EV_ON_UNIONBOSS_MISS = "EV_ON_UNIONBOSS_MISS"
GameEvent.BANKUPDATE = "BANKUPDATE"
GameEvent.EV_ON_BANK_RECODE = "EV_ON_BANK_RECODE"
GameEvent.EV_ON_SOURCE_SINGEBUY = "EV_ON_SOURCE_SINGEBUY"
GameEvent.EV_ON_SEVENDAYRECHARGE= "EV_ON_SEVENDAYRECHARGE"
GameEvent.EV_ON_EXPLOIT_GETREWARD = "EV_ON_EXPLOIT_GETREWARD"
GameEvent.EV_ON_HERO_TURNTABLE_CHANGE = "EV_ON_HERO_TURNTABLE_CHANGE"
GameEvent.EV_ON_PET_REFERSH = "EV_ON_PET_REFERSH"
GameEvent.EV_ON_PET_SKILL = "EV_ON_PET_SKILL"
GameEvent.EV_ON_LOGIC_NOTIFY_RED_POINT = "EV_ON_LOGIC_NOTIFY_RED_POINT"
GameEvent.EV_ON_HERO_FREE = "EV_ON_HERO_FREE"
GameEvent.EV_ON_UNION_HELP_REFRESH = "EV_ON_UNION_HELP_REFRESH"
GameEvent.EV_ON_PET_PLAYEFFECT = "EV_ON_PET_PLAYEFFECT"
GameEvent.EV_ON_PET_UNLOCK = "EV_ON_PET_UNLOCK"
GameEvent.EV_ON_PET_CD = "EV_ON_PET_CD"
GameEvent.EV_ON_UNION_ADREDPOINT = "EV_ON_UNION_ADREDPOINT"
GameEvent.EV_ON_UNION_HEREXPUPDATE = "EV_ON_UNION_HEREXPUPDATE"
GameEvent.EV_ON_UNION_HEREXPLOCALDATAUP = "EV_ON_UNION_HEREXPLOCALDATAUP"
GameEvent.EV_ON_UNION_CLEANCD = "EV_ON_UNION_CLEANCD"
GameEvent.EV_ON_FINISHTIP = "EV_ON_FINISHTIP"
GameEvent.EV_ON_SOLDIER_CURE_BUFF = "EV_ON_SOLDIER_CURE_BUFF"
GameEvent.EV_ON_ACTIVITY_RED = "EV_ON_ACTIVITY_RED"
GameEvent.EV_ON_UNION_REDBAG = "EV_ON_UNION_REDBAG"
GameEvent.EV_ON_GUIDE_UNLOCK_PET = "EV_ON_GUIDE_UNLOCK_PET"
GameEvent.EV_ON_OPENPANEL_ACTIONOVER = "EV_ON_OPENPANEL_ACTIONOVER"
GameEvent.EV_ON_TYPE_HARVEST = "EV_ON_TYPE_HARVEST"
GameEvent.EV_ON_QUESTIONNAIRE = "EV_ON_QUESTIONNAIRE"
GameEvent.EV_ON_DAILY_GIFT = "EV_ON_DAILY_GIFT"


--准备战斗
--global.gameEvent.EV_ON_UI_INITHERO
--global.gameEvent.EV_ON_UI_SHOWTITLE
GameEvent.EV_ON_UI_SHOWHERO ="EV_ON_UI_SHOWHERO" 
GameEvent.EV_ON_UI_SHOWTITLE ="EV_ON_UI_SHOWTITLE" 
GameEvent.EV_ON_UI_SHOWTITLEED ="EV_ON_UI_SHOWTITLEED" 
GameEvent.EV_ON_UI_SHOWSOLDIER ="EV_ON_UI_SHOWSOLDIER" 
GameEvent.EV_ON_UI_SHOWSOLDIERED ="EV_ON_UI_SHOWSOLDIERED"  
GameEvent.EV_ON_UI_SHOWPK ="EV_ON_UI_SHOWPK"  
GameEvent.EV_ON_UI_SHOWPKED ="EV_ON_UI_SHOWPKED"
GameEvent.EV_ON_UI_LOOP_ADDCHILD_DONE ="EV_ON_UI_LOOP_ADDCHILD_DONE"

-- 战斗
GameEvent.EV_ON_UI_SHOWATTACK ="EV_ON_UI_SHOWATTACK"
GameEvent.EV_ON_UI_FIGHTEND ="EV_ON_UI_FIGHTEND"


-- 准备阶段
GameEvent.EV_ON_UI_PREPARE ="EV_ON_UI_PREPARE"
GameEvent.EV_ON_UI_PREPAREED ="EV_ON_UI_PREPAREED"

-- 战斗显示结果
GameEvent.EV_ON_UI_SHOWRESULT ="EV_ON_UI_SHOWRESULT"


-- 播放跳转
GameEvent.EV_ON_UI_PLAYSKIP ="EV_ON_UI_PLAYSKIP"
GameEvent.EV_ON_UI_PLAYBESKIP ="EV_ON_UI_PLAYBESKIP"

GameEvent.WARDATA_DOWNLORD_ERROR ="WARDATA_DOWNLORD_ERROR"
GameEvent.WARDATA_DOWNLORDING ="WARDATA_DOWNLORDING"
GameEvent.WARDATA_DOWNLORD_SUCCESS ="WARDATA_DOWNLORD_SUCCESS"
GameEvent.WARDATA_FILEWRITE_SUCCESS ="WARDATA_FILEWRITE_SUCCESS"

--item
GameEvent.EV_ON_ITEM_UPDATE = "EV_ON_ITEM_UPDATE"

--soldier
GameEvent.EV_ON_SOLDIERS_UPDATE = "EV_ON_SOLDIERS_UPDATE"
GameEvent.EV_ON_SOLDIERS_FREE_RECRUIT_UPDATE = "EV_ON_SOLDIERS_FREE_RECRUIT_UPDATE"
GameEvent.EV_ON_SOURCE_BUYCOST_UPDATE = "EV_ON_SOURCE_BUYCOST_UPDATE"

--guide
GameEvent.EV_ON_GUIDE_START 		= "EV_ON_GUIDE_START" 				--开始引导事件监听
GameEvent.EV_ON_GUIDE_NEXT 			= "EV_ON_GUIDE_NEXT" 				--更新引导事件监听
GameEvent.EV_ON_GUIDE_SILDIER_300 			= "EV_ON_GUIDE_SILDIER_300"
GameEvent.EV_ON_GUIDE_UPDATE_TARGET = "EV_ON_GUIDE_UPDATE_TARGET" 		--更新引导任务目标获取
GameEvent.EV_ON_GUIDE_FINISH_CRUX_STEP = "EV_ON_GUIDE_FINISH_CRUX_STEP" 		--完成关键步骤引导
GameEvent.EV_ON_GUIDE_FINISH_ACTION_STEP = "EV_ON_GUIDE_FINISH_ACTION_STEP" 		--动画播放完成后步骤引导
GameEvent.EV_ON_GUIDE_FIRST_ATTACT_BOARD = "EV_ON_GUIDE_FIRST_ATTACT_BOARD"
GameEvent.EV_ON_GUIDE_HERO_PANEL_2 = "EV_ON_GUIDE_HERO_PANEL_2"
GameEvent.EV_ON_GUIDE_WARIN = "EV_ON_GUIDE_WARIN"
GameEvent.EV_ON_GUIDE_VILLAGE_GUIDE_DONE = "EV_ON_GUIDE_VILLAGE_GUIDE_DONE"
GameEvent.EV_ON_GUIDE_TRAIN_GUIDE_DONE = "EV_ON_GUIDE_TRAIN_GUIDE_DONE"
GameEvent.EV_ON_GUIDE_FIRST_CHANGE_HERO_IN_EDIT_SELECT_CONFRIM = "EV_ON_GUIDE_FIRST_CHANGE_HERO_IN_EDIT_SELECT_CONFRIM"
GameEvent.EV_ON_GUIDE_CHECK_ATTACK_BOARD_OPEN = "EV_ON_GUIDE_CHECK_ATTACK_BOARD_OPEN"

--world
GameEvent.EV_ON_CITY_CHANGE = "EV_ON_CITY_CHANGE"
GameEvent.EV_ON_FIGHT_CHANGE = "EV_ON_FIGHT_CHANGE"
GameEvent.EV_ON_ATTACK_FINISH = "EV_ON_ATTACK_FINISH"
GameEvent.EV_ON_WORLD_CITY_DEF_CHANGE = "EV_ON_WORLD_CITY_DEF_CHANGE"
GameEvent.EV_ON_CITY_BURNED = "EV_ON_CITY_BURNED"
GameEvent.EV_ON_MONSTER_CAMP = "EV_ON_MONSTER_CAMP"
GameEvent.EV_ON_OPEN_TIPS_PANEL = "EV_ON_OPEN_TIPS_PANEL"

--SCENE
GameEvent.EV_ON_ENTER_WORLD_SCENE = "EV_ON_ENTER_WORLD_SCENE"
GameEvent.EV_ON_ENTER_MAIN_SCENE = "EV_ON_ENTER_MAIN_SCENE"

--GUIDE LOOP
GameEvent.EV_ON_LOOP_GUIDE_UPDATE = "EV_ON_LOOP_GUIDE_UPDATE"
GameEvent.EV_ON_LOOP_GUIDE_OPEN_BUILD = "EV_ON_LOOP_GUIDE_OPEN_BUILD"
GameEvent.EV_ON_LOOP_GUIDE_TRAIN = "EV_ON_LOOP_GUIDE_TRAIN"
GameEvent.EV_ON_LOOP_GUIDE_TRAIN_SPEED = "EV_ON_LOOP_GUIDE_TRAIN_SPEED"
GameEvent.EV_ON_LOOP_GUIDE_AFTER_SEARCH = "EV_ON_LOOP_GUIDE_AFTER_SEARCH"
GameEvent.EV_ON_LOOP_GUIDE_AFTER_SEARCH_OPEN_PANEL = "EV_ON_LOOP_GUIDE_AFTER_SEARCH_OPEN_PANEL"
GameEvent.EV_ON_LOOP_GUIDE_ADD_RES_SPEED = "EV_ON_LOOP_GUIDE_ADD_RES_SPEED"
GameEvent.EV_ON_LOOP_GUIDE_PANDECT = "EV_ON_LOOP_GUIDE_PANDECT"
GameEvent.EV_ON_LOOP_GUIDE_FIX_SCENE = "EV_ON_LOOP_GUIDE_FIX_SCENE"


GameEvent.EV_ON_UI_DOWNLOADFILE_REFRESH_OTHERHEAD = "EV_ON_UI_DOWNLOADFILE_REFRESH_OTHERHEAD"

global.gameEvent = GameEvent
