---@classdef ActionObject
ActionObject = {}
function ActionObject:autorelease() end 
function ActionObject:retain() end 
function ActionObject:retainCount() end 
function ActionObject:isEqual() end 
function ActionObject:copy() end 
function ActionObject:release() end 
function ActionObject:isSingleReference() end 
function ActionObject:getCurrentTime() end 
function ActionObject:new() end 
function ActionObject:setUnitTime() end 
function ActionObject:delete() end 
function ActionObject:removeActionNode() end 
function ActionObject:new_local() end 
function ActionObject:getName() end 
function ActionObject:isPlaying() end 
function ActionObject:getUnitTime() end 
function ActionObject:setLoop() end 
function ActionObject:setCurrentTime() end 
function ActionObject:play() end 
function ActionObject:updateToFrameByTime() end 
function ActionObject:pause() end 
function ActionObject:simulationActionUpdate() end 
function ActionObject:initWithDictionary() end 
function ActionObject:addActionNode() end 
function ActionObject:setName() end 
function ActionObject:getLoop() end 
function ActionObject:stop() end 
