---@classdef Button
Button = {}
function Button:autorelease() end 
function Button:retain() end 
function Button:retainCount() end 
function Button:isEqual() end 
function Button:copy() end 
function Button:release() end 
function Button:isSingleReference() end 
function Button:visit() end 
function Button:getUserObject() end 
function Button:getSkewY() end 
function Button:convertTouchToNodeSpace() end 
function Button:getVertexZ() end 
function Button:setParent() end 
function Button:boundingBox() end 
function Button:setVisible() end 
function Button:stopActionByTag() end 
function Button:getScaleY() end 
function Button:setScaleX() end 
function Button:reorderChild() end 
function Button:setPositionX() end 
function Button:removeFromParentAndCleanup() end 
function Button:setTag() end 
function Button:getChildrenCount() end 
function Button:setScale() end 
function Button:addChild() end 
function Button:isVisible() end 
function Button:setActionManager() end 
function Button:setScheduler() end 
function Button:getContentSize() end 
function Button:getAnchorPoint() end 
function Button:getTag() end 
function Button:setGrid() end 
function Button:convertToWorldSpace() end 
function Button:setSkewX() end 
function Button:setZOrder() end 
function Button:worldToNodeTransform() end 
function Button:getPosition() end 
function Button:getSkewX() end 
function Button:getScheduler() end 
function Button:ignoreAnchorPointForPosition() end 
function Button:setPosition() end 
function Button:getParent() end 
function Button:unscheduleUpdate() end 
function Button:scheduleUpdateWithPriorityLua() end 
function Button:removeChildByTag() end 
function Button:convertToNodeSpaceAR() end 
function Button:convertTouchToNodeSpaceAR() end 
function Button:convertToWorldSpaceAR() end 
function Button:setRotation() end 
function Button:getComponent() end 
function Button:convertToNodeSpace() end 
---
-- @return @class Button
--
function Button:create() end 
function Button:getScale() end 
function Button:getPositionY() end 
function Button:getChildByTag() end 
function Button:setContentSize() end 
function Button:description() end 
function Button:cleanup() end 
function Button:getRotation() end 
function Button:nodeToParentTransform() end 
function Button:stopAction() end 
function Button:numberOfRunningActions() end 
function Button:removeAllChildren() end 
function Button:runAction() end 
function Button:setUserObject() end 
function Button:parentToNodeTransform() end 
function Button:removeChild() end 
function Button:getAnchorPointInPoints() end 
function Button:getScaleX() end 
function Button:transform() end 
function Button:getActionManager() end 
function Button:draw() end 
function Button:setScaleY() end 
function Button:unregisterScriptHandler() end 
function Button:setVertexZ() end 
function Button:setAnchorPoint() end 
function Button:getShaderProgram() end 
function Button:stopAllActions() end 
function Button:setUserData() end 
function Button:setShaderProgram() end 
function Button:getActionByTag() end 
function Button:getGLServerState() end 
function Button:getOrderOfArrival() end 
function Button:getPositionX() end 
function Button:setGLServerState() end 
function Button:setSkewY() end 
function Button:setOrderOfArrival() end 
function Button:nodeToWorldTransform() end 
function Button:getChildren() end 
function Button:transformAncestors() end 
function Button:getGrid() end 
function Button:isRunning() end 
function Button:registerScriptHandler() end 
function Button:getCamera() end 
function Button:isIgnoreAnchorPointForPosition() end 
function Button:getUserData() end 
function Button:setPositionY() end 
function Button:getZOrder() end 
function Button:removeNode() end 
function Button:onTouchBegan() end 
function Button:addNode() end 
function Button:setLayoutParameter() end 
function Button:isFlipX() end 
function Button:getSizePercent() end 
function Button:getLeftInParent() end 
function Button:getPositionPercent() end 
function Button:onTouchEnded() end 
function Button:new_local() end 
function Button:getRightInParent() end 
function Button:checkChildInfo() end 
function Button:isEnabled() end 
function Button:setSizePercent() end 
function Button:removeFromParentAndCleanup() end 
function Button:setFlipX() end 
function Button:getChildrenCount() end 
function Button:isBright() end 
function Button:setPositionPercent() end 
function Button:addChild() end 
function Button:getBottomInParent() end 
function Button:setBright() end 
function Button:getTouchStartPos() end 
function Button:removeAllChildren() end 
function Button:setPositionType() end 
function Button:removeNodeByTag() end 
function Button:getContentSize() end 
function Button:clone() end 
function Button:setFlipY() end 
function Button:getTouchEndPos() end 
function Button:setName() end 
function Button:setPosition() end 
function Button:setFocused() end 
function Button:setSizeType() end 
function Button:hitTest() end 
function Button:addTouchEventListener() end 
function Button:getCustomSize() end 
function Button:isTouchEnabled() end 
function Button:new() end 
function Button:removeFromParent() end 
---
-- @return @class Button
--
function Button:create() end 
function Button:delete() end 
function Button:getChildByTag() end 
function Button:isFocused() end 
function Button:getTopInParent() end 
function Button:isFlipY() end 
function Button:setColor() end 
function Button:removeAllChildren() end 
function Button:updateSizeAndPosition() end 
function Button:getLayoutParameter() end 
function Button:getName() end 
function Button:removeChild() end 
function Button:onEnter() end 
function Button:getVirtualRenderer() end 
function Button:getDescription() end 
function Button:getChildByName() end 
function Button:isIgnoreContentAdaptWithSize() end 
function Button:ignoreContentAdaptWithSize() end 
function Button:onExit() end 
function Button:visit() end 
function Button:getChildren() end 
function Button:onTouchMoved() end 
function Button:getLayoutSize() end 
function Button:getColor() end 
function Button:getPositionType() end 
function Button:getTouchMovePos() end 
function Button:getSize() end 
function Button:getSizeType() end 
function Button:setSize() end 
function Button:getWidgetType() end 
function Button:getOpacity() end 
function Button:clippingParentAreaContainPoint() end 
function Button:setTouchEnabled() end 
function Button:setEnabled() end 
function Button:setActionTag() end 
function Button:getWorldPosition() end 
function Button:didNotSelectSelf() end 
function Button:sortAllChildren() end 
function Button:getNodeByTag() end 
function Button:onTouchCancelled() end 
function Button:getNodes() end 
function Button:removeAllNodes() end 
function Button:setBrightStyle() end 
function Button:removeChildByTag() end 
function Button:getActionTag() end 
function Button:setOpacity() end 
function Button:getTitleFontSize() end 
function Button:new() end 
function Button:setCapInsets() end 
function Button:delete() end 
function Button:setScale9Enabled() end 
function Button:setCapInsetsDisabledRenderer() end 
function Button:loadTextures() end 
function Button:new_local() end 
function Button:getCapInsetNormalRenderer() end 
function Button:getVirtualRenderer() end 
function Button:getDescription() end 
function Button:loadTexturePressed() end 
function Button:isScale9Enabled() end 
function Button:getTitleFontName() end 
function Button:getTitleText() end 
function Button:setTitleColor() end 
function Button:setTitleFontSize() end 
function Button:setCapInsetsPressedRenderer() end 
function Button:getTitleColor() end 
function Button:getCapInsetDisabledRenderer() end 
function Button:loadTextureDisabled() end 
function Button:setTitleFontName() end 
function Button:setTitleText() end 
function Button:getCapInsetPressedRenderer() end 
function Button:getContentSize() end 
function Button:ignoreContentAdaptWithSize() end 
function Button:setPressedActionEnabled() end 
---
-- @return @class Button
--
function Button:create() end 
function Button:loadTextureNormal() end 
function Button:setCapInsetsNormalRenderer() end 
function Button:setAnchorPoint() end 
