---@classdef CCActionManager
CCActionManager = {}
function CCActionManager:autorelease() end 
function CCActionManager:retain() end 
function CCActionManager:retainCount() end 
function CCActionManager:isEqual() end 
function CCActionManager:copy() end 
function CCActionManager:release() end 
function CCActionManager:isSingleReference() end 
function CCActionManager:numberOfRunningActionsInTarget() end 
function CCActionManager:getActionByTag() end 
function CCActionManager:removeAction() end 
function CCActionManager:removeAllActionsFromTarget() end 
function CCActionManager:resumeTargets() end 
function CCActionManager:pauseAllRunningActions() end 
function CCActionManager:resumeTarget() end 
function CCActionManager:addAction() end 
function CCActionManager:pauseTarget() end 
function CCActionManager:removeAllActions() end 
function CCActionManager:removeActionByTag() end 
