---@classdef CCArmature
CCArmature = {}
function CCArmature:autorelease() end 
function CCArmature:retain() end 
function CCArmature:retainCount() end 
function CCArmature:isEqual() end 
function CCArmature:copy() end 
function CCArmature:release() end 
function CCArmature:isSingleReference() end 
function CCArmature:visit() end 
function CCArmature:getUserObject() end 
function CCArmature:getSkewY() end 
function CCArmature:convertTouchToNodeSpace() end 
function CCArmature:getVertexZ() end 
function CCArmature:setParent() end 
function CCArmature:boundingBox() end 
function CCArmature:setVisible() end 
function CCArmature:stopActionByTag() end 
function CCArmature:getScaleY() end 
function CCArmature:setScaleX() end 
function CCArmature:reorderChild() end 
function CCArmature:setPositionX() end 
function CCArmature:removeFromParentAndCleanup() end 
function CCArmature:setTag() end 
function CCArmature:getChildrenCount() end 
function CCArmature:setScale() end 
function CCArmature:addChild() end 
function CCArmature:isVisible() end 
function CCArmature:setActionManager() end 
function CCArmature:setScheduler() end 
function CCArmature:getContentSize() end 
function CCArmature:getAnchorPoint() end 
function CCArmature:getTag() end 
function CCArmature:setGrid() end 
function CCArmature:convertToWorldSpace() end 
function CCArmature:setSkewX() end 
function CCArmature:setZOrder() end 
function CCArmature:worldToNodeTransform() end 
function CCArmature:getPosition() end 
function CCArmature:getSkewX() end 
function CCArmature:getScheduler() end 
function CCArmature:ignoreAnchorPointForPosition() end 
function CCArmature:setPosition() end 
function CCArmature:getParent() end 
function CCArmature:unscheduleUpdate() end 
function CCArmature:scheduleUpdateWithPriorityLua() end 
function CCArmature:removeChildByTag() end 
function CCArmature:convertToNodeSpaceAR() end 
function CCArmature:convertTouchToNodeSpaceAR() end 
function CCArmature:convertToWorldSpaceAR() end 
function CCArmature:setRotation() end 
function CCArmature:getComponent() end 
function CCArmature:convertToNodeSpace() end 
---
-- @return @class CCArmature
--
function CCArmature:create() end 
function CCArmature:getScale() end 
function CCArmature:getPositionY() end 
function CCArmature:getChildByTag() end 
function CCArmature:setContentSize() end 
function CCArmature:description() end 
function CCArmature:cleanup() end 
function CCArmature:getRotation() end 
function CCArmature:nodeToParentTransform() end 
function CCArmature:stopAction() end 
function CCArmature:numberOfRunningActions() end 
function CCArmature:removeAllChildren() end 
function CCArmature:runAction() end 
function CCArmature:setUserObject() end 
function CCArmature:parentToNodeTransform() end 
function CCArmature:removeChild() end 
function CCArmature:getAnchorPointInPoints() end 
function CCArmature:getScaleX() end 
function CCArmature:transform() end 
function CCArmature:getActionManager() end 
function CCArmature:draw() end 
function CCArmature:setScaleY() end 
function CCArmature:unregisterScriptHandler() end 
function CCArmature:setVertexZ() end 
function CCArmature:setAnchorPoint() end 
function CCArmature:getShaderProgram() end 
function CCArmature:stopAllActions() end 
function CCArmature:setUserData() end 
function CCArmature:setShaderProgram() end 
function CCArmature:getActionByTag() end 
function CCArmature:getGLServerState() end 
function CCArmature:getOrderOfArrival() end 
function CCArmature:getPositionX() end 
function CCArmature:setGLServerState() end 
function CCArmature:setSkewY() end 
function CCArmature:setOrderOfArrival() end 
function CCArmature:nodeToWorldTransform() end 
function CCArmature:getChildren() end 
function CCArmature:transformAncestors() end 
function CCArmature:getGrid() end 
function CCArmature:isRunning() end 
function CCArmature:registerScriptHandler() end 
function CCArmature:getCamera() end 
function CCArmature:isIgnoreAnchorPointForPosition() end 
function CCArmature:getUserData() end 
function CCArmature:setPositionY() end 
function CCArmature:getZOrder() end 
function CCArmature:new() end 
function CCArmature:delete() end 
function CCArmature:updateDisplayedColor() end 
function CCArmature:init() end 
function CCArmature:setColor() end 
function CCArmature:getDisplayedColor() end 
function CCArmature:setCascadeColorEnabled() end 
function CCArmature:setCascadeOpacityEnabled() end 
function CCArmature:setOpacity() end 
function CCArmature:getColor() end 
function CCArmature:updateDisplayedOpacity() end 
function CCArmature:getOpacity() end 
function CCArmature:setOpacityModifyRGB() end 
function CCArmature:isCascadeOpacityEnabled() end 
function CCArmature:isOpacityModifyRGB() end 
function CCArmature:getDisplayedOpacity() end 
function CCArmature:new_local() end 
function CCArmature:isCascadeColorEnabled() end 
function CCArmature:visit() end 
function CCArmature:getBatchNode() end 
function CCArmature:setAnimation() end 
function CCArmature:new() end 
function CCArmature:setBlendFunc() end 
---
-- @return @class CCArmature
--
function CCArmature:create() end 
function CCArmature:delete() end 
function CCArmature:boundingBox() end 
function CCArmature:updateOffsetPoint() end 
function CCArmature:init() end 
function CCArmature:update() end 
function CCArmature:setVersion() end 
function CCArmature:setArmatureData() end 
function CCArmature:new_local() end 
function CCArmature:getName() end 
function CCArmature:getArmatureData() end 
function CCArmature:addBone() end 
function CCArmature:changeBoneParent() end 
function CCArmature:getBone() end 
function CCArmature:getAnimation() end 
function CCArmature:removeBone() end 
function CCArmature:draw() end 
function CCArmature:getArmatureTransformDirty() end 
function CCArmature:getVersion() end 
function CCArmature:getBoneAtPoint() end 
function CCArmature:getTextureAtlas() end 
function CCArmature:getParentBone() end 
function CCArmature:setTextureAtlas() end 
function CCArmature:getBlendFunc() end 
function CCArmature:setBatchNode() end 
function CCArmature:getBoneDic() end 
function CCArmature:setName() end 
function CCArmature:nodeToParentTransform() end 
function CCArmature:getTexureAtlasWithTexture() end 
function CCArmature:setParentBone() end 
