---@classdef CCAtlasNode
CCAtlasNode = {}
function CCAtlasNode:autorelease() end 
function CCAtlasNode:retain() end 
function CCAtlasNode:retainCount() end 
function CCAtlasNode:isEqual() end 
function CCAtlasNode:copy() end 
function CCAtlasNode:release() end 
function CCAtlasNode:isSingleReference() end 
function CCAtlasNode:visit() end 
function CCAtlasNode:getUserObject() end 
function CCAtlasNode:getSkewY() end 
function CCAtlasNode:convertTouchToNodeSpace() end 
function CCAtlasNode:getVertexZ() end 
function CCAtlasNode:setParent() end 
function CCAtlasNode:boundingBox() end 
function CCAtlasNode:setVisible() end 
function CCAtlasNode:stopActionByTag() end 
function CCAtlasNode:getScaleY() end 
function CCAtlasNode:setScaleX() end 
function CCAtlasNode:reorderChild() end 
function CCAtlasNode:setPositionX() end 
function CCAtlasNode:removeFromParentAndCleanup() end 
function CCAtlasNode:setTag() end 
function CCAtlasNode:getChildrenCount() end 
function CCAtlasNode:setScale() end 
function CCAtlasNode:addChild() end 
function CCAtlasNode:isVisible() end 
function CCAtlasNode:setActionManager() end 
function CCAtlasNode:setScheduler() end 
function CCAtlasNode:getContentSize() end 
function CCAtlasNode:getAnchorPoint() end 
function CCAtlasNode:getTag() end 
function CCAtlasNode:setGrid() end 
function CCAtlasNode:convertToWorldSpace() end 
function CCAtlasNode:setSkewX() end 
function CCAtlasNode:setZOrder() end 
function CCAtlasNode:worldToNodeTransform() end 
function CCAtlasNode:getPosition() end 
function CCAtlasNode:getSkewX() end 
function CCAtlasNode:getScheduler() end 
function CCAtlasNode:ignoreAnchorPointForPosition() end 
function CCAtlasNode:setPosition() end 
function CCAtlasNode:getParent() end 
function CCAtlasNode:unscheduleUpdate() end 
function CCAtlasNode:scheduleUpdateWithPriorityLua() end 
function CCAtlasNode:removeChildByTag() end 
function CCAtlasNode:convertToNodeSpaceAR() end 
function CCAtlasNode:convertTouchToNodeSpaceAR() end 
function CCAtlasNode:convertToWorldSpaceAR() end 
function CCAtlasNode:setRotation() end 
function CCAtlasNode:getComponent() end 
function CCAtlasNode:convertToNodeSpace() end 
---
-- @return @class CCAtlasNode
--
function CCAtlasNode:create() end 
function CCAtlasNode:getScale() end 
function CCAtlasNode:getPositionY() end 
function CCAtlasNode:getChildByTag() end 
function CCAtlasNode:setContentSize() end 
function CCAtlasNode:description() end 
function CCAtlasNode:cleanup() end 
function CCAtlasNode:getRotation() end 
function CCAtlasNode:nodeToParentTransform() end 
function CCAtlasNode:stopAction() end 
function CCAtlasNode:numberOfRunningActions() end 
function CCAtlasNode:removeAllChildren() end 
function CCAtlasNode:runAction() end 
function CCAtlasNode:setUserObject() end 
function CCAtlasNode:parentToNodeTransform() end 
function CCAtlasNode:removeChild() end 
function CCAtlasNode:getAnchorPointInPoints() end 
function CCAtlasNode:getScaleX() end 
function CCAtlasNode:transform() end 
function CCAtlasNode:getActionManager() end 
function CCAtlasNode:draw() end 
function CCAtlasNode:setScaleY() end 
function CCAtlasNode:unregisterScriptHandler() end 
function CCAtlasNode:setVertexZ() end 
function CCAtlasNode:setAnchorPoint() end 
function CCAtlasNode:getShaderProgram() end 
function CCAtlasNode:stopAllActions() end 
function CCAtlasNode:setUserData() end 
function CCAtlasNode:setShaderProgram() end 
function CCAtlasNode:getActionByTag() end 
function CCAtlasNode:getGLServerState() end 
function CCAtlasNode:getOrderOfArrival() end 
function CCAtlasNode:getPositionX() end 
function CCAtlasNode:setGLServerState() end 
function CCAtlasNode:setSkewY() end 
function CCAtlasNode:setOrderOfArrival() end 
function CCAtlasNode:nodeToWorldTransform() end 
function CCAtlasNode:getChildren() end 
function CCAtlasNode:transformAncestors() end 
function CCAtlasNode:getGrid() end 
function CCAtlasNode:isRunning() end 
function CCAtlasNode:registerScriptHandler() end 
function CCAtlasNode:getCamera() end 
function CCAtlasNode:isIgnoreAnchorPointForPosition() end 
function CCAtlasNode:getUserData() end 
function CCAtlasNode:setPositionY() end 
function CCAtlasNode:getZOrder() end 
function CCAtlasNode:new() end 
function CCAtlasNode:delete() end 
function CCAtlasNode:updateDisplayedColor() end 
function CCAtlasNode:init() end 
function CCAtlasNode:setColor() end 
function CCAtlasNode:getDisplayedColor() end 
function CCAtlasNode:setCascadeColorEnabled() end 
function CCAtlasNode:setCascadeOpacityEnabled() end 
function CCAtlasNode:setOpacity() end 
function CCAtlasNode:getColor() end 
function CCAtlasNode:updateDisplayedOpacity() end 
function CCAtlasNode:getOpacity() end 
function CCAtlasNode:setOpacityModifyRGB() end 
function CCAtlasNode:isCascadeOpacityEnabled() end 
function CCAtlasNode:isOpacityModifyRGB() end 
function CCAtlasNode:getDisplayedOpacity() end 
function CCAtlasNode:new_local() end 
function CCAtlasNode:isCascadeColorEnabled() end 
function CCAtlasNode:setTextureAtlas() end 
function CCAtlasNode:setTexture() end 
function CCAtlasNode:getTexture() end 
function CCAtlasNode:getTextureAtlas() end 
---
-- @return @class CCAtlasNode
--
function CCAtlasNode:create() end 
function CCAtlasNode:setOpacityModifyRGB() end 
function CCAtlasNode:setColor() end 
function CCAtlasNode:setQuadsToDraw() end 
function CCAtlasNode:isOpacityModifyRGB() end 
function CCAtlasNode:setOpacity() end 
function CCAtlasNode:getOpacity() end 
function CCAtlasNode:updateAtlasValues() end 
function CCAtlasNode:getColor() end 
function CCAtlasNode:getQuadsToDraw() end 
