---@classdef CCBatchNode
CCBatchNode = {}
function CCBatchNode:autorelease() end 
function CCBatchNode:retain() end 
function CCBatchNode:retainCount() end 
function CCBatchNode:isEqual() end 
function CCBatchNode:copy() end 
function CCBatchNode:release() end 
function CCBatchNode:isSingleReference() end 
function CCBatchNode:visit() end 
function CCBatchNode:getUserObject() end 
function CCBatchNode:getSkewY() end 
function CCBatchNode:convertTouchToNodeSpace() end 
function CCBatchNode:getVertexZ() end 
function CCBatchNode:setParent() end 
function CCBatchNode:boundingBox() end 
function CCBatchNode:setVisible() end 
function CCBatchNode:stopActionByTag() end 
function CCBatchNode:getScaleY() end 
function CCBatchNode:setScaleX() end 
function CCBatchNode:reorderChild() end 
function CCBatchNode:setPositionX() end 
function CCBatchNode:removeFromParentAndCleanup() end 
function CCBatchNode:setTag() end 
function CCBatchNode:getChildrenCount() end 
function CCBatchNode:setScale() end 
function CCBatchNode:addChild() end 
function CCBatchNode:isVisible() end 
function CCBatchNode:setActionManager() end 
function CCBatchNode:setScheduler() end 
function CCBatchNode:getContentSize() end 
function CCBatchNode:getAnchorPoint() end 
function CCBatchNode:getTag() end 
function CCBatchNode:setGrid() end 
function CCBatchNode:convertToWorldSpace() end 
function CCBatchNode:setSkewX() end 
function CCBatchNode:setZOrder() end 
function CCBatchNode:worldToNodeTransform() end 
function CCBatchNode:getPosition() end 
function CCBatchNode:getSkewX() end 
function CCBatchNode:getScheduler() end 
function CCBatchNode:ignoreAnchorPointForPosition() end 
function CCBatchNode:setPosition() end 
function CCBatchNode:getParent() end 
function CCBatchNode:unscheduleUpdate() end 
function CCBatchNode:scheduleUpdateWithPriorityLua() end 
function CCBatchNode:removeChildByTag() end 
function CCBatchNode:convertToNodeSpaceAR() end 
function CCBatchNode:convertTouchToNodeSpaceAR() end 
function CCBatchNode:convertToWorldSpaceAR() end 
function CCBatchNode:setRotation() end 
function CCBatchNode:getComponent() end 
function CCBatchNode:convertToNodeSpace() end 
---
-- @return @class CCBatchNode
--
function CCBatchNode:create() end 
function CCBatchNode:getScale() end 
function CCBatchNode:getPositionY() end 
function CCBatchNode:getChildByTag() end 
function CCBatchNode:setContentSize() end 
function CCBatchNode:description() end 
function CCBatchNode:cleanup() end 
function CCBatchNode:getRotation() end 
function CCBatchNode:nodeToParentTransform() end 
function CCBatchNode:stopAction() end 
function CCBatchNode:numberOfRunningActions() end 
function CCBatchNode:removeAllChildren() end 
function CCBatchNode:runAction() end 
function CCBatchNode:setUserObject() end 
function CCBatchNode:parentToNodeTransform() end 
function CCBatchNode:removeChild() end 
function CCBatchNode:getAnchorPointInPoints() end 
function CCBatchNode:getScaleX() end 
function CCBatchNode:transform() end 
function CCBatchNode:getActionManager() end 
function CCBatchNode:draw() end 
function CCBatchNode:setScaleY() end 
function CCBatchNode:unregisterScriptHandler() end 
function CCBatchNode:setVertexZ() end 
function CCBatchNode:setAnchorPoint() end 
function CCBatchNode:getShaderProgram() end 
function CCBatchNode:stopAllActions() end 
function CCBatchNode:setUserData() end 
function CCBatchNode:setShaderProgram() end 
function CCBatchNode:getActionByTag() end 
function CCBatchNode:getGLServerState() end 
function CCBatchNode:getOrderOfArrival() end 
function CCBatchNode:getPositionX() end 
function CCBatchNode:setGLServerState() end 
function CCBatchNode:setSkewY() end 
function CCBatchNode:setOrderOfArrival() end 
function CCBatchNode:nodeToWorldTransform() end 
function CCBatchNode:getChildren() end 
function CCBatchNode:transformAncestors() end 
function CCBatchNode:getGrid() end 
function CCBatchNode:isRunning() end 
function CCBatchNode:registerScriptHandler() end 
function CCBatchNode:getCamera() end 
function CCBatchNode:isIgnoreAnchorPointForPosition() end 
function CCBatchNode:getUserData() end 
function CCBatchNode:setPositionY() end 
function CCBatchNode:getZOrder() end 
function CCBatchNode:new() end 
function CCBatchNode:addChild() end 
---
-- @return @class CCBatchNode
--
function CCBatchNode:create() end 
function CCBatchNode:delete() end 
function CCBatchNode:new_local() end 
function CCBatchNode:removeChild() end 
function CCBatchNode:getTexureAtlasWithTexture() end 
