---@classdef CCBone
CCBone = {}
function CCBone:autorelease() end 
function CCBone:retain() end 
function CCBone:retainCount() end 
function CCBone:isEqual() end 
function CCBone:copy() end 
function CCBone:release() end 
function CCBone:isSingleReference() end 
function CCBone:visit() end 
function CCBone:getUserObject() end 
function CCBone:getSkewY() end 
function CCBone:convertTouchToNodeSpace() end 
function CCBone:getVertexZ() end 
function CCBone:setParent() end 
function CCBone:boundingBox() end 
function CCBone:setVisible() end 
function CCBone:stopActionByTag() end 
function CCBone:getScaleY() end 
function CCBone:setScaleX() end 
function CCBone:reorderChild() end 
function CCBone:setPositionX() end 
function CCBone:removeFromParentAndCleanup() end 
function CCBone:setTag() end 
function CCBone:getChildrenCount() end 
function CCBone:setScale() end 
function CCBone:addChild() end 
function CCBone:isVisible() end 
function CCBone:setActionManager() end 
function CCBone:setScheduler() end 
function CCBone:getContentSize() end 
function CCBone:getAnchorPoint() end 
function CCBone:getTag() end 
function CCBone:setGrid() end 
function CCBone:convertToWorldSpace() end 
function CCBone:setSkewX() end 
function CCBone:setZOrder() end 
function CCBone:worldToNodeTransform() end 
function CCBone:getPosition() end 
function CCBone:getSkewX() end 
function CCBone:getScheduler() end 
function CCBone:ignoreAnchorPointForPosition() end 
function CCBone:setPosition() end 
function CCBone:getParent() end 
function CCBone:unscheduleUpdate() end 
function CCBone:scheduleUpdateWithPriorityLua() end 
function CCBone:removeChildByTag() end 
function CCBone:convertToNodeSpaceAR() end 
function CCBone:convertTouchToNodeSpaceAR() end 
function CCBone:convertToWorldSpaceAR() end 
function CCBone:setRotation() end 
function CCBone:getComponent() end 
function CCBone:convertToNodeSpace() end 
---
-- @return @class CCBone
--
function CCBone:create() end 
function CCBone:getScale() end 
function CCBone:getPositionY() end 
function CCBone:getChildByTag() end 
function CCBone:setContentSize() end 
function CCBone:description() end 
function CCBone:cleanup() end 
function CCBone:getRotation() end 
function CCBone:nodeToParentTransform() end 
function CCBone:stopAction() end 
function CCBone:numberOfRunningActions() end 
function CCBone:removeAllChildren() end 
function CCBone:runAction() end 
function CCBone:setUserObject() end 
function CCBone:parentToNodeTransform() end 
function CCBone:removeChild() end 
function CCBone:getAnchorPointInPoints() end 
function CCBone:getScaleX() end 
function CCBone:transform() end 
function CCBone:getActionManager() end 
function CCBone:draw() end 
function CCBone:setScaleY() end 
function CCBone:unregisterScriptHandler() end 
function CCBone:setVertexZ() end 
function CCBone:setAnchorPoint() end 
function CCBone:getShaderProgram() end 
function CCBone:stopAllActions() end 
function CCBone:setUserData() end 
function CCBone:setShaderProgram() end 
function CCBone:getActionByTag() end 
function CCBone:getGLServerState() end 
function CCBone:getOrderOfArrival() end 
function CCBone:getPositionX() end 
function CCBone:setGLServerState() end 
function CCBone:setSkewY() end 
function CCBone:setOrderOfArrival() end 
function CCBone:nodeToWorldTransform() end 
function CCBone:getChildren() end 
function CCBone:transformAncestors() end 
function CCBone:getGrid() end 
function CCBone:isRunning() end 
function CCBone:registerScriptHandler() end 
function CCBone:getCamera() end 
function CCBone:isIgnoreAnchorPointForPosition() end 
function CCBone:getUserData() end 
function CCBone:setPositionY() end 
function CCBone:getZOrder() end 
function CCBone:new() end 
function CCBone:delete() end 
function CCBone:updateDisplayedColor() end 
function CCBone:init() end 
function CCBone:setColor() end 
function CCBone:getDisplayedColor() end 
function CCBone:setCascadeColorEnabled() end 
function CCBone:setCascadeOpacityEnabled() end 
function CCBone:setOpacity() end 
function CCBone:getColor() end 
function CCBone:updateDisplayedOpacity() end 
function CCBone:getOpacity() end 
function CCBone:setOpacityModifyRGB() end 
function CCBone:isCascadeOpacityEnabled() end 
function CCBone:isOpacityModifyRGB() end 
function CCBone:getDisplayedOpacity() end 
function CCBone:new_local() end 
function CCBone:isCascadeColorEnabled() end 
function CCBone:new() end 
function CCBone:removeFromParent() end 
---
-- @return @class CCBone
--
function CCBone:create() end 
function CCBone:delete() end 
function CCBone:updateDisplayedColor() end 
function CCBone:getDisplayRenderNode() end 
function CCBone:init() end 
function CCBone:update() end 
function CCBone:updateZOrder() end 
function CCBone:getTween() end 
function CCBone:setColor() end 
function CCBone:new_local() end 
function CCBone:updateColor() end 
function CCBone:setIgnoreMovementBoneData() end 
function CCBone:getWorldInfo() end 
function CCBone:setName() end 
function CCBone:getName() end 
function CCBone:removeDisplay() end 
function CCBone:setOpacity() end 
function CCBone:nodeToArmatureTransform() end 
function CCBone:getDisplayManager() end 
function CCBone:setDisplayManager() end 
function CCBone:addDisplay() end 
function CCBone:setChildArmature() end 
function CCBone:updateDisplayedOpacity() end 
function CCBone:setArmature() end 
function CCBone:addChildBone() end 
function CCBone:getArmature() end 
function CCBone:isTransformDirty() end 
function CCBone:getIgnoreMovementBoneData() end 
function CCBone:nodeToWorldTransform() end 
function CCBone:removeChildBone() end 
function CCBone:setTransformDirty() end 
function CCBone:getChildArmature() end 
function CCBone:getParentBone() end 
function CCBone:setZOrder() end 
function CCBone:changeDisplayWithIndex() end 
function CCBone:setParentBone() end 
function CCBone:getDisplayRenderNodeType() end 
