---@classdef CCCamera
CCCamera = {}
function CCCamera:autorelease() end 
function CCCamera:retain() end 
function CCCamera:retainCount() end 
function CCCamera:isEqual() end 
function CCCamera:copy() end 
function CCCamera:release() end 
function CCCamera:isSingleReference() end 
function CCCamera:new() end 
function CCCamera:getZEye() end 
function CCCamera:getUpXYZ() end 
function CCCamera:description() end 
function CCCamera:init() end 
function CCCamera:setUpXYZ() end 
function CCCamera:setCenterXYZ() end 
function CCCamera:setEyeXYZ() end 
function CCCamera:restore() end 
function CCCamera:locate() end 
function CCCamera:new_local() end 
function CCCamera:setDirty() end 
function CCCamera:isDirty() end 
function CCCamera:getCenterXYZ() end 
function CCCamera:getEyeXYZ() end 
