---@classdef CCControlButton
CCControlButton = {}
function CCControlButton:autorelease() end 
function CCControlButton:retain() end 
function CCControlButton:retainCount() end 
function CCControlButton:isEqual() end 
function CCControlButton:copy() end 
function CCControlButton:release() end 
function CCControlButton:isSingleReference() end 
function CCControlButton:visit() end 
function CCControlButton:getUserObject() end 
function CCControlButton:getSkewY() end 
function CCControlButton:convertTouchToNodeSpace() end 
function CCControlButton:getVertexZ() end 
function CCControlButton:setParent() end 
function CCControlButton:boundingBox() end 
function CCControlButton:setVisible() end 
function CCControlButton:stopActionByTag() end 
function CCControlButton:getScaleY() end 
function CCControlButton:setScaleX() end 
function CCControlButton:reorderChild() end 
function CCControlButton:setPositionX() end 
function CCControlButton:removeFromParentAndCleanup() end 
function CCControlButton:setTag() end 
function CCControlButton:getChildrenCount() end 
function CCControlButton:setScale() end 
function CCControlButton:addChild() end 
function CCControlButton:isVisible() end 
function CCControlButton:setActionManager() end 
function CCControlButton:setScheduler() end 
function CCControlButton:getContentSize() end 
function CCControlButton:getAnchorPoint() end 
function CCControlButton:getTag() end 
function CCControlButton:setGrid() end 
function CCControlButton:convertToWorldSpace() end 
function CCControlButton:setSkewX() end 
function CCControlButton:setZOrder() end 
function CCControlButton:worldToNodeTransform() end 
function CCControlButton:getPosition() end 
function CCControlButton:getSkewX() end 
function CCControlButton:getScheduler() end 
function CCControlButton:ignoreAnchorPointForPosition() end 
function CCControlButton:setPosition() end 
function CCControlButton:getParent() end 
function CCControlButton:unscheduleUpdate() end 
function CCControlButton:scheduleUpdateWithPriorityLua() end 
function CCControlButton:removeChildByTag() end 
function CCControlButton:convertToNodeSpaceAR() end 
function CCControlButton:convertTouchToNodeSpaceAR() end 
function CCControlButton:convertToWorldSpaceAR() end 
function CCControlButton:setRotation() end 
function CCControlButton:getComponent() end 
function CCControlButton:convertToNodeSpace() end 
---
-- @return @class CCControlButton
--
function CCControlButton:create() end 
function CCControlButton:getScale() end 
function CCControlButton:getPositionY() end 
function CCControlButton:getChildByTag() end 
function CCControlButton:setContentSize() end 
function CCControlButton:description() end 
function CCControlButton:cleanup() end 
function CCControlButton:getRotation() end 
function CCControlButton:nodeToParentTransform() end 
function CCControlButton:stopAction() end 
function CCControlButton:numberOfRunningActions() end 
function CCControlButton:removeAllChildren() end 
function CCControlButton:runAction() end 
function CCControlButton:setUserObject() end 
function CCControlButton:parentToNodeTransform() end 
function CCControlButton:removeChild() end 
function CCControlButton:getAnchorPointInPoints() end 
function CCControlButton:getScaleX() end 
function CCControlButton:transform() end 
function CCControlButton:getActionManager() end 
function CCControlButton:draw() end 
function CCControlButton:setScaleY() end 
function CCControlButton:unregisterScriptHandler() end 
function CCControlButton:setVertexZ() end 
function CCControlButton:setAnchorPoint() end 
function CCControlButton:getShaderProgram() end 
function CCControlButton:stopAllActions() end 
function CCControlButton:setUserData() end 
function CCControlButton:setShaderProgram() end 
function CCControlButton:getActionByTag() end 
function CCControlButton:getGLServerState() end 
function CCControlButton:getOrderOfArrival() end 
function CCControlButton:getPositionX() end 
function CCControlButton:setGLServerState() end 
function CCControlButton:setSkewY() end 
function CCControlButton:setOrderOfArrival() end 
function CCControlButton:nodeToWorldTransform() end 
function CCControlButton:getChildren() end 
function CCControlButton:transformAncestors() end 
function CCControlButton:getGrid() end 
function CCControlButton:isRunning() end 
function CCControlButton:registerScriptHandler() end 
function CCControlButton:getCamera() end 
function CCControlButton:isIgnoreAnchorPointForPosition() end 
function CCControlButton:getUserData() end 
function CCControlButton:setPositionY() end 
function CCControlButton:getZOrder() end 
function CCControlButton:isTouchEnabled() end 
function CCControlButton:unregisterScriptKeypadHandler() end 
function CCControlButton:registerScriptAccelerateHandler() end 
---
-- @return @class CCControlButton
--
function CCControlButton:create() end 
function CCControlButton:setAccelerometerEnabled() end 
function CCControlButton:registerScriptKeypadHandler() end 
function CCControlButton:setTouchMode() end 
function CCControlButton:isAccelerometerEnabled() end 
function CCControlButton:setTouchEnabled() end 
function CCControlButton:setTouchPriority() end 
function CCControlButton:unregisterScriptAccelerateHandler() end 
function CCControlButton:unregisterScriptTouchHandler() end 
function CCControlButton:setKeypadEnabled() end 
function CCControlButton:registerScriptTouchHandler() end 
function CCControlButton:getTouchPriority() end 
function CCControlButton:isKeypadEnabled() end 
function CCControlButton:getTouchMode() end 
function CCControlButton:new() end 
---
-- @return @class CCControlButton
--
function CCControlButton:create() end 
function CCControlButton:delete() end 
function CCControlButton:updateDisplayedColor() end 
function CCControlButton:init() end 
function CCControlButton:setColor() end 
function CCControlButton:getDisplayedColor() end 
function CCControlButton:setCascadeColorEnabled() end 
function CCControlButton:setCascadeOpacityEnabled() end 
function CCControlButton:setOpacity() end 
function CCControlButton:getColor() end 
function CCControlButton:updateDisplayedOpacity() end 
function CCControlButton:getOpacity() end 
function CCControlButton:setOpacityModifyRGB() end 
function CCControlButton:isOpacityModifyRGB() end 
function CCControlButton:isCascadeOpacityEnabled() end 
function CCControlButton:getDisplayedOpacity() end 
function CCControlButton:new_local() end 
function CCControlButton:isCascadeColorEnabled() end 
function CCControlButton:onEnter() end 
function CCControlButton:new() end 
function CCControlButton:setEnabled() end 
function CCControlButton:delete() end 
function CCControlButton:init() end 
function CCControlButton:isHighlighted() end 
function CCControlButton:new_local() end 
function CCControlButton:setHighlighted() end 
function CCControlButton:isEnabled() end 
function CCControlButton:onExit() end 
function CCControlButton:registerWithTouchDispatcher() end 
function CCControlButton:addTargetWithActionForControlEvents() end 
function CCControlButton:addHandleOfControlEvent() end 
function CCControlButton:isTouchInside() end 
function CCControlButton:isSelected() end 
function CCControlButton:setSelected() end 
function CCControlButton:setOpacityModifyRGB() end 
function CCControlButton:removeHandleOfControlEvent() end 
function CCControlButton:sendActionsForControlEvents() end 
function CCControlButton:getState() end 
function CCControlButton:needsLayout() end 
function CCControlButton:hasVisibleParents() end 
function CCControlButton:isOpacityModifyRGB() end 
function CCControlButton:removeTargetWithActionForControlEvents() end 
function CCControlButton:getTouchLocation() end 
function CCControlButton:getBackgroundSpriteDispatchTable() end 
function CCControlButton:ccTouchMoved() end 
function CCControlButton:ccTouchBegan() end 
function CCControlButton:setTitleColorDispatchTable() end 
function CCControlButton:doesAdjustBackgroundImage() end 
function CCControlButton:getTitleTTFSizeForState() end 
function CCControlButton:getCurrentTitle() end 
function CCControlButton:ccTouchEnded() end 
function CCControlButton:initWithLabelAndBackgroundSprite() end 
function CCControlButton:initWithTitleAndFontNameAndFontSize() end 
function CCControlButton:getBackgroundSpriteForState() end 
function CCControlButton:new_local() end 
function CCControlButton:initWithBackgroundSprite() end 
function CCControlButton:setTitleBMFontForState() end 
function CCControlButton:getPreferredSize() end 
function CCControlButton:getTitleColorForState() end 
function CCControlButton:setPreferredSize() end 
function CCControlButton:setSelected() end 
function CCControlButton:setAdjustBackgroundImage() end 
function CCControlButton:getTitleDispatchTable() end 
function CCControlButton:getTitleTTFForState() end 
function CCControlButton:needsLayout() end 
function CCControlButton:setBackgroundSprite() end 
function CCControlButton:getTitleLabel() end 
function CCControlButton:getCurrentTitleColor() end 
function CCControlButton:setTitleLabel() end 
function CCControlButton:new() end 
---
-- @return @class CCControlButton
--
function CCControlButton:create() end 
function CCControlButton:delete() end 
function CCControlButton:getTitleLabelDispatchTable() end 
function CCControlButton:getTitleLabelForState() end 
function CCControlButton:init() end 
function CCControlButton:isPushed() end 
function CCControlButton:getTitleForState() end 
function CCControlButton:setHighlighted() end 
function CCControlButton:setTitleTTFForState() end 
function CCControlButton:getLabelAnchorPoint() end 
function CCControlButton:setTitleDispatchTable() end 
function CCControlButton:setOpacity() end 
function CCControlButton:getZoomOnTouchDown() end 
function CCControlButton:setBackgroundSpriteFrameForState() end 
function CCControlButton:setTitleLabelForState() end 
function CCControlButton:getBackgroundSprite() end 
function CCControlButton:setTitleColorForState() end 
function CCControlButton:getHorizontalOrigin() end 
function CCControlButton:setTitleForState() end 
function CCControlButton:getOpacity() end 
function CCControlButton:setEnabled() end 
function CCControlButton:setZoomOnTouchDown() end 
function CCControlButton:setBackgroundSpriteDispatchTable() end 
function CCControlButton:setLabelAnchorPoint() end 
function CCControlButton:getTitleBMFontForState() end 
function CCControlButton:ccTouchCancelled() end 
function CCControlButton:getVerticalMargin() end 
function CCControlButton:setTitleLabelDispatchTable() end 
function CCControlButton:getTitleColorDispatchTable() end 
function CCControlButton:setMargins() end 
function CCControlButton:setTitleTTFSizeForState() end 
function CCControlButton:setBackgroundSpriteForState() end 
