---@classdef CCControl
CCControl = {}
function CCControl:autorelease() end 
function CCControl:retain() end 
function CCControl:retainCount() end 
function CCControl:isEqual() end 
function CCControl:copy() end 
function CCControl:release() end 
function CCControl:isSingleReference() end 
function CCControl:visit() end 
function CCControl:getUserObject() end 
function CCControl:getSkewY() end 
function CCControl:convertTouchToNodeSpace() end 
function CCControl:getVertexZ() end 
function CCControl:setParent() end 
function CCControl:boundingBox() end 
function CCControl:setVisible() end 
function CCControl:stopActionByTag() end 
function CCControl:getScaleY() end 
function CCControl:setScaleX() end 
function CCControl:reorderChild() end 
function CCControl:setPositionX() end 
function CCControl:removeFromParentAndCleanup() end 
function CCControl:setTag() end 
function CCControl:getChildrenCount() end 
function CCControl:setScale() end 
function CCControl:addChild() end 
function CCControl:isVisible() end 
function CCControl:setActionManager() end 
function CCControl:setScheduler() end 
function CCControl:getContentSize() end 
function CCControl:getAnchorPoint() end 
function CCControl:getTag() end 
function CCControl:setGrid() end 
function CCControl:convertToWorldSpace() end 
function CCControl:setSkewX() end 
function CCControl:setZOrder() end 
function CCControl:worldToNodeTransform() end 
function CCControl:getPosition() end 
function CCControl:getSkewX() end 
function CCControl:getScheduler() end 
function CCControl:ignoreAnchorPointForPosition() end 
function CCControl:setPosition() end 
function CCControl:getParent() end 
function CCControl:unscheduleUpdate() end 
function CCControl:scheduleUpdateWithPriorityLua() end 
function CCControl:removeChildByTag() end 
function CCControl:convertToNodeSpaceAR() end 
function CCControl:convertTouchToNodeSpaceAR() end 
function CCControl:convertToWorldSpaceAR() end 
function CCControl:setRotation() end 
function CCControl:getComponent() end 
function CCControl:convertToNodeSpace() end 
---
-- @return @class CCControl
--
function CCControl:create() end 
function CCControl:getScale() end 
function CCControl:getPositionY() end 
function CCControl:getChildByTag() end 
function CCControl:setContentSize() end 
function CCControl:description() end 
function CCControl:cleanup() end 
function CCControl:getRotation() end 
function CCControl:nodeToParentTransform() end 
function CCControl:stopAction() end 
function CCControl:numberOfRunningActions() end 
function CCControl:removeAllChildren() end 
function CCControl:runAction() end 
function CCControl:setUserObject() end 
function CCControl:parentToNodeTransform() end 
function CCControl:removeChild() end 
function CCControl:getAnchorPointInPoints() end 
function CCControl:getScaleX() end 
function CCControl:transform() end 
function CCControl:getActionManager() end 
function CCControl:draw() end 
function CCControl:setScaleY() end 
function CCControl:unregisterScriptHandler() end 
function CCControl:setVertexZ() end 
function CCControl:setAnchorPoint() end 
function CCControl:getShaderProgram() end 
function CCControl:stopAllActions() end 
function CCControl:setUserData() end 
function CCControl:setShaderProgram() end 
function CCControl:getActionByTag() end 
function CCControl:getGLServerState() end 
function CCControl:getOrderOfArrival() end 
function CCControl:getPositionX() end 
function CCControl:setGLServerState() end 
function CCControl:setSkewY() end 
function CCControl:setOrderOfArrival() end 
function CCControl:nodeToWorldTransform() end 
function CCControl:getChildren() end 
function CCControl:transformAncestors() end 
function CCControl:getGrid() end 
function CCControl:isRunning() end 
function CCControl:registerScriptHandler() end 
function CCControl:getCamera() end 
function CCControl:isIgnoreAnchorPointForPosition() end 
function CCControl:getUserData() end 
function CCControl:setPositionY() end 
function CCControl:getZOrder() end 
function CCControl:isTouchEnabled() end 
function CCControl:unregisterScriptKeypadHandler() end 
function CCControl:registerScriptAccelerateHandler() end 
---
-- @return @class CCControl
--
function CCControl:create() end 
function CCControl:setAccelerometerEnabled() end 
function CCControl:registerScriptKeypadHandler() end 
function CCControl:setTouchMode() end 
function CCControl:isAccelerometerEnabled() end 
function CCControl:setTouchEnabled() end 
function CCControl:setTouchPriority() end 
function CCControl:unregisterScriptAccelerateHandler() end 
function CCControl:unregisterScriptTouchHandler() end 
function CCControl:setKeypadEnabled() end 
function CCControl:registerScriptTouchHandler() end 
function CCControl:getTouchPriority() end 
function CCControl:isKeypadEnabled() end 
function CCControl:getTouchMode() end 
function CCControl:new() end 
---
-- @return @class CCControl
--
function CCControl:create() end 
function CCControl:delete() end 
function CCControl:updateDisplayedColor() end 
function CCControl:init() end 
function CCControl:setColor() end 
function CCControl:getDisplayedColor() end 
function CCControl:setCascadeColorEnabled() end 
function CCControl:setCascadeOpacityEnabled() end 
function CCControl:setOpacity() end 
function CCControl:getColor() end 
function CCControl:updateDisplayedOpacity() end 
function CCControl:getOpacity() end 
function CCControl:setOpacityModifyRGB() end 
function CCControl:isOpacityModifyRGB() end 
function CCControl:isCascadeOpacityEnabled() end 
function CCControl:getDisplayedOpacity() end 
function CCControl:new_local() end 
function CCControl:isCascadeColorEnabled() end 
function CCControl:onEnter() end 
function CCControl:new() end 
function CCControl:setEnabled() end 
function CCControl:delete() end 
function CCControl:init() end 
function CCControl:isHighlighted() end 
function CCControl:new_local() end 
function CCControl:setHighlighted() end 
function CCControl:isEnabled() end 
function CCControl:onExit() end 
function CCControl:registerWithTouchDispatcher() end 
function CCControl:addTargetWithActionForControlEvents() end 
function CCControl:addHandleOfControlEvent() end 
function CCControl:isTouchInside() end 
function CCControl:isSelected() end 
function CCControl:setSelected() end 
function CCControl:setOpacityModifyRGB() end 
function CCControl:removeHandleOfControlEvent() end 
function CCControl:sendActionsForControlEvents() end 
function CCControl:getState() end 
function CCControl:needsLayout() end 
function CCControl:hasVisibleParents() end 
function CCControl:isOpacityModifyRGB() end 
function CCControl:removeTargetWithActionForControlEvents() end 
function CCControl:getTouchLocation() end 
