---@classdef CCControlSwitch
CCControlSwitch = {}
function CCControlSwitch:autorelease() end 
function CCControlSwitch:retain() end 
function CCControlSwitch:retainCount() end 
function CCControlSwitch:isEqual() end 
function CCControlSwitch:copy() end 
function CCControlSwitch:release() end 
function CCControlSwitch:isSingleReference() end 
function CCControlSwitch:visit() end 
function CCControlSwitch:getUserObject() end 
function CCControlSwitch:getSkewY() end 
function CCControlSwitch:convertTouchToNodeSpace() end 
function CCControlSwitch:getVertexZ() end 
function CCControlSwitch:setParent() end 
function CCControlSwitch:boundingBox() end 
function CCControlSwitch:setVisible() end 
function CCControlSwitch:stopActionByTag() end 
function CCControlSwitch:getScaleY() end 
function CCControlSwitch:setScaleX() end 
function CCControlSwitch:reorderChild() end 
function CCControlSwitch:setPositionX() end 
function CCControlSwitch:removeFromParentAndCleanup() end 
function CCControlSwitch:setTag() end 
function CCControlSwitch:getChildrenCount() end 
function CCControlSwitch:setScale() end 
function CCControlSwitch:addChild() end 
function CCControlSwitch:isVisible() end 
function CCControlSwitch:setActionManager() end 
function CCControlSwitch:setScheduler() end 
function CCControlSwitch:getContentSize() end 
function CCControlSwitch:getAnchorPoint() end 
function CCControlSwitch:getTag() end 
function CCControlSwitch:setGrid() end 
function CCControlSwitch:convertToWorldSpace() end 
function CCControlSwitch:setSkewX() end 
function CCControlSwitch:setZOrder() end 
function CCControlSwitch:worldToNodeTransform() end 
function CCControlSwitch:getPosition() end 
function CCControlSwitch:getSkewX() end 
function CCControlSwitch:getScheduler() end 
function CCControlSwitch:ignoreAnchorPointForPosition() end 
function CCControlSwitch:setPosition() end 
function CCControlSwitch:getParent() end 
function CCControlSwitch:unscheduleUpdate() end 
function CCControlSwitch:scheduleUpdateWithPriorityLua() end 
function CCControlSwitch:removeChildByTag() end 
function CCControlSwitch:convertToNodeSpaceAR() end 
function CCControlSwitch:convertTouchToNodeSpaceAR() end 
function CCControlSwitch:convertToWorldSpaceAR() end 
function CCControlSwitch:setRotation() end 
function CCControlSwitch:getComponent() end 
function CCControlSwitch:convertToNodeSpace() end 
---
-- @return @class CCControlSwitch
--
function CCControlSwitch:create() end 
function CCControlSwitch:getScale() end 
function CCControlSwitch:getPositionY() end 
function CCControlSwitch:getChildByTag() end 
function CCControlSwitch:setContentSize() end 
function CCControlSwitch:description() end 
function CCControlSwitch:cleanup() end 
function CCControlSwitch:getRotation() end 
function CCControlSwitch:nodeToParentTransform() end 
function CCControlSwitch:stopAction() end 
function CCControlSwitch:numberOfRunningActions() end 
function CCControlSwitch:removeAllChildren() end 
function CCControlSwitch:runAction() end 
function CCControlSwitch:setUserObject() end 
function CCControlSwitch:parentToNodeTransform() end 
function CCControlSwitch:removeChild() end 
function CCControlSwitch:getAnchorPointInPoints() end 
function CCControlSwitch:getScaleX() end 
function CCControlSwitch:transform() end 
function CCControlSwitch:getActionManager() end 
function CCControlSwitch:draw() end 
function CCControlSwitch:setScaleY() end 
function CCControlSwitch:unregisterScriptHandler() end 
function CCControlSwitch:setVertexZ() end 
function CCControlSwitch:setAnchorPoint() end 
function CCControlSwitch:getShaderProgram() end 
function CCControlSwitch:stopAllActions() end 
function CCControlSwitch:setUserData() end 
function CCControlSwitch:setShaderProgram() end 
function CCControlSwitch:getActionByTag() end 
function CCControlSwitch:getGLServerState() end 
function CCControlSwitch:getOrderOfArrival() end 
function CCControlSwitch:getPositionX() end 
function CCControlSwitch:setGLServerState() end 
function CCControlSwitch:setSkewY() end 
function CCControlSwitch:setOrderOfArrival() end 
function CCControlSwitch:nodeToWorldTransform() end 
function CCControlSwitch:getChildren() end 
function CCControlSwitch:transformAncestors() end 
function CCControlSwitch:getGrid() end 
function CCControlSwitch:isRunning() end 
function CCControlSwitch:registerScriptHandler() end 
function CCControlSwitch:getCamera() end 
function CCControlSwitch:isIgnoreAnchorPointForPosition() end 
function CCControlSwitch:getUserData() end 
function CCControlSwitch:setPositionY() end 
function CCControlSwitch:getZOrder() end 
function CCControlSwitch:isTouchEnabled() end 
function CCControlSwitch:unregisterScriptKeypadHandler() end 
function CCControlSwitch:registerScriptAccelerateHandler() end 
---
-- @return @class CCControlSwitch
--
function CCControlSwitch:create() end 
function CCControlSwitch:setAccelerometerEnabled() end 
function CCControlSwitch:registerScriptKeypadHandler() end 
function CCControlSwitch:setTouchMode() end 
function CCControlSwitch:isAccelerometerEnabled() end 
function CCControlSwitch:setTouchEnabled() end 
function CCControlSwitch:setTouchPriority() end 
function CCControlSwitch:unregisterScriptAccelerateHandler() end 
function CCControlSwitch:unregisterScriptTouchHandler() end 
function CCControlSwitch:setKeypadEnabled() end 
function CCControlSwitch:registerScriptTouchHandler() end 
function CCControlSwitch:getTouchPriority() end 
function CCControlSwitch:isKeypadEnabled() end 
function CCControlSwitch:getTouchMode() end 
function CCControlSwitch:new() end 
---
-- @return @class CCControlSwitch
--
function CCControlSwitch:create() end 
function CCControlSwitch:delete() end 
function CCControlSwitch:updateDisplayedColor() end 
function CCControlSwitch:init() end 
function CCControlSwitch:setColor() end 
function CCControlSwitch:getDisplayedColor() end 
function CCControlSwitch:setCascadeColorEnabled() end 
function CCControlSwitch:setCascadeOpacityEnabled() end 
function CCControlSwitch:setOpacity() end 
function CCControlSwitch:getColor() end 
function CCControlSwitch:updateDisplayedOpacity() end 
function CCControlSwitch:getOpacity() end 
function CCControlSwitch:setOpacityModifyRGB() end 
function CCControlSwitch:isOpacityModifyRGB() end 
function CCControlSwitch:isCascadeOpacityEnabled() end 
function CCControlSwitch:getDisplayedOpacity() end 
function CCControlSwitch:new_local() end 
function CCControlSwitch:isCascadeColorEnabled() end 
function CCControlSwitch:onEnter() end 
function CCControlSwitch:new() end 
function CCControlSwitch:setEnabled() end 
function CCControlSwitch:delete() end 
function CCControlSwitch:init() end 
function CCControlSwitch:isHighlighted() end 
function CCControlSwitch:new_local() end 
function CCControlSwitch:setHighlighted() end 
function CCControlSwitch:isEnabled() end 
function CCControlSwitch:onExit() end 
function CCControlSwitch:registerWithTouchDispatcher() end 
function CCControlSwitch:addTargetWithActionForControlEvents() end 
function CCControlSwitch:addHandleOfControlEvent() end 
function CCControlSwitch:isTouchInside() end 
function CCControlSwitch:isSelected() end 
function CCControlSwitch:setSelected() end 
function CCControlSwitch:setOpacityModifyRGB() end 
function CCControlSwitch:removeHandleOfControlEvent() end 
function CCControlSwitch:sendActionsForControlEvents() end 
function CCControlSwitch:getState() end 
function CCControlSwitch:needsLayout() end 
function CCControlSwitch:hasVisibleParents() end 
function CCControlSwitch:isOpacityModifyRGB() end 
function CCControlSwitch:removeTargetWithActionForControlEvents() end 
function CCControlSwitch:getTouchLocation() end 
function CCControlSwitch:hasMoved() end 
function CCControlSwitch:ccTouchMoved() end 
function CCControlSwitch:new() end 
function CCControlSwitch:delete() end 
function CCControlSwitch:isOn() end 
function CCControlSwitch:ccTouchEnded() end 
function CCControlSwitch:ccTouchCancelled() end 
function CCControlSwitch:ccTouchBegan() end 
function CCControlSwitch:locationFromTouch() end 
function CCControlSwitch:new_local() end 
function CCControlSwitch:setEnabled() end 
function CCControlSwitch:setOn() end 
---
-- @return @class CCControlSwitch
--
function CCControlSwitch:create() end 
function CCControlSwitch:initWithMaskSprite() end 
