---@classdef CCControlStepper
CCControlStepper = {}
function CCControlStepper:autorelease() end 
function CCControlStepper:retain() end 
function CCControlStepper:retainCount() end 
function CCControlStepper:isEqual() end 
function CCControlStepper:copy() end 
function CCControlStepper:release() end 
function CCControlStepper:isSingleReference() end 
function CCControlStepper:visit() end 
function CCControlStepper:getUserObject() end 
function CCControlStepper:getSkewY() end 
function CCControlStepper:convertTouchToNodeSpace() end 
function CCControlStepper:getVertexZ() end 
function CCControlStepper:setParent() end 
function CCControlStepper:boundingBox() end 
function CCControlStepper:setVisible() end 
function CCControlStepper:stopActionByTag() end 
function CCControlStepper:getScaleY() end 
function CCControlStepper:setScaleX() end 
function CCControlStepper:reorderChild() end 
function CCControlStepper:setPositionX() end 
function CCControlStepper:removeFromParentAndCleanup() end 
function CCControlStepper:setTag() end 
function CCControlStepper:getChildrenCount() end 
function CCControlStepper:setScale() end 
function CCControlStepper:addChild() end 
function CCControlStepper:isVisible() end 
function CCControlStepper:setActionManager() end 
function CCControlStepper:setScheduler() end 
function CCControlStepper:getContentSize() end 
function CCControlStepper:getAnchorPoint() end 
function CCControlStepper:getTag() end 
function CCControlStepper:setGrid() end 
function CCControlStepper:convertToWorldSpace() end 
function CCControlStepper:setSkewX() end 
function CCControlStepper:setZOrder() end 
function CCControlStepper:worldToNodeTransform() end 
function CCControlStepper:getPosition() end 
function CCControlStepper:getSkewX() end 
function CCControlStepper:getScheduler() end 
function CCControlStepper:ignoreAnchorPointForPosition() end 
function CCControlStepper:setPosition() end 
function CCControlStepper:getParent() end 
function CCControlStepper:unscheduleUpdate() end 
function CCControlStepper:scheduleUpdateWithPriorityLua() end 
function CCControlStepper:removeChildByTag() end 
function CCControlStepper:convertToNodeSpaceAR() end 
function CCControlStepper:convertTouchToNodeSpaceAR() end 
function CCControlStepper:convertToWorldSpaceAR() end 
function CCControlStepper:setRotation() end 
function CCControlStepper:getComponent() end 
function CCControlStepper:convertToNodeSpace() end 
---
-- @return @class CCControlStepper
--
function CCControlStepper:create() end 
function CCControlStepper:getScale() end 
function CCControlStepper:getPositionY() end 
function CCControlStepper:getChildByTag() end 
function CCControlStepper:setContentSize() end 
function CCControlStepper:description() end 
function CCControlStepper:cleanup() end 
function CCControlStepper:getRotation() end 
function CCControlStepper:nodeToParentTransform() end 
function CCControlStepper:stopAction() end 
function CCControlStepper:numberOfRunningActions() end 
function CCControlStepper:removeAllChildren() end 
function CCControlStepper:runAction() end 
function CCControlStepper:setUserObject() end 
function CCControlStepper:parentToNodeTransform() end 
function CCControlStepper:removeChild() end 
function CCControlStepper:getAnchorPointInPoints() end 
function CCControlStepper:getScaleX() end 
function CCControlStepper:transform() end 
function CCControlStepper:getActionManager() end 
function CCControlStepper:draw() end 
function CCControlStepper:setScaleY() end 
function CCControlStepper:unregisterScriptHandler() end 
function CCControlStepper:setVertexZ() end 
function CCControlStepper:setAnchorPoint() end 
function CCControlStepper:getShaderProgram() end 
function CCControlStepper:stopAllActions() end 
function CCControlStepper:setUserData() end 
function CCControlStepper:setShaderProgram() end 
function CCControlStepper:getActionByTag() end 
function CCControlStepper:getGLServerState() end 
function CCControlStepper:getOrderOfArrival() end 
function CCControlStepper:getPositionX() end 
function CCControlStepper:setGLServerState() end 
function CCControlStepper:setSkewY() end 
function CCControlStepper:setOrderOfArrival() end 
function CCControlStepper:nodeToWorldTransform() end 
function CCControlStepper:getChildren() end 
function CCControlStepper:transformAncestors() end 
function CCControlStepper:getGrid() end 
function CCControlStepper:isRunning() end 
function CCControlStepper:registerScriptHandler() end 
function CCControlStepper:getCamera() end 
function CCControlStepper:isIgnoreAnchorPointForPosition() end 
function CCControlStepper:getUserData() end 
function CCControlStepper:setPositionY() end 
function CCControlStepper:getZOrder() end 
function CCControlStepper:isTouchEnabled() end 
function CCControlStepper:unregisterScriptKeypadHandler() end 
function CCControlStepper:registerScriptAccelerateHandler() end 
---
-- @return @class CCControlStepper
--
function CCControlStepper:create() end 
function CCControlStepper:setAccelerometerEnabled() end 
function CCControlStepper:registerScriptKeypadHandler() end 
function CCControlStepper:setTouchMode() end 
function CCControlStepper:isAccelerometerEnabled() end 
function CCControlStepper:setTouchEnabled() end 
function CCControlStepper:setTouchPriority() end 
function CCControlStepper:unregisterScriptAccelerateHandler() end 
function CCControlStepper:unregisterScriptTouchHandler() end 
function CCControlStepper:setKeypadEnabled() end 
function CCControlStepper:registerScriptTouchHandler() end 
function CCControlStepper:getTouchPriority() end 
function CCControlStepper:isKeypadEnabled() end 
function CCControlStepper:getTouchMode() end 
function CCControlStepper:new() end 
---
-- @return @class CCControlStepper
--
function CCControlStepper:create() end 
function CCControlStepper:delete() end 
function CCControlStepper:updateDisplayedColor() end 
function CCControlStepper:init() end 
function CCControlStepper:setColor() end 
function CCControlStepper:getDisplayedColor() end 
function CCControlStepper:setCascadeColorEnabled() end 
function CCControlStepper:setCascadeOpacityEnabled() end 
function CCControlStepper:setOpacity() end 
function CCControlStepper:getColor() end 
function CCControlStepper:updateDisplayedOpacity() end 
function CCControlStepper:getOpacity() end 
function CCControlStepper:setOpacityModifyRGB() end 
function CCControlStepper:isOpacityModifyRGB() end 
function CCControlStepper:isCascadeOpacityEnabled() end 
function CCControlStepper:getDisplayedOpacity() end 
function CCControlStepper:new_local() end 
function CCControlStepper:isCascadeColorEnabled() end 
function CCControlStepper:onEnter() end 
function CCControlStepper:new() end 
function CCControlStepper:setEnabled() end 
function CCControlStepper:delete() end 
function CCControlStepper:init() end 
function CCControlStepper:isHighlighted() end 
function CCControlStepper:new_local() end 
function CCControlStepper:setHighlighted() end 
function CCControlStepper:isEnabled() end 
function CCControlStepper:onExit() end 
function CCControlStepper:registerWithTouchDispatcher() end 
function CCControlStepper:addTargetWithActionForControlEvents() end 
function CCControlStepper:addHandleOfControlEvent() end 
function CCControlStepper:isTouchInside() end 
function CCControlStepper:isSelected() end 
function CCControlStepper:setSelected() end 
function CCControlStepper:setOpacityModifyRGB() end 
function CCControlStepper:removeHandleOfControlEvent() end 
function CCControlStepper:sendActionsForControlEvents() end 
function CCControlStepper:getState() end 
function CCControlStepper:needsLayout() end 
function CCControlStepper:hasVisibleParents() end 
function CCControlStepper:isOpacityModifyRGB() end 
function CCControlStepper:removeTargetWithActionForControlEvents() end 
function CCControlStepper:getTouchLocation() end 
function CCControlStepper:ccTouchMoved() end 
function CCControlStepper:new() end 
function CCControlStepper:stopAutorepeat() end 
function CCControlStepper:delete() end 
function CCControlStepper:ccTouchEnded() end 
function CCControlStepper:setMinimumValue() end 
function CCControlStepper:new_local() end 
function CCControlStepper:isContinuous() end 
function CCControlStepper:getValue() end 
function CCControlStepper:setWraps() end 
function CCControlStepper:initWithMinusSpriteAndPlusSprite() end 
function CCControlStepper:setMinusLabel() end 
function CCControlStepper:setMaximumValue() end 
function CCControlStepper:getPlusLabel() end 
function CCControlStepper:updateLayoutUsingTouchLocation() end 
function CCControlStepper:setMinusSprite() end 
function CCControlStepper:setPlusLabel() end 
function CCControlStepper:startAutorepeat() end 
function CCControlStepper:getMinusSprite() end 
function CCControlStepper:setPlusSprite() end 
function CCControlStepper:getMinusLabel() end 
function CCControlStepper:setValue() end 
function CCControlStepper:setStepValue() end 
---
-- @return @class CCControlStepper
--
function CCControlStepper:create() end 
function CCControlStepper:getPlusSprite() end 
function CCControlStepper:setValueWithSendingEvent() end 
function CCControlStepper:update() end 
function CCControlStepper:ccTouchBegan() end 
