---@classdef CCControlColourPicker
CCControlColourPicker = {}
function CCControlColourPicker:autorelease() end 
function CCControlColourPicker:retain() end 
function CCControlColourPicker:retainCount() end 
function CCControlColourPicker:isEqual() end 
function CCControlColourPicker:copy() end 
function CCControlColourPicker:release() end 
function CCControlColourPicker:isSingleReference() end 
function CCControlColourPicker:visit() end 
function CCControlColourPicker:getUserObject() end 
function CCControlColourPicker:getSkewY() end 
function CCControlColourPicker:convertTouchToNodeSpace() end 
function CCControlColourPicker:getVertexZ() end 
function CCControlColourPicker:setParent() end 
function CCControlColourPicker:boundingBox() end 
function CCControlColourPicker:setVisible() end 
function CCControlColourPicker:stopActionByTag() end 
function CCControlColourPicker:getScaleY() end 
function CCControlColourPicker:setScaleX() end 
function CCControlColourPicker:reorderChild() end 
function CCControlColourPicker:setPositionX() end 
function CCControlColourPicker:removeFromParentAndCleanup() end 
function CCControlColourPicker:setTag() end 
function CCControlColourPicker:getChildrenCount() end 
function CCControlColourPicker:setScale() end 
function CCControlColourPicker:addChild() end 
function CCControlColourPicker:isVisible() end 
function CCControlColourPicker:setActionManager() end 
function CCControlColourPicker:setScheduler() end 
function CCControlColourPicker:getContentSize() end 
function CCControlColourPicker:getAnchorPoint() end 
function CCControlColourPicker:getTag() end 
function CCControlColourPicker:setGrid() end 
function CCControlColourPicker:convertToWorldSpace() end 
function CCControlColourPicker:setSkewX() end 
function CCControlColourPicker:setZOrder() end 
function CCControlColourPicker:worldToNodeTransform() end 
function CCControlColourPicker:getPosition() end 
function CCControlColourPicker:getSkewX() end 
function CCControlColourPicker:getScheduler() end 
function CCControlColourPicker:ignoreAnchorPointForPosition() end 
function CCControlColourPicker:setPosition() end 
function CCControlColourPicker:getParent() end 
function CCControlColourPicker:unscheduleUpdate() end 
function CCControlColourPicker:scheduleUpdateWithPriorityLua() end 
function CCControlColourPicker:removeChildByTag() end 
function CCControlColourPicker:convertToNodeSpaceAR() end 
function CCControlColourPicker:convertTouchToNodeSpaceAR() end 
function CCControlColourPicker:convertToWorldSpaceAR() end 
function CCControlColourPicker:setRotation() end 
function CCControlColourPicker:getComponent() end 
function CCControlColourPicker:convertToNodeSpace() end 
---
-- @return @class CCControlColourPicker
--
function CCControlColourPicker:create() end 
function CCControlColourPicker:getScale() end 
function CCControlColourPicker:getPositionY() end 
function CCControlColourPicker:getChildByTag() end 
function CCControlColourPicker:setContentSize() end 
function CCControlColourPicker:description() end 
function CCControlColourPicker:cleanup() end 
function CCControlColourPicker:getRotation() end 
function CCControlColourPicker:nodeToParentTransform() end 
function CCControlColourPicker:stopAction() end 
function CCControlColourPicker:numberOfRunningActions() end 
function CCControlColourPicker:removeAllChildren() end 
function CCControlColourPicker:runAction() end 
function CCControlColourPicker:setUserObject() end 
function CCControlColourPicker:parentToNodeTransform() end 
function CCControlColourPicker:removeChild() end 
function CCControlColourPicker:getAnchorPointInPoints() end 
function CCControlColourPicker:getScaleX() end 
function CCControlColourPicker:transform() end 
function CCControlColourPicker:getActionManager() end 
function CCControlColourPicker:draw() end 
function CCControlColourPicker:setScaleY() end 
function CCControlColourPicker:unregisterScriptHandler() end 
function CCControlColourPicker:setVertexZ() end 
function CCControlColourPicker:setAnchorPoint() end 
function CCControlColourPicker:getShaderProgram() end 
function CCControlColourPicker:stopAllActions() end 
function CCControlColourPicker:setUserData() end 
function CCControlColourPicker:setShaderProgram() end 
function CCControlColourPicker:getActionByTag() end 
function CCControlColourPicker:getGLServerState() end 
function CCControlColourPicker:getOrderOfArrival() end 
function CCControlColourPicker:getPositionX() end 
function CCControlColourPicker:setGLServerState() end 
function CCControlColourPicker:setSkewY() end 
function CCControlColourPicker:setOrderOfArrival() end 
function CCControlColourPicker:nodeToWorldTransform() end 
function CCControlColourPicker:getChildren() end 
function CCControlColourPicker:transformAncestors() end 
function CCControlColourPicker:getGrid() end 
function CCControlColourPicker:isRunning() end 
function CCControlColourPicker:registerScriptHandler() end 
function CCControlColourPicker:getCamera() end 
function CCControlColourPicker:isIgnoreAnchorPointForPosition() end 
function CCControlColourPicker:getUserData() end 
function CCControlColourPicker:setPositionY() end 
function CCControlColourPicker:getZOrder() end 
function CCControlColourPicker:isTouchEnabled() end 
function CCControlColourPicker:unregisterScriptKeypadHandler() end 
function CCControlColourPicker:registerScriptAccelerateHandler() end 
---
-- @return @class CCControlColourPicker
--
function CCControlColourPicker:create() end 
function CCControlColourPicker:setAccelerometerEnabled() end 
function CCControlColourPicker:registerScriptKeypadHandler() end 
function CCControlColourPicker:setTouchMode() end 
function CCControlColourPicker:isAccelerometerEnabled() end 
function CCControlColourPicker:setTouchEnabled() end 
function CCControlColourPicker:setTouchPriority() end 
function CCControlColourPicker:unregisterScriptAccelerateHandler() end 
function CCControlColourPicker:unregisterScriptTouchHandler() end 
function CCControlColourPicker:setKeypadEnabled() end 
function CCControlColourPicker:registerScriptTouchHandler() end 
function CCControlColourPicker:getTouchPriority() end 
function CCControlColourPicker:isKeypadEnabled() end 
function CCControlColourPicker:getTouchMode() end 
function CCControlColourPicker:new() end 
---
-- @return @class CCControlColourPicker
--
function CCControlColourPicker:create() end 
function CCControlColourPicker:delete() end 
function CCControlColourPicker:updateDisplayedColor() end 
function CCControlColourPicker:init() end 
function CCControlColourPicker:setColor() end 
function CCControlColourPicker:getDisplayedColor() end 
function CCControlColourPicker:setCascadeColorEnabled() end 
function CCControlColourPicker:setCascadeOpacityEnabled() end 
function CCControlColourPicker:setOpacity() end 
function CCControlColourPicker:getColor() end 
function CCControlColourPicker:updateDisplayedOpacity() end 
function CCControlColourPicker:getOpacity() end 
function CCControlColourPicker:setOpacityModifyRGB() end 
function CCControlColourPicker:isOpacityModifyRGB() end 
function CCControlColourPicker:isCascadeOpacityEnabled() end 
function CCControlColourPicker:getDisplayedOpacity() end 
function CCControlColourPicker:new_local() end 
function CCControlColourPicker:isCascadeColorEnabled() end 
function CCControlColourPicker:onEnter() end 
function CCControlColourPicker:new() end 
function CCControlColourPicker:setEnabled() end 
function CCControlColourPicker:delete() end 
function CCControlColourPicker:init() end 
function CCControlColourPicker:isHighlighted() end 
function CCControlColourPicker:new_local() end 
function CCControlColourPicker:setHighlighted() end 
function CCControlColourPicker:isEnabled() end 
function CCControlColourPicker:onExit() end 
function CCControlColourPicker:registerWithTouchDispatcher() end 
function CCControlColourPicker:addTargetWithActionForControlEvents() end 
function CCControlColourPicker:addHandleOfControlEvent() end 
function CCControlColourPicker:isTouchInside() end 
function CCControlColourPicker:isSelected() end 
function CCControlColourPicker:setSelected() end 
function CCControlColourPicker:setOpacityModifyRGB() end 
function CCControlColourPicker:removeHandleOfControlEvent() end 
function CCControlColourPicker:sendActionsForControlEvents() end 
function CCControlColourPicker:getState() end 
function CCControlColourPicker:needsLayout() end 
function CCControlColourPicker:hasVisibleParents() end 
function CCControlColourPicker:isOpacityModifyRGB() end 
function CCControlColourPicker:removeTargetWithActionForControlEvents() end 
function CCControlColourPicker:getTouchLocation() end 
function CCControlColourPicker:new() end 
function CCControlColourPicker:delete() end 
function CCControlColourPicker:colourSliderValueChanged() end 
function CCControlColourPicker:getBackground() end 
function CCControlColourPicker:getHuePicker() end 
function CCControlColourPicker:init() end 
---
-- @return @class CCControlColourPicker
--
function CCControlColourPicker:create() end 
function CCControlColourPicker:setBackground() end 
function CCControlColourPicker:setColor() end 
function CCControlColourPicker:new_local() end 
function CCControlColourPicker:hueSliderValueChanged() end 
function CCControlColourPicker:setcolourPicker() end 
function CCControlColourPicker:getcolourPicker() end 
function CCControlColourPicker:setEnabled() end 
function CCControlColourPicker:setHuePicker() end 
