---@classdef CCControlSlider
CCControlSlider = {}
function CCControlSlider:autorelease() end 
function CCControlSlider:retain() end 
function CCControlSlider:retainCount() end 
function CCControlSlider:isEqual() end 
function CCControlSlider:copy() end 
function CCControlSlider:release() end 
function CCControlSlider:isSingleReference() end 
function CCControlSlider:visit() end 
function CCControlSlider:getUserObject() end 
function CCControlSlider:getSkewY() end 
function CCControlSlider:convertTouchToNodeSpace() end 
function CCControlSlider:getVertexZ() end 
function CCControlSlider:setParent() end 
function CCControlSlider:boundingBox() end 
function CCControlSlider:setVisible() end 
function CCControlSlider:stopActionByTag() end 
function CCControlSlider:getScaleY() end 
function CCControlSlider:setScaleX() end 
function CCControlSlider:reorderChild() end 
function CCControlSlider:setPositionX() end 
function CCControlSlider:removeFromParentAndCleanup() end 
function CCControlSlider:setTag() end 
function CCControlSlider:getChildrenCount() end 
function CCControlSlider:setScale() end 
function CCControlSlider:addChild() end 
function CCControlSlider:isVisible() end 
function CCControlSlider:setActionManager() end 
function CCControlSlider:setScheduler() end 
function CCControlSlider:getContentSize() end 
function CCControlSlider:getAnchorPoint() end 
function CCControlSlider:getTag() end 
function CCControlSlider:setGrid() end 
function CCControlSlider:convertToWorldSpace() end 
function CCControlSlider:setSkewX() end 
function CCControlSlider:setZOrder() end 
function CCControlSlider:worldToNodeTransform() end 
function CCControlSlider:getPosition() end 
function CCControlSlider:getSkewX() end 
function CCControlSlider:getScheduler() end 
function CCControlSlider:ignoreAnchorPointForPosition() end 
function CCControlSlider:setPosition() end 
function CCControlSlider:getParent() end 
function CCControlSlider:unscheduleUpdate() end 
function CCControlSlider:scheduleUpdateWithPriorityLua() end 
function CCControlSlider:removeChildByTag() end 
function CCControlSlider:convertToNodeSpaceAR() end 
function CCControlSlider:convertTouchToNodeSpaceAR() end 
function CCControlSlider:convertToWorldSpaceAR() end 
function CCControlSlider:setRotation() end 
function CCControlSlider:getComponent() end 
function CCControlSlider:convertToNodeSpace() end 
---
-- @return @class CCControlSlider
--
function CCControlSlider:create() end 
function CCControlSlider:getScale() end 
function CCControlSlider:getPositionY() end 
function CCControlSlider:getChildByTag() end 
function CCControlSlider:setContentSize() end 
function CCControlSlider:description() end 
function CCControlSlider:cleanup() end 
function CCControlSlider:getRotation() end 
function CCControlSlider:nodeToParentTransform() end 
function CCControlSlider:stopAction() end 
function CCControlSlider:numberOfRunningActions() end 
function CCControlSlider:removeAllChildren() end 
function CCControlSlider:runAction() end 
function CCControlSlider:setUserObject() end 
function CCControlSlider:parentToNodeTransform() end 
function CCControlSlider:removeChild() end 
function CCControlSlider:getAnchorPointInPoints() end 
function CCControlSlider:getScaleX() end 
function CCControlSlider:transform() end 
function CCControlSlider:getActionManager() end 
function CCControlSlider:draw() end 
function CCControlSlider:setScaleY() end 
function CCControlSlider:unregisterScriptHandler() end 
function CCControlSlider:setVertexZ() end 
function CCControlSlider:setAnchorPoint() end 
function CCControlSlider:getShaderProgram() end 
function CCControlSlider:stopAllActions() end 
function CCControlSlider:setUserData() end 
function CCControlSlider:setShaderProgram() end 
function CCControlSlider:getActionByTag() end 
function CCControlSlider:getGLServerState() end 
function CCControlSlider:getOrderOfArrival() end 
function CCControlSlider:getPositionX() end 
function CCControlSlider:setGLServerState() end 
function CCControlSlider:setSkewY() end 
function CCControlSlider:setOrderOfArrival() end 
function CCControlSlider:nodeToWorldTransform() end 
function CCControlSlider:getChildren() end 
function CCControlSlider:transformAncestors() end 
function CCControlSlider:getGrid() end 
function CCControlSlider:isRunning() end 
function CCControlSlider:registerScriptHandler() end 
function CCControlSlider:getCamera() end 
function CCControlSlider:isIgnoreAnchorPointForPosition() end 
function CCControlSlider:getUserData() end 
function CCControlSlider:setPositionY() end 
function CCControlSlider:getZOrder() end 
function CCControlSlider:isTouchEnabled() end 
function CCControlSlider:unregisterScriptKeypadHandler() end 
function CCControlSlider:registerScriptAccelerateHandler() end 
---
-- @return @class CCControlSlider
--
function CCControlSlider:create() end 
function CCControlSlider:setAccelerometerEnabled() end 
function CCControlSlider:registerScriptKeypadHandler() end 
function CCControlSlider:setTouchMode() end 
function CCControlSlider:isAccelerometerEnabled() end 
function CCControlSlider:setTouchEnabled() end 
function CCControlSlider:setTouchPriority() end 
function CCControlSlider:unregisterScriptAccelerateHandler() end 
function CCControlSlider:unregisterScriptTouchHandler() end 
function CCControlSlider:setKeypadEnabled() end 
function CCControlSlider:registerScriptTouchHandler() end 
function CCControlSlider:getTouchPriority() end 
function CCControlSlider:isKeypadEnabled() end 
function CCControlSlider:getTouchMode() end 
function CCControlSlider:new() end 
---
-- @return @class CCControlSlider
--
function CCControlSlider:create() end 
function CCControlSlider:delete() end 
function CCControlSlider:updateDisplayedColor() end 
function CCControlSlider:init() end 
function CCControlSlider:setColor() end 
function CCControlSlider:getDisplayedColor() end 
function CCControlSlider:setCascadeColorEnabled() end 
function CCControlSlider:setCascadeOpacityEnabled() end 
function CCControlSlider:setOpacity() end 
function CCControlSlider:getColor() end 
function CCControlSlider:updateDisplayedOpacity() end 
function CCControlSlider:getOpacity() end 
function CCControlSlider:setOpacityModifyRGB() end 
function CCControlSlider:isOpacityModifyRGB() end 
function CCControlSlider:isCascadeOpacityEnabled() end 
function CCControlSlider:getDisplayedOpacity() end 
function CCControlSlider:new_local() end 
function CCControlSlider:isCascadeColorEnabled() end 
function CCControlSlider:onEnter() end 
function CCControlSlider:new() end 
function CCControlSlider:setEnabled() end 
function CCControlSlider:delete() end 
function CCControlSlider:init() end 
function CCControlSlider:isHighlighted() end 
function CCControlSlider:new_local() end 
function CCControlSlider:setHighlighted() end 
function CCControlSlider:isEnabled() end 
function CCControlSlider:onExit() end 
function CCControlSlider:registerWithTouchDispatcher() end 
function CCControlSlider:addTargetWithActionForControlEvents() end 
function CCControlSlider:addHandleOfControlEvent() end 
function CCControlSlider:isTouchInside() end 
function CCControlSlider:isSelected() end 
function CCControlSlider:setSelected() end 
function CCControlSlider:setOpacityModifyRGB() end 
function CCControlSlider:removeHandleOfControlEvent() end 
function CCControlSlider:sendActionsForControlEvents() end 
function CCControlSlider:getState() end 
function CCControlSlider:needsLayout() end 
function CCControlSlider:hasVisibleParents() end 
function CCControlSlider:isOpacityModifyRGB() end 
function CCControlSlider:removeTargetWithActionForControlEvents() end 
function CCControlSlider:getTouchLocation() end 
function CCControlSlider:setMaximumAllowedValue() end 
function CCControlSlider:new() end 
function CCControlSlider:setValue() end 
function CCControlSlider:setMinimumValue() end 
function CCControlSlider:new_local() end 
function CCControlSlider:getThumbSprite() end 
function CCControlSlider:getValue() end 
function CCControlSlider:setMaximumValue() end 
function CCControlSlider:getProgressSprite() end 
function CCControlSlider:getBackgroundSprite() end 
---
-- @return @class CCControlSlider
--
function CCControlSlider:create() end 
function CCControlSlider:setProgressSprite() end 
function CCControlSlider:initWithSprites() end 
function CCControlSlider:delete() end 
function CCControlSlider:setThumbSprite() end 
function CCControlSlider:needsLayout() end 
function CCControlSlider:setBackgroundSprite() end 
function CCControlSlider:setEnabled() end 
function CCControlSlider:getMinimumValue() end 
function CCControlSlider:setMinimumAllowedValue() end 
function CCControlSlider:getMaximumValue() end 
function CCControlSlider:isTouchInside() end 
function CCControlSlider:getMinimumAllowedValue() end 
function CCControlSlider:getMaximumAllowedValue() end 
function CCControlSlider:locationFromTouch() end 
