---@classdef CCControlPotentiometer
CCControlPotentiometer = {}
function CCControlPotentiometer:autorelease() end 
function CCControlPotentiometer:retain() end 
function CCControlPotentiometer:retainCount() end 
function CCControlPotentiometer:isEqual() end 
function CCControlPotentiometer:copy() end 
function CCControlPotentiometer:release() end 
function CCControlPotentiometer:isSingleReference() end 
function CCControlPotentiometer:visit() end 
function CCControlPotentiometer:getUserObject() end 
function CCControlPotentiometer:getSkewY() end 
function CCControlPotentiometer:convertTouchToNodeSpace() end 
function CCControlPotentiometer:getVertexZ() end 
function CCControlPotentiometer:setParent() end 
function CCControlPotentiometer:boundingBox() end 
function CCControlPotentiometer:setVisible() end 
function CCControlPotentiometer:stopActionByTag() end 
function CCControlPotentiometer:getScaleY() end 
function CCControlPotentiometer:setScaleX() end 
function CCControlPotentiometer:reorderChild() end 
function CCControlPotentiometer:setPositionX() end 
function CCControlPotentiometer:removeFromParentAndCleanup() end 
function CCControlPotentiometer:setTag() end 
function CCControlPotentiometer:getChildrenCount() end 
function CCControlPotentiometer:setScale() end 
function CCControlPotentiometer:addChild() end 
function CCControlPotentiometer:isVisible() end 
function CCControlPotentiometer:setActionManager() end 
function CCControlPotentiometer:setScheduler() end 
function CCControlPotentiometer:getContentSize() end 
function CCControlPotentiometer:getAnchorPoint() end 
function CCControlPotentiometer:getTag() end 
function CCControlPotentiometer:setGrid() end 
function CCControlPotentiometer:convertToWorldSpace() end 
function CCControlPotentiometer:setSkewX() end 
function CCControlPotentiometer:setZOrder() end 
function CCControlPotentiometer:worldToNodeTransform() end 
function CCControlPotentiometer:getPosition() end 
function CCControlPotentiometer:getSkewX() end 
function CCControlPotentiometer:getScheduler() end 
function CCControlPotentiometer:ignoreAnchorPointForPosition() end 
function CCControlPotentiometer:setPosition() end 
function CCControlPotentiometer:getParent() end 
function CCControlPotentiometer:unscheduleUpdate() end 
function CCControlPotentiometer:scheduleUpdateWithPriorityLua() end 
function CCControlPotentiometer:removeChildByTag() end 
function CCControlPotentiometer:convertToNodeSpaceAR() end 
function CCControlPotentiometer:convertTouchToNodeSpaceAR() end 
function CCControlPotentiometer:convertToWorldSpaceAR() end 
function CCControlPotentiometer:setRotation() end 
function CCControlPotentiometer:getComponent() end 
function CCControlPotentiometer:convertToNodeSpace() end 
---
-- @return @class CCControlPotentiometer
--
function CCControlPotentiometer:create() end 
function CCControlPotentiometer:getScale() end 
function CCControlPotentiometer:getPositionY() end 
function CCControlPotentiometer:getChildByTag() end 
function CCControlPotentiometer:setContentSize() end 
function CCControlPotentiometer:description() end 
function CCControlPotentiometer:cleanup() end 
function CCControlPotentiometer:getRotation() end 
function CCControlPotentiometer:nodeToParentTransform() end 
function CCControlPotentiometer:stopAction() end 
function CCControlPotentiometer:numberOfRunningActions() end 
function CCControlPotentiometer:removeAllChildren() end 
function CCControlPotentiometer:runAction() end 
function CCControlPotentiometer:setUserObject() end 
function CCControlPotentiometer:parentToNodeTransform() end 
function CCControlPotentiometer:removeChild() end 
function CCControlPotentiometer:getAnchorPointInPoints() end 
function CCControlPotentiometer:getScaleX() end 
function CCControlPotentiometer:transform() end 
function CCControlPotentiometer:getActionManager() end 
function CCControlPotentiometer:draw() end 
function CCControlPotentiometer:setScaleY() end 
function CCControlPotentiometer:unregisterScriptHandler() end 
function CCControlPotentiometer:setVertexZ() end 
function CCControlPotentiometer:setAnchorPoint() end 
function CCControlPotentiometer:getShaderProgram() end 
function CCControlPotentiometer:stopAllActions() end 
function CCControlPotentiometer:setUserData() end 
function CCControlPotentiometer:setShaderProgram() end 
function CCControlPotentiometer:getActionByTag() end 
function CCControlPotentiometer:getGLServerState() end 
function CCControlPotentiometer:getOrderOfArrival() end 
function CCControlPotentiometer:getPositionX() end 
function CCControlPotentiometer:setGLServerState() end 
function CCControlPotentiometer:setSkewY() end 
function CCControlPotentiometer:setOrderOfArrival() end 
function CCControlPotentiometer:nodeToWorldTransform() end 
function CCControlPotentiometer:getChildren() end 
function CCControlPotentiometer:transformAncestors() end 
function CCControlPotentiometer:getGrid() end 
function CCControlPotentiometer:isRunning() end 
function CCControlPotentiometer:registerScriptHandler() end 
function CCControlPotentiometer:getCamera() end 
function CCControlPotentiometer:isIgnoreAnchorPointForPosition() end 
function CCControlPotentiometer:getUserData() end 
function CCControlPotentiometer:setPositionY() end 
function CCControlPotentiometer:getZOrder() end 
function CCControlPotentiometer:isTouchEnabled() end 
function CCControlPotentiometer:unregisterScriptKeypadHandler() end 
function CCControlPotentiometer:registerScriptAccelerateHandler() end 
---
-- @return @class CCControlPotentiometer
--
function CCControlPotentiometer:create() end 
function CCControlPotentiometer:setAccelerometerEnabled() end 
function CCControlPotentiometer:registerScriptKeypadHandler() end 
function CCControlPotentiometer:setTouchMode() end 
function CCControlPotentiometer:isAccelerometerEnabled() end 
function CCControlPotentiometer:setTouchEnabled() end 
function CCControlPotentiometer:setTouchPriority() end 
function CCControlPotentiometer:unregisterScriptAccelerateHandler() end 
function CCControlPotentiometer:unregisterScriptTouchHandler() end 
function CCControlPotentiometer:setKeypadEnabled() end 
function CCControlPotentiometer:registerScriptTouchHandler() end 
function CCControlPotentiometer:getTouchPriority() end 
function CCControlPotentiometer:isKeypadEnabled() end 
function CCControlPotentiometer:getTouchMode() end 
function CCControlPotentiometer:new() end 
---
-- @return @class CCControlPotentiometer
--
function CCControlPotentiometer:create() end 
function CCControlPotentiometer:delete() end 
function CCControlPotentiometer:updateDisplayedColor() end 
function CCControlPotentiometer:init() end 
function CCControlPotentiometer:setColor() end 
function CCControlPotentiometer:getDisplayedColor() end 
function CCControlPotentiometer:setCascadeColorEnabled() end 
function CCControlPotentiometer:setCascadeOpacityEnabled() end 
function CCControlPotentiometer:setOpacity() end 
function CCControlPotentiometer:getColor() end 
function CCControlPotentiometer:updateDisplayedOpacity() end 
function CCControlPotentiometer:getOpacity() end 
function CCControlPotentiometer:setOpacityModifyRGB() end 
function CCControlPotentiometer:isOpacityModifyRGB() end 
function CCControlPotentiometer:isCascadeOpacityEnabled() end 
function CCControlPotentiometer:getDisplayedOpacity() end 
function CCControlPotentiometer:new_local() end 
function CCControlPotentiometer:isCascadeColorEnabled() end 
function CCControlPotentiometer:onEnter() end 
function CCControlPotentiometer:new() end 
function CCControlPotentiometer:setEnabled() end 
function CCControlPotentiometer:delete() end 
function CCControlPotentiometer:init() end 
function CCControlPotentiometer:isHighlighted() end 
function CCControlPotentiometer:new_local() end 
function CCControlPotentiometer:setHighlighted() end 
function CCControlPotentiometer:isEnabled() end 
function CCControlPotentiometer:onExit() end 
function CCControlPotentiometer:registerWithTouchDispatcher() end 
function CCControlPotentiometer:addTargetWithActionForControlEvents() end 
function CCControlPotentiometer:addHandleOfControlEvent() end 
function CCControlPotentiometer:isTouchInside() end 
function CCControlPotentiometer:isSelected() end 
function CCControlPotentiometer:setSelected() end 
function CCControlPotentiometer:setOpacityModifyRGB() end 
function CCControlPotentiometer:removeHandleOfControlEvent() end 
function CCControlPotentiometer:sendActionsForControlEvents() end 
function CCControlPotentiometer:getState() end 
function CCControlPotentiometer:needsLayout() end 
function CCControlPotentiometer:hasVisibleParents() end 
function CCControlPotentiometer:isOpacityModifyRGB() end 
function CCControlPotentiometer:removeTargetWithActionForControlEvents() end 
function CCControlPotentiometer:getTouchLocation() end 
function CCControlPotentiometer:ccTouchMoved() end 
function CCControlPotentiometer:new() end 
function CCControlPotentiometer:potentiometerBegan() end 
function CCControlPotentiometer:setPreviousLocation() end 
function CCControlPotentiometer:delete() end 
function CCControlPotentiometer:ccTouchEnded() end 
function CCControlPotentiometer:setMinimumValue() end 
function CCControlPotentiometer:new_local() end 
function CCControlPotentiometer:getThumbSprite() end 
function CCControlPotentiometer:getPreviousLocation() end 
function CCControlPotentiometer:getValue() end 
function CCControlPotentiometer:potentiometerEnded() end 
function CCControlPotentiometer:angleInDegreesBetweenLineFromPoint_toPoint_toLineFromPoint_toPoint() end 
function CCControlPotentiometer:setMaximumValue() end 
function CCControlPotentiometer:setProgressTimer() end 
function CCControlPotentiometer:potentiometerMoved() end 
function CCControlPotentiometer:distanceBetweenPointAndPoint() end 
function CCControlPotentiometer:getProgressTimer() end 
function CCControlPotentiometer:setThumbSprite() end 
function CCControlPotentiometer:setValue() end 
function CCControlPotentiometer:getMinimumValue() end 
function CCControlPotentiometer:initWithTrackSprite_ProgressTimer_ThumbSprite() end 
function CCControlPotentiometer:getMaximumValue() end 
function CCControlPotentiometer:isTouchInside() end 
---
-- @return @class CCControlPotentiometer
--
function CCControlPotentiometer:create() end 
function CCControlPotentiometer:setEnabled() end 
function CCControlPotentiometer:ccTouchBegan() end 
