---@classdef CCDirector
CCDirector = {}
function CCDirector:autorelease() end 
function CCDirector:retain() end 
function CCDirector:retainCount() end 
function CCDirector:isEqual() end 
function CCDirector:copy() end 
function CCDirector:release() end 
function CCDirector:isSingleReference() end 
function CCDirector:isPaused() end 
function CCDirector:getNotificationNode() end 
function CCDirector:endToLua() end 
function CCDirector:popScene() end 
function CCDirector:convertToUI() end 
function CCDirector:getRunningScene() end 
function CCDirector:getOpenGLView() end 
function CCDirector:setProjection() end 
function CCDirector:setDisplayStats() end 
function CCDirector:setContentScaleFactor() end 
function CCDirector:popToRootScene() end 
function CCDirector:getActionManager() end 
function CCDirector:isDisplayStats() end 
function CCDirector:convertToGL() end 
function CCDirector:getContentScaleFactor() end 
function CCDirector:sharedDirector() end 
function CCDirector:getVisibleSize() end 
function CCDirector:replaceScene() end 
function CCDirector:resume() end 
function CCDirector:getZEye() end 
function CCDirector:getWinSizeInPixels() end 
function CCDirector:getTotalFrames() end 
function CCDirector:getTouchDispatcher() end 
function CCDirector:runWithScene() end 
function CCDirector:getProjection() end 
function CCDirector:setDepthTest() end 
function CCDirector:pause() end 
function CCDirector:setNotificationNode() end 
function CCDirector:getVisibleOrigin() end 
function CCDirector:getAnimationInterval() end 
function CCDirector:getScheduler() end 
function CCDirector:getWinSize() end 
function CCDirector:purgeCachedData() end 
function CCDirector:pushScene() end 
