---@classdef CCEditBox
CCEditBox = {}
function CCEditBox:autorelease() end 
function CCEditBox:retain() end 
function CCEditBox:retainCount() end 
function CCEditBox:isEqual() end 
function CCEditBox:copy() end 
function CCEditBox:release() end 
function CCEditBox:isSingleReference() end 
function CCEditBox:visit() end 
function CCEditBox:getUserObject() end 
function CCEditBox:getSkewY() end 
function CCEditBox:convertTouchToNodeSpace() end 
function CCEditBox:getVertexZ() end 
function CCEditBox:setParent() end 
function CCEditBox:boundingBox() end 
function CCEditBox:setVisible() end 
function CCEditBox:stopActionByTag() end 
function CCEditBox:getScaleY() end 
function CCEditBox:setScaleX() end 
function CCEditBox:reorderChild() end 
function CCEditBox:setPositionX() end 
function CCEditBox:removeFromParentAndCleanup() end 
function CCEditBox:setTag() end 
function CCEditBox:getChildrenCount() end 
function CCEditBox:setScale() end 
function CCEditBox:addChild() end 
function CCEditBox:isVisible() end 
function CCEditBox:setActionManager() end 
function CCEditBox:setScheduler() end 
function CCEditBox:getContentSize() end 
function CCEditBox:getAnchorPoint() end 
function CCEditBox:getTag() end 
function CCEditBox:setGrid() end 
function CCEditBox:convertToWorldSpace() end 
function CCEditBox:setSkewX() end 
function CCEditBox:setZOrder() end 
function CCEditBox:worldToNodeTransform() end 
function CCEditBox:getPosition() end 
function CCEditBox:getSkewX() end 
function CCEditBox:getScheduler() end 
function CCEditBox:ignoreAnchorPointForPosition() end 
function CCEditBox:setPosition() end 
function CCEditBox:getParent() end 
function CCEditBox:unscheduleUpdate() end 
function CCEditBox:scheduleUpdateWithPriorityLua() end 
function CCEditBox:removeChildByTag() end 
function CCEditBox:convertToNodeSpaceAR() end 
function CCEditBox:convertTouchToNodeSpaceAR() end 
function CCEditBox:convertToWorldSpaceAR() end 
function CCEditBox:setRotation() end 
function CCEditBox:getComponent() end 
function CCEditBox:convertToNodeSpace() end 
---
-- @return @class CCEditBox
--
function CCEditBox:create() end 
function CCEditBox:getScale() end 
function CCEditBox:getPositionY() end 
function CCEditBox:getChildByTag() end 
function CCEditBox:setContentSize() end 
function CCEditBox:description() end 
function CCEditBox:cleanup() end 
function CCEditBox:getRotation() end 
function CCEditBox:nodeToParentTransform() end 
function CCEditBox:stopAction() end 
function CCEditBox:numberOfRunningActions() end 
function CCEditBox:removeAllChildren() end 
function CCEditBox:runAction() end 
function CCEditBox:setUserObject() end 
function CCEditBox:parentToNodeTransform() end 
function CCEditBox:removeChild() end 
function CCEditBox:getAnchorPointInPoints() end 
function CCEditBox:getScaleX() end 
function CCEditBox:transform() end 
function CCEditBox:getActionManager() end 
function CCEditBox:draw() end 
function CCEditBox:setScaleY() end 
function CCEditBox:unregisterScriptHandler() end 
function CCEditBox:setVertexZ() end 
function CCEditBox:setAnchorPoint() end 
function CCEditBox:getShaderProgram() end 
function CCEditBox:stopAllActions() end 
function CCEditBox:setUserData() end 
function CCEditBox:setShaderProgram() end 
function CCEditBox:getActionByTag() end 
function CCEditBox:getGLServerState() end 
function CCEditBox:getOrderOfArrival() end 
function CCEditBox:getPositionX() end 
function CCEditBox:setGLServerState() end 
function CCEditBox:setSkewY() end 
function CCEditBox:setOrderOfArrival() end 
function CCEditBox:nodeToWorldTransform() end 
function CCEditBox:getChildren() end 
function CCEditBox:transformAncestors() end 
function CCEditBox:getGrid() end 
function CCEditBox:isRunning() end 
function CCEditBox:registerScriptHandler() end 
function CCEditBox:getCamera() end 
function CCEditBox:isIgnoreAnchorPointForPosition() end 
function CCEditBox:getUserData() end 
function CCEditBox:setPositionY() end 
function CCEditBox:getZOrder() end 
function CCEditBox:isTouchEnabled() end 
function CCEditBox:unregisterScriptKeypadHandler() end 
function CCEditBox:registerScriptAccelerateHandler() end 
---
-- @return @class CCEditBox
--
function CCEditBox:create() end 
function CCEditBox:setAccelerometerEnabled() end 
function CCEditBox:registerScriptKeypadHandler() end 
function CCEditBox:setTouchMode() end 
function CCEditBox:isAccelerometerEnabled() end 
function CCEditBox:setTouchEnabled() end 
function CCEditBox:setTouchPriority() end 
function CCEditBox:unregisterScriptAccelerateHandler() end 
function CCEditBox:unregisterScriptTouchHandler() end 
function CCEditBox:setKeypadEnabled() end 
function CCEditBox:registerScriptTouchHandler() end 
function CCEditBox:getTouchPriority() end 
function CCEditBox:isKeypadEnabled() end 
function CCEditBox:getTouchMode() end 
function CCEditBox:new() end 
---
-- @return @class CCEditBox
--
function CCEditBox:create() end 
function CCEditBox:delete() end 
function CCEditBox:updateDisplayedColor() end 
function CCEditBox:init() end 
function CCEditBox:setColor() end 
function CCEditBox:getDisplayedColor() end 
function CCEditBox:setCascadeColorEnabled() end 
function CCEditBox:setCascadeOpacityEnabled() end 
function CCEditBox:setOpacity() end 
function CCEditBox:getColor() end 
function CCEditBox:updateDisplayedOpacity() end 
function CCEditBox:getOpacity() end 
function CCEditBox:setOpacityModifyRGB() end 
function CCEditBox:isOpacityModifyRGB() end 
function CCEditBox:isCascadeOpacityEnabled() end 
function CCEditBox:getDisplayedOpacity() end 
function CCEditBox:new_local() end 
function CCEditBox:isCascadeColorEnabled() end 
function CCEditBox:onEnter() end 
function CCEditBox:new() end 
function CCEditBox:setEnabled() end 
function CCEditBox:delete() end 
function CCEditBox:init() end 
function CCEditBox:isHighlighted() end 
function CCEditBox:new_local() end 
function CCEditBox:setHighlighted() end 
function CCEditBox:isEnabled() end 
function CCEditBox:onExit() end 
function CCEditBox:registerWithTouchDispatcher() end 
function CCEditBox:addTargetWithActionForControlEvents() end 
function CCEditBox:addHandleOfControlEvent() end 
function CCEditBox:isTouchInside() end 
function CCEditBox:isSelected() end 
function CCEditBox:setSelected() end 
function CCEditBox:setOpacityModifyRGB() end 
function CCEditBox:removeHandleOfControlEvent() end 
function CCEditBox:sendActionsForControlEvents() end 
function CCEditBox:getState() end 
function CCEditBox:needsLayout() end 
function CCEditBox:hasVisibleParents() end 
function CCEditBox:isOpacityModifyRGB() end 
function CCEditBox:removeTargetWithActionForControlEvents() end 
function CCEditBox:getTouchLocation() end 
function CCEditBox:getBackgroundSpriteDispatchTable() end 
function CCEditBox:ccTouchMoved() end 
function CCEditBox:ccTouchBegan() end 
function CCEditBox:setTitleColorDispatchTable() end 
function CCEditBox:doesAdjustBackgroundImage() end 
function CCEditBox:getTitleTTFSizeForState() end 
function CCEditBox:getCurrentTitle() end 
function CCEditBox:ccTouchEnded() end 
function CCEditBox:initWithLabelAndBackgroundSprite() end 
function CCEditBox:initWithTitleAndFontNameAndFontSize() end 
function CCEditBox:getBackgroundSpriteForState() end 
function CCEditBox:new_local() end 
function CCEditBox:initWithBackgroundSprite() end 
function CCEditBox:setTitleBMFontForState() end 
function CCEditBox:getPreferredSize() end 
function CCEditBox:getTitleColorForState() end 
function CCEditBox:setPreferredSize() end 
function CCEditBox:setSelected() end 
function CCEditBox:setAdjustBackgroundImage() end 
function CCEditBox:getTitleDispatchTable() end 
function CCEditBox:getTitleTTFForState() end 
function CCEditBox:needsLayout() end 
function CCEditBox:setBackgroundSprite() end 
function CCEditBox:getTitleLabel() end 
function CCEditBox:getCurrentTitleColor() end 
function CCEditBox:setTitleLabel() end 
function CCEditBox:new() end 
---
-- @return @class CCEditBox
--
function CCEditBox:create() end 
function CCEditBox:delete() end 
function CCEditBox:getTitleLabelDispatchTable() end 
function CCEditBox:getTitleLabelForState() end 
function CCEditBox:init() end 
function CCEditBox:isPushed() end 
function CCEditBox:getTitleForState() end 
function CCEditBox:setHighlighted() end 
function CCEditBox:setTitleTTFForState() end 
function CCEditBox:getLabelAnchorPoint() end 
function CCEditBox:setTitleDispatchTable() end 
function CCEditBox:setOpacity() end 
function CCEditBox:getZoomOnTouchDown() end 
function CCEditBox:setBackgroundSpriteFrameForState() end 
function CCEditBox:setTitleLabelForState() end 
function CCEditBox:getBackgroundSprite() end 
function CCEditBox:setTitleColorForState() end 
function CCEditBox:getHorizontalOrigin() end 
function CCEditBox:setTitleForState() end 
function CCEditBox:getOpacity() end 
function CCEditBox:setEnabled() end 
function CCEditBox:setZoomOnTouchDown() end 
function CCEditBox:setBackgroundSpriteDispatchTable() end 
function CCEditBox:setLabelAnchorPoint() end 
function CCEditBox:getTitleBMFontForState() end 
function CCEditBox:ccTouchCancelled() end 
function CCEditBox:getVerticalMargin() end 
function CCEditBox:setTitleLabelDispatchTable() end 
function CCEditBox:getTitleColorDispatchTable() end 
function CCEditBox:setMargins() end 
function CCEditBox:setTitleTTFSizeForState() end 
function CCEditBox:setBackgroundSpriteForState() end 
function CCEditBox:setPlaceholderFont() end 
function CCEditBox:onEnter() end 
function CCEditBox:new() end 
function CCEditBox:setFontColor() end 
function CCEditBox:registerScriptEditBoxHandler() end 
function CCEditBox:delete() end 
function CCEditBox:setFont() end 
function CCEditBox:setVisible() end 
function CCEditBox:initWithSizeAndBackgroundSprite() end 
function CCEditBox:new_local() end 
function CCEditBox:setPlaceholderFontName() end 
function CCEditBox:unregisterScriptEditBoxHandler() end 
function CCEditBox:getMaxLength() end 
function CCEditBox:onExit() end 
function CCEditBox:setPlaceholderFontColor() end 
function CCEditBox:setFontName() end 
function CCEditBox:setInputFlag() end 
function CCEditBox:setPlaceholderFontSize() end 
function CCEditBox:setText() end 
function CCEditBox:touchDownAction() end 
function CCEditBox:visit() end 
function CCEditBox:setReturnType() end 
function CCEditBox:setMaxLength() end 
function CCEditBox:setInputMode() end 
function CCEditBox:getPlaceHolder() end 
function CCEditBox:setPlaceHolder() end 
function CCEditBox:setFontSize() end 
---
-- @return @class CCEditBox
--
function CCEditBox:create() end 
function CCEditBox:getScriptEditBoxHandler() end 
function CCEditBox:getText() end 
