---@classdef CCImage
CCImage = {}
function CCImage:autorelease() end 
function CCImage:retain() end 
function CCImage:retainCount() end 
function CCImage:isEqual() end 
function CCImage:copy() end 
function CCImage:release() end 
function CCImage:isSingleReference() end 
function CCImage:new() end 
function CCImage:delete() end 
function CCImage:initWithImageData() end 
function CCImage:new_local() end 
function CCImage:hasAlpha() end 
function CCImage:initWithImageFile() end 
function CCImage:getDataLen() end 
function CCImage:getBitsPerComponent() end 
function CCImage:getHeight() end 
function CCImage:getWidth() end 
function CCImage:saveToFile() end 
function CCImage:isPremultipliedAlpha() end 
function CCImage:getData() end 
function CCImage:initWithString() end 
function CCImage:initWithImageFileThreadSafe() end 
