---@classdef CCLayerMultiplex
CCLayerMultiplex = {}
function CCLayerMultiplex:autorelease() end 
function CCLayerMultiplex:retain() end 
function CCLayerMultiplex:retainCount() end 
function CCLayerMultiplex:isEqual() end 
function CCLayerMultiplex:copy() end 
function CCLayerMultiplex:release() end 
function CCLayerMultiplex:isSingleReference() end 
function CCLayerMultiplex:visit() end 
function CCLayerMultiplex:getUserObject() end 
function CCLayerMultiplex:getSkewY() end 
function CCLayerMultiplex:convertTouchToNodeSpace() end 
function CCLayerMultiplex:getVertexZ() end 
function CCLayerMultiplex:setParent() end 
function CCLayerMultiplex:boundingBox() end 
function CCLayerMultiplex:setVisible() end 
function CCLayerMultiplex:stopActionByTag() end 
function CCLayerMultiplex:getScaleY() end 
function CCLayerMultiplex:setScaleX() end 
function CCLayerMultiplex:reorderChild() end 
function CCLayerMultiplex:setPositionX() end 
function CCLayerMultiplex:removeFromParentAndCleanup() end 
function CCLayerMultiplex:setTag() end 
function CCLayerMultiplex:getChildrenCount() end 
function CCLayerMultiplex:setScale() end 
function CCLayerMultiplex:addChild() end 
function CCLayerMultiplex:isVisible() end 
function CCLayerMultiplex:setActionManager() end 
function CCLayerMultiplex:setScheduler() end 
function CCLayerMultiplex:getContentSize() end 
function CCLayerMultiplex:getAnchorPoint() end 
function CCLayerMultiplex:getTag() end 
function CCLayerMultiplex:setGrid() end 
function CCLayerMultiplex:convertToWorldSpace() end 
function CCLayerMultiplex:setSkewX() end 
function CCLayerMultiplex:setZOrder() end 
function CCLayerMultiplex:worldToNodeTransform() end 
function CCLayerMultiplex:getPosition() end 
function CCLayerMultiplex:getSkewX() end 
function CCLayerMultiplex:getScheduler() end 
function CCLayerMultiplex:ignoreAnchorPointForPosition() end 
function CCLayerMultiplex:setPosition() end 
function CCLayerMultiplex:getParent() end 
function CCLayerMultiplex:unscheduleUpdate() end 
function CCLayerMultiplex:scheduleUpdateWithPriorityLua() end 
function CCLayerMultiplex:removeChildByTag() end 
function CCLayerMultiplex:convertToNodeSpaceAR() end 
function CCLayerMultiplex:convertTouchToNodeSpaceAR() end 
function CCLayerMultiplex:convertToWorldSpaceAR() end 
function CCLayerMultiplex:setRotation() end 
function CCLayerMultiplex:getComponent() end 
function CCLayerMultiplex:convertToNodeSpace() end 
---
-- @return @class CCLayerMultiplex
--
function CCLayerMultiplex:create() end 
function CCLayerMultiplex:getScale() end 
function CCLayerMultiplex:getPositionY() end 
function CCLayerMultiplex:getChildByTag() end 
function CCLayerMultiplex:setContentSize() end 
function CCLayerMultiplex:description() end 
function CCLayerMultiplex:cleanup() end 
function CCLayerMultiplex:getRotation() end 
function CCLayerMultiplex:nodeToParentTransform() end 
function CCLayerMultiplex:stopAction() end 
function CCLayerMultiplex:numberOfRunningActions() end 
function CCLayerMultiplex:removeAllChildren() end 
function CCLayerMultiplex:runAction() end 
function CCLayerMultiplex:setUserObject() end 
function CCLayerMultiplex:parentToNodeTransform() end 
function CCLayerMultiplex:removeChild() end 
function CCLayerMultiplex:getAnchorPointInPoints() end 
function CCLayerMultiplex:getScaleX() end 
function CCLayerMultiplex:transform() end 
function CCLayerMultiplex:getActionManager() end 
function CCLayerMultiplex:draw() end 
function CCLayerMultiplex:setScaleY() end 
function CCLayerMultiplex:unregisterScriptHandler() end 
function CCLayerMultiplex:setVertexZ() end 
function CCLayerMultiplex:setAnchorPoint() end 
function CCLayerMultiplex:getShaderProgram() end 
function CCLayerMultiplex:stopAllActions() end 
function CCLayerMultiplex:setUserData() end 
function CCLayerMultiplex:setShaderProgram() end 
function CCLayerMultiplex:getActionByTag() end 
function CCLayerMultiplex:getGLServerState() end 
function CCLayerMultiplex:getOrderOfArrival() end 
function CCLayerMultiplex:getPositionX() end 
function CCLayerMultiplex:setGLServerState() end 
function CCLayerMultiplex:setSkewY() end 
function CCLayerMultiplex:setOrderOfArrival() end 
function CCLayerMultiplex:nodeToWorldTransform() end 
function CCLayerMultiplex:getChildren() end 
function CCLayerMultiplex:transformAncestors() end 
function CCLayerMultiplex:getGrid() end 
function CCLayerMultiplex:isRunning() end 
function CCLayerMultiplex:registerScriptHandler() end 
function CCLayerMultiplex:getCamera() end 
function CCLayerMultiplex:isIgnoreAnchorPointForPosition() end 
function CCLayerMultiplex:getUserData() end 
function CCLayerMultiplex:setPositionY() end 
function CCLayerMultiplex:getZOrder() end 
function CCLayerMultiplex:isTouchEnabled() end 
function CCLayerMultiplex:unregisterScriptKeypadHandler() end 
function CCLayerMultiplex:registerScriptAccelerateHandler() end 
---
-- @return @class CCLayerMultiplex
--
function CCLayerMultiplex:create() end 
function CCLayerMultiplex:setAccelerometerEnabled() end 
function CCLayerMultiplex:registerScriptKeypadHandler() end 
function CCLayerMultiplex:setTouchMode() end 
function CCLayerMultiplex:isAccelerometerEnabled() end 
function CCLayerMultiplex:setTouchEnabled() end 
function CCLayerMultiplex:setTouchPriority() end 
function CCLayerMultiplex:unregisterScriptAccelerateHandler() end 
function CCLayerMultiplex:unregisterScriptTouchHandler() end 
function CCLayerMultiplex:setKeypadEnabled() end 
function CCLayerMultiplex:registerScriptTouchHandler() end 
function CCLayerMultiplex:getTouchPriority() end 
function CCLayerMultiplex:isKeypadEnabled() end 
function CCLayerMultiplex:getTouchMode() end 
---
-- @return @class CCLayerMultiplex
--
function CCLayerMultiplex:create() end 
function CCLayerMultiplex:switchToAndReleaseMe() end 
function CCLayerMultiplex:switchTo() end 
function CCLayerMultiplex:addLayer() end 
function CCLayerMultiplex:createWithLayer() end 
function CCLayerMultiplex:createWithArray() end 
