---@classdef CCLabelTTF
CCLabelTTF = {}
function CCLabelTTF:autorelease() end 
function CCLabelTTF:retain() end 
function CCLabelTTF:retainCount() end 
function CCLabelTTF:isEqual() end 
function CCLabelTTF:copy() end 
function CCLabelTTF:release() end 
function CCLabelTTF:isSingleReference() end 
function CCLabelTTF:visit() end 
function CCLabelTTF:getUserObject() end 
function CCLabelTTF:getSkewY() end 
function CCLabelTTF:convertTouchToNodeSpace() end 
function CCLabelTTF:getVertexZ() end 
function CCLabelTTF:setParent() end 
function CCLabelTTF:boundingBox() end 
function CCLabelTTF:setVisible() end 
function CCLabelTTF:stopActionByTag() end 
function CCLabelTTF:getScaleY() end 
function CCLabelTTF:setScaleX() end 
function CCLabelTTF:reorderChild() end 
function CCLabelTTF:setPositionX() end 
function CCLabelTTF:removeFromParentAndCleanup() end 
function CCLabelTTF:setTag() end 
function CCLabelTTF:getChildrenCount() end 
function CCLabelTTF:setScale() end 
function CCLabelTTF:addChild() end 
function CCLabelTTF:isVisible() end 
function CCLabelTTF:setActionManager() end 
function CCLabelTTF:setScheduler() end 
function CCLabelTTF:getContentSize() end 
function CCLabelTTF:getAnchorPoint() end 
function CCLabelTTF:getTag() end 
function CCLabelTTF:setGrid() end 
function CCLabelTTF:convertToWorldSpace() end 
function CCLabelTTF:setSkewX() end 
function CCLabelTTF:setZOrder() end 
function CCLabelTTF:worldToNodeTransform() end 
function CCLabelTTF:getPosition() end 
function CCLabelTTF:getSkewX() end 
function CCLabelTTF:getScheduler() end 
function CCLabelTTF:ignoreAnchorPointForPosition() end 
function CCLabelTTF:setPosition() end 
function CCLabelTTF:getParent() end 
function CCLabelTTF:unscheduleUpdate() end 
function CCLabelTTF:scheduleUpdateWithPriorityLua() end 
function CCLabelTTF:removeChildByTag() end 
function CCLabelTTF:convertToNodeSpaceAR() end 
function CCLabelTTF:convertTouchToNodeSpaceAR() end 
function CCLabelTTF:convertToWorldSpaceAR() end 
function CCLabelTTF:setRotation() end 
function CCLabelTTF:getComponent() end 
function CCLabelTTF:convertToNodeSpace() end 
---
-- @return @class CCLabelTTF
--
function CCLabelTTF:create() end 
function CCLabelTTF:getScale() end 
function CCLabelTTF:getPositionY() end 
function CCLabelTTF:getChildByTag() end 
function CCLabelTTF:setContentSize() end 
function CCLabelTTF:description() end 
function CCLabelTTF:cleanup() end 
function CCLabelTTF:getRotation() end 
function CCLabelTTF:nodeToParentTransform() end 
function CCLabelTTF:stopAction() end 
function CCLabelTTF:numberOfRunningActions() end 
function CCLabelTTF:removeAllChildren() end 
function CCLabelTTF:runAction() end 
function CCLabelTTF:setUserObject() end 
function CCLabelTTF:parentToNodeTransform() end 
function CCLabelTTF:removeChild() end 
function CCLabelTTF:getAnchorPointInPoints() end 
function CCLabelTTF:getScaleX() end 
function CCLabelTTF:transform() end 
function CCLabelTTF:getActionManager() end 
function CCLabelTTF:draw() end 
function CCLabelTTF:setScaleY() end 
function CCLabelTTF:unregisterScriptHandler() end 
function CCLabelTTF:setVertexZ() end 
function CCLabelTTF:setAnchorPoint() end 
function CCLabelTTF:getShaderProgram() end 
function CCLabelTTF:stopAllActions() end 
function CCLabelTTF:setUserData() end 
function CCLabelTTF:setShaderProgram() end 
function CCLabelTTF:getActionByTag() end 
function CCLabelTTF:getGLServerState() end 
function CCLabelTTF:getOrderOfArrival() end 
function CCLabelTTF:getPositionX() end 
function CCLabelTTF:setGLServerState() end 
function CCLabelTTF:setSkewY() end 
function CCLabelTTF:setOrderOfArrival() end 
function CCLabelTTF:nodeToWorldTransform() end 
function CCLabelTTF:getChildren() end 
function CCLabelTTF:transformAncestors() end 
function CCLabelTTF:getGrid() end 
function CCLabelTTF:isRunning() end 
function CCLabelTTF:registerScriptHandler() end 
function CCLabelTTF:getCamera() end 
function CCLabelTTF:isIgnoreAnchorPointForPosition() end 
function CCLabelTTF:getUserData() end 
function CCLabelTTF:setPositionY() end 
function CCLabelTTF:getZOrder() end 
function CCLabelTTF:new() end 
function CCLabelTTF:delete() end 
function CCLabelTTF:updateDisplayedColor() end 
function CCLabelTTF:init() end 
function CCLabelTTF:setColor() end 
function CCLabelTTF:getDisplayedColor() end 
function CCLabelTTF:setCascadeColorEnabled() end 
function CCLabelTTF:setCascadeOpacityEnabled() end 
function CCLabelTTF:setOpacity() end 
function CCLabelTTF:getColor() end 
function CCLabelTTF:updateDisplayedOpacity() end 
function CCLabelTTF:getOpacity() end 
function CCLabelTTF:setOpacityModifyRGB() end 
function CCLabelTTF:isCascadeOpacityEnabled() end 
function CCLabelTTF:isOpacityModifyRGB() end 
function CCLabelTTF:getDisplayedOpacity() end 
function CCLabelTTF:new_local() end 
function CCLabelTTF:isCascadeColorEnabled() end 
function CCLabelTTF:getTextureRect() end 
function CCLabelTTF:getBatchNode() end 
function CCLabelTTF:setTextureAtlas() end 
function CCLabelTTF:setRotation() end 
function CCLabelTTF:setBlendFunc() end 
function CCLabelTTF:isFlipX() end 
---
-- @return @class CCLabelTTF
--
function CCLabelTTF:create() end 
function CCLabelTTF:getBlendFunc() end 
function CCLabelTTF:createWithSpriteFrameName() end 
function CCLabelTTF:getTexture() end 
function CCLabelTTF:isFlipY() end 
function CCLabelTTF:createWithSpriteFrame() end 
function CCLabelTTF:createWithTexture() end 
function CCLabelTTF:setVisible() end 
function CCLabelTTF:isTextureRectRotated() end 
function CCLabelTTF:setDisplayFrameWithAnimationName() end 
function CCLabelTTF:setColor() end 
function CCLabelTTF:removeAllChildren() end 
function CCLabelTTF:setTextureRect() end 
function CCLabelTTF:setDirty() end 
function CCLabelTTF:reorderChild() end 
function CCLabelTTF:displayFrame() end 
function CCLabelTTF:setTexture() end 
function CCLabelTTF:setDisplayFrame() end 
function CCLabelTTF:setVertexRect() end 
function CCLabelTTF:setFlipX() end 
function CCLabelTTF:updateTransform() end 
function CCLabelTTF:isFrameDisplayed() end 
function CCLabelTTF:setVertexZ() end 
function CCLabelTTF:isOpacityModifyRGB() end 
function CCLabelTTF:addChild() end 
function CCLabelTTF:getColor() end 
function CCLabelTTF:setSkewX() end 
function CCLabelTTF:getOpacity() end 
function CCLabelTTF:setOpacity() end 
function CCLabelTTF:removeChild() end 
function CCLabelTTF:setScaleX() end 
function CCLabelTTF:setScale() end 
function CCLabelTTF:getTextureAtlas() end 
function CCLabelTTF:setSkewY() end 
function CCLabelTTF:getAtlasIndex() end 
function CCLabelTTF:setOpacityModifyRGB() end 
function CCLabelTTF:sortAllChildren() end 
function CCLabelTTF:setFlipY() end 
function CCLabelTTF:setBatchNode() end 
function CCLabelTTF:getQuad() end 
function CCLabelTTF:ignoreAnchorPointForPosition() end 
function CCLabelTTF:isDirty() end 
function CCLabelTTF:getOffsetPosition() end 
function CCLabelTTF:setAtlasIndex() end 
function CCLabelTTF:setScaleY() end 
function CCLabelTTF:getVerticalAlignment() end 
function CCLabelTTF:new() end 
function CCLabelTTF:setFontName() end 
function CCLabelTTF:delete() end 
function CCLabelTTF:getFontName() end 
function CCLabelTTF:getString() end 
---
-- @return @class CCLabelTTF
--
function CCLabelTTF:create() end 
function CCLabelTTF:setVerticalAlignment() end 
function CCLabelTTF:setFontSize() end 
function CCLabelTTF:getFontSize() end 
function CCLabelTTF:init() end 
function CCLabelTTF:getDimensions() end 
function CCLabelTTF:new_local() end 
function CCLabelTTF:setHorizontalAlignment() end 
function CCLabelTTF:setString() end 
function CCLabelTTF:getHorizontalAlignment() end 
function CCLabelTTF:setDimensions() end 
