---@classdef CCLayerRGBA
CCLayerRGBA = {}
function CCLayerRGBA:autorelease() end 
function CCLayerRGBA:retain() end 
function CCLayerRGBA:retainCount() end 
function CCLayerRGBA:isEqual() end 
function CCLayerRGBA:copy() end 
function CCLayerRGBA:release() end 
function CCLayerRGBA:isSingleReference() end 
function CCLayerRGBA:visit() end 
function CCLayerRGBA:getUserObject() end 
function CCLayerRGBA:getSkewY() end 
function CCLayerRGBA:convertTouchToNodeSpace() end 
function CCLayerRGBA:getVertexZ() end 
function CCLayerRGBA:setParent() end 
function CCLayerRGBA:boundingBox() end 
function CCLayerRGBA:setVisible() end 
function CCLayerRGBA:stopActionByTag() end 
function CCLayerRGBA:getScaleY() end 
function CCLayerRGBA:setScaleX() end 
function CCLayerRGBA:reorderChild() end 
function CCLayerRGBA:setPositionX() end 
function CCLayerRGBA:removeFromParentAndCleanup() end 
function CCLayerRGBA:setTag() end 
function CCLayerRGBA:getChildrenCount() end 
function CCLayerRGBA:setScale() end 
function CCLayerRGBA:addChild() end 
function CCLayerRGBA:isVisible() end 
function CCLayerRGBA:setActionManager() end 
function CCLayerRGBA:setScheduler() end 
function CCLayerRGBA:getContentSize() end 
function CCLayerRGBA:getAnchorPoint() end 
function CCLayerRGBA:getTag() end 
function CCLayerRGBA:setGrid() end 
function CCLayerRGBA:convertToWorldSpace() end 
function CCLayerRGBA:setSkewX() end 
function CCLayerRGBA:setZOrder() end 
function CCLayerRGBA:worldToNodeTransform() end 
function CCLayerRGBA:getPosition() end 
function CCLayerRGBA:getSkewX() end 
function CCLayerRGBA:getScheduler() end 
function CCLayerRGBA:ignoreAnchorPointForPosition() end 
function CCLayerRGBA:setPosition() end 
function CCLayerRGBA:getParent() end 
function CCLayerRGBA:unscheduleUpdate() end 
function CCLayerRGBA:scheduleUpdateWithPriorityLua() end 
function CCLayerRGBA:removeChildByTag() end 
function CCLayerRGBA:convertToNodeSpaceAR() end 
function CCLayerRGBA:convertTouchToNodeSpaceAR() end 
function CCLayerRGBA:convertToWorldSpaceAR() end 
function CCLayerRGBA:setRotation() end 
function CCLayerRGBA:getComponent() end 
function CCLayerRGBA:convertToNodeSpace() end 
---
-- @return @class CCLayerRGBA
--
function CCLayerRGBA:create() end 
function CCLayerRGBA:getScale() end 
function CCLayerRGBA:getPositionY() end 
function CCLayerRGBA:getChildByTag() end 
function CCLayerRGBA:setContentSize() end 
function CCLayerRGBA:description() end 
function CCLayerRGBA:cleanup() end 
function CCLayerRGBA:getRotation() end 
function CCLayerRGBA:nodeToParentTransform() end 
function CCLayerRGBA:stopAction() end 
function CCLayerRGBA:numberOfRunningActions() end 
function CCLayerRGBA:removeAllChildren() end 
function CCLayerRGBA:runAction() end 
function CCLayerRGBA:setUserObject() end 
function CCLayerRGBA:parentToNodeTransform() end 
function CCLayerRGBA:removeChild() end 
function CCLayerRGBA:getAnchorPointInPoints() end 
function CCLayerRGBA:getScaleX() end 
function CCLayerRGBA:transform() end 
function CCLayerRGBA:getActionManager() end 
function CCLayerRGBA:draw() end 
function CCLayerRGBA:setScaleY() end 
function CCLayerRGBA:unregisterScriptHandler() end 
function CCLayerRGBA:setVertexZ() end 
function CCLayerRGBA:setAnchorPoint() end 
function CCLayerRGBA:getShaderProgram() end 
function CCLayerRGBA:stopAllActions() end 
function CCLayerRGBA:setUserData() end 
function CCLayerRGBA:setShaderProgram() end 
function CCLayerRGBA:getActionByTag() end 
function CCLayerRGBA:getGLServerState() end 
function CCLayerRGBA:getOrderOfArrival() end 
function CCLayerRGBA:getPositionX() end 
function CCLayerRGBA:setGLServerState() end 
function CCLayerRGBA:setSkewY() end 
function CCLayerRGBA:setOrderOfArrival() end 
function CCLayerRGBA:nodeToWorldTransform() end 
function CCLayerRGBA:getChildren() end 
function CCLayerRGBA:transformAncestors() end 
function CCLayerRGBA:getGrid() end 
function CCLayerRGBA:isRunning() end 
function CCLayerRGBA:registerScriptHandler() end 
function CCLayerRGBA:getCamera() end 
function CCLayerRGBA:isIgnoreAnchorPointForPosition() end 
function CCLayerRGBA:getUserData() end 
function CCLayerRGBA:setPositionY() end 
function CCLayerRGBA:getZOrder() end 
function CCLayerRGBA:isTouchEnabled() end 
function CCLayerRGBA:unregisterScriptKeypadHandler() end 
function CCLayerRGBA:registerScriptAccelerateHandler() end 
---
-- @return @class CCLayerRGBA
--
function CCLayerRGBA:create() end 
function CCLayerRGBA:setAccelerometerEnabled() end 
function CCLayerRGBA:registerScriptKeypadHandler() end 
function CCLayerRGBA:setTouchMode() end 
function CCLayerRGBA:isAccelerometerEnabled() end 
function CCLayerRGBA:setTouchEnabled() end 
function CCLayerRGBA:setTouchPriority() end 
function CCLayerRGBA:unregisterScriptAccelerateHandler() end 
function CCLayerRGBA:unregisterScriptTouchHandler() end 
function CCLayerRGBA:setKeypadEnabled() end 
function CCLayerRGBA:registerScriptTouchHandler() end 
function CCLayerRGBA:getTouchPriority() end 
function CCLayerRGBA:isKeypadEnabled() end 
function CCLayerRGBA:getTouchMode() end 
function CCLayerRGBA:new() end 
---
-- @return @class CCLayerRGBA
--
function CCLayerRGBA:create() end 
function CCLayerRGBA:delete() end 
function CCLayerRGBA:updateDisplayedColor() end 
function CCLayerRGBA:init() end 
function CCLayerRGBA:setColor() end 
function CCLayerRGBA:getDisplayedColor() end 
function CCLayerRGBA:setCascadeColorEnabled() end 
function CCLayerRGBA:setCascadeOpacityEnabled() end 
function CCLayerRGBA:setOpacity() end 
function CCLayerRGBA:getColor() end 
function CCLayerRGBA:updateDisplayedOpacity() end 
function CCLayerRGBA:getOpacity() end 
function CCLayerRGBA:setOpacityModifyRGB() end 
function CCLayerRGBA:isOpacityModifyRGB() end 
function CCLayerRGBA:isCascadeOpacityEnabled() end 
function CCLayerRGBA:getDisplayedOpacity() end 
function CCLayerRGBA:new_local() end 
function CCLayerRGBA:isCascadeColorEnabled() end 
