---@classdef CCLabelAtlas
CCLabelAtlas = {}
function CCLabelAtlas:autorelease() end 
function CCLabelAtlas:retain() end 
function CCLabelAtlas:retainCount() end 
function CCLabelAtlas:isEqual() end 
function CCLabelAtlas:copy() end 
function CCLabelAtlas:release() end 
function CCLabelAtlas:isSingleReference() end 
function CCLabelAtlas:visit() end 
function CCLabelAtlas:getUserObject() end 
function CCLabelAtlas:getSkewY() end 
function CCLabelAtlas:convertTouchToNodeSpace() end 
function CCLabelAtlas:getVertexZ() end 
function CCLabelAtlas:setParent() end 
function CCLabelAtlas:boundingBox() end 
function CCLabelAtlas:setVisible() end 
function CCLabelAtlas:stopActionByTag() end 
function CCLabelAtlas:getScaleY() end 
function CCLabelAtlas:setScaleX() end 
function CCLabelAtlas:reorderChild() end 
function CCLabelAtlas:setPositionX() end 
function CCLabelAtlas:removeFromParentAndCleanup() end 
function CCLabelAtlas:setTag() end 
function CCLabelAtlas:getChildrenCount() end 
function CCLabelAtlas:setScale() end 
function CCLabelAtlas:addChild() end 
function CCLabelAtlas:isVisible() end 
function CCLabelAtlas:setActionManager() end 
function CCLabelAtlas:setScheduler() end 
function CCLabelAtlas:getContentSize() end 
function CCLabelAtlas:getAnchorPoint() end 
function CCLabelAtlas:getTag() end 
function CCLabelAtlas:setGrid() end 
function CCLabelAtlas:convertToWorldSpace() end 
function CCLabelAtlas:setSkewX() end 
function CCLabelAtlas:setZOrder() end 
function CCLabelAtlas:worldToNodeTransform() end 
function CCLabelAtlas:getPosition() end 
function CCLabelAtlas:getSkewX() end 
function CCLabelAtlas:getScheduler() end 
function CCLabelAtlas:ignoreAnchorPointForPosition() end 
function CCLabelAtlas:setPosition() end 
function CCLabelAtlas:getParent() end 
function CCLabelAtlas:unscheduleUpdate() end 
function CCLabelAtlas:scheduleUpdateWithPriorityLua() end 
function CCLabelAtlas:removeChildByTag() end 
function CCLabelAtlas:convertToNodeSpaceAR() end 
function CCLabelAtlas:convertTouchToNodeSpaceAR() end 
function CCLabelAtlas:convertToWorldSpaceAR() end 
function CCLabelAtlas:setRotation() end 
function CCLabelAtlas:getComponent() end 
function CCLabelAtlas:convertToNodeSpace() end 
---
-- @return @class CCLabelAtlas
--
function CCLabelAtlas:create() end 
function CCLabelAtlas:getScale() end 
function CCLabelAtlas:getPositionY() end 
function CCLabelAtlas:getChildByTag() end 
function CCLabelAtlas:setContentSize() end 
function CCLabelAtlas:description() end 
function CCLabelAtlas:cleanup() end 
function CCLabelAtlas:getRotation() end 
function CCLabelAtlas:nodeToParentTransform() end 
function CCLabelAtlas:stopAction() end 
function CCLabelAtlas:numberOfRunningActions() end 
function CCLabelAtlas:removeAllChildren() end 
function CCLabelAtlas:runAction() end 
function CCLabelAtlas:setUserObject() end 
function CCLabelAtlas:parentToNodeTransform() end 
function CCLabelAtlas:removeChild() end 
function CCLabelAtlas:getAnchorPointInPoints() end 
function CCLabelAtlas:getScaleX() end 
function CCLabelAtlas:transform() end 
function CCLabelAtlas:getActionManager() end 
function CCLabelAtlas:draw() end 
function CCLabelAtlas:setScaleY() end 
function CCLabelAtlas:unregisterScriptHandler() end 
function CCLabelAtlas:setVertexZ() end 
function CCLabelAtlas:setAnchorPoint() end 
function CCLabelAtlas:getShaderProgram() end 
function CCLabelAtlas:stopAllActions() end 
function CCLabelAtlas:setUserData() end 
function CCLabelAtlas:setShaderProgram() end 
function CCLabelAtlas:getActionByTag() end 
function CCLabelAtlas:getGLServerState() end 
function CCLabelAtlas:getOrderOfArrival() end 
function CCLabelAtlas:getPositionX() end 
function CCLabelAtlas:setGLServerState() end 
function CCLabelAtlas:setSkewY() end 
function CCLabelAtlas:setOrderOfArrival() end 
function CCLabelAtlas:nodeToWorldTransform() end 
function CCLabelAtlas:getChildren() end 
function CCLabelAtlas:transformAncestors() end 
function CCLabelAtlas:getGrid() end 
function CCLabelAtlas:isRunning() end 
function CCLabelAtlas:registerScriptHandler() end 
function CCLabelAtlas:getCamera() end 
function CCLabelAtlas:isIgnoreAnchorPointForPosition() end 
function CCLabelAtlas:getUserData() end 
function CCLabelAtlas:setPositionY() end 
function CCLabelAtlas:getZOrder() end 
function CCLabelAtlas:new() end 
function CCLabelAtlas:delete() end 
function CCLabelAtlas:updateDisplayedColor() end 
function CCLabelAtlas:init() end 
function CCLabelAtlas:setColor() end 
function CCLabelAtlas:getDisplayedColor() end 
function CCLabelAtlas:setCascadeColorEnabled() end 
function CCLabelAtlas:setCascadeOpacityEnabled() end 
function CCLabelAtlas:setOpacity() end 
function CCLabelAtlas:getColor() end 
function CCLabelAtlas:updateDisplayedOpacity() end 
function CCLabelAtlas:getOpacity() end 
function CCLabelAtlas:setOpacityModifyRGB() end 
function CCLabelAtlas:isCascadeOpacityEnabled() end 
function CCLabelAtlas:isOpacityModifyRGB() end 
function CCLabelAtlas:getDisplayedOpacity() end 
function CCLabelAtlas:new_local() end 
function CCLabelAtlas:isCascadeColorEnabled() end 
function CCLabelAtlas:setTextureAtlas() end 
function CCLabelAtlas:setTexture() end 
function CCLabelAtlas:getTexture() end 
function CCLabelAtlas:getTextureAtlas() end 
---
-- @return @class CCLabelAtlas
--
function CCLabelAtlas:create() end 
function CCLabelAtlas:setOpacityModifyRGB() end 
function CCLabelAtlas:setColor() end 
function CCLabelAtlas:setQuadsToDraw() end 
function CCLabelAtlas:isOpacityModifyRGB() end 
function CCLabelAtlas:setOpacity() end 
function CCLabelAtlas:getOpacity() end 
function CCLabelAtlas:updateAtlasValues() end 
function CCLabelAtlas:getColor() end 
function CCLabelAtlas:getQuadsToDraw() end 
function CCLabelAtlas:setTexture() end 
function CCLabelAtlas:getTexture() end 
function CCLabelAtlas:setString() end 
---
-- @return @class CCLabelAtlas
--
function CCLabelAtlas:create() end 
function CCLabelAtlas:updateAtlasValues() end 
function CCLabelAtlas:getString() end 
