---@classdef CCLayerColor
CCLayerColor = {}
function CCLayerColor:autorelease() end 
function CCLayerColor:retain() end 
function CCLayerColor:retainCount() end 
function CCLayerColor:isEqual() end 
function CCLayerColor:copy() end 
function CCLayerColor:release() end 
function CCLayerColor:isSingleReference() end 
function CCLayerColor:visit() end 
function CCLayerColor:getUserObject() end 
function CCLayerColor:getSkewY() end 
function CCLayerColor:convertTouchToNodeSpace() end 
function CCLayerColor:getVertexZ() end 
function CCLayerColor:setParent() end 
function CCLayerColor:boundingBox() end 
function CCLayerColor:setVisible() end 
function CCLayerColor:stopActionByTag() end 
function CCLayerColor:getScaleY() end 
function CCLayerColor:setScaleX() end 
function CCLayerColor:reorderChild() end 
function CCLayerColor:setPositionX() end 
function CCLayerColor:removeFromParentAndCleanup() end 
function CCLayerColor:setTag() end 
function CCLayerColor:getChildrenCount() end 
function CCLayerColor:setScale() end 
function CCLayerColor:addChild() end 
function CCLayerColor:isVisible() end 
function CCLayerColor:setActionManager() end 
function CCLayerColor:setScheduler() end 
function CCLayerColor:getContentSize() end 
function CCLayerColor:getAnchorPoint() end 
function CCLayerColor:getTag() end 
function CCLayerColor:setGrid() end 
function CCLayerColor:convertToWorldSpace() end 
function CCLayerColor:setSkewX() end 
function CCLayerColor:setZOrder() end 
function CCLayerColor:worldToNodeTransform() end 
function CCLayerColor:getPosition() end 
function CCLayerColor:getSkewX() end 
function CCLayerColor:getScheduler() end 
function CCLayerColor:ignoreAnchorPointForPosition() end 
function CCLayerColor:setPosition() end 
function CCLayerColor:getParent() end 
function CCLayerColor:unscheduleUpdate() end 
function CCLayerColor:scheduleUpdateWithPriorityLua() end 
function CCLayerColor:removeChildByTag() end 
function CCLayerColor:convertToNodeSpaceAR() end 
function CCLayerColor:convertTouchToNodeSpaceAR() end 
function CCLayerColor:convertToWorldSpaceAR() end 
function CCLayerColor:setRotation() end 
function CCLayerColor:getComponent() end 
function CCLayerColor:convertToNodeSpace() end 
---
-- @return @class CCLayerColor
--
function CCLayerColor:create() end 
function CCLayerColor:getScale() end 
function CCLayerColor:getPositionY() end 
function CCLayerColor:getChildByTag() end 
function CCLayerColor:setContentSize() end 
function CCLayerColor:description() end 
function CCLayerColor:cleanup() end 
function CCLayerColor:getRotation() end 
function CCLayerColor:nodeToParentTransform() end 
function CCLayerColor:stopAction() end 
function CCLayerColor:numberOfRunningActions() end 
function CCLayerColor:removeAllChildren() end 
function CCLayerColor:runAction() end 
function CCLayerColor:setUserObject() end 
function CCLayerColor:parentToNodeTransform() end 
function CCLayerColor:removeChild() end 
function CCLayerColor:getAnchorPointInPoints() end 
function CCLayerColor:getScaleX() end 
function CCLayerColor:transform() end 
function CCLayerColor:getActionManager() end 
function CCLayerColor:draw() end 
function CCLayerColor:setScaleY() end 
function CCLayerColor:unregisterScriptHandler() end 
function CCLayerColor:setVertexZ() end 
function CCLayerColor:setAnchorPoint() end 
function CCLayerColor:getShaderProgram() end 
function CCLayerColor:stopAllActions() end 
function CCLayerColor:setUserData() end 
function CCLayerColor:setShaderProgram() end 
function CCLayerColor:getActionByTag() end 
function CCLayerColor:getGLServerState() end 
function CCLayerColor:getOrderOfArrival() end 
function CCLayerColor:getPositionX() end 
function CCLayerColor:setGLServerState() end 
function CCLayerColor:setSkewY() end 
function CCLayerColor:setOrderOfArrival() end 
function CCLayerColor:nodeToWorldTransform() end 
function CCLayerColor:getChildren() end 
function CCLayerColor:transformAncestors() end 
function CCLayerColor:getGrid() end 
function CCLayerColor:isRunning() end 
function CCLayerColor:registerScriptHandler() end 
function CCLayerColor:getCamera() end 
function CCLayerColor:isIgnoreAnchorPointForPosition() end 
function CCLayerColor:getUserData() end 
function CCLayerColor:setPositionY() end 
function CCLayerColor:getZOrder() end 
function CCLayerColor:isTouchEnabled() end 
function CCLayerColor:unregisterScriptKeypadHandler() end 
function CCLayerColor:registerScriptAccelerateHandler() end 
---
-- @return @class CCLayerColor
--
function CCLayerColor:create() end 
function CCLayerColor:setAccelerometerEnabled() end 
function CCLayerColor:registerScriptKeypadHandler() end 
function CCLayerColor:setTouchMode() end 
function CCLayerColor:isAccelerometerEnabled() end 
function CCLayerColor:setTouchEnabled() end 
function CCLayerColor:setTouchPriority() end 
function CCLayerColor:unregisterScriptAccelerateHandler() end 
function CCLayerColor:unregisterScriptTouchHandler() end 
function CCLayerColor:setKeypadEnabled() end 
function CCLayerColor:registerScriptTouchHandler() end 
function CCLayerColor:getTouchPriority() end 
function CCLayerColor:isKeypadEnabled() end 
function CCLayerColor:getTouchMode() end 
function CCLayerColor:new() end 
---
-- @return @class CCLayerColor
--
function CCLayerColor:create() end 
function CCLayerColor:delete() end 
function CCLayerColor:updateDisplayedColor() end 
function CCLayerColor:init() end 
function CCLayerColor:setColor() end 
function CCLayerColor:getDisplayedColor() end 
function CCLayerColor:setCascadeColorEnabled() end 
function CCLayerColor:setCascadeOpacityEnabled() end 
function CCLayerColor:setOpacity() end 
function CCLayerColor:getColor() end 
function CCLayerColor:updateDisplayedOpacity() end 
function CCLayerColor:getOpacity() end 
function CCLayerColor:setOpacityModifyRGB() end 
function CCLayerColor:isOpacityModifyRGB() end 
function CCLayerColor:isCascadeOpacityEnabled() end 
function CCLayerColor:getDisplayedOpacity() end 
function CCLayerColor:new_local() end 
function CCLayerColor:isCascadeColorEnabled() end 
function CCLayerColor:changeWidthAndHeight() end 
function CCLayerColor:setOpacity() end 
function CCLayerColor:getColor() end 
function CCLayerColor:getOpacity() end 
function CCLayerColor:setColor() end 
---
-- @return @class CCLayerColor
--
function CCLayerColor:create() end 
function CCLayerColor:isOpacityModifyRGB() end 
function CCLayerColor:setOpacityModifyRGB() end 
function CCLayerColor:getBlendFunc() end 
function CCLayerColor:setBlendFunc() end 
function CCLayerColor:changeWidth() end 
function CCLayerColor:changeHeight() end 
