---@classdef CCLabelBMFont
CCLabelBMFont = {}
function CCLabelBMFont:autorelease() end 
function CCLabelBMFont:retain() end 
function CCLabelBMFont:retainCount() end 
function CCLabelBMFont:isEqual() end 
function CCLabelBMFont:copy() end 
function CCLabelBMFont:release() end 
function CCLabelBMFont:isSingleReference() end 
function CCLabelBMFont:visit() end 
function CCLabelBMFont:getUserObject() end 
function CCLabelBMFont:getSkewY() end 
function CCLabelBMFont:convertTouchToNodeSpace() end 
function CCLabelBMFont:getVertexZ() end 
function CCLabelBMFont:setParent() end 
function CCLabelBMFont:boundingBox() end 
function CCLabelBMFont:setVisible() end 
function CCLabelBMFont:stopActionByTag() end 
function CCLabelBMFont:getScaleY() end 
function CCLabelBMFont:setScaleX() end 
function CCLabelBMFont:reorderChild() end 
function CCLabelBMFont:setPositionX() end 
function CCLabelBMFont:removeFromParentAndCleanup() end 
function CCLabelBMFont:setTag() end 
function CCLabelBMFont:getChildrenCount() end 
function CCLabelBMFont:setScale() end 
function CCLabelBMFont:addChild() end 
function CCLabelBMFont:isVisible() end 
function CCLabelBMFont:setActionManager() end 
function CCLabelBMFont:setScheduler() end 
function CCLabelBMFont:getContentSize() end 
function CCLabelBMFont:getAnchorPoint() end 
function CCLabelBMFont:getTag() end 
function CCLabelBMFont:setGrid() end 
function CCLabelBMFont:convertToWorldSpace() end 
function CCLabelBMFont:setSkewX() end 
function CCLabelBMFont:setZOrder() end 
function CCLabelBMFont:worldToNodeTransform() end 
function CCLabelBMFont:getPosition() end 
function CCLabelBMFont:getSkewX() end 
function CCLabelBMFont:getScheduler() end 
function CCLabelBMFont:ignoreAnchorPointForPosition() end 
function CCLabelBMFont:setPosition() end 
function CCLabelBMFont:getParent() end 
function CCLabelBMFont:unscheduleUpdate() end 
function CCLabelBMFont:scheduleUpdateWithPriorityLua() end 
function CCLabelBMFont:removeChildByTag() end 
function CCLabelBMFont:convertToNodeSpaceAR() end 
function CCLabelBMFont:convertTouchToNodeSpaceAR() end 
function CCLabelBMFont:convertToWorldSpaceAR() end 
function CCLabelBMFont:setRotation() end 
function CCLabelBMFont:getComponent() end 
function CCLabelBMFont:convertToNodeSpace() end 
---
-- @return @class CCLabelBMFont
--
function CCLabelBMFont:create() end 
function CCLabelBMFont:getScale() end 
function CCLabelBMFont:getPositionY() end 
function CCLabelBMFont:getChildByTag() end 
function CCLabelBMFont:setContentSize() end 
function CCLabelBMFont:description() end 
function CCLabelBMFont:cleanup() end 
function CCLabelBMFont:getRotation() end 
function CCLabelBMFont:nodeToParentTransform() end 
function CCLabelBMFont:stopAction() end 
function CCLabelBMFont:numberOfRunningActions() end 
function CCLabelBMFont:removeAllChildren() end 
function CCLabelBMFont:runAction() end 
function CCLabelBMFont:setUserObject() end 
function CCLabelBMFont:parentToNodeTransform() end 
function CCLabelBMFont:removeChild() end 
function CCLabelBMFont:getAnchorPointInPoints() end 
function CCLabelBMFont:getScaleX() end 
function CCLabelBMFont:transform() end 
function CCLabelBMFont:getActionManager() end 
function CCLabelBMFont:draw() end 
function CCLabelBMFont:setScaleY() end 
function CCLabelBMFont:unregisterScriptHandler() end 
function CCLabelBMFont:setVertexZ() end 
function CCLabelBMFont:setAnchorPoint() end 
function CCLabelBMFont:getShaderProgram() end 
function CCLabelBMFont:stopAllActions() end 
function CCLabelBMFont:setUserData() end 
function CCLabelBMFont:setShaderProgram() end 
function CCLabelBMFont:getActionByTag() end 
function CCLabelBMFont:getGLServerState() end 
function CCLabelBMFont:getOrderOfArrival() end 
function CCLabelBMFont:getPositionX() end 
function CCLabelBMFont:setGLServerState() end 
function CCLabelBMFont:setSkewY() end 
function CCLabelBMFont:setOrderOfArrival() end 
function CCLabelBMFont:nodeToWorldTransform() end 
function CCLabelBMFont:getChildren() end 
function CCLabelBMFont:transformAncestors() end 
function CCLabelBMFont:getGrid() end 
function CCLabelBMFont:isRunning() end 
function CCLabelBMFont:registerScriptHandler() end 
function CCLabelBMFont:getCamera() end 
function CCLabelBMFont:isIgnoreAnchorPointForPosition() end 
function CCLabelBMFont:getUserData() end 
function CCLabelBMFont:setPositionY() end 
function CCLabelBMFont:getZOrder() end 
function CCLabelBMFont:setTextureAtlas() end 
function CCLabelBMFont:setBlendFunc() end 
---
-- @return @class CCLabelBMFont
--
function CCLabelBMFont:create() end 
function CCLabelBMFont:getTexture() end 
function CCLabelBMFont:appendChild() end 
function CCLabelBMFont:removeAllChildren() end 
function CCLabelBMFont:createWithTexture() end 
function CCLabelBMFont:removeChild() end 
function CCLabelBMFont:rebuildIndexInOrder() end 
function CCLabelBMFont:atlasIndexForChild() end 
function CCLabelBMFont:increaseAtlasCapacity() end 
function CCLabelBMFont:addChild() end 
function CCLabelBMFont:setTexture() end 
function CCLabelBMFont:getTextureAtlas() end 
function CCLabelBMFont:removeChildAtIndex() end 
function CCLabelBMFont:getDescendants() end 
function CCLabelBMFont:sortAllChildren() end 
function CCLabelBMFont:getBlendFunc() end 
function CCLabelBMFont:reorderBatch() end 
function CCLabelBMFont:insertChild() end 
function CCLabelBMFont:highestAtlasIndexInChild() end 
function CCLabelBMFont:removeSpriteFromAtlas() end 
function CCLabelBMFont:lowestAtlasIndexInChild() end 
function CCLabelBMFont:reorderChild() end 
function CCLabelBMFont:new() end 
function CCLabelBMFont:purgeCachedData() end 
function CCLabelBMFont:delete() end 
function CCLabelBMFont:setAlignment() end 
function CCLabelBMFont:getString() end 
function CCLabelBMFont:init() end 
function CCLabelBMFont:setColor() end 
function CCLabelBMFont:new_local() end 
function CCLabelBMFont:setScaleX() end 
function CCLabelBMFont:getFntFile() end 
function CCLabelBMFont:setOpacity() end 
function CCLabelBMFont:getColor() end 
function CCLabelBMFont:setLineBreakWithoutSpace() end 
function CCLabelBMFont:getOpacity() end 
function CCLabelBMFont:setOpacityModifyRGB() end 
---
-- @return @class CCLabelBMFont
--
function CCLabelBMFont:create() end 
function CCLabelBMFont:isOpacityModifyRGB() end 
function CCLabelBMFont:setString() end 
function CCLabelBMFont:setFntFile() end 
function CCLabelBMFont:setScale() end 
function CCLabelBMFont:setCString() end 
function CCLabelBMFont:setWidth() end 
function CCLabelBMFont:setScaleY() end 
