---@classdef CCMenuItemLabel
CCMenuItemLabel = {}
function CCMenuItemLabel:autorelease() end 
function CCMenuItemLabel:retain() end 
function CCMenuItemLabel:retainCount() end 
function CCMenuItemLabel:isEqual() end 
function CCMenuItemLabel:copy() end 
function CCMenuItemLabel:release() end 
function CCMenuItemLabel:isSingleReference() end 
function CCMenuItemLabel:visit() end 
function CCMenuItemLabel:getUserObject() end 
function CCMenuItemLabel:getSkewY() end 
function CCMenuItemLabel:convertTouchToNodeSpace() end 
function CCMenuItemLabel:getVertexZ() end 
function CCMenuItemLabel:setParent() end 
function CCMenuItemLabel:boundingBox() end 
function CCMenuItemLabel:setVisible() end 
function CCMenuItemLabel:stopActionByTag() end 
function CCMenuItemLabel:getScaleY() end 
function CCMenuItemLabel:setScaleX() end 
function CCMenuItemLabel:reorderChild() end 
function CCMenuItemLabel:setPositionX() end 
function CCMenuItemLabel:removeFromParentAndCleanup() end 
function CCMenuItemLabel:setTag() end 
function CCMenuItemLabel:getChildrenCount() end 
function CCMenuItemLabel:setScale() end 
function CCMenuItemLabel:addChild() end 
function CCMenuItemLabel:isVisible() end 
function CCMenuItemLabel:setActionManager() end 
function CCMenuItemLabel:setScheduler() end 
function CCMenuItemLabel:getContentSize() end 
function CCMenuItemLabel:getAnchorPoint() end 
function CCMenuItemLabel:getTag() end 
function CCMenuItemLabel:setGrid() end 
function CCMenuItemLabel:convertToWorldSpace() end 
function CCMenuItemLabel:setSkewX() end 
function CCMenuItemLabel:setZOrder() end 
function CCMenuItemLabel:worldToNodeTransform() end 
function CCMenuItemLabel:getPosition() end 
function CCMenuItemLabel:getSkewX() end 
function CCMenuItemLabel:getScheduler() end 
function CCMenuItemLabel:ignoreAnchorPointForPosition() end 
function CCMenuItemLabel:setPosition() end 
function CCMenuItemLabel:getParent() end 
function CCMenuItemLabel:unscheduleUpdate() end 
function CCMenuItemLabel:scheduleUpdateWithPriorityLua() end 
function CCMenuItemLabel:removeChildByTag() end 
function CCMenuItemLabel:convertToNodeSpaceAR() end 
function CCMenuItemLabel:convertTouchToNodeSpaceAR() end 
function CCMenuItemLabel:convertToWorldSpaceAR() end 
function CCMenuItemLabel:setRotation() end 
function CCMenuItemLabel:getComponent() end 
function CCMenuItemLabel:convertToNodeSpace() end 
---
-- @return @class CCMenuItemLabel
--
function CCMenuItemLabel:create() end 
function CCMenuItemLabel:getScale() end 
function CCMenuItemLabel:getPositionY() end 
function CCMenuItemLabel:getChildByTag() end 
function CCMenuItemLabel:setContentSize() end 
function CCMenuItemLabel:description() end 
function CCMenuItemLabel:cleanup() end 
function CCMenuItemLabel:getRotation() end 
function CCMenuItemLabel:nodeToParentTransform() end 
function CCMenuItemLabel:stopAction() end 
function CCMenuItemLabel:numberOfRunningActions() end 
function CCMenuItemLabel:removeAllChildren() end 
function CCMenuItemLabel:runAction() end 
function CCMenuItemLabel:setUserObject() end 
function CCMenuItemLabel:parentToNodeTransform() end 
function CCMenuItemLabel:removeChild() end 
function CCMenuItemLabel:getAnchorPointInPoints() end 
function CCMenuItemLabel:getScaleX() end 
function CCMenuItemLabel:transform() end 
function CCMenuItemLabel:getActionManager() end 
function CCMenuItemLabel:draw() end 
function CCMenuItemLabel:setScaleY() end 
function CCMenuItemLabel:unregisterScriptHandler() end 
function CCMenuItemLabel:setVertexZ() end 
function CCMenuItemLabel:setAnchorPoint() end 
function CCMenuItemLabel:getShaderProgram() end 
function CCMenuItemLabel:stopAllActions() end 
function CCMenuItemLabel:setUserData() end 
function CCMenuItemLabel:setShaderProgram() end 
function CCMenuItemLabel:getActionByTag() end 
function CCMenuItemLabel:getGLServerState() end 
function CCMenuItemLabel:getOrderOfArrival() end 
function CCMenuItemLabel:getPositionX() end 
function CCMenuItemLabel:setGLServerState() end 
function CCMenuItemLabel:setSkewY() end 
function CCMenuItemLabel:setOrderOfArrival() end 
function CCMenuItemLabel:nodeToWorldTransform() end 
function CCMenuItemLabel:getChildren() end 
function CCMenuItemLabel:transformAncestors() end 
function CCMenuItemLabel:getGrid() end 
function CCMenuItemLabel:isRunning() end 
function CCMenuItemLabel:registerScriptHandler() end 
function CCMenuItemLabel:getCamera() end 
function CCMenuItemLabel:isIgnoreAnchorPointForPosition() end 
function CCMenuItemLabel:getUserData() end 
function CCMenuItemLabel:setPositionY() end 
function CCMenuItemLabel:getZOrder() end 
function CCMenuItemLabel:new() end 
function CCMenuItemLabel:delete() end 
function CCMenuItemLabel:updateDisplayedColor() end 
function CCMenuItemLabel:init() end 
function CCMenuItemLabel:setColor() end 
function CCMenuItemLabel:getDisplayedColor() end 
function CCMenuItemLabel:setCascadeColorEnabled() end 
function CCMenuItemLabel:setCascadeOpacityEnabled() end 
function CCMenuItemLabel:setOpacity() end 
function CCMenuItemLabel:getColor() end 
function CCMenuItemLabel:updateDisplayedOpacity() end 
function CCMenuItemLabel:getOpacity() end 
function CCMenuItemLabel:setOpacityModifyRGB() end 
function CCMenuItemLabel:isCascadeOpacityEnabled() end 
function CCMenuItemLabel:isOpacityModifyRGB() end 
function CCMenuItemLabel:getDisplayedOpacity() end 
function CCMenuItemLabel:new_local() end 
function CCMenuItemLabel:isCascadeColorEnabled() end 
function CCMenuItemLabel:setEnabled() end 
function CCMenuItemLabel:unregisterScriptTapHandler() end 
function CCMenuItemLabel:rect() end 
function CCMenuItemLabel:isSelected() end 
function CCMenuItemLabel:activate() end 
function CCMenuItemLabel:unselected() end 
function CCMenuItemLabel:selected() end 
function CCMenuItemLabel:isEnabled() end 
function CCMenuItemLabel:registerScriptTapHandler() end 
function CCMenuItemLabel:setOpacity() end 
function CCMenuItemLabel:getColor() end 
---
-- @return @class CCMenuItemLabel
--
function CCMenuItemLabel:create() end 
function CCMenuItemLabel:isOpacityModifyRGB() end 
function CCMenuItemLabel:setOpacityModifyRGB() end 
function CCMenuItemLabel:getOpacity() end 
function CCMenuItemLabel:setEnabled() end 
function CCMenuItemLabel:activate() end 
function CCMenuItemLabel:setColor() end 
function CCMenuItemLabel:getLabel() end 
function CCMenuItemLabel:getDisabledColor() end 
function CCMenuItemLabel:selected() end 
function CCMenuItemLabel:setString() end 
function CCMenuItemLabel:unselected() end 
function CCMenuItemLabel:setLabel() end 
function CCMenuItemLabel:setDisabledColor() end 
