---@classdef CCMenuItem
CCMenuItem = {}
function CCMenuItem:autorelease() end 
function CCMenuItem:retain() end 
function CCMenuItem:retainCount() end 
function CCMenuItem:isEqual() end 
function CCMenuItem:copy() end 
function CCMenuItem:release() end 
function CCMenuItem:isSingleReference() end 
function CCMenuItem:visit() end 
function CCMenuItem:getUserObject() end 
function CCMenuItem:getSkewY() end 
function CCMenuItem:convertTouchToNodeSpace() end 
function CCMenuItem:getVertexZ() end 
function CCMenuItem:setParent() end 
function CCMenuItem:boundingBox() end 
function CCMenuItem:setVisible() end 
function CCMenuItem:stopActionByTag() end 
function CCMenuItem:getScaleY() end 
function CCMenuItem:setScaleX() end 
function CCMenuItem:reorderChild() end 
function CCMenuItem:setPositionX() end 
function CCMenuItem:removeFromParentAndCleanup() end 
function CCMenuItem:setTag() end 
function CCMenuItem:getChildrenCount() end 
function CCMenuItem:setScale() end 
function CCMenuItem:addChild() end 
function CCMenuItem:isVisible() end 
function CCMenuItem:setActionManager() end 
function CCMenuItem:setScheduler() end 
function CCMenuItem:getContentSize() end 
function CCMenuItem:getAnchorPoint() end 
function CCMenuItem:getTag() end 
function CCMenuItem:setGrid() end 
function CCMenuItem:convertToWorldSpace() end 
function CCMenuItem:setSkewX() end 
function CCMenuItem:setZOrder() end 
function CCMenuItem:worldToNodeTransform() end 
function CCMenuItem:getPosition() end 
function CCMenuItem:getSkewX() end 
function CCMenuItem:getScheduler() end 
function CCMenuItem:ignoreAnchorPointForPosition() end 
function CCMenuItem:setPosition() end 
function CCMenuItem:getParent() end 
function CCMenuItem:unscheduleUpdate() end 
function CCMenuItem:scheduleUpdateWithPriorityLua() end 
function CCMenuItem:removeChildByTag() end 
function CCMenuItem:convertToNodeSpaceAR() end 
function CCMenuItem:convertTouchToNodeSpaceAR() end 
function CCMenuItem:convertToWorldSpaceAR() end 
function CCMenuItem:setRotation() end 
function CCMenuItem:getComponent() end 
function CCMenuItem:convertToNodeSpace() end 
---
-- @return @class CCMenuItem
--
function CCMenuItem:create() end 
function CCMenuItem:getScale() end 
function CCMenuItem:getPositionY() end 
function CCMenuItem:getChildByTag() end 
function CCMenuItem:setContentSize() end 
function CCMenuItem:description() end 
function CCMenuItem:cleanup() end 
function CCMenuItem:getRotation() end 
function CCMenuItem:nodeToParentTransform() end 
function CCMenuItem:stopAction() end 
function CCMenuItem:numberOfRunningActions() end 
function CCMenuItem:removeAllChildren() end 
function CCMenuItem:runAction() end 
function CCMenuItem:setUserObject() end 
function CCMenuItem:parentToNodeTransform() end 
function CCMenuItem:removeChild() end 
function CCMenuItem:getAnchorPointInPoints() end 
function CCMenuItem:getScaleX() end 
function CCMenuItem:transform() end 
function CCMenuItem:getActionManager() end 
function CCMenuItem:draw() end 
function CCMenuItem:setScaleY() end 
function CCMenuItem:unregisterScriptHandler() end 
function CCMenuItem:setVertexZ() end 
function CCMenuItem:setAnchorPoint() end 
function CCMenuItem:getShaderProgram() end 
function CCMenuItem:stopAllActions() end 
function CCMenuItem:setUserData() end 
function CCMenuItem:setShaderProgram() end 
function CCMenuItem:getActionByTag() end 
function CCMenuItem:getGLServerState() end 
function CCMenuItem:getOrderOfArrival() end 
function CCMenuItem:getPositionX() end 
function CCMenuItem:setGLServerState() end 
function CCMenuItem:setSkewY() end 
function CCMenuItem:setOrderOfArrival() end 
function CCMenuItem:nodeToWorldTransform() end 
function CCMenuItem:getChildren() end 
function CCMenuItem:transformAncestors() end 
function CCMenuItem:getGrid() end 
function CCMenuItem:isRunning() end 
function CCMenuItem:registerScriptHandler() end 
function CCMenuItem:getCamera() end 
function CCMenuItem:isIgnoreAnchorPointForPosition() end 
function CCMenuItem:getUserData() end 
function CCMenuItem:setPositionY() end 
function CCMenuItem:getZOrder() end 
function CCMenuItem:new() end 
function CCMenuItem:delete() end 
function CCMenuItem:updateDisplayedColor() end 
function CCMenuItem:init() end 
function CCMenuItem:setColor() end 
function CCMenuItem:getDisplayedColor() end 
function CCMenuItem:setCascadeColorEnabled() end 
function CCMenuItem:setCascadeOpacityEnabled() end 
function CCMenuItem:setOpacity() end 
function CCMenuItem:getColor() end 
function CCMenuItem:updateDisplayedOpacity() end 
function CCMenuItem:getOpacity() end 
function CCMenuItem:setOpacityModifyRGB() end 
function CCMenuItem:isCascadeOpacityEnabled() end 
function CCMenuItem:isOpacityModifyRGB() end 
function CCMenuItem:getDisplayedOpacity() end 
function CCMenuItem:new_local() end 
function CCMenuItem:isCascadeColorEnabled() end 
function CCMenuItem:setEnabled() end 
function CCMenuItem:unregisterScriptTapHandler() end 
function CCMenuItem:rect() end 
function CCMenuItem:isSelected() end 
function CCMenuItem:activate() end 
function CCMenuItem:unselected() end 
function CCMenuItem:selected() end 
function CCMenuItem:isEnabled() end 
function CCMenuItem:registerScriptTapHandler() end 
