---@classdef CCMenuItemAtlasFont
CCMenuItemAtlasFont = {}
function CCMenuItemAtlasFont:autorelease() end 
function CCMenuItemAtlasFont:retain() end 
function CCMenuItemAtlasFont:retainCount() end 
function CCMenuItemAtlasFont:isEqual() end 
function CCMenuItemAtlasFont:copy() end 
function CCMenuItemAtlasFont:release() end 
function CCMenuItemAtlasFont:isSingleReference() end 
function CCMenuItemAtlasFont:visit() end 
function CCMenuItemAtlasFont:getUserObject() end 
function CCMenuItemAtlasFont:getSkewY() end 
function CCMenuItemAtlasFont:convertTouchToNodeSpace() end 
function CCMenuItemAtlasFont:getVertexZ() end 
function CCMenuItemAtlasFont:setParent() end 
function CCMenuItemAtlasFont:boundingBox() end 
function CCMenuItemAtlasFont:setVisible() end 
function CCMenuItemAtlasFont:stopActionByTag() end 
function CCMenuItemAtlasFont:getScaleY() end 
function CCMenuItemAtlasFont:setScaleX() end 
function CCMenuItemAtlasFont:reorderChild() end 
function CCMenuItemAtlasFont:setPositionX() end 
function CCMenuItemAtlasFont:removeFromParentAndCleanup() end 
function CCMenuItemAtlasFont:setTag() end 
function CCMenuItemAtlasFont:getChildrenCount() end 
function CCMenuItemAtlasFont:setScale() end 
function CCMenuItemAtlasFont:addChild() end 
function CCMenuItemAtlasFont:isVisible() end 
function CCMenuItemAtlasFont:setActionManager() end 
function CCMenuItemAtlasFont:setScheduler() end 
function CCMenuItemAtlasFont:getContentSize() end 
function CCMenuItemAtlasFont:getAnchorPoint() end 
function CCMenuItemAtlasFont:getTag() end 
function CCMenuItemAtlasFont:setGrid() end 
function CCMenuItemAtlasFont:convertToWorldSpace() end 
function CCMenuItemAtlasFont:setSkewX() end 
function CCMenuItemAtlasFont:setZOrder() end 
function CCMenuItemAtlasFont:worldToNodeTransform() end 
function CCMenuItemAtlasFont:getPosition() end 
function CCMenuItemAtlasFont:getSkewX() end 
function CCMenuItemAtlasFont:getScheduler() end 
function CCMenuItemAtlasFont:ignoreAnchorPointForPosition() end 
function CCMenuItemAtlasFont:setPosition() end 
function CCMenuItemAtlasFont:getParent() end 
function CCMenuItemAtlasFont:unscheduleUpdate() end 
function CCMenuItemAtlasFont:scheduleUpdateWithPriorityLua() end 
function CCMenuItemAtlasFont:removeChildByTag() end 
function CCMenuItemAtlasFont:convertToNodeSpaceAR() end 
function CCMenuItemAtlasFont:convertTouchToNodeSpaceAR() end 
function CCMenuItemAtlasFont:convertToWorldSpaceAR() end 
function CCMenuItemAtlasFont:setRotation() end 
function CCMenuItemAtlasFont:getComponent() end 
function CCMenuItemAtlasFont:convertToNodeSpace() end 
---
-- @return @class CCMenuItemAtlasFont
--
function CCMenuItemAtlasFont:create() end 
function CCMenuItemAtlasFont:getScale() end 
function CCMenuItemAtlasFont:getPositionY() end 
function CCMenuItemAtlasFont:getChildByTag() end 
function CCMenuItemAtlasFont:setContentSize() end 
function CCMenuItemAtlasFont:description() end 
function CCMenuItemAtlasFont:cleanup() end 
function CCMenuItemAtlasFont:getRotation() end 
function CCMenuItemAtlasFont:nodeToParentTransform() end 
function CCMenuItemAtlasFont:stopAction() end 
function CCMenuItemAtlasFont:numberOfRunningActions() end 
function CCMenuItemAtlasFont:removeAllChildren() end 
function CCMenuItemAtlasFont:runAction() end 
function CCMenuItemAtlasFont:setUserObject() end 
function CCMenuItemAtlasFont:parentToNodeTransform() end 
function CCMenuItemAtlasFont:removeChild() end 
function CCMenuItemAtlasFont:getAnchorPointInPoints() end 
function CCMenuItemAtlasFont:getScaleX() end 
function CCMenuItemAtlasFont:transform() end 
function CCMenuItemAtlasFont:getActionManager() end 
function CCMenuItemAtlasFont:draw() end 
function CCMenuItemAtlasFont:setScaleY() end 
function CCMenuItemAtlasFont:unregisterScriptHandler() end 
function CCMenuItemAtlasFont:setVertexZ() end 
function CCMenuItemAtlasFont:setAnchorPoint() end 
function CCMenuItemAtlasFont:getShaderProgram() end 
function CCMenuItemAtlasFont:stopAllActions() end 
function CCMenuItemAtlasFont:setUserData() end 
function CCMenuItemAtlasFont:setShaderProgram() end 
function CCMenuItemAtlasFont:getActionByTag() end 
function CCMenuItemAtlasFont:getGLServerState() end 
function CCMenuItemAtlasFont:getOrderOfArrival() end 
function CCMenuItemAtlasFont:getPositionX() end 
function CCMenuItemAtlasFont:setGLServerState() end 
function CCMenuItemAtlasFont:setSkewY() end 
function CCMenuItemAtlasFont:setOrderOfArrival() end 
function CCMenuItemAtlasFont:nodeToWorldTransform() end 
function CCMenuItemAtlasFont:getChildren() end 
function CCMenuItemAtlasFont:transformAncestors() end 
function CCMenuItemAtlasFont:getGrid() end 
function CCMenuItemAtlasFont:isRunning() end 
function CCMenuItemAtlasFont:registerScriptHandler() end 
function CCMenuItemAtlasFont:getCamera() end 
function CCMenuItemAtlasFont:isIgnoreAnchorPointForPosition() end 
function CCMenuItemAtlasFont:getUserData() end 
function CCMenuItemAtlasFont:setPositionY() end 
function CCMenuItemAtlasFont:getZOrder() end 
function CCMenuItemAtlasFont:new() end 
function CCMenuItemAtlasFont:delete() end 
function CCMenuItemAtlasFont:updateDisplayedColor() end 
function CCMenuItemAtlasFont:init() end 
function CCMenuItemAtlasFont:setColor() end 
function CCMenuItemAtlasFont:getDisplayedColor() end 
function CCMenuItemAtlasFont:setCascadeColorEnabled() end 
function CCMenuItemAtlasFont:setCascadeOpacityEnabled() end 
function CCMenuItemAtlasFont:setOpacity() end 
function CCMenuItemAtlasFont:getColor() end 
function CCMenuItemAtlasFont:updateDisplayedOpacity() end 
function CCMenuItemAtlasFont:getOpacity() end 
function CCMenuItemAtlasFont:setOpacityModifyRGB() end 
function CCMenuItemAtlasFont:isCascadeOpacityEnabled() end 
function CCMenuItemAtlasFont:isOpacityModifyRGB() end 
function CCMenuItemAtlasFont:getDisplayedOpacity() end 
function CCMenuItemAtlasFont:new_local() end 
function CCMenuItemAtlasFont:isCascadeColorEnabled() end 
function CCMenuItemAtlasFont:setEnabled() end 
function CCMenuItemAtlasFont:unregisterScriptTapHandler() end 
function CCMenuItemAtlasFont:rect() end 
function CCMenuItemAtlasFont:isSelected() end 
function CCMenuItemAtlasFont:activate() end 
function CCMenuItemAtlasFont:unselected() end 
function CCMenuItemAtlasFont:selected() end 
function CCMenuItemAtlasFont:isEnabled() end 
function CCMenuItemAtlasFont:registerScriptTapHandler() end 
function CCMenuItemAtlasFont:setOpacity() end 
function CCMenuItemAtlasFont:getColor() end 
---
-- @return @class CCMenuItemAtlasFont
--
function CCMenuItemAtlasFont:create() end 
function CCMenuItemAtlasFont:isOpacityModifyRGB() end 
function CCMenuItemAtlasFont:setOpacityModifyRGB() end 
function CCMenuItemAtlasFont:getOpacity() end 
function CCMenuItemAtlasFont:setEnabled() end 
function CCMenuItemAtlasFont:activate() end 
function CCMenuItemAtlasFont:setColor() end 
function CCMenuItemAtlasFont:getLabel() end 
function CCMenuItemAtlasFont:getDisabledColor() end 
function CCMenuItemAtlasFont:selected() end 
function CCMenuItemAtlasFont:setString() end 
function CCMenuItemAtlasFont:unselected() end 
function CCMenuItemAtlasFont:setLabel() end 
function CCMenuItemAtlasFont:setDisabledColor() end 
---
-- @return @class CCMenuItemAtlasFont
--
function CCMenuItemAtlasFont:create() end 
