---@classdef CCMenuItemImage
CCMenuItemImage = {}
function CCMenuItemImage:autorelease() end 
function CCMenuItemImage:retain() end 
function CCMenuItemImage:retainCount() end 
function CCMenuItemImage:isEqual() end 
function CCMenuItemImage:copy() end 
function CCMenuItemImage:release() end 
function CCMenuItemImage:isSingleReference() end 
function CCMenuItemImage:visit() end 
function CCMenuItemImage:getUserObject() end 
function CCMenuItemImage:getSkewY() end 
function CCMenuItemImage:convertTouchToNodeSpace() end 
function CCMenuItemImage:getVertexZ() end 
function CCMenuItemImage:setParent() end 
function CCMenuItemImage:boundingBox() end 
function CCMenuItemImage:setVisible() end 
function CCMenuItemImage:stopActionByTag() end 
function CCMenuItemImage:getScaleY() end 
function CCMenuItemImage:setScaleX() end 
function CCMenuItemImage:reorderChild() end 
function CCMenuItemImage:setPositionX() end 
function CCMenuItemImage:removeFromParentAndCleanup() end 
function CCMenuItemImage:setTag() end 
function CCMenuItemImage:getChildrenCount() end 
function CCMenuItemImage:setScale() end 
function CCMenuItemImage:addChild() end 
function CCMenuItemImage:isVisible() end 
function CCMenuItemImage:setActionManager() end 
function CCMenuItemImage:setScheduler() end 
function CCMenuItemImage:getContentSize() end 
function CCMenuItemImage:getAnchorPoint() end 
function CCMenuItemImage:getTag() end 
function CCMenuItemImage:setGrid() end 
function CCMenuItemImage:convertToWorldSpace() end 
function CCMenuItemImage:setSkewX() end 
function CCMenuItemImage:setZOrder() end 
function CCMenuItemImage:worldToNodeTransform() end 
function CCMenuItemImage:getPosition() end 
function CCMenuItemImage:getSkewX() end 
function CCMenuItemImage:getScheduler() end 
function CCMenuItemImage:ignoreAnchorPointForPosition() end 
function CCMenuItemImage:setPosition() end 
function CCMenuItemImage:getParent() end 
function CCMenuItemImage:unscheduleUpdate() end 
function CCMenuItemImage:scheduleUpdateWithPriorityLua() end 
function CCMenuItemImage:removeChildByTag() end 
function CCMenuItemImage:convertToNodeSpaceAR() end 
function CCMenuItemImage:convertTouchToNodeSpaceAR() end 
function CCMenuItemImage:convertToWorldSpaceAR() end 
function CCMenuItemImage:setRotation() end 
function CCMenuItemImage:getComponent() end 
function CCMenuItemImage:convertToNodeSpace() end 
---
-- @return @class CCMenuItemImage
--
function CCMenuItemImage:create() end 
function CCMenuItemImage:getScale() end 
function CCMenuItemImage:getPositionY() end 
function CCMenuItemImage:getChildByTag() end 
function CCMenuItemImage:setContentSize() end 
function CCMenuItemImage:description() end 
function CCMenuItemImage:cleanup() end 
function CCMenuItemImage:getRotation() end 
function CCMenuItemImage:nodeToParentTransform() end 
function CCMenuItemImage:stopAction() end 
function CCMenuItemImage:numberOfRunningActions() end 
function CCMenuItemImage:removeAllChildren() end 
function CCMenuItemImage:runAction() end 
function CCMenuItemImage:setUserObject() end 
function CCMenuItemImage:parentToNodeTransform() end 
function CCMenuItemImage:removeChild() end 
function CCMenuItemImage:getAnchorPointInPoints() end 
function CCMenuItemImage:getScaleX() end 
function CCMenuItemImage:transform() end 
function CCMenuItemImage:getActionManager() end 
function CCMenuItemImage:draw() end 
function CCMenuItemImage:setScaleY() end 
function CCMenuItemImage:unregisterScriptHandler() end 
function CCMenuItemImage:setVertexZ() end 
function CCMenuItemImage:setAnchorPoint() end 
function CCMenuItemImage:getShaderProgram() end 
function CCMenuItemImage:stopAllActions() end 
function CCMenuItemImage:setUserData() end 
function CCMenuItemImage:setShaderProgram() end 
function CCMenuItemImage:getActionByTag() end 
function CCMenuItemImage:getGLServerState() end 
function CCMenuItemImage:getOrderOfArrival() end 
function CCMenuItemImage:getPositionX() end 
function CCMenuItemImage:setGLServerState() end 
function CCMenuItemImage:setSkewY() end 
function CCMenuItemImage:setOrderOfArrival() end 
function CCMenuItemImage:nodeToWorldTransform() end 
function CCMenuItemImage:getChildren() end 
function CCMenuItemImage:transformAncestors() end 
function CCMenuItemImage:getGrid() end 
function CCMenuItemImage:isRunning() end 
function CCMenuItemImage:registerScriptHandler() end 
function CCMenuItemImage:getCamera() end 
function CCMenuItemImage:isIgnoreAnchorPointForPosition() end 
function CCMenuItemImage:getUserData() end 
function CCMenuItemImage:setPositionY() end 
function CCMenuItemImage:getZOrder() end 
function CCMenuItemImage:new() end 
function CCMenuItemImage:delete() end 
function CCMenuItemImage:updateDisplayedColor() end 
function CCMenuItemImage:init() end 
function CCMenuItemImage:setColor() end 
function CCMenuItemImage:getDisplayedColor() end 
function CCMenuItemImage:setCascadeColorEnabled() end 
function CCMenuItemImage:setCascadeOpacityEnabled() end 
function CCMenuItemImage:setOpacity() end 
function CCMenuItemImage:getColor() end 
function CCMenuItemImage:updateDisplayedOpacity() end 
function CCMenuItemImage:getOpacity() end 
function CCMenuItemImage:setOpacityModifyRGB() end 
function CCMenuItemImage:isCascadeOpacityEnabled() end 
function CCMenuItemImage:isOpacityModifyRGB() end 
function CCMenuItemImage:getDisplayedOpacity() end 
function CCMenuItemImage:new_local() end 
function CCMenuItemImage:isCascadeColorEnabled() end 
function CCMenuItemImage:setEnabled() end 
function CCMenuItemImage:unregisterScriptTapHandler() end 
function CCMenuItemImage:rect() end 
function CCMenuItemImage:isSelected() end 
function CCMenuItemImage:activate() end 
function CCMenuItemImage:unselected() end 
function CCMenuItemImage:selected() end 
function CCMenuItemImage:isEnabled() end 
function CCMenuItemImage:registerScriptTapHandler() end 
function CCMenuItemImage:setOpacity() end 
function CCMenuItemImage:getColor() end 
function CCMenuItemImage:setSelectedImage() end 
function CCMenuItemImage:getNormalImage() end 
---
-- @return @class CCMenuItemImage
--
function CCMenuItemImage:create() end 
function CCMenuItemImage:getOpacity() end 
function CCMenuItemImage:isOpacityModifyRGB() end 
function CCMenuItemImage:setOpacityModifyRGB() end 
function CCMenuItemImage:setColor() end 
function CCMenuItemImage:setEnabled() end 
function CCMenuItemImage:setDisabledImage() end 
function CCMenuItemImage:selected() end 
function CCMenuItemImage:getDisabledImage() end 
function CCMenuItemImage:unselected() end 
function CCMenuItemImage:getSelectedImage() end 
function CCMenuItemImage:setNormalImage() end 
function CCMenuItemImage:setOpacity() end 
function CCMenuItemImage:getColor() end 
function CCMenuItemImage:setDisabledSpriteFrame() end 
function CCMenuItemImage:getOpacity() end 
function CCMenuItemImage:setColor() end 
---
-- @return @class CCMenuItemImage
--
function CCMenuItemImage:create() end 
function CCMenuItemImage:setSelectedSpriteFrame() end 
function CCMenuItemImage:setNormalSpriteFrame() end 
