---@classdef CCMenuItemSprite
CCMenuItemSprite = {}
function CCMenuItemSprite:autorelease() end 
function CCMenuItemSprite:retain() end 
function CCMenuItemSprite:retainCount() end 
function CCMenuItemSprite:isEqual() end 
function CCMenuItemSprite:copy() end 
function CCMenuItemSprite:release() end 
function CCMenuItemSprite:isSingleReference() end 
function CCMenuItemSprite:visit() end 
function CCMenuItemSprite:getUserObject() end 
function CCMenuItemSprite:getSkewY() end 
function CCMenuItemSprite:convertTouchToNodeSpace() end 
function CCMenuItemSprite:getVertexZ() end 
function CCMenuItemSprite:setParent() end 
function CCMenuItemSprite:boundingBox() end 
function CCMenuItemSprite:setVisible() end 
function CCMenuItemSprite:stopActionByTag() end 
function CCMenuItemSprite:getScaleY() end 
function CCMenuItemSprite:setScaleX() end 
function CCMenuItemSprite:reorderChild() end 
function CCMenuItemSprite:setPositionX() end 
function CCMenuItemSprite:removeFromParentAndCleanup() end 
function CCMenuItemSprite:setTag() end 
function CCMenuItemSprite:getChildrenCount() end 
function CCMenuItemSprite:setScale() end 
function CCMenuItemSprite:addChild() end 
function CCMenuItemSprite:isVisible() end 
function CCMenuItemSprite:setActionManager() end 
function CCMenuItemSprite:setScheduler() end 
function CCMenuItemSprite:getContentSize() end 
function CCMenuItemSprite:getAnchorPoint() end 
function CCMenuItemSprite:getTag() end 
function CCMenuItemSprite:setGrid() end 
function CCMenuItemSprite:convertToWorldSpace() end 
function CCMenuItemSprite:setSkewX() end 
function CCMenuItemSprite:setZOrder() end 
function CCMenuItemSprite:worldToNodeTransform() end 
function CCMenuItemSprite:getPosition() end 
function CCMenuItemSprite:getSkewX() end 
function CCMenuItemSprite:getScheduler() end 
function CCMenuItemSprite:ignoreAnchorPointForPosition() end 
function CCMenuItemSprite:setPosition() end 
function CCMenuItemSprite:getParent() end 
function CCMenuItemSprite:unscheduleUpdate() end 
function CCMenuItemSprite:scheduleUpdateWithPriorityLua() end 
function CCMenuItemSprite:removeChildByTag() end 
function CCMenuItemSprite:convertToNodeSpaceAR() end 
function CCMenuItemSprite:convertTouchToNodeSpaceAR() end 
function CCMenuItemSprite:convertToWorldSpaceAR() end 
function CCMenuItemSprite:setRotation() end 
function CCMenuItemSprite:getComponent() end 
function CCMenuItemSprite:convertToNodeSpace() end 
---
-- @return @class CCMenuItemSprite
--
function CCMenuItemSprite:create() end 
function CCMenuItemSprite:getScale() end 
function CCMenuItemSprite:getPositionY() end 
function CCMenuItemSprite:getChildByTag() end 
function CCMenuItemSprite:setContentSize() end 
function CCMenuItemSprite:description() end 
function CCMenuItemSprite:cleanup() end 
function CCMenuItemSprite:getRotation() end 
function CCMenuItemSprite:nodeToParentTransform() end 
function CCMenuItemSprite:stopAction() end 
function CCMenuItemSprite:numberOfRunningActions() end 
function CCMenuItemSprite:removeAllChildren() end 
function CCMenuItemSprite:runAction() end 
function CCMenuItemSprite:setUserObject() end 
function CCMenuItemSprite:parentToNodeTransform() end 
function CCMenuItemSprite:removeChild() end 
function CCMenuItemSprite:getAnchorPointInPoints() end 
function CCMenuItemSprite:getScaleX() end 
function CCMenuItemSprite:transform() end 
function CCMenuItemSprite:getActionManager() end 
function CCMenuItemSprite:draw() end 
function CCMenuItemSprite:setScaleY() end 
function CCMenuItemSprite:unregisterScriptHandler() end 
function CCMenuItemSprite:setVertexZ() end 
function CCMenuItemSprite:setAnchorPoint() end 
function CCMenuItemSprite:getShaderProgram() end 
function CCMenuItemSprite:stopAllActions() end 
function CCMenuItemSprite:setUserData() end 
function CCMenuItemSprite:setShaderProgram() end 
function CCMenuItemSprite:getActionByTag() end 
function CCMenuItemSprite:getGLServerState() end 
function CCMenuItemSprite:getOrderOfArrival() end 
function CCMenuItemSprite:getPositionX() end 
function CCMenuItemSprite:setGLServerState() end 
function CCMenuItemSprite:setSkewY() end 
function CCMenuItemSprite:setOrderOfArrival() end 
function CCMenuItemSprite:nodeToWorldTransform() end 
function CCMenuItemSprite:getChildren() end 
function CCMenuItemSprite:transformAncestors() end 
function CCMenuItemSprite:getGrid() end 
function CCMenuItemSprite:isRunning() end 
function CCMenuItemSprite:registerScriptHandler() end 
function CCMenuItemSprite:getCamera() end 
function CCMenuItemSprite:isIgnoreAnchorPointForPosition() end 
function CCMenuItemSprite:getUserData() end 
function CCMenuItemSprite:setPositionY() end 
function CCMenuItemSprite:getZOrder() end 
function CCMenuItemSprite:new() end 
function CCMenuItemSprite:delete() end 
function CCMenuItemSprite:updateDisplayedColor() end 
function CCMenuItemSprite:init() end 
function CCMenuItemSprite:setColor() end 
function CCMenuItemSprite:getDisplayedColor() end 
function CCMenuItemSprite:setCascadeColorEnabled() end 
function CCMenuItemSprite:setCascadeOpacityEnabled() end 
function CCMenuItemSprite:setOpacity() end 
function CCMenuItemSprite:getColor() end 
function CCMenuItemSprite:updateDisplayedOpacity() end 
function CCMenuItemSprite:getOpacity() end 
function CCMenuItemSprite:setOpacityModifyRGB() end 
function CCMenuItemSprite:isCascadeOpacityEnabled() end 
function CCMenuItemSprite:isOpacityModifyRGB() end 
function CCMenuItemSprite:getDisplayedOpacity() end 
function CCMenuItemSprite:new_local() end 
function CCMenuItemSprite:isCascadeColorEnabled() end 
function CCMenuItemSprite:setEnabled() end 
function CCMenuItemSprite:unregisterScriptTapHandler() end 
function CCMenuItemSprite:rect() end 
function CCMenuItemSprite:isSelected() end 
function CCMenuItemSprite:activate() end 
function CCMenuItemSprite:unselected() end 
function CCMenuItemSprite:selected() end 
function CCMenuItemSprite:isEnabled() end 
function CCMenuItemSprite:registerScriptTapHandler() end 
function CCMenuItemSprite:setOpacity() end 
function CCMenuItemSprite:getColor() end 
function CCMenuItemSprite:setSelectedImage() end 
function CCMenuItemSprite:getNormalImage() end 
---
-- @return @class CCMenuItemSprite
--
function CCMenuItemSprite:create() end 
function CCMenuItemSprite:getOpacity() end 
function CCMenuItemSprite:isOpacityModifyRGB() end 
function CCMenuItemSprite:setOpacityModifyRGB() end 
function CCMenuItemSprite:setColor() end 
function CCMenuItemSprite:setEnabled() end 
function CCMenuItemSprite:setDisabledImage() end 
function CCMenuItemSprite:selected() end 
function CCMenuItemSprite:getDisabledImage() end 
function CCMenuItemSprite:unselected() end 
function CCMenuItemSprite:getSelectedImage() end 
function CCMenuItemSprite:setNormalImage() end 
