---@classdef CCMenuItemFont
CCMenuItemFont = {}
function CCMenuItemFont:autorelease() end 
function CCMenuItemFont:retain() end 
function CCMenuItemFont:retainCount() end 
function CCMenuItemFont:isEqual() end 
function CCMenuItemFont:copy() end 
function CCMenuItemFont:release() end 
function CCMenuItemFont:isSingleReference() end 
function CCMenuItemFont:visit() end 
function CCMenuItemFont:getUserObject() end 
function CCMenuItemFont:getSkewY() end 
function CCMenuItemFont:convertTouchToNodeSpace() end 
function CCMenuItemFont:getVertexZ() end 
function CCMenuItemFont:setParent() end 
function CCMenuItemFont:boundingBox() end 
function CCMenuItemFont:setVisible() end 
function CCMenuItemFont:stopActionByTag() end 
function CCMenuItemFont:getScaleY() end 
function CCMenuItemFont:setScaleX() end 
function CCMenuItemFont:reorderChild() end 
function CCMenuItemFont:setPositionX() end 
function CCMenuItemFont:removeFromParentAndCleanup() end 
function CCMenuItemFont:setTag() end 
function CCMenuItemFont:getChildrenCount() end 
function CCMenuItemFont:setScale() end 
function CCMenuItemFont:addChild() end 
function CCMenuItemFont:isVisible() end 
function CCMenuItemFont:setActionManager() end 
function CCMenuItemFont:setScheduler() end 
function CCMenuItemFont:getContentSize() end 
function CCMenuItemFont:getAnchorPoint() end 
function CCMenuItemFont:getTag() end 
function CCMenuItemFont:setGrid() end 
function CCMenuItemFont:convertToWorldSpace() end 
function CCMenuItemFont:setSkewX() end 
function CCMenuItemFont:setZOrder() end 
function CCMenuItemFont:worldToNodeTransform() end 
function CCMenuItemFont:getPosition() end 
function CCMenuItemFont:getSkewX() end 
function CCMenuItemFont:getScheduler() end 
function CCMenuItemFont:ignoreAnchorPointForPosition() end 
function CCMenuItemFont:setPosition() end 
function CCMenuItemFont:getParent() end 
function CCMenuItemFont:unscheduleUpdate() end 
function CCMenuItemFont:scheduleUpdateWithPriorityLua() end 
function CCMenuItemFont:removeChildByTag() end 
function CCMenuItemFont:convertToNodeSpaceAR() end 
function CCMenuItemFont:convertTouchToNodeSpaceAR() end 
function CCMenuItemFont:convertToWorldSpaceAR() end 
function CCMenuItemFont:setRotation() end 
function CCMenuItemFont:getComponent() end 
function CCMenuItemFont:convertToNodeSpace() end 
---
-- @return @class CCMenuItemFont
--
function CCMenuItemFont:create() end 
function CCMenuItemFont:getScale() end 
function CCMenuItemFont:getPositionY() end 
function CCMenuItemFont:getChildByTag() end 
function CCMenuItemFont:setContentSize() end 
function CCMenuItemFont:description() end 
function CCMenuItemFont:cleanup() end 
function CCMenuItemFont:getRotation() end 
function CCMenuItemFont:nodeToParentTransform() end 
function CCMenuItemFont:stopAction() end 
function CCMenuItemFont:numberOfRunningActions() end 
function CCMenuItemFont:removeAllChildren() end 
function CCMenuItemFont:runAction() end 
function CCMenuItemFont:setUserObject() end 
function CCMenuItemFont:parentToNodeTransform() end 
function CCMenuItemFont:removeChild() end 
function CCMenuItemFont:getAnchorPointInPoints() end 
function CCMenuItemFont:getScaleX() end 
function CCMenuItemFont:transform() end 
function CCMenuItemFont:getActionManager() end 
function CCMenuItemFont:draw() end 
function CCMenuItemFont:setScaleY() end 
function CCMenuItemFont:unregisterScriptHandler() end 
function CCMenuItemFont:setVertexZ() end 
function CCMenuItemFont:setAnchorPoint() end 
function CCMenuItemFont:getShaderProgram() end 
function CCMenuItemFont:stopAllActions() end 
function CCMenuItemFont:setUserData() end 
function CCMenuItemFont:setShaderProgram() end 
function CCMenuItemFont:getActionByTag() end 
function CCMenuItemFont:getGLServerState() end 
function CCMenuItemFont:getOrderOfArrival() end 
function CCMenuItemFont:getPositionX() end 
function CCMenuItemFont:setGLServerState() end 
function CCMenuItemFont:setSkewY() end 
function CCMenuItemFont:setOrderOfArrival() end 
function CCMenuItemFont:nodeToWorldTransform() end 
function CCMenuItemFont:getChildren() end 
function CCMenuItemFont:transformAncestors() end 
function CCMenuItemFont:getGrid() end 
function CCMenuItemFont:isRunning() end 
function CCMenuItemFont:registerScriptHandler() end 
function CCMenuItemFont:getCamera() end 
function CCMenuItemFont:isIgnoreAnchorPointForPosition() end 
function CCMenuItemFont:getUserData() end 
function CCMenuItemFont:setPositionY() end 
function CCMenuItemFont:getZOrder() end 
function CCMenuItemFont:new() end 
function CCMenuItemFont:delete() end 
function CCMenuItemFont:updateDisplayedColor() end 
function CCMenuItemFont:init() end 
function CCMenuItemFont:setColor() end 
function CCMenuItemFont:getDisplayedColor() end 
function CCMenuItemFont:setCascadeColorEnabled() end 
function CCMenuItemFont:setCascadeOpacityEnabled() end 
function CCMenuItemFont:setOpacity() end 
function CCMenuItemFont:getColor() end 
function CCMenuItemFont:updateDisplayedOpacity() end 
function CCMenuItemFont:getOpacity() end 
function CCMenuItemFont:setOpacityModifyRGB() end 
function CCMenuItemFont:isCascadeOpacityEnabled() end 
function CCMenuItemFont:isOpacityModifyRGB() end 
function CCMenuItemFont:getDisplayedOpacity() end 
function CCMenuItemFont:new_local() end 
function CCMenuItemFont:isCascadeColorEnabled() end 
function CCMenuItemFont:setEnabled() end 
function CCMenuItemFont:unregisterScriptTapHandler() end 
function CCMenuItemFont:rect() end 
function CCMenuItemFont:isSelected() end 
function CCMenuItemFont:activate() end 
function CCMenuItemFont:unselected() end 
function CCMenuItemFont:selected() end 
function CCMenuItemFont:isEnabled() end 
function CCMenuItemFont:registerScriptTapHandler() end 
function CCMenuItemFont:setOpacity() end 
function CCMenuItemFont:getColor() end 
---
-- @return @class CCMenuItemFont
--
function CCMenuItemFont:create() end 
function CCMenuItemFont:isOpacityModifyRGB() end 
function CCMenuItemFont:setOpacityModifyRGB() end 
function CCMenuItemFont:getOpacity() end 
function CCMenuItemFont:setEnabled() end 
function CCMenuItemFont:activate() end 
function CCMenuItemFont:setColor() end 
function CCMenuItemFont:getLabel() end 
function CCMenuItemFont:getDisabledColor() end 
function CCMenuItemFont:selected() end 
function CCMenuItemFont:setString() end 
function CCMenuItemFont:unselected() end 
function CCMenuItemFont:setLabel() end 
function CCMenuItemFont:setDisabledColor() end 
function CCMenuItemFont:setFontName() end 
---
-- @return @class CCMenuItemFont
--
function CCMenuItemFont:create() end 
function CCMenuItemFont:fontSizeObj() end 
function CCMenuItemFont:setFontNameObj() end 
function CCMenuItemFont:fontName() end 
function CCMenuItemFont:setFontSize() end 
function CCMenuItemFont:fontNameObj() end 
function CCMenuItemFont:setFontSizeObj() end 
function CCMenuItemFont:fontSize() end 
