---@classdef CCMenu
CCMenu = {}
function CCMenu:autorelease() end 
function CCMenu:retain() end 
function CCMenu:retainCount() end 
function CCMenu:isEqual() end 
function CCMenu:copy() end 
function CCMenu:release() end 
function CCMenu:isSingleReference() end 
function CCMenu:visit() end 
function CCMenu:getUserObject() end 
function CCMenu:getSkewY() end 
function CCMenu:convertTouchToNodeSpace() end 
function CCMenu:getVertexZ() end 
function CCMenu:setParent() end 
function CCMenu:boundingBox() end 
function CCMenu:setVisible() end 
function CCMenu:stopActionByTag() end 
function CCMenu:getScaleY() end 
function CCMenu:setScaleX() end 
function CCMenu:reorderChild() end 
function CCMenu:setPositionX() end 
function CCMenu:removeFromParentAndCleanup() end 
function CCMenu:setTag() end 
function CCMenu:getChildrenCount() end 
function CCMenu:setScale() end 
function CCMenu:addChild() end 
function CCMenu:isVisible() end 
function CCMenu:setActionManager() end 
function CCMenu:setScheduler() end 
function CCMenu:getContentSize() end 
function CCMenu:getAnchorPoint() end 
function CCMenu:getTag() end 
function CCMenu:setGrid() end 
function CCMenu:convertToWorldSpace() end 
function CCMenu:setSkewX() end 
function CCMenu:setZOrder() end 
function CCMenu:worldToNodeTransform() end 
function CCMenu:getPosition() end 
function CCMenu:getSkewX() end 
function CCMenu:getScheduler() end 
function CCMenu:ignoreAnchorPointForPosition() end 
function CCMenu:setPosition() end 
function CCMenu:getParent() end 
function CCMenu:unscheduleUpdate() end 
function CCMenu:scheduleUpdateWithPriorityLua() end 
function CCMenu:removeChildByTag() end 
function CCMenu:convertToNodeSpaceAR() end 
function CCMenu:convertTouchToNodeSpaceAR() end 
function CCMenu:convertToWorldSpaceAR() end 
function CCMenu:setRotation() end 
function CCMenu:getComponent() end 
function CCMenu:convertToNodeSpace() end 
---
-- @return @class CCMenu
--
function CCMenu:create() end 
function CCMenu:getScale() end 
function CCMenu:getPositionY() end 
function CCMenu:getChildByTag() end 
function CCMenu:setContentSize() end 
function CCMenu:description() end 
function CCMenu:cleanup() end 
function CCMenu:getRotation() end 
function CCMenu:nodeToParentTransform() end 
function CCMenu:stopAction() end 
function CCMenu:numberOfRunningActions() end 
function CCMenu:removeAllChildren() end 
function CCMenu:runAction() end 
function CCMenu:setUserObject() end 
function CCMenu:parentToNodeTransform() end 
function CCMenu:removeChild() end 
function CCMenu:getAnchorPointInPoints() end 
function CCMenu:getScaleX() end 
function CCMenu:transform() end 
function CCMenu:getActionManager() end 
function CCMenu:draw() end 
function CCMenu:setScaleY() end 
function CCMenu:unregisterScriptHandler() end 
function CCMenu:setVertexZ() end 
function CCMenu:setAnchorPoint() end 
function CCMenu:getShaderProgram() end 
function CCMenu:stopAllActions() end 
function CCMenu:setUserData() end 
function CCMenu:setShaderProgram() end 
function CCMenu:getActionByTag() end 
function CCMenu:getGLServerState() end 
function CCMenu:getOrderOfArrival() end 
function CCMenu:getPositionX() end 
function CCMenu:setGLServerState() end 
function CCMenu:setSkewY() end 
function CCMenu:setOrderOfArrival() end 
function CCMenu:nodeToWorldTransform() end 
function CCMenu:getChildren() end 
function CCMenu:transformAncestors() end 
function CCMenu:getGrid() end 
function CCMenu:isRunning() end 
function CCMenu:registerScriptHandler() end 
function CCMenu:getCamera() end 
function CCMenu:isIgnoreAnchorPointForPosition() end 
function CCMenu:getUserData() end 
function CCMenu:setPositionY() end 
function CCMenu:getZOrder() end 
function CCMenu:isTouchEnabled() end 
function CCMenu:unregisterScriptKeypadHandler() end 
function CCMenu:registerScriptAccelerateHandler() end 
---
-- @return @class CCMenu
--
function CCMenu:create() end 
function CCMenu:setAccelerometerEnabled() end 
function CCMenu:registerScriptKeypadHandler() end 
function CCMenu:setTouchMode() end 
function CCMenu:isAccelerometerEnabled() end 
function CCMenu:setTouchEnabled() end 
function CCMenu:setTouchPriority() end 
function CCMenu:unregisterScriptAccelerateHandler() end 
function CCMenu:unregisterScriptTouchHandler() end 
function CCMenu:setKeypadEnabled() end 
function CCMenu:registerScriptTouchHandler() end 
function CCMenu:getTouchPriority() end 
function CCMenu:isKeypadEnabled() end 
function CCMenu:getTouchMode() end 
function CCMenu:new() end 
---
-- @return @class CCMenu
--
function CCMenu:create() end 
function CCMenu:delete() end 
function CCMenu:updateDisplayedColor() end 
function CCMenu:init() end 
function CCMenu:setColor() end 
function CCMenu:getDisplayedColor() end 
function CCMenu:setCascadeColorEnabled() end 
function CCMenu:setCascadeOpacityEnabled() end 
function CCMenu:setOpacity() end 
function CCMenu:getColor() end 
function CCMenu:updateDisplayedOpacity() end 
function CCMenu:getOpacity() end 
function CCMenu:setOpacityModifyRGB() end 
function CCMenu:isOpacityModifyRGB() end 
function CCMenu:isCascadeOpacityEnabled() end 
function CCMenu:getDisplayedOpacity() end 
function CCMenu:new_local() end 
function CCMenu:isCascadeColorEnabled() end 
function CCMenu:alignItemsHorizontally() end 
function CCMenu:createWithArray() end 
function CCMenu:addChild() end 
function CCMenu:getColor() end 
function CCMenu:createWithItem() end 
---
-- @return @class CCMenu
--
function CCMenu:create() end 
function CCMenu:setEnabled() end 
function CCMenu:getOpacity() end 
function CCMenu:isOpacityModifyRGB() end 
function CCMenu:setOpacityModifyRGB() end 
function CCMenu:setColor() end 
function CCMenu:setOpacity() end 
function CCMenu:setHandlerPriority() end 
function CCMenu:alignItemsInRowsWithArray() end 
function CCMenu:alignItemsInColumnsWithArray() end 
function CCMenu:isEnabled() end 
function CCMenu:alignItemsVertically() end 
function CCMenu:alignItemsVerticallyWithPadding() end 
function CCMenu:alignItemsHorizontallyWithPadding() end 
