---@classdef CCMenuItemToggle
CCMenuItemToggle = {}
function CCMenuItemToggle:autorelease() end 
function CCMenuItemToggle:retain() end 
function CCMenuItemToggle:retainCount() end 
function CCMenuItemToggle:isEqual() end 
function CCMenuItemToggle:copy() end 
function CCMenuItemToggle:release() end 
function CCMenuItemToggle:isSingleReference() end 
function CCMenuItemToggle:visit() end 
function CCMenuItemToggle:getUserObject() end 
function CCMenuItemToggle:getSkewY() end 
function CCMenuItemToggle:convertTouchToNodeSpace() end 
function CCMenuItemToggle:getVertexZ() end 
function CCMenuItemToggle:setParent() end 
function CCMenuItemToggle:boundingBox() end 
function CCMenuItemToggle:setVisible() end 
function CCMenuItemToggle:stopActionByTag() end 
function CCMenuItemToggle:getScaleY() end 
function CCMenuItemToggle:setScaleX() end 
function CCMenuItemToggle:reorderChild() end 
function CCMenuItemToggle:setPositionX() end 
function CCMenuItemToggle:removeFromParentAndCleanup() end 
function CCMenuItemToggle:setTag() end 
function CCMenuItemToggle:getChildrenCount() end 
function CCMenuItemToggle:setScale() end 
function CCMenuItemToggle:addChild() end 
function CCMenuItemToggle:isVisible() end 
function CCMenuItemToggle:setActionManager() end 
function CCMenuItemToggle:setScheduler() end 
function CCMenuItemToggle:getContentSize() end 
function CCMenuItemToggle:getAnchorPoint() end 
function CCMenuItemToggle:getTag() end 
function CCMenuItemToggle:setGrid() end 
function CCMenuItemToggle:convertToWorldSpace() end 
function CCMenuItemToggle:setSkewX() end 
function CCMenuItemToggle:setZOrder() end 
function CCMenuItemToggle:worldToNodeTransform() end 
function CCMenuItemToggle:getPosition() end 
function CCMenuItemToggle:getSkewX() end 
function CCMenuItemToggle:getScheduler() end 
function CCMenuItemToggle:ignoreAnchorPointForPosition() end 
function CCMenuItemToggle:setPosition() end 
function CCMenuItemToggle:getParent() end 
function CCMenuItemToggle:unscheduleUpdate() end 
function CCMenuItemToggle:scheduleUpdateWithPriorityLua() end 
function CCMenuItemToggle:removeChildByTag() end 
function CCMenuItemToggle:convertToNodeSpaceAR() end 
function CCMenuItemToggle:convertTouchToNodeSpaceAR() end 
function CCMenuItemToggle:convertToWorldSpaceAR() end 
function CCMenuItemToggle:setRotation() end 
function CCMenuItemToggle:getComponent() end 
function CCMenuItemToggle:convertToNodeSpace() end 
---
-- @return @class CCMenuItemToggle
--
function CCMenuItemToggle:create() end 
function CCMenuItemToggle:getScale() end 
function CCMenuItemToggle:getPositionY() end 
function CCMenuItemToggle:getChildByTag() end 
function CCMenuItemToggle:setContentSize() end 
function CCMenuItemToggle:description() end 
function CCMenuItemToggle:cleanup() end 
function CCMenuItemToggle:getRotation() end 
function CCMenuItemToggle:nodeToParentTransform() end 
function CCMenuItemToggle:stopAction() end 
function CCMenuItemToggle:numberOfRunningActions() end 
function CCMenuItemToggle:removeAllChildren() end 
function CCMenuItemToggle:runAction() end 
function CCMenuItemToggle:setUserObject() end 
function CCMenuItemToggle:parentToNodeTransform() end 
function CCMenuItemToggle:removeChild() end 
function CCMenuItemToggle:getAnchorPointInPoints() end 
function CCMenuItemToggle:getScaleX() end 
function CCMenuItemToggle:transform() end 
function CCMenuItemToggle:getActionManager() end 
function CCMenuItemToggle:draw() end 
function CCMenuItemToggle:setScaleY() end 
function CCMenuItemToggle:unregisterScriptHandler() end 
function CCMenuItemToggle:setVertexZ() end 
function CCMenuItemToggle:setAnchorPoint() end 
function CCMenuItemToggle:getShaderProgram() end 
function CCMenuItemToggle:stopAllActions() end 
function CCMenuItemToggle:setUserData() end 
function CCMenuItemToggle:setShaderProgram() end 
function CCMenuItemToggle:getActionByTag() end 
function CCMenuItemToggle:getGLServerState() end 
function CCMenuItemToggle:getOrderOfArrival() end 
function CCMenuItemToggle:getPositionX() end 
function CCMenuItemToggle:setGLServerState() end 
function CCMenuItemToggle:setSkewY() end 
function CCMenuItemToggle:setOrderOfArrival() end 
function CCMenuItemToggle:nodeToWorldTransform() end 
function CCMenuItemToggle:getChildren() end 
function CCMenuItemToggle:transformAncestors() end 
function CCMenuItemToggle:getGrid() end 
function CCMenuItemToggle:isRunning() end 
function CCMenuItemToggle:registerScriptHandler() end 
function CCMenuItemToggle:getCamera() end 
function CCMenuItemToggle:isIgnoreAnchorPointForPosition() end 
function CCMenuItemToggle:getUserData() end 
function CCMenuItemToggle:setPositionY() end 
function CCMenuItemToggle:getZOrder() end 
function CCMenuItemToggle:new() end 
function CCMenuItemToggle:delete() end 
function CCMenuItemToggle:updateDisplayedColor() end 
function CCMenuItemToggle:init() end 
function CCMenuItemToggle:setColor() end 
function CCMenuItemToggle:getDisplayedColor() end 
function CCMenuItemToggle:setCascadeColorEnabled() end 
function CCMenuItemToggle:setCascadeOpacityEnabled() end 
function CCMenuItemToggle:setOpacity() end 
function CCMenuItemToggle:getColor() end 
function CCMenuItemToggle:updateDisplayedOpacity() end 
function CCMenuItemToggle:getOpacity() end 
function CCMenuItemToggle:setOpacityModifyRGB() end 
function CCMenuItemToggle:isCascadeOpacityEnabled() end 
function CCMenuItemToggle:isOpacityModifyRGB() end 
function CCMenuItemToggle:getDisplayedOpacity() end 
function CCMenuItemToggle:new_local() end 
function CCMenuItemToggle:isCascadeColorEnabled() end 
function CCMenuItemToggle:setEnabled() end 
function CCMenuItemToggle:unregisterScriptTapHandler() end 
function CCMenuItemToggle:rect() end 
function CCMenuItemToggle:isSelected() end 
function CCMenuItemToggle:activate() end 
function CCMenuItemToggle:unselected() end 
function CCMenuItemToggle:selected() end 
function CCMenuItemToggle:isEnabled() end 
function CCMenuItemToggle:registerScriptTapHandler() end 
function CCMenuItemToggle:setOpacity() end 
function CCMenuItemToggle:getColor() end 
---
-- @return @class CCMenuItemToggle
--
function CCMenuItemToggle:create() end 
function CCMenuItemToggle:isOpacityModifyRGB() end 
function CCMenuItemToggle:setOpacityModifyRGB() end 
function CCMenuItemToggle:setEnabled() end 
function CCMenuItemToggle:getOpacity() end 
function CCMenuItemToggle:getSelectedIndex() end 
function CCMenuItemToggle:activate() end 
function CCMenuItemToggle:setColor() end 
function CCMenuItemToggle:unselected() end 
function CCMenuItemToggle:selected() end 
function CCMenuItemToggle:selectedItem() end 
function CCMenuItemToggle:addSubItem() end 
function CCMenuItemToggle:setSubItems() end 
function CCMenuItemToggle:setSelectedIndex() end 
function CCMenuItemToggle:getSubItems() end 
