---@classdef CCMotionStreak
CCMotionStreak = {}
function CCMotionStreak:autorelease() end 
function CCMotionStreak:retain() end 
function CCMotionStreak:retainCount() end 
function CCMotionStreak:isEqual() end 
function CCMotionStreak:copy() end 
function CCMotionStreak:release() end 
function CCMotionStreak:isSingleReference() end 
function CCMotionStreak:visit() end 
function CCMotionStreak:getUserObject() end 
function CCMotionStreak:getSkewY() end 
function CCMotionStreak:convertTouchToNodeSpace() end 
function CCMotionStreak:getVertexZ() end 
function CCMotionStreak:setParent() end 
function CCMotionStreak:boundingBox() end 
function CCMotionStreak:setVisible() end 
function CCMotionStreak:stopActionByTag() end 
function CCMotionStreak:getScaleY() end 
function CCMotionStreak:setScaleX() end 
function CCMotionStreak:reorderChild() end 
function CCMotionStreak:setPositionX() end 
function CCMotionStreak:removeFromParentAndCleanup() end 
function CCMotionStreak:setTag() end 
function CCMotionStreak:getChildrenCount() end 
function CCMotionStreak:setScale() end 
function CCMotionStreak:addChild() end 
function CCMotionStreak:isVisible() end 
function CCMotionStreak:setActionManager() end 
function CCMotionStreak:setScheduler() end 
function CCMotionStreak:getContentSize() end 
function CCMotionStreak:getAnchorPoint() end 
function CCMotionStreak:getTag() end 
function CCMotionStreak:setGrid() end 
function CCMotionStreak:convertToWorldSpace() end 
function CCMotionStreak:setSkewX() end 
function CCMotionStreak:setZOrder() end 
function CCMotionStreak:worldToNodeTransform() end 
function CCMotionStreak:getPosition() end 
function CCMotionStreak:getSkewX() end 
function CCMotionStreak:getScheduler() end 
function CCMotionStreak:ignoreAnchorPointForPosition() end 
function CCMotionStreak:setPosition() end 
function CCMotionStreak:getParent() end 
function CCMotionStreak:unscheduleUpdate() end 
function CCMotionStreak:scheduleUpdateWithPriorityLua() end 
function CCMotionStreak:removeChildByTag() end 
function CCMotionStreak:convertToNodeSpaceAR() end 
function CCMotionStreak:convertTouchToNodeSpaceAR() end 
function CCMotionStreak:convertToWorldSpaceAR() end 
function CCMotionStreak:setRotation() end 
function CCMotionStreak:getComponent() end 
function CCMotionStreak:convertToNodeSpace() end 
---
-- @return @class CCMotionStreak
--
function CCMotionStreak:create() end 
function CCMotionStreak:getScale() end 
function CCMotionStreak:getPositionY() end 
function CCMotionStreak:getChildByTag() end 
function CCMotionStreak:setContentSize() end 
function CCMotionStreak:description() end 
function CCMotionStreak:cleanup() end 
function CCMotionStreak:getRotation() end 
function CCMotionStreak:nodeToParentTransform() end 
function CCMotionStreak:stopAction() end 
function CCMotionStreak:numberOfRunningActions() end 
function CCMotionStreak:removeAllChildren() end 
function CCMotionStreak:runAction() end 
function CCMotionStreak:setUserObject() end 
function CCMotionStreak:parentToNodeTransform() end 
function CCMotionStreak:removeChild() end 
function CCMotionStreak:getAnchorPointInPoints() end 
function CCMotionStreak:getScaleX() end 
function CCMotionStreak:transform() end 
function CCMotionStreak:getActionManager() end 
function CCMotionStreak:draw() end 
function CCMotionStreak:setScaleY() end 
function CCMotionStreak:unregisterScriptHandler() end 
function CCMotionStreak:setVertexZ() end 
function CCMotionStreak:setAnchorPoint() end 
function CCMotionStreak:getShaderProgram() end 
function CCMotionStreak:stopAllActions() end 
function CCMotionStreak:setUserData() end 
function CCMotionStreak:setShaderProgram() end 
function CCMotionStreak:getActionByTag() end 
function CCMotionStreak:getGLServerState() end 
function CCMotionStreak:getOrderOfArrival() end 
function CCMotionStreak:getPositionX() end 
function CCMotionStreak:setGLServerState() end 
function CCMotionStreak:setSkewY() end 
function CCMotionStreak:setOrderOfArrival() end 
function CCMotionStreak:nodeToWorldTransform() end 
function CCMotionStreak:getChildren() end 
function CCMotionStreak:transformAncestors() end 
function CCMotionStreak:getGrid() end 
function CCMotionStreak:isRunning() end 
function CCMotionStreak:registerScriptHandler() end 
function CCMotionStreak:getCamera() end 
function CCMotionStreak:isIgnoreAnchorPointForPosition() end 
function CCMotionStreak:getUserData() end 
function CCMotionStreak:setPositionY() end 
function CCMotionStreak:getZOrder() end 
function CCMotionStreak:new() end 
function CCMotionStreak:delete() end 
function CCMotionStreak:updateDisplayedColor() end 
function CCMotionStreak:init() end 
function CCMotionStreak:setColor() end 
function CCMotionStreak:getDisplayedColor() end 
function CCMotionStreak:setCascadeColorEnabled() end 
function CCMotionStreak:setCascadeOpacityEnabled() end 
function CCMotionStreak:setOpacity() end 
function CCMotionStreak:getColor() end 
function CCMotionStreak:updateDisplayedOpacity() end 
function CCMotionStreak:getOpacity() end 
function CCMotionStreak:setOpacityModifyRGB() end 
function CCMotionStreak:isCascadeOpacityEnabled() end 
function CCMotionStreak:isOpacityModifyRGB() end 
function CCMotionStreak:getDisplayedOpacity() end 
function CCMotionStreak:new_local() end 
function CCMotionStreak:isCascadeColorEnabled() end 
function CCMotionStreak:setOpacity() end 
---
-- @return @class CCMotionStreak
--
function CCMotionStreak:create() end 
function CCMotionStreak:setStartingPositionInitialized() end 
function CCMotionStreak:isOpacityModifyRGB() end 
function CCMotionStreak:getTexture() end 
function CCMotionStreak:setFastMode() end 
function CCMotionStreak:getOpacity() end 
function CCMotionStreak:reset() end 
function CCMotionStreak:setColor() end 
function CCMotionStreak:isStartingPositionInitialized() end 
function CCMotionStreak:setOpacityModifyRGB() end 
function CCMotionStreak:getColor() end 
function CCMotionStreak:getBlendFunc() end 
function CCMotionStreak:setBlendFunc() end 
function CCMotionStreak:tintWithColor() end 
function CCMotionStreak:setTexture() end 
function CCMotionStreak:isFastMode() end 
