---@classdef CCNode
CCNode = {}
function CCNode:autorelease() end 
function CCNode:retain() end 
function CCNode:retainCount() end 
function CCNode:isEqual() end 
function CCNode:copy() end 
function CCNode:release() end 
function CCNode:isSingleReference() end 
function CCNode:visit() end 
function CCNode:getUserObject() end 
function CCNode:getSkewY() end 
function CCNode:convertTouchToNodeSpace() end 
function CCNode:getVertexZ() end 
function CCNode:setParent() end 
function CCNode:boundingBox() end 
function CCNode:setVisible() end 
function CCNode:stopActionByTag() end 
function CCNode:getScaleY() end 
function CCNode:setScaleX() end 
function CCNode:reorderChild() end 
function CCNode:setPositionX() end 
function CCNode:removeFromParentAndCleanup() end 
function CCNode:setTag() end 
function CCNode:getChildrenCount() end 
function CCNode:setScale() end 
function CCNode:addChild() end 
function CCNode:isVisible() end 
function CCNode:setActionManager() end 
function CCNode:setScheduler() end 
function CCNode:getContentSize() end 
function CCNode:getAnchorPoint() end 
function CCNode:getTag() end 
function CCNode:setGrid() end 
function CCNode:convertToWorldSpace() end 
function CCNode:setSkewX() end 
function CCNode:setZOrder() end 
function CCNode:worldToNodeTransform() end 
function CCNode:getPosition() end 
function CCNode:getSkewX() end 
function CCNode:getScheduler() end 
function CCNode:ignoreAnchorPointForPosition() end 
function CCNode:setPosition() end 
function CCNode:getParent() end 
function CCNode:unscheduleUpdate() end 
function CCNode:scheduleUpdateWithPriorityLua() end 
function CCNode:removeChildByTag() end 
function CCNode:convertToNodeSpaceAR() end 
function CCNode:convertTouchToNodeSpaceAR() end 
function CCNode:convertToWorldSpaceAR() end 
function CCNode:setRotation() end 
function CCNode:getComponent() end 
function CCNode:convertToNodeSpace() end 
---
-- @return @class CCNode
--
function CCNode:create() end 
function CCNode:getScale() end 
function CCNode:getPositionY() end 
function CCNode:getChildByTag() end 
function CCNode:setContentSize() end 
function CCNode:description() end 
function CCNode:cleanup() end 
function CCNode:getRotation() end 
function CCNode:nodeToParentTransform() end 
function CCNode:stopAction() end 
function CCNode:numberOfRunningActions() end 
function CCNode:removeAllChildren() end 
function CCNode:runAction() end 
function CCNode:setUserObject() end 
function CCNode:parentToNodeTransform() end 
function CCNode:removeChild() end 
function CCNode:getAnchorPointInPoints() end 
function CCNode:getScaleX() end 
function CCNode:transform() end 
function CCNode:getActionManager() end 
function CCNode:draw() end 
function CCNode:setScaleY() end 
function CCNode:unregisterScriptHandler() end 
function CCNode:setVertexZ() end 
function CCNode:setAnchorPoint() end 
function CCNode:getShaderProgram() end 
function CCNode:stopAllActions() end 
function CCNode:setUserData() end 
function CCNode:setShaderProgram() end 
function CCNode:getActionByTag() end 
function CCNode:getGLServerState() end 
function CCNode:getOrderOfArrival() end 
function CCNode:getPositionX() end 
function CCNode:setGLServerState() end 
function CCNode:setSkewY() end 
function CCNode:setOrderOfArrival() end 
function CCNode:nodeToWorldTransform() end 
function CCNode:getChildren() end 
function CCNode:transformAncestors() end 
function CCNode:getGrid() end 
function CCNode:isRunning() end 
function CCNode:registerScriptHandler() end 
function CCNode:getCamera() end 
function CCNode:isIgnoreAnchorPointForPosition() end 
function CCNode:getUserData() end 
function CCNode:setPositionY() end 
function CCNode:getZOrder() end 
