---@classdef CCNodeRGBA
CCNodeRGBA = {}
function CCNodeRGBA:autorelease() end 
function CCNodeRGBA:retain() end 
function CCNodeRGBA:retainCount() end 
function CCNodeRGBA:isEqual() end 
function CCNodeRGBA:copy() end 
function CCNodeRGBA:release() end 
function CCNodeRGBA:isSingleReference() end 
function CCNodeRGBA:visit() end 
function CCNodeRGBA:getUserObject() end 
function CCNodeRGBA:getSkewY() end 
function CCNodeRGBA:convertTouchToNodeSpace() end 
function CCNodeRGBA:getVertexZ() end 
function CCNodeRGBA:setParent() end 
function CCNodeRGBA:boundingBox() end 
function CCNodeRGBA:setVisible() end 
function CCNodeRGBA:stopActionByTag() end 
function CCNodeRGBA:getScaleY() end 
function CCNodeRGBA:setScaleX() end 
function CCNodeRGBA:reorderChild() end 
function CCNodeRGBA:setPositionX() end 
function CCNodeRGBA:removeFromParentAndCleanup() end 
function CCNodeRGBA:setTag() end 
function CCNodeRGBA:getChildrenCount() end 
function CCNodeRGBA:setScale() end 
function CCNodeRGBA:addChild() end 
function CCNodeRGBA:isVisible() end 
function CCNodeRGBA:setActionManager() end 
function CCNodeRGBA:setScheduler() end 
function CCNodeRGBA:getContentSize() end 
function CCNodeRGBA:getAnchorPoint() end 
function CCNodeRGBA:getTag() end 
function CCNodeRGBA:setGrid() end 
function CCNodeRGBA:convertToWorldSpace() end 
function CCNodeRGBA:setSkewX() end 
function CCNodeRGBA:setZOrder() end 
function CCNodeRGBA:worldToNodeTransform() end 
function CCNodeRGBA:getPosition() end 
function CCNodeRGBA:getSkewX() end 
function CCNodeRGBA:getScheduler() end 
function CCNodeRGBA:ignoreAnchorPointForPosition() end 
function CCNodeRGBA:setPosition() end 
function CCNodeRGBA:getParent() end 
function CCNodeRGBA:unscheduleUpdate() end 
function CCNodeRGBA:scheduleUpdateWithPriorityLua() end 
function CCNodeRGBA:removeChildByTag() end 
function CCNodeRGBA:convertToNodeSpaceAR() end 
function CCNodeRGBA:convertTouchToNodeSpaceAR() end 
function CCNodeRGBA:convertToWorldSpaceAR() end 
function CCNodeRGBA:setRotation() end 
function CCNodeRGBA:getComponent() end 
function CCNodeRGBA:convertToNodeSpace() end 
---
-- @return @class CCNodeRGBA
--
function CCNodeRGBA:create() end 
function CCNodeRGBA:getScale() end 
function CCNodeRGBA:getPositionY() end 
function CCNodeRGBA:getChildByTag() end 
function CCNodeRGBA:setContentSize() end 
function CCNodeRGBA:description() end 
function CCNodeRGBA:cleanup() end 
function CCNodeRGBA:getRotation() end 
function CCNodeRGBA:nodeToParentTransform() end 
function CCNodeRGBA:stopAction() end 
function CCNodeRGBA:numberOfRunningActions() end 
function CCNodeRGBA:removeAllChildren() end 
function CCNodeRGBA:runAction() end 
function CCNodeRGBA:setUserObject() end 
function CCNodeRGBA:parentToNodeTransform() end 
function CCNodeRGBA:removeChild() end 
function CCNodeRGBA:getAnchorPointInPoints() end 
function CCNodeRGBA:getScaleX() end 
function CCNodeRGBA:transform() end 
function CCNodeRGBA:getActionManager() end 
function CCNodeRGBA:draw() end 
function CCNodeRGBA:setScaleY() end 
function CCNodeRGBA:unregisterScriptHandler() end 
function CCNodeRGBA:setVertexZ() end 
function CCNodeRGBA:setAnchorPoint() end 
function CCNodeRGBA:getShaderProgram() end 
function CCNodeRGBA:stopAllActions() end 
function CCNodeRGBA:setUserData() end 
function CCNodeRGBA:setShaderProgram() end 
function CCNodeRGBA:getActionByTag() end 
function CCNodeRGBA:getGLServerState() end 
function CCNodeRGBA:getOrderOfArrival() end 
function CCNodeRGBA:getPositionX() end 
function CCNodeRGBA:setGLServerState() end 
function CCNodeRGBA:setSkewY() end 
function CCNodeRGBA:setOrderOfArrival() end 
function CCNodeRGBA:nodeToWorldTransform() end 
function CCNodeRGBA:getChildren() end 
function CCNodeRGBA:transformAncestors() end 
function CCNodeRGBA:getGrid() end 
function CCNodeRGBA:isRunning() end 
function CCNodeRGBA:registerScriptHandler() end 
function CCNodeRGBA:getCamera() end 
function CCNodeRGBA:isIgnoreAnchorPointForPosition() end 
function CCNodeRGBA:getUserData() end 
function CCNodeRGBA:setPositionY() end 
function CCNodeRGBA:getZOrder() end 
function CCNodeRGBA:new() end 
function CCNodeRGBA:delete() end 
function CCNodeRGBA:updateDisplayedColor() end 
function CCNodeRGBA:init() end 
function CCNodeRGBA:setColor() end 
function CCNodeRGBA:getDisplayedColor() end 
function CCNodeRGBA:setCascadeColorEnabled() end 
function CCNodeRGBA:setCascadeOpacityEnabled() end 
function CCNodeRGBA:setOpacity() end 
function CCNodeRGBA:getColor() end 
function CCNodeRGBA:updateDisplayedOpacity() end 
function CCNodeRGBA:getOpacity() end 
function CCNodeRGBA:setOpacityModifyRGB() end 
function CCNodeRGBA:isCascadeOpacityEnabled() end 
function CCNodeRGBA:isOpacityModifyRGB() end 
function CCNodeRGBA:getDisplayedOpacity() end 
function CCNodeRGBA:new_local() end 
function CCNodeRGBA:isCascadeColorEnabled() end 
