---@classdef CCParticleMeteor
CCParticleMeteor = {}
function CCParticleMeteor:autorelease() end 
function CCParticleMeteor:retain() end 
function CCParticleMeteor:retainCount() end 
function CCParticleMeteor:isEqual() end 
function CCParticleMeteor:copy() end 
function CCParticleMeteor:release() end 
function CCParticleMeteor:isSingleReference() end 
function CCParticleMeteor:visit() end 
function CCParticleMeteor:getUserObject() end 
function CCParticleMeteor:getSkewY() end 
function CCParticleMeteor:convertTouchToNodeSpace() end 
function CCParticleMeteor:getVertexZ() end 
function CCParticleMeteor:setParent() end 
function CCParticleMeteor:boundingBox() end 
function CCParticleMeteor:setVisible() end 
function CCParticleMeteor:stopActionByTag() end 
function CCParticleMeteor:getScaleY() end 
function CCParticleMeteor:setScaleX() end 
function CCParticleMeteor:reorderChild() end 
function CCParticleMeteor:setPositionX() end 
function CCParticleMeteor:removeFromParentAndCleanup() end 
function CCParticleMeteor:setTag() end 
function CCParticleMeteor:getChildrenCount() end 
function CCParticleMeteor:setScale() end 
function CCParticleMeteor:addChild() end 
function CCParticleMeteor:isVisible() end 
function CCParticleMeteor:setActionManager() end 
function CCParticleMeteor:setScheduler() end 
function CCParticleMeteor:getContentSize() end 
function CCParticleMeteor:getAnchorPoint() end 
function CCParticleMeteor:getTag() end 
function CCParticleMeteor:setGrid() end 
function CCParticleMeteor:convertToWorldSpace() end 
function CCParticleMeteor:setSkewX() end 
function CCParticleMeteor:setZOrder() end 
function CCParticleMeteor:worldToNodeTransform() end 
function CCParticleMeteor:getPosition() end 
function CCParticleMeteor:getSkewX() end 
function CCParticleMeteor:getScheduler() end 
function CCParticleMeteor:ignoreAnchorPointForPosition() end 
function CCParticleMeteor:setPosition() end 
function CCParticleMeteor:getParent() end 
function CCParticleMeteor:unscheduleUpdate() end 
function CCParticleMeteor:scheduleUpdateWithPriorityLua() end 
function CCParticleMeteor:removeChildByTag() end 
function CCParticleMeteor:convertToNodeSpaceAR() end 
function CCParticleMeteor:convertTouchToNodeSpaceAR() end 
function CCParticleMeteor:convertToWorldSpaceAR() end 
function CCParticleMeteor:setRotation() end 
function CCParticleMeteor:getComponent() end 
function CCParticleMeteor:convertToNodeSpace() end 
---
-- @return @class CCParticleMeteor
--
function CCParticleMeteor:create() end 
function CCParticleMeteor:getScale() end 
function CCParticleMeteor:getPositionY() end 
function CCParticleMeteor:getChildByTag() end 
function CCParticleMeteor:setContentSize() end 
function CCParticleMeteor:description() end 
function CCParticleMeteor:cleanup() end 
function CCParticleMeteor:getRotation() end 
function CCParticleMeteor:nodeToParentTransform() end 
function CCParticleMeteor:stopAction() end 
function CCParticleMeteor:numberOfRunningActions() end 
function CCParticleMeteor:removeAllChildren() end 
function CCParticleMeteor:runAction() end 
function CCParticleMeteor:setUserObject() end 
function CCParticleMeteor:parentToNodeTransform() end 
function CCParticleMeteor:removeChild() end 
function CCParticleMeteor:getAnchorPointInPoints() end 
function CCParticleMeteor:getScaleX() end 
function CCParticleMeteor:transform() end 
function CCParticleMeteor:getActionManager() end 
function CCParticleMeteor:draw() end 
function CCParticleMeteor:setScaleY() end 
function CCParticleMeteor:unregisterScriptHandler() end 
function CCParticleMeteor:setVertexZ() end 
function CCParticleMeteor:setAnchorPoint() end 
function CCParticleMeteor:getShaderProgram() end 
function CCParticleMeteor:stopAllActions() end 
function CCParticleMeteor:setUserData() end 
function CCParticleMeteor:setShaderProgram() end 
function CCParticleMeteor:getActionByTag() end 
function CCParticleMeteor:getGLServerState() end 
function CCParticleMeteor:getOrderOfArrival() end 
function CCParticleMeteor:getPositionX() end 
function CCParticleMeteor:setGLServerState() end 
function CCParticleMeteor:setSkewY() end 
function CCParticleMeteor:setOrderOfArrival() end 
function CCParticleMeteor:nodeToWorldTransform() end 
function CCParticleMeteor:getChildren() end 
function CCParticleMeteor:transformAncestors() end 
function CCParticleMeteor:getGrid() end 
function CCParticleMeteor:isRunning() end 
function CCParticleMeteor:registerScriptHandler() end 
function CCParticleMeteor:getCamera() end 
function CCParticleMeteor:isIgnoreAnchorPointForPosition() end 
function CCParticleMeteor:getUserData() end 
function CCParticleMeteor:setPositionY() end 
function CCParticleMeteor:getZOrder() end 
function CCParticleMeteor:setRadialAccelVar() end 
function CCParticleMeteor:getRotatePerSecond() end 
function CCParticleMeteor:getBlendFunc() end 
function CCParticleMeteor:getEndColorVar() end 
function CCParticleMeteor:setPosVar() end 
function CCParticleMeteor:getEmitterMode() end 
function CCParticleMeteor:setRotatePerSecondVar() end 
function CCParticleMeteor:getStartColorVar() end 
function CCParticleMeteor:getEndSizeVar() end 
function CCParticleMeteor:getEndRadiusVar() end 
function CCParticleMeteor:setTangentialAccel() end 
function CCParticleMeteor:getStartRadiusVar() end 
function CCParticleMeteor:getSourcePosition() end 
function CCParticleMeteor:isFull() end 
function CCParticleMeteor:setEmitterMode() end 
function CCParticleMeteor:setEmissionRate() end 
function CCParticleMeteor:getTexture() end 
function CCParticleMeteor:setTexture() end 
function CCParticleMeteor:setScaleX() end 
function CCParticleMeteor:getRadialAccelVar() end 
function CCParticleMeteor:isAutoRemoveOnFinish() end 
function CCParticleMeteor:getEndColor() end 
function CCParticleMeteor:setPositionType() end 
function CCParticleMeteor:getRotatePerSecondVar() end 
function CCParticleMeteor:setStartColorVar() end 
function CCParticleMeteor:setBlendAdditive() end 
function CCParticleMeteor:getTangentialAccel() end 
function CCParticleMeteor:setStartRadiusVar() end 
function CCParticleMeteor:setLife() end 
function CCParticleMeteor:getParticleCount() end 
function CCParticleMeteor:setSourcePosition() end 
function CCParticleMeteor:setScale() end 
function CCParticleMeteor:setBatchNode() end 
function CCParticleMeteor:setEndColor() end 
function CCParticleMeteor:isBlendAdditive() end 
function CCParticleMeteor:isActive() end 
function CCParticleMeteor:setGravity() end 
function CCParticleMeteor:stopSystem() end 
function CCParticleMeteor:getTangentialAccelVar() end 
function CCParticleMeteor:initWithTotalParticles() end 
function CCParticleMeteor:setBlendFunc() end 
function CCParticleMeteor:setSpeed() end 
function CCParticleMeteor:getStartRadius() end 
function CCParticleMeteor:getBatchNode() end 
function CCParticleMeteor:setLifeVar() end 
function CCParticleMeteor:setRotation() end 
function CCParticleMeteor:setStartRadius() end 
function CCParticleMeteor:setEndRadiusVar() end 
---
-- @return @class CCParticleMeteor
--
function CCParticleMeteor:create() end 
function CCParticleMeteor:setAutoRemoveOnFinish() end 
function CCParticleMeteor:setStartSpin() end 
function CCParticleMeteor:setEndSpin() end 
function CCParticleMeteor:getStartSizeVar() end 
function CCParticleMeteor:initWithFile() end 
function CCParticleMeteor:setStartColor() end 
function CCParticleMeteor:setStartSizeVar() end 
function CCParticleMeteor:setTangentialAccelVar() end 
function CCParticleMeteor:getLife() end 
function CCParticleMeteor:getTotalParticles() end 
function CCParticleMeteor:getSpeed() end 
function CCParticleMeteor:getEmissionRate() end 
function CCParticleMeteor:getEndSpinVar() end 
function CCParticleMeteor:setEndSpinVar() end 
function CCParticleMeteor:getEndSpin() end 
function CCParticleMeteor:getAngle() end 
function CCParticleMeteor:updateQuadWithParticle() end 
function CCParticleMeteor:setSpeedVar() end 
function CCParticleMeteor:getStartSpinVar() end 
function CCParticleMeteor:setStartSpinVar() end 
function CCParticleMeteor:getStartSpin() end 
function CCParticleMeteor:setEndSize() end 
function CCParticleMeteor:getRadialAccel() end 
function CCParticleMeteor:getPosVar() end 
function CCParticleMeteor:getEndSize() end 
function CCParticleMeteor:getLifeVar() end 
function CCParticleMeteor:getPositionType() end 
function CCParticleMeteor:getStartColor() end 
function CCParticleMeteor:getEndRadius() end 
function CCParticleMeteor:addParticle() end 
function CCParticleMeteor:postStep() end 
function CCParticleMeteor:setEndSizeVar() end 
function CCParticleMeteor:getDuration() end 
function CCParticleMeteor:getSpeedVar() end 
function CCParticleMeteor:initParticle() end 
function CCParticleMeteor:getAngleVar() end 
function CCParticleMeteor:getStartSize() end 
function CCParticleMeteor:setRotatePerSecond() end 
function CCParticleMeteor:setEndRadius() end 
function CCParticleMeteor:setAngleVar() end 
function CCParticleMeteor:getGravity() end 
function CCParticleMeteor:setEndColorVar() end 
function CCParticleMeteor:setAngle() end 
function CCParticleMeteor:resetSystem() end 
function CCParticleMeteor:setDuration() end 
function CCParticleMeteor:setRadialAccel() end 
function CCParticleMeteor:setStartSize() end 
function CCParticleMeteor:setScaleY() end 
function CCParticleMeteor:new() end 
function CCParticleMeteor:postStep() end 
---
-- @return @class CCParticleMeteor
--
function CCParticleMeteor:create() end 
function CCParticleMeteor:setTextureWithRect() end 
function CCParticleMeteor:setTotalParticles() end 
function CCParticleMeteor:new_local() end 
function CCParticleMeteor:setBatchNode() end 
function CCParticleMeteor:updateQuadWithParticle() end 
function CCParticleMeteor:setTexture() end 
function CCParticleMeteor:setDisplayFrame() end 
---
-- @return @class CCParticleMeteor
--
function CCParticleMeteor:create() end 
