---@classdef CCParticleSpiral
CCParticleSpiral = {}
function CCParticleSpiral:autorelease() end 
function CCParticleSpiral:retain() end 
function CCParticleSpiral:retainCount() end 
function CCParticleSpiral:isEqual() end 
function CCParticleSpiral:copy() end 
function CCParticleSpiral:release() end 
function CCParticleSpiral:isSingleReference() end 
function CCParticleSpiral:visit() end 
function CCParticleSpiral:getUserObject() end 
function CCParticleSpiral:getSkewY() end 
function CCParticleSpiral:convertTouchToNodeSpace() end 
function CCParticleSpiral:getVertexZ() end 
function CCParticleSpiral:setParent() end 
function CCParticleSpiral:boundingBox() end 
function CCParticleSpiral:setVisible() end 
function CCParticleSpiral:stopActionByTag() end 
function CCParticleSpiral:getScaleY() end 
function CCParticleSpiral:setScaleX() end 
function CCParticleSpiral:reorderChild() end 
function CCParticleSpiral:setPositionX() end 
function CCParticleSpiral:removeFromParentAndCleanup() end 
function CCParticleSpiral:setTag() end 
function CCParticleSpiral:getChildrenCount() end 
function CCParticleSpiral:setScale() end 
function CCParticleSpiral:addChild() end 
function CCParticleSpiral:isVisible() end 
function CCParticleSpiral:setActionManager() end 
function CCParticleSpiral:setScheduler() end 
function CCParticleSpiral:getContentSize() end 
function CCParticleSpiral:getAnchorPoint() end 
function CCParticleSpiral:getTag() end 
function CCParticleSpiral:setGrid() end 
function CCParticleSpiral:convertToWorldSpace() end 
function CCParticleSpiral:setSkewX() end 
function CCParticleSpiral:setZOrder() end 
function CCParticleSpiral:worldToNodeTransform() end 
function CCParticleSpiral:getPosition() end 
function CCParticleSpiral:getSkewX() end 
function CCParticleSpiral:getScheduler() end 
function CCParticleSpiral:ignoreAnchorPointForPosition() end 
function CCParticleSpiral:setPosition() end 
function CCParticleSpiral:getParent() end 
function CCParticleSpiral:unscheduleUpdate() end 
function CCParticleSpiral:scheduleUpdateWithPriorityLua() end 
function CCParticleSpiral:removeChildByTag() end 
function CCParticleSpiral:convertToNodeSpaceAR() end 
function CCParticleSpiral:convertTouchToNodeSpaceAR() end 
function CCParticleSpiral:convertToWorldSpaceAR() end 
function CCParticleSpiral:setRotation() end 
function CCParticleSpiral:getComponent() end 
function CCParticleSpiral:convertToNodeSpace() end 
---
-- @return @class CCParticleSpiral
--
function CCParticleSpiral:create() end 
function CCParticleSpiral:getScale() end 
function CCParticleSpiral:getPositionY() end 
function CCParticleSpiral:getChildByTag() end 
function CCParticleSpiral:setContentSize() end 
function CCParticleSpiral:description() end 
function CCParticleSpiral:cleanup() end 
function CCParticleSpiral:getRotation() end 
function CCParticleSpiral:nodeToParentTransform() end 
function CCParticleSpiral:stopAction() end 
function CCParticleSpiral:numberOfRunningActions() end 
function CCParticleSpiral:removeAllChildren() end 
function CCParticleSpiral:runAction() end 
function CCParticleSpiral:setUserObject() end 
function CCParticleSpiral:parentToNodeTransform() end 
function CCParticleSpiral:removeChild() end 
function CCParticleSpiral:getAnchorPointInPoints() end 
function CCParticleSpiral:getScaleX() end 
function CCParticleSpiral:transform() end 
function CCParticleSpiral:getActionManager() end 
function CCParticleSpiral:draw() end 
function CCParticleSpiral:setScaleY() end 
function CCParticleSpiral:unregisterScriptHandler() end 
function CCParticleSpiral:setVertexZ() end 
function CCParticleSpiral:setAnchorPoint() end 
function CCParticleSpiral:getShaderProgram() end 
function CCParticleSpiral:stopAllActions() end 
function CCParticleSpiral:setUserData() end 
function CCParticleSpiral:setShaderProgram() end 
function CCParticleSpiral:getActionByTag() end 
function CCParticleSpiral:getGLServerState() end 
function CCParticleSpiral:getOrderOfArrival() end 
function CCParticleSpiral:getPositionX() end 
function CCParticleSpiral:setGLServerState() end 
function CCParticleSpiral:setSkewY() end 
function CCParticleSpiral:setOrderOfArrival() end 
function CCParticleSpiral:nodeToWorldTransform() end 
function CCParticleSpiral:getChildren() end 
function CCParticleSpiral:transformAncestors() end 
function CCParticleSpiral:getGrid() end 
function CCParticleSpiral:isRunning() end 
function CCParticleSpiral:registerScriptHandler() end 
function CCParticleSpiral:getCamera() end 
function CCParticleSpiral:isIgnoreAnchorPointForPosition() end 
function CCParticleSpiral:getUserData() end 
function CCParticleSpiral:setPositionY() end 
function CCParticleSpiral:getZOrder() end 
function CCParticleSpiral:setRadialAccelVar() end 
function CCParticleSpiral:getRotatePerSecond() end 
function CCParticleSpiral:getBlendFunc() end 
function CCParticleSpiral:getEndColorVar() end 
function CCParticleSpiral:setPosVar() end 
function CCParticleSpiral:getEmitterMode() end 
function CCParticleSpiral:setRotatePerSecondVar() end 
function CCParticleSpiral:getStartColorVar() end 
function CCParticleSpiral:getEndSizeVar() end 
function CCParticleSpiral:getEndRadiusVar() end 
function CCParticleSpiral:setTangentialAccel() end 
function CCParticleSpiral:getStartRadiusVar() end 
function CCParticleSpiral:getSourcePosition() end 
function CCParticleSpiral:isFull() end 
function CCParticleSpiral:setEmitterMode() end 
function CCParticleSpiral:setEmissionRate() end 
function CCParticleSpiral:getTexture() end 
function CCParticleSpiral:setTexture() end 
function CCParticleSpiral:setScaleX() end 
function CCParticleSpiral:getRadialAccelVar() end 
function CCParticleSpiral:isAutoRemoveOnFinish() end 
function CCParticleSpiral:getEndColor() end 
function CCParticleSpiral:setPositionType() end 
function CCParticleSpiral:getRotatePerSecondVar() end 
function CCParticleSpiral:setStartColorVar() end 
function CCParticleSpiral:setBlendAdditive() end 
function CCParticleSpiral:getTangentialAccel() end 
function CCParticleSpiral:setStartRadiusVar() end 
function CCParticleSpiral:setLife() end 
function CCParticleSpiral:getParticleCount() end 
function CCParticleSpiral:setSourcePosition() end 
function CCParticleSpiral:setScale() end 
function CCParticleSpiral:setBatchNode() end 
function CCParticleSpiral:setEndColor() end 
function CCParticleSpiral:isBlendAdditive() end 
function CCParticleSpiral:isActive() end 
function CCParticleSpiral:setGravity() end 
function CCParticleSpiral:stopSystem() end 
function CCParticleSpiral:getTangentialAccelVar() end 
function CCParticleSpiral:initWithTotalParticles() end 
function CCParticleSpiral:setBlendFunc() end 
function CCParticleSpiral:setSpeed() end 
function CCParticleSpiral:getStartRadius() end 
function CCParticleSpiral:getBatchNode() end 
function CCParticleSpiral:setLifeVar() end 
function CCParticleSpiral:setRotation() end 
function CCParticleSpiral:setStartRadius() end 
function CCParticleSpiral:setEndRadiusVar() end 
---
-- @return @class CCParticleSpiral
--
function CCParticleSpiral:create() end 
function CCParticleSpiral:setAutoRemoveOnFinish() end 
function CCParticleSpiral:setStartSpin() end 
function CCParticleSpiral:setEndSpin() end 
function CCParticleSpiral:getStartSizeVar() end 
function CCParticleSpiral:initWithFile() end 
function CCParticleSpiral:setStartColor() end 
function CCParticleSpiral:setStartSizeVar() end 
function CCParticleSpiral:setTangentialAccelVar() end 
function CCParticleSpiral:getLife() end 
function CCParticleSpiral:getTotalParticles() end 
function CCParticleSpiral:getSpeed() end 
function CCParticleSpiral:getEmissionRate() end 
function CCParticleSpiral:getEndSpinVar() end 
function CCParticleSpiral:setEndSpinVar() end 
function CCParticleSpiral:getEndSpin() end 
function CCParticleSpiral:getAngle() end 
function CCParticleSpiral:updateQuadWithParticle() end 
function CCParticleSpiral:setSpeedVar() end 
function CCParticleSpiral:getStartSpinVar() end 
function CCParticleSpiral:setStartSpinVar() end 
function CCParticleSpiral:getStartSpin() end 
function CCParticleSpiral:setEndSize() end 
function CCParticleSpiral:getRadialAccel() end 
function CCParticleSpiral:getPosVar() end 
function CCParticleSpiral:getEndSize() end 
function CCParticleSpiral:getLifeVar() end 
function CCParticleSpiral:getPositionType() end 
function CCParticleSpiral:getStartColor() end 
function CCParticleSpiral:getEndRadius() end 
function CCParticleSpiral:addParticle() end 
function CCParticleSpiral:postStep() end 
function CCParticleSpiral:setEndSizeVar() end 
function CCParticleSpiral:getDuration() end 
function CCParticleSpiral:getSpeedVar() end 
function CCParticleSpiral:initParticle() end 
function CCParticleSpiral:getAngleVar() end 
function CCParticleSpiral:getStartSize() end 
function CCParticleSpiral:setRotatePerSecond() end 
function CCParticleSpiral:setEndRadius() end 
function CCParticleSpiral:setAngleVar() end 
function CCParticleSpiral:getGravity() end 
function CCParticleSpiral:setEndColorVar() end 
function CCParticleSpiral:setAngle() end 
function CCParticleSpiral:resetSystem() end 
function CCParticleSpiral:setDuration() end 
function CCParticleSpiral:setRadialAccel() end 
function CCParticleSpiral:setStartSize() end 
function CCParticleSpiral:setScaleY() end 
function CCParticleSpiral:new() end 
function CCParticleSpiral:postStep() end 
---
-- @return @class CCParticleSpiral
--
function CCParticleSpiral:create() end 
function CCParticleSpiral:setTextureWithRect() end 
function CCParticleSpiral:setTotalParticles() end 
function CCParticleSpiral:new_local() end 
function CCParticleSpiral:setBatchNode() end 
function CCParticleSpiral:updateQuadWithParticle() end 
function CCParticleSpiral:setTexture() end 
function CCParticleSpiral:setDisplayFrame() end 
---
-- @return @class CCParticleSpiral
--
function CCParticleSpiral:create() end 
