---@classdef CCParticleSystemQuad
CCParticleSystemQuad = {}
function CCParticleSystemQuad:autorelease() end 
function CCParticleSystemQuad:retain() end 
function CCParticleSystemQuad:retainCount() end 
function CCParticleSystemQuad:isEqual() end 
function CCParticleSystemQuad:copy() end 
function CCParticleSystemQuad:release() end 
function CCParticleSystemQuad:isSingleReference() end 
function CCParticleSystemQuad:visit() end 
function CCParticleSystemQuad:getUserObject() end 
function CCParticleSystemQuad:getSkewY() end 
function CCParticleSystemQuad:convertTouchToNodeSpace() end 
function CCParticleSystemQuad:getVertexZ() end 
function CCParticleSystemQuad:setParent() end 
function CCParticleSystemQuad:boundingBox() end 
function CCParticleSystemQuad:setVisible() end 
function CCParticleSystemQuad:stopActionByTag() end 
function CCParticleSystemQuad:getScaleY() end 
function CCParticleSystemQuad:setScaleX() end 
function CCParticleSystemQuad:reorderChild() end 
function CCParticleSystemQuad:setPositionX() end 
function CCParticleSystemQuad:removeFromParentAndCleanup() end 
function CCParticleSystemQuad:setTag() end 
function CCParticleSystemQuad:getChildrenCount() end 
function CCParticleSystemQuad:setScale() end 
function CCParticleSystemQuad:addChild() end 
function CCParticleSystemQuad:isVisible() end 
function CCParticleSystemQuad:setActionManager() end 
function CCParticleSystemQuad:setScheduler() end 
function CCParticleSystemQuad:getContentSize() end 
function CCParticleSystemQuad:getAnchorPoint() end 
function CCParticleSystemQuad:getTag() end 
function CCParticleSystemQuad:setGrid() end 
function CCParticleSystemQuad:convertToWorldSpace() end 
function CCParticleSystemQuad:setSkewX() end 
function CCParticleSystemQuad:setZOrder() end 
function CCParticleSystemQuad:worldToNodeTransform() end 
function CCParticleSystemQuad:getPosition() end 
function CCParticleSystemQuad:getSkewX() end 
function CCParticleSystemQuad:getScheduler() end 
function CCParticleSystemQuad:ignoreAnchorPointForPosition() end 
function CCParticleSystemQuad:setPosition() end 
function CCParticleSystemQuad:getParent() end 
function CCParticleSystemQuad:unscheduleUpdate() end 
function CCParticleSystemQuad:scheduleUpdateWithPriorityLua() end 
function CCParticleSystemQuad:removeChildByTag() end 
function CCParticleSystemQuad:convertToNodeSpaceAR() end 
function CCParticleSystemQuad:convertTouchToNodeSpaceAR() end 
function CCParticleSystemQuad:convertToWorldSpaceAR() end 
function CCParticleSystemQuad:setRotation() end 
function CCParticleSystemQuad:getComponent() end 
function CCParticleSystemQuad:convertToNodeSpace() end 
---
-- @return @class CCParticleSystemQuad
--
function CCParticleSystemQuad:create() end 
function CCParticleSystemQuad:getScale() end 
function CCParticleSystemQuad:getPositionY() end 
function CCParticleSystemQuad:getChildByTag() end 
function CCParticleSystemQuad:setContentSize() end 
function CCParticleSystemQuad:description() end 
function CCParticleSystemQuad:cleanup() end 
function CCParticleSystemQuad:getRotation() end 
function CCParticleSystemQuad:nodeToParentTransform() end 
function CCParticleSystemQuad:stopAction() end 
function CCParticleSystemQuad:numberOfRunningActions() end 
function CCParticleSystemQuad:removeAllChildren() end 
function CCParticleSystemQuad:runAction() end 
function CCParticleSystemQuad:setUserObject() end 
function CCParticleSystemQuad:parentToNodeTransform() end 
function CCParticleSystemQuad:removeChild() end 
function CCParticleSystemQuad:getAnchorPointInPoints() end 
function CCParticleSystemQuad:getScaleX() end 
function CCParticleSystemQuad:transform() end 
function CCParticleSystemQuad:getActionManager() end 
function CCParticleSystemQuad:draw() end 
function CCParticleSystemQuad:setScaleY() end 
function CCParticleSystemQuad:unregisterScriptHandler() end 
function CCParticleSystemQuad:setVertexZ() end 
function CCParticleSystemQuad:setAnchorPoint() end 
function CCParticleSystemQuad:getShaderProgram() end 
function CCParticleSystemQuad:stopAllActions() end 
function CCParticleSystemQuad:setUserData() end 
function CCParticleSystemQuad:setShaderProgram() end 
function CCParticleSystemQuad:getActionByTag() end 
function CCParticleSystemQuad:getGLServerState() end 
function CCParticleSystemQuad:getOrderOfArrival() end 
function CCParticleSystemQuad:getPositionX() end 
function CCParticleSystemQuad:setGLServerState() end 
function CCParticleSystemQuad:setSkewY() end 
function CCParticleSystemQuad:setOrderOfArrival() end 
function CCParticleSystemQuad:nodeToWorldTransform() end 
function CCParticleSystemQuad:getChildren() end 
function CCParticleSystemQuad:transformAncestors() end 
function CCParticleSystemQuad:getGrid() end 
function CCParticleSystemQuad:isRunning() end 
function CCParticleSystemQuad:registerScriptHandler() end 
function CCParticleSystemQuad:getCamera() end 
function CCParticleSystemQuad:isIgnoreAnchorPointForPosition() end 
function CCParticleSystemQuad:getUserData() end 
function CCParticleSystemQuad:setPositionY() end 
function CCParticleSystemQuad:getZOrder() end 
function CCParticleSystemQuad:setRadialAccelVar() end 
function CCParticleSystemQuad:getRotatePerSecond() end 
function CCParticleSystemQuad:getBlendFunc() end 
function CCParticleSystemQuad:getEndColorVar() end 
function CCParticleSystemQuad:setPosVar() end 
function CCParticleSystemQuad:getEmitterMode() end 
function CCParticleSystemQuad:setRotatePerSecondVar() end 
function CCParticleSystemQuad:getStartColorVar() end 
function CCParticleSystemQuad:getEndSizeVar() end 
function CCParticleSystemQuad:getEndRadiusVar() end 
function CCParticleSystemQuad:setTangentialAccel() end 
function CCParticleSystemQuad:getStartRadiusVar() end 
function CCParticleSystemQuad:getSourcePosition() end 
function CCParticleSystemQuad:isFull() end 
function CCParticleSystemQuad:setEmitterMode() end 
function CCParticleSystemQuad:setEmissionRate() end 
function CCParticleSystemQuad:getTexture() end 
function CCParticleSystemQuad:setTexture() end 
function CCParticleSystemQuad:setScaleX() end 
function CCParticleSystemQuad:getRadialAccelVar() end 
function CCParticleSystemQuad:isAutoRemoveOnFinish() end 
function CCParticleSystemQuad:getEndColor() end 
function CCParticleSystemQuad:setPositionType() end 
function CCParticleSystemQuad:getRotatePerSecondVar() end 
function CCParticleSystemQuad:setStartColorVar() end 
function CCParticleSystemQuad:setBlendAdditive() end 
function CCParticleSystemQuad:getTangentialAccel() end 
function CCParticleSystemQuad:setStartRadiusVar() end 
function CCParticleSystemQuad:setLife() end 
function CCParticleSystemQuad:getParticleCount() end 
function CCParticleSystemQuad:setSourcePosition() end 
function CCParticleSystemQuad:setScale() end 
function CCParticleSystemQuad:setBatchNode() end 
function CCParticleSystemQuad:setEndColor() end 
function CCParticleSystemQuad:isBlendAdditive() end 
function CCParticleSystemQuad:isActive() end 
function CCParticleSystemQuad:setGravity() end 
function CCParticleSystemQuad:stopSystem() end 
function CCParticleSystemQuad:getTangentialAccelVar() end 
function CCParticleSystemQuad:initWithTotalParticles() end 
function CCParticleSystemQuad:setBlendFunc() end 
function CCParticleSystemQuad:setSpeed() end 
function CCParticleSystemQuad:getStartRadius() end 
function CCParticleSystemQuad:getBatchNode() end 
function CCParticleSystemQuad:setLifeVar() end 
function CCParticleSystemQuad:setRotation() end 
function CCParticleSystemQuad:setStartRadius() end 
function CCParticleSystemQuad:setEndRadiusVar() end 
---
-- @return @class CCParticleSystemQuad
--
function CCParticleSystemQuad:create() end 
function CCParticleSystemQuad:setAutoRemoveOnFinish() end 
function CCParticleSystemQuad:setStartSpin() end 
function CCParticleSystemQuad:setEndSpin() end 
function CCParticleSystemQuad:getStartSizeVar() end 
function CCParticleSystemQuad:initWithFile() end 
function CCParticleSystemQuad:setStartColor() end 
function CCParticleSystemQuad:setStartSizeVar() end 
function CCParticleSystemQuad:setTangentialAccelVar() end 
function CCParticleSystemQuad:getLife() end 
function CCParticleSystemQuad:getTotalParticles() end 
function CCParticleSystemQuad:getSpeed() end 
function CCParticleSystemQuad:getEmissionRate() end 
function CCParticleSystemQuad:getEndSpinVar() end 
function CCParticleSystemQuad:setEndSpinVar() end 
function CCParticleSystemQuad:getEndSpin() end 
function CCParticleSystemQuad:getAngle() end 
function CCParticleSystemQuad:updateQuadWithParticle() end 
function CCParticleSystemQuad:setSpeedVar() end 
function CCParticleSystemQuad:getStartSpinVar() end 
function CCParticleSystemQuad:setStartSpinVar() end 
function CCParticleSystemQuad:getStartSpin() end 
function CCParticleSystemQuad:setEndSize() end 
function CCParticleSystemQuad:getRadialAccel() end 
function CCParticleSystemQuad:getPosVar() end 
function CCParticleSystemQuad:getEndSize() end 
function CCParticleSystemQuad:getLifeVar() end 
function CCParticleSystemQuad:getPositionType() end 
function CCParticleSystemQuad:getStartColor() end 
function CCParticleSystemQuad:getEndRadius() end 
function CCParticleSystemQuad:addParticle() end 
function CCParticleSystemQuad:postStep() end 
function CCParticleSystemQuad:setEndSizeVar() end 
function CCParticleSystemQuad:getDuration() end 
function CCParticleSystemQuad:getSpeedVar() end 
function CCParticleSystemQuad:initParticle() end 
function CCParticleSystemQuad:getAngleVar() end 
function CCParticleSystemQuad:getStartSize() end 
function CCParticleSystemQuad:setRotatePerSecond() end 
function CCParticleSystemQuad:setEndRadius() end 
function CCParticleSystemQuad:setAngleVar() end 
function CCParticleSystemQuad:getGravity() end 
function CCParticleSystemQuad:setEndColorVar() end 
function CCParticleSystemQuad:setAngle() end 
function CCParticleSystemQuad:resetSystem() end 
function CCParticleSystemQuad:setDuration() end 
function CCParticleSystemQuad:setRadialAccel() end 
function CCParticleSystemQuad:setStartSize() end 
function CCParticleSystemQuad:setScaleY() end 
function CCParticleSystemQuad:new() end 
function CCParticleSystemQuad:postStep() end 
---
-- @return @class CCParticleSystemQuad
--
function CCParticleSystemQuad:create() end 
function CCParticleSystemQuad:setTextureWithRect() end 
function CCParticleSystemQuad:setTotalParticles() end 
function CCParticleSystemQuad:new_local() end 
function CCParticleSystemQuad:setBatchNode() end 
function CCParticleSystemQuad:updateQuadWithParticle() end 
function CCParticleSystemQuad:setTexture() end 
function CCParticleSystemQuad:setDisplayFrame() end 
