---@classdef CCParticleGalaxy
CCParticleGalaxy = {}
function CCParticleGalaxy:autorelease() end 
function CCParticleGalaxy:retain() end 
function CCParticleGalaxy:retainCount() end 
function CCParticleGalaxy:isEqual() end 
function CCParticleGalaxy:copy() end 
function CCParticleGalaxy:release() end 
function CCParticleGalaxy:isSingleReference() end 
function CCParticleGalaxy:visit() end 
function CCParticleGalaxy:getUserObject() end 
function CCParticleGalaxy:getSkewY() end 
function CCParticleGalaxy:convertTouchToNodeSpace() end 
function CCParticleGalaxy:getVertexZ() end 
function CCParticleGalaxy:setParent() end 
function CCParticleGalaxy:boundingBox() end 
function CCParticleGalaxy:setVisible() end 
function CCParticleGalaxy:stopActionByTag() end 
function CCParticleGalaxy:getScaleY() end 
function CCParticleGalaxy:setScaleX() end 
function CCParticleGalaxy:reorderChild() end 
function CCParticleGalaxy:setPositionX() end 
function CCParticleGalaxy:removeFromParentAndCleanup() end 
function CCParticleGalaxy:setTag() end 
function CCParticleGalaxy:getChildrenCount() end 
function CCParticleGalaxy:setScale() end 
function CCParticleGalaxy:addChild() end 
function CCParticleGalaxy:isVisible() end 
function CCParticleGalaxy:setActionManager() end 
function CCParticleGalaxy:setScheduler() end 
function CCParticleGalaxy:getContentSize() end 
function CCParticleGalaxy:getAnchorPoint() end 
function CCParticleGalaxy:getTag() end 
function CCParticleGalaxy:setGrid() end 
function CCParticleGalaxy:convertToWorldSpace() end 
function CCParticleGalaxy:setSkewX() end 
function CCParticleGalaxy:setZOrder() end 
function CCParticleGalaxy:worldToNodeTransform() end 
function CCParticleGalaxy:getPosition() end 
function CCParticleGalaxy:getSkewX() end 
function CCParticleGalaxy:getScheduler() end 
function CCParticleGalaxy:ignoreAnchorPointForPosition() end 
function CCParticleGalaxy:setPosition() end 
function CCParticleGalaxy:getParent() end 
function CCParticleGalaxy:unscheduleUpdate() end 
function CCParticleGalaxy:scheduleUpdateWithPriorityLua() end 
function CCParticleGalaxy:removeChildByTag() end 
function CCParticleGalaxy:convertToNodeSpaceAR() end 
function CCParticleGalaxy:convertTouchToNodeSpaceAR() end 
function CCParticleGalaxy:convertToWorldSpaceAR() end 
function CCParticleGalaxy:setRotation() end 
function CCParticleGalaxy:getComponent() end 
function CCParticleGalaxy:convertToNodeSpace() end 
---
-- @return @class CCParticleGalaxy
--
function CCParticleGalaxy:create() end 
function CCParticleGalaxy:getScale() end 
function CCParticleGalaxy:getPositionY() end 
function CCParticleGalaxy:getChildByTag() end 
function CCParticleGalaxy:setContentSize() end 
function CCParticleGalaxy:description() end 
function CCParticleGalaxy:cleanup() end 
function CCParticleGalaxy:getRotation() end 
function CCParticleGalaxy:nodeToParentTransform() end 
function CCParticleGalaxy:stopAction() end 
function CCParticleGalaxy:numberOfRunningActions() end 
function CCParticleGalaxy:removeAllChildren() end 
function CCParticleGalaxy:runAction() end 
function CCParticleGalaxy:setUserObject() end 
function CCParticleGalaxy:parentToNodeTransform() end 
function CCParticleGalaxy:removeChild() end 
function CCParticleGalaxy:getAnchorPointInPoints() end 
function CCParticleGalaxy:getScaleX() end 
function CCParticleGalaxy:transform() end 
function CCParticleGalaxy:getActionManager() end 
function CCParticleGalaxy:draw() end 
function CCParticleGalaxy:setScaleY() end 
function CCParticleGalaxy:unregisterScriptHandler() end 
function CCParticleGalaxy:setVertexZ() end 
function CCParticleGalaxy:setAnchorPoint() end 
function CCParticleGalaxy:getShaderProgram() end 
function CCParticleGalaxy:stopAllActions() end 
function CCParticleGalaxy:setUserData() end 
function CCParticleGalaxy:setShaderProgram() end 
function CCParticleGalaxy:getActionByTag() end 
function CCParticleGalaxy:getGLServerState() end 
function CCParticleGalaxy:getOrderOfArrival() end 
function CCParticleGalaxy:getPositionX() end 
function CCParticleGalaxy:setGLServerState() end 
function CCParticleGalaxy:setSkewY() end 
function CCParticleGalaxy:setOrderOfArrival() end 
function CCParticleGalaxy:nodeToWorldTransform() end 
function CCParticleGalaxy:getChildren() end 
function CCParticleGalaxy:transformAncestors() end 
function CCParticleGalaxy:getGrid() end 
function CCParticleGalaxy:isRunning() end 
function CCParticleGalaxy:registerScriptHandler() end 
function CCParticleGalaxy:getCamera() end 
function CCParticleGalaxy:isIgnoreAnchorPointForPosition() end 
function CCParticleGalaxy:getUserData() end 
function CCParticleGalaxy:setPositionY() end 
function CCParticleGalaxy:getZOrder() end 
function CCParticleGalaxy:setRadialAccelVar() end 
function CCParticleGalaxy:getRotatePerSecond() end 
function CCParticleGalaxy:getBlendFunc() end 
function CCParticleGalaxy:getEndColorVar() end 
function CCParticleGalaxy:setPosVar() end 
function CCParticleGalaxy:getEmitterMode() end 
function CCParticleGalaxy:setRotatePerSecondVar() end 
function CCParticleGalaxy:getStartColorVar() end 
function CCParticleGalaxy:getEndSizeVar() end 
function CCParticleGalaxy:getEndRadiusVar() end 
function CCParticleGalaxy:setTangentialAccel() end 
function CCParticleGalaxy:getStartRadiusVar() end 
function CCParticleGalaxy:getSourcePosition() end 
function CCParticleGalaxy:isFull() end 
function CCParticleGalaxy:setEmitterMode() end 
function CCParticleGalaxy:setEmissionRate() end 
function CCParticleGalaxy:getTexture() end 
function CCParticleGalaxy:setTexture() end 
function CCParticleGalaxy:setScaleX() end 
function CCParticleGalaxy:getRadialAccelVar() end 
function CCParticleGalaxy:isAutoRemoveOnFinish() end 
function CCParticleGalaxy:getEndColor() end 
function CCParticleGalaxy:setPositionType() end 
function CCParticleGalaxy:getRotatePerSecondVar() end 
function CCParticleGalaxy:setStartColorVar() end 
function CCParticleGalaxy:setBlendAdditive() end 
function CCParticleGalaxy:getTangentialAccel() end 
function CCParticleGalaxy:setStartRadiusVar() end 
function CCParticleGalaxy:setLife() end 
function CCParticleGalaxy:getParticleCount() end 
function CCParticleGalaxy:setSourcePosition() end 
function CCParticleGalaxy:setScale() end 
function CCParticleGalaxy:setBatchNode() end 
function CCParticleGalaxy:setEndColor() end 
function CCParticleGalaxy:isBlendAdditive() end 
function CCParticleGalaxy:isActive() end 
function CCParticleGalaxy:setGravity() end 
function CCParticleGalaxy:stopSystem() end 
function CCParticleGalaxy:getTangentialAccelVar() end 
function CCParticleGalaxy:initWithTotalParticles() end 
function CCParticleGalaxy:setBlendFunc() end 
function CCParticleGalaxy:setSpeed() end 
function CCParticleGalaxy:getStartRadius() end 
function CCParticleGalaxy:getBatchNode() end 
function CCParticleGalaxy:setLifeVar() end 
function CCParticleGalaxy:setRotation() end 
function CCParticleGalaxy:setStartRadius() end 
function CCParticleGalaxy:setEndRadiusVar() end 
---
-- @return @class CCParticleGalaxy
--
function CCParticleGalaxy:create() end 
function CCParticleGalaxy:setAutoRemoveOnFinish() end 
function CCParticleGalaxy:setStartSpin() end 
function CCParticleGalaxy:setEndSpin() end 
function CCParticleGalaxy:getStartSizeVar() end 
function CCParticleGalaxy:initWithFile() end 
function CCParticleGalaxy:setStartColor() end 
function CCParticleGalaxy:setStartSizeVar() end 
function CCParticleGalaxy:setTangentialAccelVar() end 
function CCParticleGalaxy:getLife() end 
function CCParticleGalaxy:getTotalParticles() end 
function CCParticleGalaxy:getSpeed() end 
function CCParticleGalaxy:getEmissionRate() end 
function CCParticleGalaxy:getEndSpinVar() end 
function CCParticleGalaxy:setEndSpinVar() end 
function CCParticleGalaxy:getEndSpin() end 
function CCParticleGalaxy:getAngle() end 
function CCParticleGalaxy:updateQuadWithParticle() end 
function CCParticleGalaxy:setSpeedVar() end 
function CCParticleGalaxy:getStartSpinVar() end 
function CCParticleGalaxy:setStartSpinVar() end 
function CCParticleGalaxy:getStartSpin() end 
function CCParticleGalaxy:setEndSize() end 
function CCParticleGalaxy:getRadialAccel() end 
function CCParticleGalaxy:getPosVar() end 
function CCParticleGalaxy:getEndSize() end 
function CCParticleGalaxy:getLifeVar() end 
function CCParticleGalaxy:getPositionType() end 
function CCParticleGalaxy:getStartColor() end 
function CCParticleGalaxy:getEndRadius() end 
function CCParticleGalaxy:addParticle() end 
function CCParticleGalaxy:postStep() end 
function CCParticleGalaxy:setEndSizeVar() end 
function CCParticleGalaxy:getDuration() end 
function CCParticleGalaxy:getSpeedVar() end 
function CCParticleGalaxy:initParticle() end 
function CCParticleGalaxy:getAngleVar() end 
function CCParticleGalaxy:getStartSize() end 
function CCParticleGalaxy:setRotatePerSecond() end 
function CCParticleGalaxy:setEndRadius() end 
function CCParticleGalaxy:setAngleVar() end 
function CCParticleGalaxy:getGravity() end 
function CCParticleGalaxy:setEndColorVar() end 
function CCParticleGalaxy:setAngle() end 
function CCParticleGalaxy:resetSystem() end 
function CCParticleGalaxy:setDuration() end 
function CCParticleGalaxy:setRadialAccel() end 
function CCParticleGalaxy:setStartSize() end 
function CCParticleGalaxy:setScaleY() end 
function CCParticleGalaxy:new() end 
function CCParticleGalaxy:postStep() end 
---
-- @return @class CCParticleGalaxy
--
function CCParticleGalaxy:create() end 
function CCParticleGalaxy:setTextureWithRect() end 
function CCParticleGalaxy:setTotalParticles() end 
function CCParticleGalaxy:new_local() end 
function CCParticleGalaxy:setBatchNode() end 
function CCParticleGalaxy:updateQuadWithParticle() end 
function CCParticleGalaxy:setTexture() end 
function CCParticleGalaxy:setDisplayFrame() end 
---
-- @return @class CCParticleGalaxy
--
function CCParticleGalaxy:create() end 
