---@classdef CCParticleRain
CCParticleRain = {}
function CCParticleRain:autorelease() end 
function CCParticleRain:retain() end 
function CCParticleRain:retainCount() end 
function CCParticleRain:isEqual() end 
function CCParticleRain:copy() end 
function CCParticleRain:release() end 
function CCParticleRain:isSingleReference() end 
function CCParticleRain:visit() end 
function CCParticleRain:getUserObject() end 
function CCParticleRain:getSkewY() end 
function CCParticleRain:convertTouchToNodeSpace() end 
function CCParticleRain:getVertexZ() end 
function CCParticleRain:setParent() end 
function CCParticleRain:boundingBox() end 
function CCParticleRain:setVisible() end 
function CCParticleRain:stopActionByTag() end 
function CCParticleRain:getScaleY() end 
function CCParticleRain:setScaleX() end 
function CCParticleRain:reorderChild() end 
function CCParticleRain:setPositionX() end 
function CCParticleRain:removeFromParentAndCleanup() end 
function CCParticleRain:setTag() end 
function CCParticleRain:getChildrenCount() end 
function CCParticleRain:setScale() end 
function CCParticleRain:addChild() end 
function CCParticleRain:isVisible() end 
function CCParticleRain:setActionManager() end 
function CCParticleRain:setScheduler() end 
function CCParticleRain:getContentSize() end 
function CCParticleRain:getAnchorPoint() end 
function CCParticleRain:getTag() end 
function CCParticleRain:setGrid() end 
function CCParticleRain:convertToWorldSpace() end 
function CCParticleRain:setSkewX() end 
function CCParticleRain:setZOrder() end 
function CCParticleRain:worldToNodeTransform() end 
function CCParticleRain:getPosition() end 
function CCParticleRain:getSkewX() end 
function CCParticleRain:getScheduler() end 
function CCParticleRain:ignoreAnchorPointForPosition() end 
function CCParticleRain:setPosition() end 
function CCParticleRain:getParent() end 
function CCParticleRain:unscheduleUpdate() end 
function CCParticleRain:scheduleUpdateWithPriorityLua() end 
function CCParticleRain:removeChildByTag() end 
function CCParticleRain:convertToNodeSpaceAR() end 
function CCParticleRain:convertTouchToNodeSpaceAR() end 
function CCParticleRain:convertToWorldSpaceAR() end 
function CCParticleRain:setRotation() end 
function CCParticleRain:getComponent() end 
function CCParticleRain:convertToNodeSpace() end 
---
-- @return @class CCParticleRain
--
function CCParticleRain:create() end 
function CCParticleRain:getScale() end 
function CCParticleRain:getPositionY() end 
function CCParticleRain:getChildByTag() end 
function CCParticleRain:setContentSize() end 
function CCParticleRain:description() end 
function CCParticleRain:cleanup() end 
function CCParticleRain:getRotation() end 
function CCParticleRain:nodeToParentTransform() end 
function CCParticleRain:stopAction() end 
function CCParticleRain:numberOfRunningActions() end 
function CCParticleRain:removeAllChildren() end 
function CCParticleRain:runAction() end 
function CCParticleRain:setUserObject() end 
function CCParticleRain:parentToNodeTransform() end 
function CCParticleRain:removeChild() end 
function CCParticleRain:getAnchorPointInPoints() end 
function CCParticleRain:getScaleX() end 
function CCParticleRain:transform() end 
function CCParticleRain:getActionManager() end 
function CCParticleRain:draw() end 
function CCParticleRain:setScaleY() end 
function CCParticleRain:unregisterScriptHandler() end 
function CCParticleRain:setVertexZ() end 
function CCParticleRain:setAnchorPoint() end 
function CCParticleRain:getShaderProgram() end 
function CCParticleRain:stopAllActions() end 
function CCParticleRain:setUserData() end 
function CCParticleRain:setShaderProgram() end 
function CCParticleRain:getActionByTag() end 
function CCParticleRain:getGLServerState() end 
function CCParticleRain:getOrderOfArrival() end 
function CCParticleRain:getPositionX() end 
function CCParticleRain:setGLServerState() end 
function CCParticleRain:setSkewY() end 
function CCParticleRain:setOrderOfArrival() end 
function CCParticleRain:nodeToWorldTransform() end 
function CCParticleRain:getChildren() end 
function CCParticleRain:transformAncestors() end 
function CCParticleRain:getGrid() end 
function CCParticleRain:isRunning() end 
function CCParticleRain:registerScriptHandler() end 
function CCParticleRain:getCamera() end 
function CCParticleRain:isIgnoreAnchorPointForPosition() end 
function CCParticleRain:getUserData() end 
function CCParticleRain:setPositionY() end 
function CCParticleRain:getZOrder() end 
function CCParticleRain:setRadialAccelVar() end 
function CCParticleRain:getRotatePerSecond() end 
function CCParticleRain:getBlendFunc() end 
function CCParticleRain:getEndColorVar() end 
function CCParticleRain:setPosVar() end 
function CCParticleRain:getEmitterMode() end 
function CCParticleRain:setRotatePerSecondVar() end 
function CCParticleRain:getStartColorVar() end 
function CCParticleRain:getEndSizeVar() end 
function CCParticleRain:getEndRadiusVar() end 
function CCParticleRain:setTangentialAccel() end 
function CCParticleRain:getStartRadiusVar() end 
function CCParticleRain:getSourcePosition() end 
function CCParticleRain:isFull() end 
function CCParticleRain:setEmitterMode() end 
function CCParticleRain:setEmissionRate() end 
function CCParticleRain:getTexture() end 
function CCParticleRain:setTexture() end 
function CCParticleRain:setScaleX() end 
function CCParticleRain:getRadialAccelVar() end 
function CCParticleRain:isAutoRemoveOnFinish() end 
function CCParticleRain:getEndColor() end 
function CCParticleRain:setPositionType() end 
function CCParticleRain:getRotatePerSecondVar() end 
function CCParticleRain:setStartColorVar() end 
function CCParticleRain:setBlendAdditive() end 
function CCParticleRain:getTangentialAccel() end 
function CCParticleRain:setStartRadiusVar() end 
function CCParticleRain:setLife() end 
function CCParticleRain:getParticleCount() end 
function CCParticleRain:setSourcePosition() end 
function CCParticleRain:setScale() end 
function CCParticleRain:setBatchNode() end 
function CCParticleRain:setEndColor() end 
function CCParticleRain:isBlendAdditive() end 
function CCParticleRain:isActive() end 
function CCParticleRain:setGravity() end 
function CCParticleRain:stopSystem() end 
function CCParticleRain:getTangentialAccelVar() end 
function CCParticleRain:initWithTotalParticles() end 
function CCParticleRain:setBlendFunc() end 
function CCParticleRain:setSpeed() end 
function CCParticleRain:getStartRadius() end 
function CCParticleRain:getBatchNode() end 
function CCParticleRain:setLifeVar() end 
function CCParticleRain:setRotation() end 
function CCParticleRain:setStartRadius() end 
function CCParticleRain:setEndRadiusVar() end 
---
-- @return @class CCParticleRain
--
function CCParticleRain:create() end 
function CCParticleRain:setAutoRemoveOnFinish() end 
function CCParticleRain:setStartSpin() end 
function CCParticleRain:setEndSpin() end 
function CCParticleRain:getStartSizeVar() end 
function CCParticleRain:initWithFile() end 
function CCParticleRain:setStartColor() end 
function CCParticleRain:setStartSizeVar() end 
function CCParticleRain:setTangentialAccelVar() end 
function CCParticleRain:getLife() end 
function CCParticleRain:getTotalParticles() end 
function CCParticleRain:getSpeed() end 
function CCParticleRain:getEmissionRate() end 
function CCParticleRain:getEndSpinVar() end 
function CCParticleRain:setEndSpinVar() end 
function CCParticleRain:getEndSpin() end 
function CCParticleRain:getAngle() end 
function CCParticleRain:updateQuadWithParticle() end 
function CCParticleRain:setSpeedVar() end 
function CCParticleRain:getStartSpinVar() end 
function CCParticleRain:setStartSpinVar() end 
function CCParticleRain:getStartSpin() end 
function CCParticleRain:setEndSize() end 
function CCParticleRain:getRadialAccel() end 
function CCParticleRain:getPosVar() end 
function CCParticleRain:getEndSize() end 
function CCParticleRain:getLifeVar() end 
function CCParticleRain:getPositionType() end 
function CCParticleRain:getStartColor() end 
function CCParticleRain:getEndRadius() end 
function CCParticleRain:addParticle() end 
function CCParticleRain:postStep() end 
function CCParticleRain:setEndSizeVar() end 
function CCParticleRain:getDuration() end 
function CCParticleRain:getSpeedVar() end 
function CCParticleRain:initParticle() end 
function CCParticleRain:getAngleVar() end 
function CCParticleRain:getStartSize() end 
function CCParticleRain:setRotatePerSecond() end 
function CCParticleRain:setEndRadius() end 
function CCParticleRain:setAngleVar() end 
function CCParticleRain:getGravity() end 
function CCParticleRain:setEndColorVar() end 
function CCParticleRain:setAngle() end 
function CCParticleRain:resetSystem() end 
function CCParticleRain:setDuration() end 
function CCParticleRain:setRadialAccel() end 
function CCParticleRain:setStartSize() end 
function CCParticleRain:setScaleY() end 
function CCParticleRain:new() end 
function CCParticleRain:postStep() end 
---
-- @return @class CCParticleRain
--
function CCParticleRain:create() end 
function CCParticleRain:setTextureWithRect() end 
function CCParticleRain:setTotalParticles() end 
function CCParticleRain:new_local() end 
function CCParticleRain:setBatchNode() end 
function CCParticleRain:updateQuadWithParticle() end 
function CCParticleRain:setTexture() end 
function CCParticleRain:setDisplayFrame() end 
---
-- @return @class CCParticleRain
--
function CCParticleRain:create() end 
