---@classdef CCParticleBatchNode
CCParticleBatchNode = {}
function CCParticleBatchNode:autorelease() end 
function CCParticleBatchNode:retain() end 
function CCParticleBatchNode:retainCount() end 
function CCParticleBatchNode:isEqual() end 
function CCParticleBatchNode:copy() end 
function CCParticleBatchNode:release() end 
function CCParticleBatchNode:isSingleReference() end 
function CCParticleBatchNode:visit() end 
function CCParticleBatchNode:getUserObject() end 
function CCParticleBatchNode:getSkewY() end 
function CCParticleBatchNode:convertTouchToNodeSpace() end 
function CCParticleBatchNode:getVertexZ() end 
function CCParticleBatchNode:setParent() end 
function CCParticleBatchNode:boundingBox() end 
function CCParticleBatchNode:setVisible() end 
function CCParticleBatchNode:stopActionByTag() end 
function CCParticleBatchNode:getScaleY() end 
function CCParticleBatchNode:setScaleX() end 
function CCParticleBatchNode:reorderChild() end 
function CCParticleBatchNode:setPositionX() end 
function CCParticleBatchNode:removeFromParentAndCleanup() end 
function CCParticleBatchNode:setTag() end 
function CCParticleBatchNode:getChildrenCount() end 
function CCParticleBatchNode:setScale() end 
function CCParticleBatchNode:addChild() end 
function CCParticleBatchNode:isVisible() end 
function CCParticleBatchNode:setActionManager() end 
function CCParticleBatchNode:setScheduler() end 
function CCParticleBatchNode:getContentSize() end 
function CCParticleBatchNode:getAnchorPoint() end 
function CCParticleBatchNode:getTag() end 
function CCParticleBatchNode:setGrid() end 
function CCParticleBatchNode:convertToWorldSpace() end 
function CCParticleBatchNode:setSkewX() end 
function CCParticleBatchNode:setZOrder() end 
function CCParticleBatchNode:worldToNodeTransform() end 
function CCParticleBatchNode:getPosition() end 
function CCParticleBatchNode:getSkewX() end 
function CCParticleBatchNode:getScheduler() end 
function CCParticleBatchNode:ignoreAnchorPointForPosition() end 
function CCParticleBatchNode:setPosition() end 
function CCParticleBatchNode:getParent() end 
function CCParticleBatchNode:unscheduleUpdate() end 
function CCParticleBatchNode:scheduleUpdateWithPriorityLua() end 
function CCParticleBatchNode:removeChildByTag() end 
function CCParticleBatchNode:convertToNodeSpaceAR() end 
function CCParticleBatchNode:convertTouchToNodeSpaceAR() end 
function CCParticleBatchNode:convertToWorldSpaceAR() end 
function CCParticleBatchNode:setRotation() end 
function CCParticleBatchNode:getComponent() end 
function CCParticleBatchNode:convertToNodeSpace() end 
---
-- @return @class CCParticleBatchNode
--
function CCParticleBatchNode:create() end 
function CCParticleBatchNode:getScale() end 
function CCParticleBatchNode:getPositionY() end 
function CCParticleBatchNode:getChildByTag() end 
function CCParticleBatchNode:setContentSize() end 
function CCParticleBatchNode:description() end 
function CCParticleBatchNode:cleanup() end 
function CCParticleBatchNode:getRotation() end 
function CCParticleBatchNode:nodeToParentTransform() end 
function CCParticleBatchNode:stopAction() end 
function CCParticleBatchNode:numberOfRunningActions() end 
function CCParticleBatchNode:removeAllChildren() end 
function CCParticleBatchNode:runAction() end 
function CCParticleBatchNode:setUserObject() end 
function CCParticleBatchNode:parentToNodeTransform() end 
function CCParticleBatchNode:removeChild() end 
function CCParticleBatchNode:getAnchorPointInPoints() end 
function CCParticleBatchNode:getScaleX() end 
function CCParticleBatchNode:transform() end 
function CCParticleBatchNode:getActionManager() end 
function CCParticleBatchNode:draw() end 
function CCParticleBatchNode:setScaleY() end 
function CCParticleBatchNode:unregisterScriptHandler() end 
function CCParticleBatchNode:setVertexZ() end 
function CCParticleBatchNode:setAnchorPoint() end 
function CCParticleBatchNode:getShaderProgram() end 
function CCParticleBatchNode:stopAllActions() end 
function CCParticleBatchNode:setUserData() end 
function CCParticleBatchNode:setShaderProgram() end 
function CCParticleBatchNode:getActionByTag() end 
function CCParticleBatchNode:getGLServerState() end 
function CCParticleBatchNode:getOrderOfArrival() end 
function CCParticleBatchNode:getPositionX() end 
function CCParticleBatchNode:setGLServerState() end 
function CCParticleBatchNode:setSkewY() end 
function CCParticleBatchNode:setOrderOfArrival() end 
function CCParticleBatchNode:nodeToWorldTransform() end 
function CCParticleBatchNode:getChildren() end 
function CCParticleBatchNode:transformAncestors() end 
function CCParticleBatchNode:getGrid() end 
function CCParticleBatchNode:isRunning() end 
function CCParticleBatchNode:registerScriptHandler() end 
function CCParticleBatchNode:getCamera() end 
function CCParticleBatchNode:isIgnoreAnchorPointForPosition() end 
function CCParticleBatchNode:getUserData() end 
function CCParticleBatchNode:setPositionY() end 
function CCParticleBatchNode:getZOrder() end 
function CCParticleBatchNode:addChild() end 
function CCParticleBatchNode:setTexture() end 
function CCParticleBatchNode:getTexture() end 
function CCParticleBatchNode:disableParticle() end 
function CCParticleBatchNode:removeChildAtIndex() end 
---
-- @return @class CCParticleBatchNode
--
function CCParticleBatchNode:create() end 
function CCParticleBatchNode:removeAllChildren() end 
function CCParticleBatchNode:createWithTexture() end 
function CCParticleBatchNode:getBlendFunc() end 
function CCParticleBatchNode:setBlendFunc() end 
function CCParticleBatchNode:reorderChild() end 
function CCParticleBatchNode:insertChild() end 
function CCParticleBatchNode:removeChild() end 
