---@classdef CCParticleExplosion
CCParticleExplosion = {}
function CCParticleExplosion:autorelease() end 
function CCParticleExplosion:retain() end 
function CCParticleExplosion:retainCount() end 
function CCParticleExplosion:isEqual() end 
function CCParticleExplosion:copy() end 
function CCParticleExplosion:release() end 
function CCParticleExplosion:isSingleReference() end 
function CCParticleExplosion:visit() end 
function CCParticleExplosion:getUserObject() end 
function CCParticleExplosion:getSkewY() end 
function CCParticleExplosion:convertTouchToNodeSpace() end 
function CCParticleExplosion:getVertexZ() end 
function CCParticleExplosion:setParent() end 
function CCParticleExplosion:boundingBox() end 
function CCParticleExplosion:setVisible() end 
function CCParticleExplosion:stopActionByTag() end 
function CCParticleExplosion:getScaleY() end 
function CCParticleExplosion:setScaleX() end 
function CCParticleExplosion:reorderChild() end 
function CCParticleExplosion:setPositionX() end 
function CCParticleExplosion:removeFromParentAndCleanup() end 
function CCParticleExplosion:setTag() end 
function CCParticleExplosion:getChildrenCount() end 
function CCParticleExplosion:setScale() end 
function CCParticleExplosion:addChild() end 
function CCParticleExplosion:isVisible() end 
function CCParticleExplosion:setActionManager() end 
function CCParticleExplosion:setScheduler() end 
function CCParticleExplosion:getContentSize() end 
function CCParticleExplosion:getAnchorPoint() end 
function CCParticleExplosion:getTag() end 
function CCParticleExplosion:setGrid() end 
function CCParticleExplosion:convertToWorldSpace() end 
function CCParticleExplosion:setSkewX() end 
function CCParticleExplosion:setZOrder() end 
function CCParticleExplosion:worldToNodeTransform() end 
function CCParticleExplosion:getPosition() end 
function CCParticleExplosion:getSkewX() end 
function CCParticleExplosion:getScheduler() end 
function CCParticleExplosion:ignoreAnchorPointForPosition() end 
function CCParticleExplosion:setPosition() end 
function CCParticleExplosion:getParent() end 
function CCParticleExplosion:unscheduleUpdate() end 
function CCParticleExplosion:scheduleUpdateWithPriorityLua() end 
function CCParticleExplosion:removeChildByTag() end 
function CCParticleExplosion:convertToNodeSpaceAR() end 
function CCParticleExplosion:convertTouchToNodeSpaceAR() end 
function CCParticleExplosion:convertToWorldSpaceAR() end 
function CCParticleExplosion:setRotation() end 
function CCParticleExplosion:getComponent() end 
function CCParticleExplosion:convertToNodeSpace() end 
---
-- @return @class CCParticleExplosion
--
function CCParticleExplosion:create() end 
function CCParticleExplosion:getScale() end 
function CCParticleExplosion:getPositionY() end 
function CCParticleExplosion:getChildByTag() end 
function CCParticleExplosion:setContentSize() end 
function CCParticleExplosion:description() end 
function CCParticleExplosion:cleanup() end 
function CCParticleExplosion:getRotation() end 
function CCParticleExplosion:nodeToParentTransform() end 
function CCParticleExplosion:stopAction() end 
function CCParticleExplosion:numberOfRunningActions() end 
function CCParticleExplosion:removeAllChildren() end 
function CCParticleExplosion:runAction() end 
function CCParticleExplosion:setUserObject() end 
function CCParticleExplosion:parentToNodeTransform() end 
function CCParticleExplosion:removeChild() end 
function CCParticleExplosion:getAnchorPointInPoints() end 
function CCParticleExplosion:getScaleX() end 
function CCParticleExplosion:transform() end 
function CCParticleExplosion:getActionManager() end 
function CCParticleExplosion:draw() end 
function CCParticleExplosion:setScaleY() end 
function CCParticleExplosion:unregisterScriptHandler() end 
function CCParticleExplosion:setVertexZ() end 
function CCParticleExplosion:setAnchorPoint() end 
function CCParticleExplosion:getShaderProgram() end 
function CCParticleExplosion:stopAllActions() end 
function CCParticleExplosion:setUserData() end 
function CCParticleExplosion:setShaderProgram() end 
function CCParticleExplosion:getActionByTag() end 
function CCParticleExplosion:getGLServerState() end 
function CCParticleExplosion:getOrderOfArrival() end 
function CCParticleExplosion:getPositionX() end 
function CCParticleExplosion:setGLServerState() end 
function CCParticleExplosion:setSkewY() end 
function CCParticleExplosion:setOrderOfArrival() end 
function CCParticleExplosion:nodeToWorldTransform() end 
function CCParticleExplosion:getChildren() end 
function CCParticleExplosion:transformAncestors() end 
function CCParticleExplosion:getGrid() end 
function CCParticleExplosion:isRunning() end 
function CCParticleExplosion:registerScriptHandler() end 
function CCParticleExplosion:getCamera() end 
function CCParticleExplosion:isIgnoreAnchorPointForPosition() end 
function CCParticleExplosion:getUserData() end 
function CCParticleExplosion:setPositionY() end 
function CCParticleExplosion:getZOrder() end 
function CCParticleExplosion:setRadialAccelVar() end 
function CCParticleExplosion:getRotatePerSecond() end 
function CCParticleExplosion:getBlendFunc() end 
function CCParticleExplosion:getEndColorVar() end 
function CCParticleExplosion:setPosVar() end 
function CCParticleExplosion:getEmitterMode() end 
function CCParticleExplosion:setRotatePerSecondVar() end 
function CCParticleExplosion:getStartColorVar() end 
function CCParticleExplosion:getEndSizeVar() end 
function CCParticleExplosion:getEndRadiusVar() end 
function CCParticleExplosion:setTangentialAccel() end 
function CCParticleExplosion:getStartRadiusVar() end 
function CCParticleExplosion:getSourcePosition() end 
function CCParticleExplosion:isFull() end 
function CCParticleExplosion:setEmitterMode() end 
function CCParticleExplosion:setEmissionRate() end 
function CCParticleExplosion:getTexture() end 
function CCParticleExplosion:setTexture() end 
function CCParticleExplosion:setScaleX() end 
function CCParticleExplosion:getRadialAccelVar() end 
function CCParticleExplosion:isAutoRemoveOnFinish() end 
function CCParticleExplosion:getEndColor() end 
function CCParticleExplosion:setPositionType() end 
function CCParticleExplosion:getRotatePerSecondVar() end 
function CCParticleExplosion:setStartColorVar() end 
function CCParticleExplosion:setBlendAdditive() end 
function CCParticleExplosion:getTangentialAccel() end 
function CCParticleExplosion:setStartRadiusVar() end 
function CCParticleExplosion:setLife() end 
function CCParticleExplosion:getParticleCount() end 
function CCParticleExplosion:setSourcePosition() end 
function CCParticleExplosion:setScale() end 
function CCParticleExplosion:setBatchNode() end 
function CCParticleExplosion:setEndColor() end 
function CCParticleExplosion:isBlendAdditive() end 
function CCParticleExplosion:isActive() end 
function CCParticleExplosion:setGravity() end 
function CCParticleExplosion:stopSystem() end 
function CCParticleExplosion:getTangentialAccelVar() end 
function CCParticleExplosion:initWithTotalParticles() end 
function CCParticleExplosion:setBlendFunc() end 
function CCParticleExplosion:setSpeed() end 
function CCParticleExplosion:getStartRadius() end 
function CCParticleExplosion:getBatchNode() end 
function CCParticleExplosion:setLifeVar() end 
function CCParticleExplosion:setRotation() end 
function CCParticleExplosion:setStartRadius() end 
function CCParticleExplosion:setEndRadiusVar() end 
---
-- @return @class CCParticleExplosion
--
function CCParticleExplosion:create() end 
function CCParticleExplosion:setAutoRemoveOnFinish() end 
function CCParticleExplosion:setStartSpin() end 
function CCParticleExplosion:setEndSpin() end 
function CCParticleExplosion:getStartSizeVar() end 
function CCParticleExplosion:initWithFile() end 
function CCParticleExplosion:setStartColor() end 
function CCParticleExplosion:setStartSizeVar() end 
function CCParticleExplosion:setTangentialAccelVar() end 
function CCParticleExplosion:getLife() end 
function CCParticleExplosion:getTotalParticles() end 
function CCParticleExplosion:getSpeed() end 
function CCParticleExplosion:getEmissionRate() end 
function CCParticleExplosion:getEndSpinVar() end 
function CCParticleExplosion:setEndSpinVar() end 
function CCParticleExplosion:getEndSpin() end 
function CCParticleExplosion:getAngle() end 
function CCParticleExplosion:updateQuadWithParticle() end 
function CCParticleExplosion:setSpeedVar() end 
function CCParticleExplosion:getStartSpinVar() end 
function CCParticleExplosion:setStartSpinVar() end 
function CCParticleExplosion:getStartSpin() end 
function CCParticleExplosion:setEndSize() end 
function CCParticleExplosion:getRadialAccel() end 
function CCParticleExplosion:getPosVar() end 
function CCParticleExplosion:getEndSize() end 
function CCParticleExplosion:getLifeVar() end 
function CCParticleExplosion:getPositionType() end 
function CCParticleExplosion:getStartColor() end 
function CCParticleExplosion:getEndRadius() end 
function CCParticleExplosion:addParticle() end 
function CCParticleExplosion:postStep() end 
function CCParticleExplosion:setEndSizeVar() end 
function CCParticleExplosion:getDuration() end 
function CCParticleExplosion:getSpeedVar() end 
function CCParticleExplosion:initParticle() end 
function CCParticleExplosion:getAngleVar() end 
function CCParticleExplosion:getStartSize() end 
function CCParticleExplosion:setRotatePerSecond() end 
function CCParticleExplosion:setEndRadius() end 
function CCParticleExplosion:setAngleVar() end 
function CCParticleExplosion:getGravity() end 
function CCParticleExplosion:setEndColorVar() end 
function CCParticleExplosion:setAngle() end 
function CCParticleExplosion:resetSystem() end 
function CCParticleExplosion:setDuration() end 
function CCParticleExplosion:setRadialAccel() end 
function CCParticleExplosion:setStartSize() end 
function CCParticleExplosion:setScaleY() end 
function CCParticleExplosion:new() end 
function CCParticleExplosion:postStep() end 
---
-- @return @class CCParticleExplosion
--
function CCParticleExplosion:create() end 
function CCParticleExplosion:setTextureWithRect() end 
function CCParticleExplosion:setTotalParticles() end 
function CCParticleExplosion:new_local() end 
function CCParticleExplosion:setBatchNode() end 
function CCParticleExplosion:updateQuadWithParticle() end 
function CCParticleExplosion:setTexture() end 
function CCParticleExplosion:setDisplayFrame() end 
---
-- @return @class CCParticleExplosion
--
function CCParticleExplosion:create() end 
