---@classdef CCParticleFireworks
CCParticleFireworks = {}
function CCParticleFireworks:autorelease() end 
function CCParticleFireworks:retain() end 
function CCParticleFireworks:retainCount() end 
function CCParticleFireworks:isEqual() end 
function CCParticleFireworks:copy() end 
function CCParticleFireworks:release() end 
function CCParticleFireworks:isSingleReference() end 
function CCParticleFireworks:visit() end 
function CCParticleFireworks:getUserObject() end 
function CCParticleFireworks:getSkewY() end 
function CCParticleFireworks:convertTouchToNodeSpace() end 
function CCParticleFireworks:getVertexZ() end 
function CCParticleFireworks:setParent() end 
function CCParticleFireworks:boundingBox() end 
function CCParticleFireworks:setVisible() end 
function CCParticleFireworks:stopActionByTag() end 
function CCParticleFireworks:getScaleY() end 
function CCParticleFireworks:setScaleX() end 
function CCParticleFireworks:reorderChild() end 
function CCParticleFireworks:setPositionX() end 
function CCParticleFireworks:removeFromParentAndCleanup() end 
function CCParticleFireworks:setTag() end 
function CCParticleFireworks:getChildrenCount() end 
function CCParticleFireworks:setScale() end 
function CCParticleFireworks:addChild() end 
function CCParticleFireworks:isVisible() end 
function CCParticleFireworks:setActionManager() end 
function CCParticleFireworks:setScheduler() end 
function CCParticleFireworks:getContentSize() end 
function CCParticleFireworks:getAnchorPoint() end 
function CCParticleFireworks:getTag() end 
function CCParticleFireworks:setGrid() end 
function CCParticleFireworks:convertToWorldSpace() end 
function CCParticleFireworks:setSkewX() end 
function CCParticleFireworks:setZOrder() end 
function CCParticleFireworks:worldToNodeTransform() end 
function CCParticleFireworks:getPosition() end 
function CCParticleFireworks:getSkewX() end 
function CCParticleFireworks:getScheduler() end 
function CCParticleFireworks:ignoreAnchorPointForPosition() end 
function CCParticleFireworks:setPosition() end 
function CCParticleFireworks:getParent() end 
function CCParticleFireworks:unscheduleUpdate() end 
function CCParticleFireworks:scheduleUpdateWithPriorityLua() end 
function CCParticleFireworks:removeChildByTag() end 
function CCParticleFireworks:convertToNodeSpaceAR() end 
function CCParticleFireworks:convertTouchToNodeSpaceAR() end 
function CCParticleFireworks:convertToWorldSpaceAR() end 
function CCParticleFireworks:setRotation() end 
function CCParticleFireworks:getComponent() end 
function CCParticleFireworks:convertToNodeSpace() end 
---
-- @return @class CCParticleFireworks
--
function CCParticleFireworks:create() end 
function CCParticleFireworks:getScale() end 
function CCParticleFireworks:getPositionY() end 
function CCParticleFireworks:getChildByTag() end 
function CCParticleFireworks:setContentSize() end 
function CCParticleFireworks:description() end 
function CCParticleFireworks:cleanup() end 
function CCParticleFireworks:getRotation() end 
function CCParticleFireworks:nodeToParentTransform() end 
function CCParticleFireworks:stopAction() end 
function CCParticleFireworks:numberOfRunningActions() end 
function CCParticleFireworks:removeAllChildren() end 
function CCParticleFireworks:runAction() end 
function CCParticleFireworks:setUserObject() end 
function CCParticleFireworks:parentToNodeTransform() end 
function CCParticleFireworks:removeChild() end 
function CCParticleFireworks:getAnchorPointInPoints() end 
function CCParticleFireworks:getScaleX() end 
function CCParticleFireworks:transform() end 
function CCParticleFireworks:getActionManager() end 
function CCParticleFireworks:draw() end 
function CCParticleFireworks:setScaleY() end 
function CCParticleFireworks:unregisterScriptHandler() end 
function CCParticleFireworks:setVertexZ() end 
function CCParticleFireworks:setAnchorPoint() end 
function CCParticleFireworks:getShaderProgram() end 
function CCParticleFireworks:stopAllActions() end 
function CCParticleFireworks:setUserData() end 
function CCParticleFireworks:setShaderProgram() end 
function CCParticleFireworks:getActionByTag() end 
function CCParticleFireworks:getGLServerState() end 
function CCParticleFireworks:getOrderOfArrival() end 
function CCParticleFireworks:getPositionX() end 
function CCParticleFireworks:setGLServerState() end 
function CCParticleFireworks:setSkewY() end 
function CCParticleFireworks:setOrderOfArrival() end 
function CCParticleFireworks:nodeToWorldTransform() end 
function CCParticleFireworks:getChildren() end 
function CCParticleFireworks:transformAncestors() end 
function CCParticleFireworks:getGrid() end 
function CCParticleFireworks:isRunning() end 
function CCParticleFireworks:registerScriptHandler() end 
function CCParticleFireworks:getCamera() end 
function CCParticleFireworks:isIgnoreAnchorPointForPosition() end 
function CCParticleFireworks:getUserData() end 
function CCParticleFireworks:setPositionY() end 
function CCParticleFireworks:getZOrder() end 
function CCParticleFireworks:setRadialAccelVar() end 
function CCParticleFireworks:getRotatePerSecond() end 
function CCParticleFireworks:getBlendFunc() end 
function CCParticleFireworks:getEndColorVar() end 
function CCParticleFireworks:setPosVar() end 
function CCParticleFireworks:getEmitterMode() end 
function CCParticleFireworks:setRotatePerSecondVar() end 
function CCParticleFireworks:getStartColorVar() end 
function CCParticleFireworks:getEndSizeVar() end 
function CCParticleFireworks:getEndRadiusVar() end 
function CCParticleFireworks:setTangentialAccel() end 
function CCParticleFireworks:getStartRadiusVar() end 
function CCParticleFireworks:getSourcePosition() end 
function CCParticleFireworks:isFull() end 
function CCParticleFireworks:setEmitterMode() end 
function CCParticleFireworks:setEmissionRate() end 
function CCParticleFireworks:getTexture() end 
function CCParticleFireworks:setTexture() end 
function CCParticleFireworks:setScaleX() end 
function CCParticleFireworks:getRadialAccelVar() end 
function CCParticleFireworks:isAutoRemoveOnFinish() end 
function CCParticleFireworks:getEndColor() end 
function CCParticleFireworks:setPositionType() end 
function CCParticleFireworks:getRotatePerSecondVar() end 
function CCParticleFireworks:setStartColorVar() end 
function CCParticleFireworks:setBlendAdditive() end 
function CCParticleFireworks:getTangentialAccel() end 
function CCParticleFireworks:setStartRadiusVar() end 
function CCParticleFireworks:setLife() end 
function CCParticleFireworks:getParticleCount() end 
function CCParticleFireworks:setSourcePosition() end 
function CCParticleFireworks:setScale() end 
function CCParticleFireworks:setBatchNode() end 
function CCParticleFireworks:setEndColor() end 
function CCParticleFireworks:isBlendAdditive() end 
function CCParticleFireworks:isActive() end 
function CCParticleFireworks:setGravity() end 
function CCParticleFireworks:stopSystem() end 
function CCParticleFireworks:getTangentialAccelVar() end 
function CCParticleFireworks:initWithTotalParticles() end 
function CCParticleFireworks:setBlendFunc() end 
function CCParticleFireworks:setSpeed() end 
function CCParticleFireworks:getStartRadius() end 
function CCParticleFireworks:getBatchNode() end 
function CCParticleFireworks:setLifeVar() end 
function CCParticleFireworks:setRotation() end 
function CCParticleFireworks:setStartRadius() end 
function CCParticleFireworks:setEndRadiusVar() end 
---
-- @return @class CCParticleFireworks
--
function CCParticleFireworks:create() end 
function CCParticleFireworks:setAutoRemoveOnFinish() end 
function CCParticleFireworks:setStartSpin() end 
function CCParticleFireworks:setEndSpin() end 
function CCParticleFireworks:getStartSizeVar() end 
function CCParticleFireworks:initWithFile() end 
function CCParticleFireworks:setStartColor() end 
function CCParticleFireworks:setStartSizeVar() end 
function CCParticleFireworks:setTangentialAccelVar() end 
function CCParticleFireworks:getLife() end 
function CCParticleFireworks:getTotalParticles() end 
function CCParticleFireworks:getSpeed() end 
function CCParticleFireworks:getEmissionRate() end 
function CCParticleFireworks:getEndSpinVar() end 
function CCParticleFireworks:setEndSpinVar() end 
function CCParticleFireworks:getEndSpin() end 
function CCParticleFireworks:getAngle() end 
function CCParticleFireworks:updateQuadWithParticle() end 
function CCParticleFireworks:setSpeedVar() end 
function CCParticleFireworks:getStartSpinVar() end 
function CCParticleFireworks:setStartSpinVar() end 
function CCParticleFireworks:getStartSpin() end 
function CCParticleFireworks:setEndSize() end 
function CCParticleFireworks:getRadialAccel() end 
function CCParticleFireworks:getPosVar() end 
function CCParticleFireworks:getEndSize() end 
function CCParticleFireworks:getLifeVar() end 
function CCParticleFireworks:getPositionType() end 
function CCParticleFireworks:getStartColor() end 
function CCParticleFireworks:getEndRadius() end 
function CCParticleFireworks:addParticle() end 
function CCParticleFireworks:postStep() end 
function CCParticleFireworks:setEndSizeVar() end 
function CCParticleFireworks:getDuration() end 
function CCParticleFireworks:getSpeedVar() end 
function CCParticleFireworks:initParticle() end 
function CCParticleFireworks:getAngleVar() end 
function CCParticleFireworks:getStartSize() end 
function CCParticleFireworks:setRotatePerSecond() end 
function CCParticleFireworks:setEndRadius() end 
function CCParticleFireworks:setAngleVar() end 
function CCParticleFireworks:getGravity() end 
function CCParticleFireworks:setEndColorVar() end 
function CCParticleFireworks:setAngle() end 
function CCParticleFireworks:resetSystem() end 
function CCParticleFireworks:setDuration() end 
function CCParticleFireworks:setRadialAccel() end 
function CCParticleFireworks:setStartSize() end 
function CCParticleFireworks:setScaleY() end 
function CCParticleFireworks:new() end 
function CCParticleFireworks:postStep() end 
---
-- @return @class CCParticleFireworks
--
function CCParticleFireworks:create() end 
function CCParticleFireworks:setTextureWithRect() end 
function CCParticleFireworks:setTotalParticles() end 
function CCParticleFireworks:new_local() end 
function CCParticleFireworks:setBatchNode() end 
function CCParticleFireworks:updateQuadWithParticle() end 
function CCParticleFireworks:setTexture() end 
function CCParticleFireworks:setDisplayFrame() end 
---
-- @return @class CCParticleFireworks
--
function CCParticleFireworks:create() end 
