---@classdef CCParticleSnow
CCParticleSnow = {}
function CCParticleSnow:autorelease() end 
function CCParticleSnow:retain() end 
function CCParticleSnow:retainCount() end 
function CCParticleSnow:isEqual() end 
function CCParticleSnow:copy() end 
function CCParticleSnow:release() end 
function CCParticleSnow:isSingleReference() end 
function CCParticleSnow:visit() end 
function CCParticleSnow:getUserObject() end 
function CCParticleSnow:getSkewY() end 
function CCParticleSnow:convertTouchToNodeSpace() end 
function CCParticleSnow:getVertexZ() end 
function CCParticleSnow:setParent() end 
function CCParticleSnow:boundingBox() end 
function CCParticleSnow:setVisible() end 
function CCParticleSnow:stopActionByTag() end 
function CCParticleSnow:getScaleY() end 
function CCParticleSnow:setScaleX() end 
function CCParticleSnow:reorderChild() end 
function CCParticleSnow:setPositionX() end 
function CCParticleSnow:removeFromParentAndCleanup() end 
function CCParticleSnow:setTag() end 
function CCParticleSnow:getChildrenCount() end 
function CCParticleSnow:setScale() end 
function CCParticleSnow:addChild() end 
function CCParticleSnow:isVisible() end 
function CCParticleSnow:setActionManager() end 
function CCParticleSnow:setScheduler() end 
function CCParticleSnow:getContentSize() end 
function CCParticleSnow:getAnchorPoint() end 
function CCParticleSnow:getTag() end 
function CCParticleSnow:setGrid() end 
function CCParticleSnow:convertToWorldSpace() end 
function CCParticleSnow:setSkewX() end 
function CCParticleSnow:setZOrder() end 
function CCParticleSnow:worldToNodeTransform() end 
function CCParticleSnow:getPosition() end 
function CCParticleSnow:getSkewX() end 
function CCParticleSnow:getScheduler() end 
function CCParticleSnow:ignoreAnchorPointForPosition() end 
function CCParticleSnow:setPosition() end 
function CCParticleSnow:getParent() end 
function CCParticleSnow:unscheduleUpdate() end 
function CCParticleSnow:scheduleUpdateWithPriorityLua() end 
function CCParticleSnow:removeChildByTag() end 
function CCParticleSnow:convertToNodeSpaceAR() end 
function CCParticleSnow:convertTouchToNodeSpaceAR() end 
function CCParticleSnow:convertToWorldSpaceAR() end 
function CCParticleSnow:setRotation() end 
function CCParticleSnow:getComponent() end 
function CCParticleSnow:convertToNodeSpace() end 
---
-- @return @class CCParticleSnow
--
function CCParticleSnow:create() end 
function CCParticleSnow:getScale() end 
function CCParticleSnow:getPositionY() end 
function CCParticleSnow:getChildByTag() end 
function CCParticleSnow:setContentSize() end 
function CCParticleSnow:description() end 
function CCParticleSnow:cleanup() end 
function CCParticleSnow:getRotation() end 
function CCParticleSnow:nodeToParentTransform() end 
function CCParticleSnow:stopAction() end 
function CCParticleSnow:numberOfRunningActions() end 
function CCParticleSnow:removeAllChildren() end 
function CCParticleSnow:runAction() end 
function CCParticleSnow:setUserObject() end 
function CCParticleSnow:parentToNodeTransform() end 
function CCParticleSnow:removeChild() end 
function CCParticleSnow:getAnchorPointInPoints() end 
function CCParticleSnow:getScaleX() end 
function CCParticleSnow:transform() end 
function CCParticleSnow:getActionManager() end 
function CCParticleSnow:draw() end 
function CCParticleSnow:setScaleY() end 
function CCParticleSnow:unregisterScriptHandler() end 
function CCParticleSnow:setVertexZ() end 
function CCParticleSnow:setAnchorPoint() end 
function CCParticleSnow:getShaderProgram() end 
function CCParticleSnow:stopAllActions() end 
function CCParticleSnow:setUserData() end 
function CCParticleSnow:setShaderProgram() end 
function CCParticleSnow:getActionByTag() end 
function CCParticleSnow:getGLServerState() end 
function CCParticleSnow:getOrderOfArrival() end 
function CCParticleSnow:getPositionX() end 
function CCParticleSnow:setGLServerState() end 
function CCParticleSnow:setSkewY() end 
function CCParticleSnow:setOrderOfArrival() end 
function CCParticleSnow:nodeToWorldTransform() end 
function CCParticleSnow:getChildren() end 
function CCParticleSnow:transformAncestors() end 
function CCParticleSnow:getGrid() end 
function CCParticleSnow:isRunning() end 
function CCParticleSnow:registerScriptHandler() end 
function CCParticleSnow:getCamera() end 
function CCParticleSnow:isIgnoreAnchorPointForPosition() end 
function CCParticleSnow:getUserData() end 
function CCParticleSnow:setPositionY() end 
function CCParticleSnow:getZOrder() end 
function CCParticleSnow:setRadialAccelVar() end 
function CCParticleSnow:getRotatePerSecond() end 
function CCParticleSnow:getBlendFunc() end 
function CCParticleSnow:getEndColorVar() end 
function CCParticleSnow:setPosVar() end 
function CCParticleSnow:getEmitterMode() end 
function CCParticleSnow:setRotatePerSecondVar() end 
function CCParticleSnow:getStartColorVar() end 
function CCParticleSnow:getEndSizeVar() end 
function CCParticleSnow:getEndRadiusVar() end 
function CCParticleSnow:setTangentialAccel() end 
function CCParticleSnow:getStartRadiusVar() end 
function CCParticleSnow:getSourcePosition() end 
function CCParticleSnow:isFull() end 
function CCParticleSnow:setEmitterMode() end 
function CCParticleSnow:setEmissionRate() end 
function CCParticleSnow:getTexture() end 
function CCParticleSnow:setTexture() end 
function CCParticleSnow:setScaleX() end 
function CCParticleSnow:getRadialAccelVar() end 
function CCParticleSnow:isAutoRemoveOnFinish() end 
function CCParticleSnow:getEndColor() end 
function CCParticleSnow:setPositionType() end 
function CCParticleSnow:getRotatePerSecondVar() end 
function CCParticleSnow:setStartColorVar() end 
function CCParticleSnow:setBlendAdditive() end 
function CCParticleSnow:getTangentialAccel() end 
function CCParticleSnow:setStartRadiusVar() end 
function CCParticleSnow:setLife() end 
function CCParticleSnow:getParticleCount() end 
function CCParticleSnow:setSourcePosition() end 
function CCParticleSnow:setScale() end 
function CCParticleSnow:setBatchNode() end 
function CCParticleSnow:setEndColor() end 
function CCParticleSnow:isBlendAdditive() end 
function CCParticleSnow:isActive() end 
function CCParticleSnow:setGravity() end 
function CCParticleSnow:stopSystem() end 
function CCParticleSnow:getTangentialAccelVar() end 
function CCParticleSnow:initWithTotalParticles() end 
function CCParticleSnow:setBlendFunc() end 
function CCParticleSnow:setSpeed() end 
function CCParticleSnow:getStartRadius() end 
function CCParticleSnow:getBatchNode() end 
function CCParticleSnow:setLifeVar() end 
function CCParticleSnow:setRotation() end 
function CCParticleSnow:setStartRadius() end 
function CCParticleSnow:setEndRadiusVar() end 
---
-- @return @class CCParticleSnow
--
function CCParticleSnow:create() end 
function CCParticleSnow:setAutoRemoveOnFinish() end 
function CCParticleSnow:setStartSpin() end 
function CCParticleSnow:setEndSpin() end 
function CCParticleSnow:getStartSizeVar() end 
function CCParticleSnow:initWithFile() end 
function CCParticleSnow:setStartColor() end 
function CCParticleSnow:setStartSizeVar() end 
function CCParticleSnow:setTangentialAccelVar() end 
function CCParticleSnow:getLife() end 
function CCParticleSnow:getTotalParticles() end 
function CCParticleSnow:getSpeed() end 
function CCParticleSnow:getEmissionRate() end 
function CCParticleSnow:getEndSpinVar() end 
function CCParticleSnow:setEndSpinVar() end 
function CCParticleSnow:getEndSpin() end 
function CCParticleSnow:getAngle() end 
function CCParticleSnow:updateQuadWithParticle() end 
function CCParticleSnow:setSpeedVar() end 
function CCParticleSnow:getStartSpinVar() end 
function CCParticleSnow:setStartSpinVar() end 
function CCParticleSnow:getStartSpin() end 
function CCParticleSnow:setEndSize() end 
function CCParticleSnow:getRadialAccel() end 
function CCParticleSnow:getPosVar() end 
function CCParticleSnow:getEndSize() end 
function CCParticleSnow:getLifeVar() end 
function CCParticleSnow:getPositionType() end 
function CCParticleSnow:getStartColor() end 
function CCParticleSnow:getEndRadius() end 
function CCParticleSnow:addParticle() end 
function CCParticleSnow:postStep() end 
function CCParticleSnow:setEndSizeVar() end 
function CCParticleSnow:getDuration() end 
function CCParticleSnow:getSpeedVar() end 
function CCParticleSnow:initParticle() end 
function CCParticleSnow:getAngleVar() end 
function CCParticleSnow:getStartSize() end 
function CCParticleSnow:setRotatePerSecond() end 
function CCParticleSnow:setEndRadius() end 
function CCParticleSnow:setAngleVar() end 
function CCParticleSnow:getGravity() end 
function CCParticleSnow:setEndColorVar() end 
function CCParticleSnow:setAngle() end 
function CCParticleSnow:resetSystem() end 
function CCParticleSnow:setDuration() end 
function CCParticleSnow:setRadialAccel() end 
function CCParticleSnow:setStartSize() end 
function CCParticleSnow:setScaleY() end 
function CCParticleSnow:new() end 
function CCParticleSnow:postStep() end 
---
-- @return @class CCParticleSnow
--
function CCParticleSnow:create() end 
function CCParticleSnow:setTextureWithRect() end 
function CCParticleSnow:setTotalParticles() end 
function CCParticleSnow:new_local() end 
function CCParticleSnow:setBatchNode() end 
function CCParticleSnow:updateQuadWithParticle() end 
function CCParticleSnow:setTexture() end 
function CCParticleSnow:setDisplayFrame() end 
---
-- @return @class CCParticleSnow
--
function CCParticleSnow:create() end 
