---@classdef CCParticleFlower
CCParticleFlower = {}
function CCParticleFlower:autorelease() end 
function CCParticleFlower:retain() end 
function CCParticleFlower:retainCount() end 
function CCParticleFlower:isEqual() end 
function CCParticleFlower:copy() end 
function CCParticleFlower:release() end 
function CCParticleFlower:isSingleReference() end 
function CCParticleFlower:visit() end 
function CCParticleFlower:getUserObject() end 
function CCParticleFlower:getSkewY() end 
function CCParticleFlower:convertTouchToNodeSpace() end 
function CCParticleFlower:getVertexZ() end 
function CCParticleFlower:setParent() end 
function CCParticleFlower:boundingBox() end 
function CCParticleFlower:setVisible() end 
function CCParticleFlower:stopActionByTag() end 
function CCParticleFlower:getScaleY() end 
function CCParticleFlower:setScaleX() end 
function CCParticleFlower:reorderChild() end 
function CCParticleFlower:setPositionX() end 
function CCParticleFlower:removeFromParentAndCleanup() end 
function CCParticleFlower:setTag() end 
function CCParticleFlower:getChildrenCount() end 
function CCParticleFlower:setScale() end 
function CCParticleFlower:addChild() end 
function CCParticleFlower:isVisible() end 
function CCParticleFlower:setActionManager() end 
function CCParticleFlower:setScheduler() end 
function CCParticleFlower:getContentSize() end 
function CCParticleFlower:getAnchorPoint() end 
function CCParticleFlower:getTag() end 
function CCParticleFlower:setGrid() end 
function CCParticleFlower:convertToWorldSpace() end 
function CCParticleFlower:setSkewX() end 
function CCParticleFlower:setZOrder() end 
function CCParticleFlower:worldToNodeTransform() end 
function CCParticleFlower:getPosition() end 
function CCParticleFlower:getSkewX() end 
function CCParticleFlower:getScheduler() end 
function CCParticleFlower:ignoreAnchorPointForPosition() end 
function CCParticleFlower:setPosition() end 
function CCParticleFlower:getParent() end 
function CCParticleFlower:unscheduleUpdate() end 
function CCParticleFlower:scheduleUpdateWithPriorityLua() end 
function CCParticleFlower:removeChildByTag() end 
function CCParticleFlower:convertToNodeSpaceAR() end 
function CCParticleFlower:convertTouchToNodeSpaceAR() end 
function CCParticleFlower:convertToWorldSpaceAR() end 
function CCParticleFlower:setRotation() end 
function CCParticleFlower:getComponent() end 
function CCParticleFlower:convertToNodeSpace() end 
---
-- @return @class CCParticleFlower
--
function CCParticleFlower:create() end 
function CCParticleFlower:getScale() end 
function CCParticleFlower:getPositionY() end 
function CCParticleFlower:getChildByTag() end 
function CCParticleFlower:setContentSize() end 
function CCParticleFlower:description() end 
function CCParticleFlower:cleanup() end 
function CCParticleFlower:getRotation() end 
function CCParticleFlower:nodeToParentTransform() end 
function CCParticleFlower:stopAction() end 
function CCParticleFlower:numberOfRunningActions() end 
function CCParticleFlower:removeAllChildren() end 
function CCParticleFlower:runAction() end 
function CCParticleFlower:setUserObject() end 
function CCParticleFlower:parentToNodeTransform() end 
function CCParticleFlower:removeChild() end 
function CCParticleFlower:getAnchorPointInPoints() end 
function CCParticleFlower:getScaleX() end 
function CCParticleFlower:transform() end 
function CCParticleFlower:getActionManager() end 
function CCParticleFlower:draw() end 
function CCParticleFlower:setScaleY() end 
function CCParticleFlower:unregisterScriptHandler() end 
function CCParticleFlower:setVertexZ() end 
function CCParticleFlower:setAnchorPoint() end 
function CCParticleFlower:getShaderProgram() end 
function CCParticleFlower:stopAllActions() end 
function CCParticleFlower:setUserData() end 
function CCParticleFlower:setShaderProgram() end 
function CCParticleFlower:getActionByTag() end 
function CCParticleFlower:getGLServerState() end 
function CCParticleFlower:getOrderOfArrival() end 
function CCParticleFlower:getPositionX() end 
function CCParticleFlower:setGLServerState() end 
function CCParticleFlower:setSkewY() end 
function CCParticleFlower:setOrderOfArrival() end 
function CCParticleFlower:nodeToWorldTransform() end 
function CCParticleFlower:getChildren() end 
function CCParticleFlower:transformAncestors() end 
function CCParticleFlower:getGrid() end 
function CCParticleFlower:isRunning() end 
function CCParticleFlower:registerScriptHandler() end 
function CCParticleFlower:getCamera() end 
function CCParticleFlower:isIgnoreAnchorPointForPosition() end 
function CCParticleFlower:getUserData() end 
function CCParticleFlower:setPositionY() end 
function CCParticleFlower:getZOrder() end 
function CCParticleFlower:setRadialAccelVar() end 
function CCParticleFlower:getRotatePerSecond() end 
function CCParticleFlower:getBlendFunc() end 
function CCParticleFlower:getEndColorVar() end 
function CCParticleFlower:setPosVar() end 
function CCParticleFlower:getEmitterMode() end 
function CCParticleFlower:setRotatePerSecondVar() end 
function CCParticleFlower:getStartColorVar() end 
function CCParticleFlower:getEndSizeVar() end 
function CCParticleFlower:getEndRadiusVar() end 
function CCParticleFlower:setTangentialAccel() end 
function CCParticleFlower:getStartRadiusVar() end 
function CCParticleFlower:getSourcePosition() end 
function CCParticleFlower:isFull() end 
function CCParticleFlower:setEmitterMode() end 
function CCParticleFlower:setEmissionRate() end 
function CCParticleFlower:getTexture() end 
function CCParticleFlower:setTexture() end 
function CCParticleFlower:setScaleX() end 
function CCParticleFlower:getRadialAccelVar() end 
function CCParticleFlower:isAutoRemoveOnFinish() end 
function CCParticleFlower:getEndColor() end 
function CCParticleFlower:setPositionType() end 
function CCParticleFlower:getRotatePerSecondVar() end 
function CCParticleFlower:setStartColorVar() end 
function CCParticleFlower:setBlendAdditive() end 
function CCParticleFlower:getTangentialAccel() end 
function CCParticleFlower:setStartRadiusVar() end 
function CCParticleFlower:setLife() end 
function CCParticleFlower:getParticleCount() end 
function CCParticleFlower:setSourcePosition() end 
function CCParticleFlower:setScale() end 
function CCParticleFlower:setBatchNode() end 
function CCParticleFlower:setEndColor() end 
function CCParticleFlower:isBlendAdditive() end 
function CCParticleFlower:isActive() end 
function CCParticleFlower:setGravity() end 
function CCParticleFlower:stopSystem() end 
function CCParticleFlower:getTangentialAccelVar() end 
function CCParticleFlower:initWithTotalParticles() end 
function CCParticleFlower:setBlendFunc() end 
function CCParticleFlower:setSpeed() end 
function CCParticleFlower:getStartRadius() end 
function CCParticleFlower:getBatchNode() end 
function CCParticleFlower:setLifeVar() end 
function CCParticleFlower:setRotation() end 
function CCParticleFlower:setStartRadius() end 
function CCParticleFlower:setEndRadiusVar() end 
---
-- @return @class CCParticleFlower
--
function CCParticleFlower:create() end 
function CCParticleFlower:setAutoRemoveOnFinish() end 
function CCParticleFlower:setStartSpin() end 
function CCParticleFlower:setEndSpin() end 
function CCParticleFlower:getStartSizeVar() end 
function CCParticleFlower:initWithFile() end 
function CCParticleFlower:setStartColor() end 
function CCParticleFlower:setStartSizeVar() end 
function CCParticleFlower:setTangentialAccelVar() end 
function CCParticleFlower:getLife() end 
function CCParticleFlower:getTotalParticles() end 
function CCParticleFlower:getSpeed() end 
function CCParticleFlower:getEmissionRate() end 
function CCParticleFlower:getEndSpinVar() end 
function CCParticleFlower:setEndSpinVar() end 
function CCParticleFlower:getEndSpin() end 
function CCParticleFlower:getAngle() end 
function CCParticleFlower:updateQuadWithParticle() end 
function CCParticleFlower:setSpeedVar() end 
function CCParticleFlower:getStartSpinVar() end 
function CCParticleFlower:setStartSpinVar() end 
function CCParticleFlower:getStartSpin() end 
function CCParticleFlower:setEndSize() end 
function CCParticleFlower:getRadialAccel() end 
function CCParticleFlower:getPosVar() end 
function CCParticleFlower:getEndSize() end 
function CCParticleFlower:getLifeVar() end 
function CCParticleFlower:getPositionType() end 
function CCParticleFlower:getStartColor() end 
function CCParticleFlower:getEndRadius() end 
function CCParticleFlower:addParticle() end 
function CCParticleFlower:postStep() end 
function CCParticleFlower:setEndSizeVar() end 
function CCParticleFlower:getDuration() end 
function CCParticleFlower:getSpeedVar() end 
function CCParticleFlower:initParticle() end 
function CCParticleFlower:getAngleVar() end 
function CCParticleFlower:getStartSize() end 
function CCParticleFlower:setRotatePerSecond() end 
function CCParticleFlower:setEndRadius() end 
function CCParticleFlower:setAngleVar() end 
function CCParticleFlower:getGravity() end 
function CCParticleFlower:setEndColorVar() end 
function CCParticleFlower:setAngle() end 
function CCParticleFlower:resetSystem() end 
function CCParticleFlower:setDuration() end 
function CCParticleFlower:setRadialAccel() end 
function CCParticleFlower:setStartSize() end 
function CCParticleFlower:setScaleY() end 
function CCParticleFlower:new() end 
function CCParticleFlower:postStep() end 
---
-- @return @class CCParticleFlower
--
function CCParticleFlower:create() end 
function CCParticleFlower:setTextureWithRect() end 
function CCParticleFlower:setTotalParticles() end 
function CCParticleFlower:new_local() end 
function CCParticleFlower:setBatchNode() end 
function CCParticleFlower:updateQuadWithParticle() end 
function CCParticleFlower:setTexture() end 
function CCParticleFlower:setDisplayFrame() end 
---
-- @return @class CCParticleFlower
--
function CCParticleFlower:create() end 
