---@classdef CCParallaxNode
CCParallaxNode = {}
function CCParallaxNode:autorelease() end 
function CCParallaxNode:retain() end 
function CCParallaxNode:retainCount() end 
function CCParallaxNode:isEqual() end 
function CCParallaxNode:copy() end 
function CCParallaxNode:release() end 
function CCParallaxNode:isSingleReference() end 
function CCParallaxNode:visit() end 
function CCParallaxNode:getUserObject() end 
function CCParallaxNode:getSkewY() end 
function CCParallaxNode:convertTouchToNodeSpace() end 
function CCParallaxNode:getVertexZ() end 
function CCParallaxNode:setParent() end 
function CCParallaxNode:boundingBox() end 
function CCParallaxNode:setVisible() end 
function CCParallaxNode:stopActionByTag() end 
function CCParallaxNode:getScaleY() end 
function CCParallaxNode:setScaleX() end 
function CCParallaxNode:reorderChild() end 
function CCParallaxNode:setPositionX() end 
function CCParallaxNode:removeFromParentAndCleanup() end 
function CCParallaxNode:setTag() end 
function CCParallaxNode:getChildrenCount() end 
function CCParallaxNode:setScale() end 
function CCParallaxNode:addChild() end 
function CCParallaxNode:isVisible() end 
function CCParallaxNode:setActionManager() end 
function CCParallaxNode:setScheduler() end 
function CCParallaxNode:getContentSize() end 
function CCParallaxNode:getAnchorPoint() end 
function CCParallaxNode:getTag() end 
function CCParallaxNode:setGrid() end 
function CCParallaxNode:convertToWorldSpace() end 
function CCParallaxNode:setSkewX() end 
function CCParallaxNode:setZOrder() end 
function CCParallaxNode:worldToNodeTransform() end 
function CCParallaxNode:getPosition() end 
function CCParallaxNode:getSkewX() end 
function CCParallaxNode:getScheduler() end 
function CCParallaxNode:ignoreAnchorPointForPosition() end 
function CCParallaxNode:setPosition() end 
function CCParallaxNode:getParent() end 
function CCParallaxNode:unscheduleUpdate() end 
function CCParallaxNode:scheduleUpdateWithPriorityLua() end 
function CCParallaxNode:removeChildByTag() end 
function CCParallaxNode:convertToNodeSpaceAR() end 
function CCParallaxNode:convertTouchToNodeSpaceAR() end 
function CCParallaxNode:convertToWorldSpaceAR() end 
function CCParallaxNode:setRotation() end 
function CCParallaxNode:getComponent() end 
function CCParallaxNode:convertToNodeSpace() end 
---
-- @return @class CCParallaxNode
--
function CCParallaxNode:create() end 
function CCParallaxNode:getScale() end 
function CCParallaxNode:getPositionY() end 
function CCParallaxNode:getChildByTag() end 
function CCParallaxNode:setContentSize() end 
function CCParallaxNode:description() end 
function CCParallaxNode:cleanup() end 
function CCParallaxNode:getRotation() end 
function CCParallaxNode:nodeToParentTransform() end 
function CCParallaxNode:stopAction() end 
function CCParallaxNode:numberOfRunningActions() end 
function CCParallaxNode:removeAllChildren() end 
function CCParallaxNode:runAction() end 
function CCParallaxNode:setUserObject() end 
function CCParallaxNode:parentToNodeTransform() end 
function CCParallaxNode:removeChild() end 
function CCParallaxNode:getAnchorPointInPoints() end 
function CCParallaxNode:getScaleX() end 
function CCParallaxNode:transform() end 
function CCParallaxNode:getActionManager() end 
function CCParallaxNode:draw() end 
function CCParallaxNode:setScaleY() end 
function CCParallaxNode:unregisterScriptHandler() end 
function CCParallaxNode:setVertexZ() end 
function CCParallaxNode:setAnchorPoint() end 
function CCParallaxNode:getShaderProgram() end 
function CCParallaxNode:stopAllActions() end 
function CCParallaxNode:setUserData() end 
function CCParallaxNode:setShaderProgram() end 
function CCParallaxNode:getActionByTag() end 
function CCParallaxNode:getGLServerState() end 
function CCParallaxNode:getOrderOfArrival() end 
function CCParallaxNode:getPositionX() end 
function CCParallaxNode:setGLServerState() end 
function CCParallaxNode:setSkewY() end 
function CCParallaxNode:setOrderOfArrival() end 
function CCParallaxNode:nodeToWorldTransform() end 
function CCParallaxNode:getChildren() end 
function CCParallaxNode:transformAncestors() end 
function CCParallaxNode:getGrid() end 
function CCParallaxNode:isRunning() end 
function CCParallaxNode:registerScriptHandler() end 
function CCParallaxNode:getCamera() end 
function CCParallaxNode:isIgnoreAnchorPointForPosition() end 
function CCParallaxNode:getUserData() end 
function CCParallaxNode:setPositionY() end 
function CCParallaxNode:getZOrder() end 
function CCParallaxNode:addChild() end 
---
-- @return @class CCParallaxNode
--
function CCParallaxNode:create() end 
function CCParallaxNode:removeAllChildren() end 
function CCParallaxNode:removeChild() end 
function CCParallaxNode:visit() end 
