---@classdef CCParticleFire
CCParticleFire = {}
function CCParticleFire:autorelease() end 
function CCParticleFire:retain() end 
function CCParticleFire:retainCount() end 
function CCParticleFire:isEqual() end 
function CCParticleFire:copy() end 
function CCParticleFire:release() end 
function CCParticleFire:isSingleReference() end 
function CCParticleFire:visit() end 
function CCParticleFire:getUserObject() end 
function CCParticleFire:getSkewY() end 
function CCParticleFire:convertTouchToNodeSpace() end 
function CCParticleFire:getVertexZ() end 
function CCParticleFire:setParent() end 
function CCParticleFire:boundingBox() end 
function CCParticleFire:setVisible() end 
function CCParticleFire:stopActionByTag() end 
function CCParticleFire:getScaleY() end 
function CCParticleFire:setScaleX() end 
function CCParticleFire:reorderChild() end 
function CCParticleFire:setPositionX() end 
function CCParticleFire:removeFromParentAndCleanup() end 
function CCParticleFire:setTag() end 
function CCParticleFire:getChildrenCount() end 
function CCParticleFire:setScale() end 
function CCParticleFire:addChild() end 
function CCParticleFire:isVisible() end 
function CCParticleFire:setActionManager() end 
function CCParticleFire:setScheduler() end 
function CCParticleFire:getContentSize() end 
function CCParticleFire:getAnchorPoint() end 
function CCParticleFire:getTag() end 
function CCParticleFire:setGrid() end 
function CCParticleFire:convertToWorldSpace() end 
function CCParticleFire:setSkewX() end 
function CCParticleFire:setZOrder() end 
function CCParticleFire:worldToNodeTransform() end 
function CCParticleFire:getPosition() end 
function CCParticleFire:getSkewX() end 
function CCParticleFire:getScheduler() end 
function CCParticleFire:ignoreAnchorPointForPosition() end 
function CCParticleFire:setPosition() end 
function CCParticleFire:getParent() end 
function CCParticleFire:unscheduleUpdate() end 
function CCParticleFire:scheduleUpdateWithPriorityLua() end 
function CCParticleFire:removeChildByTag() end 
function CCParticleFire:convertToNodeSpaceAR() end 
function CCParticleFire:convertTouchToNodeSpaceAR() end 
function CCParticleFire:convertToWorldSpaceAR() end 
function CCParticleFire:setRotation() end 
function CCParticleFire:getComponent() end 
function CCParticleFire:convertToNodeSpace() end 
---
-- @return @class CCParticleFire
--
function CCParticleFire:create() end 
function CCParticleFire:getScale() end 
function CCParticleFire:getPositionY() end 
function CCParticleFire:getChildByTag() end 
function CCParticleFire:setContentSize() end 
function CCParticleFire:description() end 
function CCParticleFire:cleanup() end 
function CCParticleFire:getRotation() end 
function CCParticleFire:nodeToParentTransform() end 
function CCParticleFire:stopAction() end 
function CCParticleFire:numberOfRunningActions() end 
function CCParticleFire:removeAllChildren() end 
function CCParticleFire:runAction() end 
function CCParticleFire:setUserObject() end 
function CCParticleFire:parentToNodeTransform() end 
function CCParticleFire:removeChild() end 
function CCParticleFire:getAnchorPointInPoints() end 
function CCParticleFire:getScaleX() end 
function CCParticleFire:transform() end 
function CCParticleFire:getActionManager() end 
function CCParticleFire:draw() end 
function CCParticleFire:setScaleY() end 
function CCParticleFire:unregisterScriptHandler() end 
function CCParticleFire:setVertexZ() end 
function CCParticleFire:setAnchorPoint() end 
function CCParticleFire:getShaderProgram() end 
function CCParticleFire:stopAllActions() end 
function CCParticleFire:setUserData() end 
function CCParticleFire:setShaderProgram() end 
function CCParticleFire:getActionByTag() end 
function CCParticleFire:getGLServerState() end 
function CCParticleFire:getOrderOfArrival() end 
function CCParticleFire:getPositionX() end 
function CCParticleFire:setGLServerState() end 
function CCParticleFire:setSkewY() end 
function CCParticleFire:setOrderOfArrival() end 
function CCParticleFire:nodeToWorldTransform() end 
function CCParticleFire:getChildren() end 
function CCParticleFire:transformAncestors() end 
function CCParticleFire:getGrid() end 
function CCParticleFire:isRunning() end 
function CCParticleFire:registerScriptHandler() end 
function CCParticleFire:getCamera() end 
function CCParticleFire:isIgnoreAnchorPointForPosition() end 
function CCParticleFire:getUserData() end 
function CCParticleFire:setPositionY() end 
function CCParticleFire:getZOrder() end 
function CCParticleFire:setRadialAccelVar() end 
function CCParticleFire:getRotatePerSecond() end 
function CCParticleFire:getBlendFunc() end 
function CCParticleFire:getEndColorVar() end 
function CCParticleFire:setPosVar() end 
function CCParticleFire:getEmitterMode() end 
function CCParticleFire:setRotatePerSecondVar() end 
function CCParticleFire:getStartColorVar() end 
function CCParticleFire:getEndSizeVar() end 
function CCParticleFire:getEndRadiusVar() end 
function CCParticleFire:setTangentialAccel() end 
function CCParticleFire:getStartRadiusVar() end 
function CCParticleFire:getSourcePosition() end 
function CCParticleFire:isFull() end 
function CCParticleFire:setEmitterMode() end 
function CCParticleFire:setEmissionRate() end 
function CCParticleFire:getTexture() end 
function CCParticleFire:setTexture() end 
function CCParticleFire:setScaleX() end 
function CCParticleFire:getRadialAccelVar() end 
function CCParticleFire:isAutoRemoveOnFinish() end 
function CCParticleFire:getEndColor() end 
function CCParticleFire:setPositionType() end 
function CCParticleFire:getRotatePerSecondVar() end 
function CCParticleFire:setStartColorVar() end 
function CCParticleFire:setBlendAdditive() end 
function CCParticleFire:getTangentialAccel() end 
function CCParticleFire:setStartRadiusVar() end 
function CCParticleFire:setLife() end 
function CCParticleFire:getParticleCount() end 
function CCParticleFire:setSourcePosition() end 
function CCParticleFire:setScale() end 
function CCParticleFire:setBatchNode() end 
function CCParticleFire:setEndColor() end 
function CCParticleFire:isBlendAdditive() end 
function CCParticleFire:isActive() end 
function CCParticleFire:setGravity() end 
function CCParticleFire:stopSystem() end 
function CCParticleFire:getTangentialAccelVar() end 
function CCParticleFire:initWithTotalParticles() end 
function CCParticleFire:setBlendFunc() end 
function CCParticleFire:setSpeed() end 
function CCParticleFire:getStartRadius() end 
function CCParticleFire:getBatchNode() end 
function CCParticleFire:setLifeVar() end 
function CCParticleFire:setRotation() end 
function CCParticleFire:setStartRadius() end 
function CCParticleFire:setEndRadiusVar() end 
---
-- @return @class CCParticleFire
--
function CCParticleFire:create() end 
function CCParticleFire:setAutoRemoveOnFinish() end 
function CCParticleFire:setStartSpin() end 
function CCParticleFire:setEndSpin() end 
function CCParticleFire:getStartSizeVar() end 
function CCParticleFire:initWithFile() end 
function CCParticleFire:setStartColor() end 
function CCParticleFire:setStartSizeVar() end 
function CCParticleFire:setTangentialAccelVar() end 
function CCParticleFire:getLife() end 
function CCParticleFire:getTotalParticles() end 
function CCParticleFire:getSpeed() end 
function CCParticleFire:getEmissionRate() end 
function CCParticleFire:getEndSpinVar() end 
function CCParticleFire:setEndSpinVar() end 
function CCParticleFire:getEndSpin() end 
function CCParticleFire:getAngle() end 
function CCParticleFire:updateQuadWithParticle() end 
function CCParticleFire:setSpeedVar() end 
function CCParticleFire:getStartSpinVar() end 
function CCParticleFire:setStartSpinVar() end 
function CCParticleFire:getStartSpin() end 
function CCParticleFire:setEndSize() end 
function CCParticleFire:getRadialAccel() end 
function CCParticleFire:getPosVar() end 
function CCParticleFire:getEndSize() end 
function CCParticleFire:getLifeVar() end 
function CCParticleFire:getPositionType() end 
function CCParticleFire:getStartColor() end 
function CCParticleFire:getEndRadius() end 
function CCParticleFire:addParticle() end 
function CCParticleFire:postStep() end 
function CCParticleFire:setEndSizeVar() end 
function CCParticleFire:getDuration() end 
function CCParticleFire:getSpeedVar() end 
function CCParticleFire:initParticle() end 
function CCParticleFire:getAngleVar() end 
function CCParticleFire:getStartSize() end 
function CCParticleFire:setRotatePerSecond() end 
function CCParticleFire:setEndRadius() end 
function CCParticleFire:setAngleVar() end 
function CCParticleFire:getGravity() end 
function CCParticleFire:setEndColorVar() end 
function CCParticleFire:setAngle() end 
function CCParticleFire:resetSystem() end 
function CCParticleFire:setDuration() end 
function CCParticleFire:setRadialAccel() end 
function CCParticleFire:setStartSize() end 
function CCParticleFire:setScaleY() end 
function CCParticleFire:new() end 
function CCParticleFire:postStep() end 
---
-- @return @class CCParticleFire
--
function CCParticleFire:create() end 
function CCParticleFire:setTextureWithRect() end 
function CCParticleFire:setTotalParticles() end 
function CCParticleFire:new_local() end 
function CCParticleFire:setBatchNode() end 
function CCParticleFire:updateQuadWithParticle() end 
function CCParticleFire:setTexture() end 
function CCParticleFire:setDisplayFrame() end 
---
-- @return @class CCParticleFire
--
function CCParticleFire:create() end 
