---@classdef CCParticleSun
CCParticleSun = {}
function CCParticleSun:autorelease() end 
function CCParticleSun:retain() end 
function CCParticleSun:retainCount() end 
function CCParticleSun:isEqual() end 
function CCParticleSun:copy() end 
function CCParticleSun:release() end 
function CCParticleSun:isSingleReference() end 
function CCParticleSun:visit() end 
function CCParticleSun:getUserObject() end 
function CCParticleSun:getSkewY() end 
function CCParticleSun:convertTouchToNodeSpace() end 
function CCParticleSun:getVertexZ() end 
function CCParticleSun:setParent() end 
function CCParticleSun:boundingBox() end 
function CCParticleSun:setVisible() end 
function CCParticleSun:stopActionByTag() end 
function CCParticleSun:getScaleY() end 
function CCParticleSun:setScaleX() end 
function CCParticleSun:reorderChild() end 
function CCParticleSun:setPositionX() end 
function CCParticleSun:removeFromParentAndCleanup() end 
function CCParticleSun:setTag() end 
function CCParticleSun:getChildrenCount() end 
function CCParticleSun:setScale() end 
function CCParticleSun:addChild() end 
function CCParticleSun:isVisible() end 
function CCParticleSun:setActionManager() end 
function CCParticleSun:setScheduler() end 
function CCParticleSun:getContentSize() end 
function CCParticleSun:getAnchorPoint() end 
function CCParticleSun:getTag() end 
function CCParticleSun:setGrid() end 
function CCParticleSun:convertToWorldSpace() end 
function CCParticleSun:setSkewX() end 
function CCParticleSun:setZOrder() end 
function CCParticleSun:worldToNodeTransform() end 
function CCParticleSun:getPosition() end 
function CCParticleSun:getSkewX() end 
function CCParticleSun:getScheduler() end 
function CCParticleSun:ignoreAnchorPointForPosition() end 
function CCParticleSun:setPosition() end 
function CCParticleSun:getParent() end 
function CCParticleSun:unscheduleUpdate() end 
function CCParticleSun:scheduleUpdateWithPriorityLua() end 
function CCParticleSun:removeChildByTag() end 
function CCParticleSun:convertToNodeSpaceAR() end 
function CCParticleSun:convertTouchToNodeSpaceAR() end 
function CCParticleSun:convertToWorldSpaceAR() end 
function CCParticleSun:setRotation() end 
function CCParticleSun:getComponent() end 
function CCParticleSun:convertToNodeSpace() end 
---
-- @return @class CCParticleSun
--
function CCParticleSun:create() end 
function CCParticleSun:getScale() end 
function CCParticleSun:getPositionY() end 
function CCParticleSun:getChildByTag() end 
function CCParticleSun:setContentSize() end 
function CCParticleSun:description() end 
function CCParticleSun:cleanup() end 
function CCParticleSun:getRotation() end 
function CCParticleSun:nodeToParentTransform() end 
function CCParticleSun:stopAction() end 
function CCParticleSun:numberOfRunningActions() end 
function CCParticleSun:removeAllChildren() end 
function CCParticleSun:runAction() end 
function CCParticleSun:setUserObject() end 
function CCParticleSun:parentToNodeTransform() end 
function CCParticleSun:removeChild() end 
function CCParticleSun:getAnchorPointInPoints() end 
function CCParticleSun:getScaleX() end 
function CCParticleSun:transform() end 
function CCParticleSun:getActionManager() end 
function CCParticleSun:draw() end 
function CCParticleSun:setScaleY() end 
function CCParticleSun:unregisterScriptHandler() end 
function CCParticleSun:setVertexZ() end 
function CCParticleSun:setAnchorPoint() end 
function CCParticleSun:getShaderProgram() end 
function CCParticleSun:stopAllActions() end 
function CCParticleSun:setUserData() end 
function CCParticleSun:setShaderProgram() end 
function CCParticleSun:getActionByTag() end 
function CCParticleSun:getGLServerState() end 
function CCParticleSun:getOrderOfArrival() end 
function CCParticleSun:getPositionX() end 
function CCParticleSun:setGLServerState() end 
function CCParticleSun:setSkewY() end 
function CCParticleSun:setOrderOfArrival() end 
function CCParticleSun:nodeToWorldTransform() end 
function CCParticleSun:getChildren() end 
function CCParticleSun:transformAncestors() end 
function CCParticleSun:getGrid() end 
function CCParticleSun:isRunning() end 
function CCParticleSun:registerScriptHandler() end 
function CCParticleSun:getCamera() end 
function CCParticleSun:isIgnoreAnchorPointForPosition() end 
function CCParticleSun:getUserData() end 
function CCParticleSun:setPositionY() end 
function CCParticleSun:getZOrder() end 
function CCParticleSun:setRadialAccelVar() end 
function CCParticleSun:getRotatePerSecond() end 
function CCParticleSun:getBlendFunc() end 
function CCParticleSun:getEndColorVar() end 
function CCParticleSun:setPosVar() end 
function CCParticleSun:getEmitterMode() end 
function CCParticleSun:setRotatePerSecondVar() end 
function CCParticleSun:getStartColorVar() end 
function CCParticleSun:getEndSizeVar() end 
function CCParticleSun:getEndRadiusVar() end 
function CCParticleSun:setTangentialAccel() end 
function CCParticleSun:getStartRadiusVar() end 
function CCParticleSun:getSourcePosition() end 
function CCParticleSun:isFull() end 
function CCParticleSun:setEmitterMode() end 
function CCParticleSun:setEmissionRate() end 
function CCParticleSun:getTexture() end 
function CCParticleSun:setTexture() end 
function CCParticleSun:setScaleX() end 
function CCParticleSun:getRadialAccelVar() end 
function CCParticleSun:isAutoRemoveOnFinish() end 
function CCParticleSun:getEndColor() end 
function CCParticleSun:setPositionType() end 
function CCParticleSun:getRotatePerSecondVar() end 
function CCParticleSun:setStartColorVar() end 
function CCParticleSun:setBlendAdditive() end 
function CCParticleSun:getTangentialAccel() end 
function CCParticleSun:setStartRadiusVar() end 
function CCParticleSun:setLife() end 
function CCParticleSun:getParticleCount() end 
function CCParticleSun:setSourcePosition() end 
function CCParticleSun:setScale() end 
function CCParticleSun:setBatchNode() end 
function CCParticleSun:setEndColor() end 
function CCParticleSun:isBlendAdditive() end 
function CCParticleSun:isActive() end 
function CCParticleSun:setGravity() end 
function CCParticleSun:stopSystem() end 
function CCParticleSun:getTangentialAccelVar() end 
function CCParticleSun:initWithTotalParticles() end 
function CCParticleSun:setBlendFunc() end 
function CCParticleSun:setSpeed() end 
function CCParticleSun:getStartRadius() end 
function CCParticleSun:getBatchNode() end 
function CCParticleSun:setLifeVar() end 
function CCParticleSun:setRotation() end 
function CCParticleSun:setStartRadius() end 
function CCParticleSun:setEndRadiusVar() end 
---
-- @return @class CCParticleSun
--
function CCParticleSun:create() end 
function CCParticleSun:setAutoRemoveOnFinish() end 
function CCParticleSun:setStartSpin() end 
function CCParticleSun:setEndSpin() end 
function CCParticleSun:getStartSizeVar() end 
function CCParticleSun:initWithFile() end 
function CCParticleSun:setStartColor() end 
function CCParticleSun:setStartSizeVar() end 
function CCParticleSun:setTangentialAccelVar() end 
function CCParticleSun:getLife() end 
function CCParticleSun:getTotalParticles() end 
function CCParticleSun:getSpeed() end 
function CCParticleSun:getEmissionRate() end 
function CCParticleSun:getEndSpinVar() end 
function CCParticleSun:setEndSpinVar() end 
function CCParticleSun:getEndSpin() end 
function CCParticleSun:getAngle() end 
function CCParticleSun:updateQuadWithParticle() end 
function CCParticleSun:setSpeedVar() end 
function CCParticleSun:getStartSpinVar() end 
function CCParticleSun:setStartSpinVar() end 
function CCParticleSun:getStartSpin() end 
function CCParticleSun:setEndSize() end 
function CCParticleSun:getRadialAccel() end 
function CCParticleSun:getPosVar() end 
function CCParticleSun:getEndSize() end 
function CCParticleSun:getLifeVar() end 
function CCParticleSun:getPositionType() end 
function CCParticleSun:getStartColor() end 
function CCParticleSun:getEndRadius() end 
function CCParticleSun:addParticle() end 
function CCParticleSun:postStep() end 
function CCParticleSun:setEndSizeVar() end 
function CCParticleSun:getDuration() end 
function CCParticleSun:getSpeedVar() end 
function CCParticleSun:initParticle() end 
function CCParticleSun:getAngleVar() end 
function CCParticleSun:getStartSize() end 
function CCParticleSun:setRotatePerSecond() end 
function CCParticleSun:setEndRadius() end 
function CCParticleSun:setAngleVar() end 
function CCParticleSun:getGravity() end 
function CCParticleSun:setEndColorVar() end 
function CCParticleSun:setAngle() end 
function CCParticleSun:resetSystem() end 
function CCParticleSun:setDuration() end 
function CCParticleSun:setRadialAccel() end 
function CCParticleSun:setStartSize() end 
function CCParticleSun:setScaleY() end 
function CCParticleSun:new() end 
function CCParticleSun:postStep() end 
---
-- @return @class CCParticleSun
--
function CCParticleSun:create() end 
function CCParticleSun:setTextureWithRect() end 
function CCParticleSun:setTotalParticles() end 
function CCParticleSun:new_local() end 
function CCParticleSun:setBatchNode() end 
function CCParticleSun:updateQuadWithParticle() end 
function CCParticleSun:setTexture() end 
function CCParticleSun:setDisplayFrame() end 
---
-- @return @class CCParticleSun
--
function CCParticleSun:create() end 
