---@classdef CCParticleSystem
CCParticleSystem = {}
function CCParticleSystem:autorelease() end 
function CCParticleSystem:retain() end 
function CCParticleSystem:retainCount() end 
function CCParticleSystem:isEqual() end 
function CCParticleSystem:copy() end 
function CCParticleSystem:release() end 
function CCParticleSystem:isSingleReference() end 
function CCParticleSystem:visit() end 
function CCParticleSystem:getUserObject() end 
function CCParticleSystem:getSkewY() end 
function CCParticleSystem:convertTouchToNodeSpace() end 
function CCParticleSystem:getVertexZ() end 
function CCParticleSystem:setParent() end 
function CCParticleSystem:boundingBox() end 
function CCParticleSystem:setVisible() end 
function CCParticleSystem:stopActionByTag() end 
function CCParticleSystem:getScaleY() end 
function CCParticleSystem:setScaleX() end 
function CCParticleSystem:reorderChild() end 
function CCParticleSystem:setPositionX() end 
function CCParticleSystem:removeFromParentAndCleanup() end 
function CCParticleSystem:setTag() end 
function CCParticleSystem:getChildrenCount() end 
function CCParticleSystem:setScale() end 
function CCParticleSystem:addChild() end 
function CCParticleSystem:isVisible() end 
function CCParticleSystem:setActionManager() end 
function CCParticleSystem:setScheduler() end 
function CCParticleSystem:getContentSize() end 
function CCParticleSystem:getAnchorPoint() end 
function CCParticleSystem:getTag() end 
function CCParticleSystem:setGrid() end 
function CCParticleSystem:convertToWorldSpace() end 
function CCParticleSystem:setSkewX() end 
function CCParticleSystem:setZOrder() end 
function CCParticleSystem:worldToNodeTransform() end 
function CCParticleSystem:getPosition() end 
function CCParticleSystem:getSkewX() end 
function CCParticleSystem:getScheduler() end 
function CCParticleSystem:ignoreAnchorPointForPosition() end 
function CCParticleSystem:setPosition() end 
function CCParticleSystem:getParent() end 
function CCParticleSystem:unscheduleUpdate() end 
function CCParticleSystem:scheduleUpdateWithPriorityLua() end 
function CCParticleSystem:removeChildByTag() end 
function CCParticleSystem:convertToNodeSpaceAR() end 
function CCParticleSystem:convertTouchToNodeSpaceAR() end 
function CCParticleSystem:convertToWorldSpaceAR() end 
function CCParticleSystem:setRotation() end 
function CCParticleSystem:getComponent() end 
function CCParticleSystem:convertToNodeSpace() end 
---
-- @return @class CCParticleSystem
--
function CCParticleSystem:create() end 
function CCParticleSystem:getScale() end 
function CCParticleSystem:getPositionY() end 
function CCParticleSystem:getChildByTag() end 
function CCParticleSystem:setContentSize() end 
function CCParticleSystem:description() end 
function CCParticleSystem:cleanup() end 
function CCParticleSystem:getRotation() end 
function CCParticleSystem:nodeToParentTransform() end 
function CCParticleSystem:stopAction() end 
function CCParticleSystem:numberOfRunningActions() end 
function CCParticleSystem:removeAllChildren() end 
function CCParticleSystem:runAction() end 
function CCParticleSystem:setUserObject() end 
function CCParticleSystem:parentToNodeTransform() end 
function CCParticleSystem:removeChild() end 
function CCParticleSystem:getAnchorPointInPoints() end 
function CCParticleSystem:getScaleX() end 
function CCParticleSystem:transform() end 
function CCParticleSystem:getActionManager() end 
function CCParticleSystem:draw() end 
function CCParticleSystem:setScaleY() end 
function CCParticleSystem:unregisterScriptHandler() end 
function CCParticleSystem:setVertexZ() end 
function CCParticleSystem:setAnchorPoint() end 
function CCParticleSystem:getShaderProgram() end 
function CCParticleSystem:stopAllActions() end 
function CCParticleSystem:setUserData() end 
function CCParticleSystem:setShaderProgram() end 
function CCParticleSystem:getActionByTag() end 
function CCParticleSystem:getGLServerState() end 
function CCParticleSystem:getOrderOfArrival() end 
function CCParticleSystem:getPositionX() end 
function CCParticleSystem:setGLServerState() end 
function CCParticleSystem:setSkewY() end 
function CCParticleSystem:setOrderOfArrival() end 
function CCParticleSystem:nodeToWorldTransform() end 
function CCParticleSystem:getChildren() end 
function CCParticleSystem:transformAncestors() end 
function CCParticleSystem:getGrid() end 
function CCParticleSystem:isRunning() end 
function CCParticleSystem:registerScriptHandler() end 
function CCParticleSystem:getCamera() end 
function CCParticleSystem:isIgnoreAnchorPointForPosition() end 
function CCParticleSystem:getUserData() end 
function CCParticleSystem:setPositionY() end 
function CCParticleSystem:getZOrder() end 
function CCParticleSystem:setRadialAccelVar() end 
function CCParticleSystem:getRotatePerSecond() end 
function CCParticleSystem:getBlendFunc() end 
function CCParticleSystem:getEndColorVar() end 
function CCParticleSystem:setPosVar() end 
function CCParticleSystem:getEmitterMode() end 
function CCParticleSystem:setRotatePerSecondVar() end 
function CCParticleSystem:getStartColorVar() end 
function CCParticleSystem:getEndSizeVar() end 
function CCParticleSystem:getEndRadiusVar() end 
function CCParticleSystem:setTangentialAccel() end 
function CCParticleSystem:getStartRadiusVar() end 
function CCParticleSystem:getSourcePosition() end 
function CCParticleSystem:isFull() end 
function CCParticleSystem:setEmitterMode() end 
function CCParticleSystem:setEmissionRate() end 
function CCParticleSystem:getTexture() end 
function CCParticleSystem:setTexture() end 
function CCParticleSystem:setScaleX() end 
function CCParticleSystem:getRadialAccelVar() end 
function CCParticleSystem:isAutoRemoveOnFinish() end 
function CCParticleSystem:getEndColor() end 
function CCParticleSystem:setPositionType() end 
function CCParticleSystem:getRotatePerSecondVar() end 
function CCParticleSystem:setStartColorVar() end 
function CCParticleSystem:setBlendAdditive() end 
function CCParticleSystem:getTangentialAccel() end 
function CCParticleSystem:setStartRadiusVar() end 
function CCParticleSystem:setLife() end 
function CCParticleSystem:getParticleCount() end 
function CCParticleSystem:setSourcePosition() end 
function CCParticleSystem:setScale() end 
function CCParticleSystem:setBatchNode() end 
function CCParticleSystem:setEndColor() end 
function CCParticleSystem:isBlendAdditive() end 
function CCParticleSystem:isActive() end 
function CCParticleSystem:setGravity() end 
function CCParticleSystem:stopSystem() end 
function CCParticleSystem:getTangentialAccelVar() end 
function CCParticleSystem:initWithTotalParticles() end 
function CCParticleSystem:setBlendFunc() end 
function CCParticleSystem:setSpeed() end 
function CCParticleSystem:getStartRadius() end 
function CCParticleSystem:getBatchNode() end 
function CCParticleSystem:setLifeVar() end 
function CCParticleSystem:setRotation() end 
function CCParticleSystem:setStartRadius() end 
function CCParticleSystem:setEndRadiusVar() end 
---
-- @return @class CCParticleSystem
--
function CCParticleSystem:create() end 
function CCParticleSystem:setAutoRemoveOnFinish() end 
function CCParticleSystem:setStartSpin() end 
function CCParticleSystem:setEndSpin() end 
function CCParticleSystem:getStartSizeVar() end 
function CCParticleSystem:initWithFile() end 
function CCParticleSystem:setStartColor() end 
function CCParticleSystem:setStartSizeVar() end 
function CCParticleSystem:setTangentialAccelVar() end 
function CCParticleSystem:getLife() end 
function CCParticleSystem:getTotalParticles() end 
function CCParticleSystem:getSpeed() end 
function CCParticleSystem:getEmissionRate() end 
function CCParticleSystem:getEndSpinVar() end 
function CCParticleSystem:setEndSpinVar() end 
function CCParticleSystem:getEndSpin() end 
function CCParticleSystem:getAngle() end 
function CCParticleSystem:updateQuadWithParticle() end 
function CCParticleSystem:setSpeedVar() end 
function CCParticleSystem:getStartSpinVar() end 
function CCParticleSystem:setStartSpinVar() end 
function CCParticleSystem:getStartSpin() end 
function CCParticleSystem:setEndSize() end 
function CCParticleSystem:getRadialAccel() end 
function CCParticleSystem:getPosVar() end 
function CCParticleSystem:getEndSize() end 
function CCParticleSystem:getLifeVar() end 
function CCParticleSystem:getPositionType() end 
function CCParticleSystem:getStartColor() end 
function CCParticleSystem:getEndRadius() end 
function CCParticleSystem:addParticle() end 
function CCParticleSystem:postStep() end 
function CCParticleSystem:setEndSizeVar() end 
function CCParticleSystem:getDuration() end 
function CCParticleSystem:getSpeedVar() end 
function CCParticleSystem:initParticle() end 
function CCParticleSystem:getAngleVar() end 
function CCParticleSystem:getStartSize() end 
function CCParticleSystem:setRotatePerSecond() end 
function CCParticleSystem:setEndRadius() end 
function CCParticleSystem:setAngleVar() end 
function CCParticleSystem:getGravity() end 
function CCParticleSystem:setEndColorVar() end 
function CCParticleSystem:setAngle() end 
function CCParticleSystem:resetSystem() end 
function CCParticleSystem:setDuration() end 
function CCParticleSystem:setRadialAccel() end 
function CCParticleSystem:setStartSize() end 
function CCParticleSystem:setScaleY() end 
