---@classdef CCParticleSmoke
CCParticleSmoke = {}
function CCParticleSmoke:autorelease() end 
function CCParticleSmoke:retain() end 
function CCParticleSmoke:retainCount() end 
function CCParticleSmoke:isEqual() end 
function CCParticleSmoke:copy() end 
function CCParticleSmoke:release() end 
function CCParticleSmoke:isSingleReference() end 
function CCParticleSmoke:visit() end 
function CCParticleSmoke:getUserObject() end 
function CCParticleSmoke:getSkewY() end 
function CCParticleSmoke:convertTouchToNodeSpace() end 
function CCParticleSmoke:getVertexZ() end 
function CCParticleSmoke:setParent() end 
function CCParticleSmoke:boundingBox() end 
function CCParticleSmoke:setVisible() end 
function CCParticleSmoke:stopActionByTag() end 
function CCParticleSmoke:getScaleY() end 
function CCParticleSmoke:setScaleX() end 
function CCParticleSmoke:reorderChild() end 
function CCParticleSmoke:setPositionX() end 
function CCParticleSmoke:removeFromParentAndCleanup() end 
function CCParticleSmoke:setTag() end 
function CCParticleSmoke:getChildrenCount() end 
function CCParticleSmoke:setScale() end 
function CCParticleSmoke:addChild() end 
function CCParticleSmoke:isVisible() end 
function CCParticleSmoke:setActionManager() end 
function CCParticleSmoke:setScheduler() end 
function CCParticleSmoke:getContentSize() end 
function CCParticleSmoke:getAnchorPoint() end 
function CCParticleSmoke:getTag() end 
function CCParticleSmoke:setGrid() end 
function CCParticleSmoke:convertToWorldSpace() end 
function CCParticleSmoke:setSkewX() end 
function CCParticleSmoke:setZOrder() end 
function CCParticleSmoke:worldToNodeTransform() end 
function CCParticleSmoke:getPosition() end 
function CCParticleSmoke:getSkewX() end 
function CCParticleSmoke:getScheduler() end 
function CCParticleSmoke:ignoreAnchorPointForPosition() end 
function CCParticleSmoke:setPosition() end 
function CCParticleSmoke:getParent() end 
function CCParticleSmoke:unscheduleUpdate() end 
function CCParticleSmoke:scheduleUpdateWithPriorityLua() end 
function CCParticleSmoke:removeChildByTag() end 
function CCParticleSmoke:convertToNodeSpaceAR() end 
function CCParticleSmoke:convertTouchToNodeSpaceAR() end 
function CCParticleSmoke:convertToWorldSpaceAR() end 
function CCParticleSmoke:setRotation() end 
function CCParticleSmoke:getComponent() end 
function CCParticleSmoke:convertToNodeSpace() end 
---
-- @return @class CCParticleSmoke
--
function CCParticleSmoke:create() end 
function CCParticleSmoke:getScale() end 
function CCParticleSmoke:getPositionY() end 
function CCParticleSmoke:getChildByTag() end 
function CCParticleSmoke:setContentSize() end 
function CCParticleSmoke:description() end 
function CCParticleSmoke:cleanup() end 
function CCParticleSmoke:getRotation() end 
function CCParticleSmoke:nodeToParentTransform() end 
function CCParticleSmoke:stopAction() end 
function CCParticleSmoke:numberOfRunningActions() end 
function CCParticleSmoke:removeAllChildren() end 
function CCParticleSmoke:runAction() end 
function CCParticleSmoke:setUserObject() end 
function CCParticleSmoke:parentToNodeTransform() end 
function CCParticleSmoke:removeChild() end 
function CCParticleSmoke:getAnchorPointInPoints() end 
function CCParticleSmoke:getScaleX() end 
function CCParticleSmoke:transform() end 
function CCParticleSmoke:getActionManager() end 
function CCParticleSmoke:draw() end 
function CCParticleSmoke:setScaleY() end 
function CCParticleSmoke:unregisterScriptHandler() end 
function CCParticleSmoke:setVertexZ() end 
function CCParticleSmoke:setAnchorPoint() end 
function CCParticleSmoke:getShaderProgram() end 
function CCParticleSmoke:stopAllActions() end 
function CCParticleSmoke:setUserData() end 
function CCParticleSmoke:setShaderProgram() end 
function CCParticleSmoke:getActionByTag() end 
function CCParticleSmoke:getGLServerState() end 
function CCParticleSmoke:getOrderOfArrival() end 
function CCParticleSmoke:getPositionX() end 
function CCParticleSmoke:setGLServerState() end 
function CCParticleSmoke:setSkewY() end 
function CCParticleSmoke:setOrderOfArrival() end 
function CCParticleSmoke:nodeToWorldTransform() end 
function CCParticleSmoke:getChildren() end 
function CCParticleSmoke:transformAncestors() end 
function CCParticleSmoke:getGrid() end 
function CCParticleSmoke:isRunning() end 
function CCParticleSmoke:registerScriptHandler() end 
function CCParticleSmoke:getCamera() end 
function CCParticleSmoke:isIgnoreAnchorPointForPosition() end 
function CCParticleSmoke:getUserData() end 
function CCParticleSmoke:setPositionY() end 
function CCParticleSmoke:getZOrder() end 
function CCParticleSmoke:setRadialAccelVar() end 
function CCParticleSmoke:getRotatePerSecond() end 
function CCParticleSmoke:getBlendFunc() end 
function CCParticleSmoke:getEndColorVar() end 
function CCParticleSmoke:setPosVar() end 
function CCParticleSmoke:getEmitterMode() end 
function CCParticleSmoke:setRotatePerSecondVar() end 
function CCParticleSmoke:getStartColorVar() end 
function CCParticleSmoke:getEndSizeVar() end 
function CCParticleSmoke:getEndRadiusVar() end 
function CCParticleSmoke:setTangentialAccel() end 
function CCParticleSmoke:getStartRadiusVar() end 
function CCParticleSmoke:getSourcePosition() end 
function CCParticleSmoke:isFull() end 
function CCParticleSmoke:setEmitterMode() end 
function CCParticleSmoke:setEmissionRate() end 
function CCParticleSmoke:getTexture() end 
function CCParticleSmoke:setTexture() end 
function CCParticleSmoke:setScaleX() end 
function CCParticleSmoke:getRadialAccelVar() end 
function CCParticleSmoke:isAutoRemoveOnFinish() end 
function CCParticleSmoke:getEndColor() end 
function CCParticleSmoke:setPositionType() end 
function CCParticleSmoke:getRotatePerSecondVar() end 
function CCParticleSmoke:setStartColorVar() end 
function CCParticleSmoke:setBlendAdditive() end 
function CCParticleSmoke:getTangentialAccel() end 
function CCParticleSmoke:setStartRadiusVar() end 
function CCParticleSmoke:setLife() end 
function CCParticleSmoke:getParticleCount() end 
function CCParticleSmoke:setSourcePosition() end 
function CCParticleSmoke:setScale() end 
function CCParticleSmoke:setBatchNode() end 
function CCParticleSmoke:setEndColor() end 
function CCParticleSmoke:isBlendAdditive() end 
function CCParticleSmoke:isActive() end 
function CCParticleSmoke:setGravity() end 
function CCParticleSmoke:stopSystem() end 
function CCParticleSmoke:getTangentialAccelVar() end 
function CCParticleSmoke:initWithTotalParticles() end 
function CCParticleSmoke:setBlendFunc() end 
function CCParticleSmoke:setSpeed() end 
function CCParticleSmoke:getStartRadius() end 
function CCParticleSmoke:getBatchNode() end 
function CCParticleSmoke:setLifeVar() end 
function CCParticleSmoke:setRotation() end 
function CCParticleSmoke:setStartRadius() end 
function CCParticleSmoke:setEndRadiusVar() end 
---
-- @return @class CCParticleSmoke
--
function CCParticleSmoke:create() end 
function CCParticleSmoke:setAutoRemoveOnFinish() end 
function CCParticleSmoke:setStartSpin() end 
function CCParticleSmoke:setEndSpin() end 
function CCParticleSmoke:getStartSizeVar() end 
function CCParticleSmoke:initWithFile() end 
function CCParticleSmoke:setStartColor() end 
function CCParticleSmoke:setStartSizeVar() end 
function CCParticleSmoke:setTangentialAccelVar() end 
function CCParticleSmoke:getLife() end 
function CCParticleSmoke:getTotalParticles() end 
function CCParticleSmoke:getSpeed() end 
function CCParticleSmoke:getEmissionRate() end 
function CCParticleSmoke:getEndSpinVar() end 
function CCParticleSmoke:setEndSpinVar() end 
function CCParticleSmoke:getEndSpin() end 
function CCParticleSmoke:getAngle() end 
function CCParticleSmoke:updateQuadWithParticle() end 
function CCParticleSmoke:setSpeedVar() end 
function CCParticleSmoke:getStartSpinVar() end 
function CCParticleSmoke:setStartSpinVar() end 
function CCParticleSmoke:getStartSpin() end 
function CCParticleSmoke:setEndSize() end 
function CCParticleSmoke:getRadialAccel() end 
function CCParticleSmoke:getPosVar() end 
function CCParticleSmoke:getEndSize() end 
function CCParticleSmoke:getLifeVar() end 
function CCParticleSmoke:getPositionType() end 
function CCParticleSmoke:getStartColor() end 
function CCParticleSmoke:getEndRadius() end 
function CCParticleSmoke:addParticle() end 
function CCParticleSmoke:postStep() end 
function CCParticleSmoke:setEndSizeVar() end 
function CCParticleSmoke:getDuration() end 
function CCParticleSmoke:getSpeedVar() end 
function CCParticleSmoke:initParticle() end 
function CCParticleSmoke:getAngleVar() end 
function CCParticleSmoke:getStartSize() end 
function CCParticleSmoke:setRotatePerSecond() end 
function CCParticleSmoke:setEndRadius() end 
function CCParticleSmoke:setAngleVar() end 
function CCParticleSmoke:getGravity() end 
function CCParticleSmoke:setEndColorVar() end 
function CCParticleSmoke:setAngle() end 
function CCParticleSmoke:resetSystem() end 
function CCParticleSmoke:setDuration() end 
function CCParticleSmoke:setRadialAccel() end 
function CCParticleSmoke:setStartSize() end 
function CCParticleSmoke:setScaleY() end 
function CCParticleSmoke:new() end 
function CCParticleSmoke:postStep() end 
---
-- @return @class CCParticleSmoke
--
function CCParticleSmoke:create() end 
function CCParticleSmoke:setTextureWithRect() end 
function CCParticleSmoke:setTotalParticles() end 
function CCParticleSmoke:new_local() end 
function CCParticleSmoke:setBatchNode() end 
function CCParticleSmoke:updateQuadWithParticle() end 
function CCParticleSmoke:setTexture() end 
function CCParticleSmoke:setDisplayFrame() end 
---
-- @return @class CCParticleSmoke
--
function CCParticleSmoke:create() end 
