---@classdef CCPointArray
CCPointArray = {}
function CCPointArray:autorelease() end 
function CCPointArray:retain() end 
function CCPointArray:retainCount() end 
function CCPointArray:isEqual() end 
function CCPointArray:copy() end 
function CCPointArray:release() end 
function CCPointArray:isSingleReference() end 
function CCPointArray:visit() end 
function CCPointArray:getUserObject() end 
function CCPointArray:getSkewY() end 
function CCPointArray:convertTouchToNodeSpace() end 
function CCPointArray:getVertexZ() end 
function CCPointArray:setParent() end 
function CCPointArray:boundingBox() end 
function CCPointArray:setVisible() end 
function CCPointArray:stopActionByTag() end 
function CCPointArray:getScaleY() end 
function CCPointArray:setScaleX() end 
function CCPointArray:reorderChild() end 
function CCPointArray:setPositionX() end 
function CCPointArray:removeFromParentAndCleanup() end 
function CCPointArray:setTag() end 
function CCPointArray:getChildrenCount() end 
function CCPointArray:setScale() end 
function CCPointArray:addChild() end 
function CCPointArray:isVisible() end 
function CCPointArray:setActionManager() end 
function CCPointArray:setScheduler() end 
function CCPointArray:getContentSize() end 
function CCPointArray:getAnchorPoint() end 
function CCPointArray:getTag() end 
function CCPointArray:setGrid() end 
function CCPointArray:convertToWorldSpace() end 
function CCPointArray:setSkewX() end 
function CCPointArray:setZOrder() end 
function CCPointArray:worldToNodeTransform() end 
function CCPointArray:getPosition() end 
function CCPointArray:getSkewX() end 
function CCPointArray:getScheduler() end 
function CCPointArray:ignoreAnchorPointForPosition() end 
function CCPointArray:setPosition() end 
function CCPointArray:getParent() end 
function CCPointArray:unscheduleUpdate() end 
function CCPointArray:scheduleUpdateWithPriorityLua() end 
function CCPointArray:removeChildByTag() end 
function CCPointArray:convertToNodeSpaceAR() end 
function CCPointArray:convertTouchToNodeSpaceAR() end 
function CCPointArray:convertToWorldSpaceAR() end 
function CCPointArray:setRotation() end 
function CCPointArray:getComponent() end 
function CCPointArray:convertToNodeSpace() end 
---
-- @return @class CCPointArray
--
function CCPointArray:create() end 
function CCPointArray:getScale() end 
function CCPointArray:getPositionY() end 
function CCPointArray:getChildByTag() end 
function CCPointArray:setContentSize() end 
function CCPointArray:description() end 
function CCPointArray:cleanup() end 
function CCPointArray:getRotation() end 
function CCPointArray:nodeToParentTransform() end 
function CCPointArray:stopAction() end 
function CCPointArray:numberOfRunningActions() end 
function CCPointArray:removeAllChildren() end 
function CCPointArray:runAction() end 
function CCPointArray:setUserObject() end 
function CCPointArray:parentToNodeTransform() end 
function CCPointArray:removeChild() end 
function CCPointArray:getAnchorPointInPoints() end 
function CCPointArray:getScaleX() end 
function CCPointArray:transform() end 
function CCPointArray:getActionManager() end 
function CCPointArray:draw() end 
function CCPointArray:setScaleY() end 
function CCPointArray:unregisterScriptHandler() end 
function CCPointArray:setVertexZ() end 
function CCPointArray:setAnchorPoint() end 
function CCPointArray:getShaderProgram() end 
function CCPointArray:stopAllActions() end 
function CCPointArray:setUserData() end 
function CCPointArray:setShaderProgram() end 
function CCPointArray:getActionByTag() end 
function CCPointArray:getGLServerState() end 
function CCPointArray:getOrderOfArrival() end 
function CCPointArray:getPositionX() end 
function CCPointArray:setGLServerState() end 
function CCPointArray:setSkewY() end 
function CCPointArray:setOrderOfArrival() end 
function CCPointArray:nodeToWorldTransform() end 
function CCPointArray:getChildren() end 
function CCPointArray:transformAncestors() end 
function CCPointArray:getGrid() end 
function CCPointArray:isRunning() end 
function CCPointArray:registerScriptHandler() end 
function CCPointArray:getCamera() end 
function CCPointArray:isIgnoreAnchorPointForPosition() end 
function CCPointArray:getUserData() end 
function CCPointArray:setPositionY() end 
function CCPointArray:getZOrder() end 
function CCPointArray:replaceControlPoint() end 
---
-- @return @class CCPointArray
--
function CCPointArray:create() end 
function CCPointArray:initWithCapacity() end 
function CCPointArray:insertControlPoint() end 
function CCPointArray:setControlPoints() end 
function CCPointArray:reverseInline() end 
function CCPointArray:addControlPoint() end 
function CCPointArray:reverse() end 
function CCPointArray:count() end 
function CCPointArray:removeControlPointAtIndex() end 
function CCPointArray:getControlPointAtIndex() end 
function CCPointArray:getControlPoints() end 
