---@classdef CCProgressTimer
CCProgressTimer = {}
function CCProgressTimer:autorelease() end 
function CCProgressTimer:retain() end 
function CCProgressTimer:retainCount() end 
function CCProgressTimer:isEqual() end 
function CCProgressTimer:copy() end 
function CCProgressTimer:release() end 
function CCProgressTimer:isSingleReference() end 
function CCProgressTimer:visit() end 
function CCProgressTimer:getUserObject() end 
function CCProgressTimer:getSkewY() end 
function CCProgressTimer:convertTouchToNodeSpace() end 
function CCProgressTimer:getVertexZ() end 
function CCProgressTimer:setParent() end 
function CCProgressTimer:boundingBox() end 
function CCProgressTimer:setVisible() end 
function CCProgressTimer:stopActionByTag() end 
function CCProgressTimer:getScaleY() end 
function CCProgressTimer:setScaleX() end 
function CCProgressTimer:reorderChild() end 
function CCProgressTimer:setPositionX() end 
function CCProgressTimer:removeFromParentAndCleanup() end 
function CCProgressTimer:setTag() end 
function CCProgressTimer:getChildrenCount() end 
function CCProgressTimer:setScale() end 
function CCProgressTimer:addChild() end 
function CCProgressTimer:isVisible() end 
function CCProgressTimer:setActionManager() end 
function CCProgressTimer:setScheduler() end 
function CCProgressTimer:getContentSize() end 
function CCProgressTimer:getAnchorPoint() end 
function CCProgressTimer:getTag() end 
function CCProgressTimer:setGrid() end 
function CCProgressTimer:convertToWorldSpace() end 
function CCProgressTimer:setSkewX() end 
function CCProgressTimer:setZOrder() end 
function CCProgressTimer:worldToNodeTransform() end 
function CCProgressTimer:getPosition() end 
function CCProgressTimer:getSkewX() end 
function CCProgressTimer:getScheduler() end 
function CCProgressTimer:ignoreAnchorPointForPosition() end 
function CCProgressTimer:setPosition() end 
function CCProgressTimer:getParent() end 
function CCProgressTimer:unscheduleUpdate() end 
function CCProgressTimer:scheduleUpdateWithPriorityLua() end 
function CCProgressTimer:removeChildByTag() end 
function CCProgressTimer:convertToNodeSpaceAR() end 
function CCProgressTimer:convertTouchToNodeSpaceAR() end 
function CCProgressTimer:convertToWorldSpaceAR() end 
function CCProgressTimer:setRotation() end 
function CCProgressTimer:getComponent() end 
function CCProgressTimer:convertToNodeSpace() end 
---
-- @return @class CCProgressTimer
--
function CCProgressTimer:create() end 
function CCProgressTimer:getScale() end 
function CCProgressTimer:getPositionY() end 
function CCProgressTimer:getChildByTag() end 
function CCProgressTimer:setContentSize() end 
function CCProgressTimer:description() end 
function CCProgressTimer:cleanup() end 
function CCProgressTimer:getRotation() end 
function CCProgressTimer:nodeToParentTransform() end 
function CCProgressTimer:stopAction() end 
function CCProgressTimer:numberOfRunningActions() end 
function CCProgressTimer:removeAllChildren() end 
function CCProgressTimer:runAction() end 
function CCProgressTimer:setUserObject() end 
function CCProgressTimer:parentToNodeTransform() end 
function CCProgressTimer:removeChild() end 
function CCProgressTimer:getAnchorPointInPoints() end 
function CCProgressTimer:getScaleX() end 
function CCProgressTimer:transform() end 
function CCProgressTimer:getActionManager() end 
function CCProgressTimer:draw() end 
function CCProgressTimer:setScaleY() end 
function CCProgressTimer:unregisterScriptHandler() end 
function CCProgressTimer:setVertexZ() end 
function CCProgressTimer:setAnchorPoint() end 
function CCProgressTimer:getShaderProgram() end 
function CCProgressTimer:stopAllActions() end 
function CCProgressTimer:setUserData() end 
function CCProgressTimer:setShaderProgram() end 
function CCProgressTimer:getActionByTag() end 
function CCProgressTimer:getGLServerState() end 
function CCProgressTimer:getOrderOfArrival() end 
function CCProgressTimer:getPositionX() end 
function CCProgressTimer:setGLServerState() end 
function CCProgressTimer:setSkewY() end 
function CCProgressTimer:setOrderOfArrival() end 
function CCProgressTimer:nodeToWorldTransform() end 
function CCProgressTimer:getChildren() end 
function CCProgressTimer:transformAncestors() end 
function CCProgressTimer:getGrid() end 
function CCProgressTimer:isRunning() end 
function CCProgressTimer:registerScriptHandler() end 
function CCProgressTimer:getCamera() end 
function CCProgressTimer:isIgnoreAnchorPointForPosition() end 
function CCProgressTimer:getUserData() end 
function CCProgressTimer:setPositionY() end 
function CCProgressTimer:getZOrder() end 
function CCProgressTimer:new() end 
function CCProgressTimer:delete() end 
function CCProgressTimer:updateDisplayedColor() end 
function CCProgressTimer:init() end 
function CCProgressTimer:setColor() end 
function CCProgressTimer:getDisplayedColor() end 
function CCProgressTimer:setCascadeColorEnabled() end 
function CCProgressTimer:setCascadeOpacityEnabled() end 
function CCProgressTimer:setOpacity() end 
function CCProgressTimer:getColor() end 
function CCProgressTimer:updateDisplayedOpacity() end 
function CCProgressTimer:getOpacity() end 
function CCProgressTimer:setOpacityModifyRGB() end 
function CCProgressTimer:isCascadeOpacityEnabled() end 
function CCProgressTimer:isOpacityModifyRGB() end 
function CCProgressTimer:getDisplayedOpacity() end 
function CCProgressTimer:new_local() end 
function CCProgressTimer:isCascadeColorEnabled() end 
function CCProgressTimer:getPercentage() end 
function CCProgressTimer:setOpacity() end 
function CCProgressTimer:setReverseDirection() end 
function CCProgressTimer:getColor() end 
function CCProgressTimer:getType() end 
function CCProgressTimer:setBarChangeRate() end 
function CCProgressTimer:isOpacityModifyRGB() end 
function CCProgressTimer:setMidpoint() end 
function CCProgressTimer:getMidpoint() end 
function CCProgressTimer:setPercentage() end 
function CCProgressTimer:getOpacity() end 
---
-- @return @class CCProgressTimer
--
function CCProgressTimer:create() end 
function CCProgressTimer:setSprite() end 
function CCProgressTimer:setColor() end 
function CCProgressTimer:setReverseProgress() end 
function CCProgressTimer:getBarChangeRate() end 
function CCProgressTimer:setOpacityModifyRGB() end 
function CCProgressTimer:getSprite() end 
function CCProgressTimer:setType() end 
function CCProgressTimer:isReverseDirection() end 
