---@classdef CCRenderTexture
CCRenderTexture = {}
function CCRenderTexture:autorelease() end 
function CCRenderTexture:retain() end 
function CCRenderTexture:retainCount() end 
function CCRenderTexture:isEqual() end 
function CCRenderTexture:copy() end 
function CCRenderTexture:release() end 
function CCRenderTexture:isSingleReference() end 
function CCRenderTexture:visit() end 
function CCRenderTexture:getUserObject() end 
function CCRenderTexture:getSkewY() end 
function CCRenderTexture:convertTouchToNodeSpace() end 
function CCRenderTexture:getVertexZ() end 
function CCRenderTexture:setParent() end 
function CCRenderTexture:boundingBox() end 
function CCRenderTexture:setVisible() end 
function CCRenderTexture:stopActionByTag() end 
function CCRenderTexture:getScaleY() end 
function CCRenderTexture:setScaleX() end 
function CCRenderTexture:reorderChild() end 
function CCRenderTexture:setPositionX() end 
function CCRenderTexture:removeFromParentAndCleanup() end 
function CCRenderTexture:setTag() end 
function CCRenderTexture:getChildrenCount() end 
function CCRenderTexture:setScale() end 
function CCRenderTexture:addChild() end 
function CCRenderTexture:isVisible() end 
function CCRenderTexture:setActionManager() end 
function CCRenderTexture:setScheduler() end 
function CCRenderTexture:getContentSize() end 
function CCRenderTexture:getAnchorPoint() end 
function CCRenderTexture:getTag() end 
function CCRenderTexture:setGrid() end 
function CCRenderTexture:convertToWorldSpace() end 
function CCRenderTexture:setSkewX() end 
function CCRenderTexture:setZOrder() end 
function CCRenderTexture:worldToNodeTransform() end 
function CCRenderTexture:getPosition() end 
function CCRenderTexture:getSkewX() end 
function CCRenderTexture:getScheduler() end 
function CCRenderTexture:ignoreAnchorPointForPosition() end 
function CCRenderTexture:setPosition() end 
function CCRenderTexture:getParent() end 
function CCRenderTexture:unscheduleUpdate() end 
function CCRenderTexture:scheduleUpdateWithPriorityLua() end 
function CCRenderTexture:removeChildByTag() end 
function CCRenderTexture:convertToNodeSpaceAR() end 
function CCRenderTexture:convertTouchToNodeSpaceAR() end 
function CCRenderTexture:convertToWorldSpaceAR() end 
function CCRenderTexture:setRotation() end 
function CCRenderTexture:getComponent() end 
function CCRenderTexture:convertToNodeSpace() end 
---
-- @return @class CCRenderTexture
--
function CCRenderTexture:create() end 
function CCRenderTexture:getScale() end 
function CCRenderTexture:getPositionY() end 
function CCRenderTexture:getChildByTag() end 
function CCRenderTexture:setContentSize() end 
function CCRenderTexture:description() end 
function CCRenderTexture:cleanup() end 
function CCRenderTexture:getRotation() end 
function CCRenderTexture:nodeToParentTransform() end 
function CCRenderTexture:stopAction() end 
function CCRenderTexture:numberOfRunningActions() end 
function CCRenderTexture:removeAllChildren() end 
function CCRenderTexture:runAction() end 
function CCRenderTexture:setUserObject() end 
function CCRenderTexture:parentToNodeTransform() end 
function CCRenderTexture:removeChild() end 
function CCRenderTexture:getAnchorPointInPoints() end 
function CCRenderTexture:getScaleX() end 
function CCRenderTexture:transform() end 
function CCRenderTexture:getActionManager() end 
function CCRenderTexture:draw() end 
function CCRenderTexture:setScaleY() end 
function CCRenderTexture:unregisterScriptHandler() end 
function CCRenderTexture:setVertexZ() end 
function CCRenderTexture:setAnchorPoint() end 
function CCRenderTexture:getShaderProgram() end 
function CCRenderTexture:stopAllActions() end 
function CCRenderTexture:setUserData() end 
function CCRenderTexture:setShaderProgram() end 
function CCRenderTexture:getActionByTag() end 
function CCRenderTexture:getGLServerState() end 
function CCRenderTexture:getOrderOfArrival() end 
function CCRenderTexture:getPositionX() end 
function CCRenderTexture:setGLServerState() end 
function CCRenderTexture:setSkewY() end 
function CCRenderTexture:setOrderOfArrival() end 
function CCRenderTexture:nodeToWorldTransform() end 
function CCRenderTexture:getChildren() end 
function CCRenderTexture:transformAncestors() end 
function CCRenderTexture:getGrid() end 
function CCRenderTexture:isRunning() end 
function CCRenderTexture:registerScriptHandler() end 
function CCRenderTexture:getCamera() end 
function CCRenderTexture:isIgnoreAnchorPointForPosition() end 
function CCRenderTexture:getUserData() end 
function CCRenderTexture:setPositionY() end 
function CCRenderTexture:getZOrder() end 
function CCRenderTexture:endToLua() end 
---
-- @return @class CCRenderTexture
--
function CCRenderTexture:create() end 
function CCRenderTexture:setSprite() end 
function CCRenderTexture:newCCImage() end 
function CCRenderTexture:beginWithClear() end 
function CCRenderTexture:saveToFile() end 
function CCRenderTexture:clearStencil() end 
function CCRenderTexture:getSprite() end 
function CCRenderTexture:clearDepth() end 
function CCRenderTexture:begin() end 
function CCRenderTexture:clear() end 
