---@classdef CCScrollView
CCScrollView = {}
function CCScrollView:autorelease() end 
function CCScrollView:retain() end 
function CCScrollView:retainCount() end 
function CCScrollView:isEqual() end 
function CCScrollView:copy() end 
function CCScrollView:release() end 
function CCScrollView:isSingleReference() end 
function CCScrollView:visit() end 
function CCScrollView:getUserObject() end 
function CCScrollView:getSkewY() end 
function CCScrollView:convertTouchToNodeSpace() end 
function CCScrollView:getVertexZ() end 
function CCScrollView:setParent() end 
function CCScrollView:boundingBox() end 
function CCScrollView:setVisible() end 
function CCScrollView:stopActionByTag() end 
function CCScrollView:getScaleY() end 
function CCScrollView:setScaleX() end 
function CCScrollView:reorderChild() end 
function CCScrollView:setPositionX() end 
function CCScrollView:removeFromParentAndCleanup() end 
function CCScrollView:setTag() end 
function CCScrollView:getChildrenCount() end 
function CCScrollView:setScale() end 
function CCScrollView:addChild() end 
function CCScrollView:isVisible() end 
function CCScrollView:setActionManager() end 
function CCScrollView:setScheduler() end 
function CCScrollView:getContentSize() end 
function CCScrollView:getAnchorPoint() end 
function CCScrollView:getTag() end 
function CCScrollView:setGrid() end 
function CCScrollView:convertToWorldSpace() end 
function CCScrollView:setSkewX() end 
function CCScrollView:setZOrder() end 
function CCScrollView:worldToNodeTransform() end 
function CCScrollView:getPosition() end 
function CCScrollView:getSkewX() end 
function CCScrollView:getScheduler() end 
function CCScrollView:ignoreAnchorPointForPosition() end 
function CCScrollView:setPosition() end 
function CCScrollView:getParent() end 
function CCScrollView:unscheduleUpdate() end 
function CCScrollView:scheduleUpdateWithPriorityLua() end 
function CCScrollView:removeChildByTag() end 
function CCScrollView:convertToNodeSpaceAR() end 
function CCScrollView:convertTouchToNodeSpaceAR() end 
function CCScrollView:convertToWorldSpaceAR() end 
function CCScrollView:setRotation() end 
function CCScrollView:getComponent() end 
function CCScrollView:convertToNodeSpace() end 
---
-- @return @class CCScrollView
--
function CCScrollView:create() end 
function CCScrollView:getScale() end 
function CCScrollView:getPositionY() end 
function CCScrollView:getChildByTag() end 
function CCScrollView:setContentSize() end 
function CCScrollView:description() end 
function CCScrollView:cleanup() end 
function CCScrollView:getRotation() end 
function CCScrollView:nodeToParentTransform() end 
function CCScrollView:stopAction() end 
function CCScrollView:numberOfRunningActions() end 
function CCScrollView:removeAllChildren() end 
function CCScrollView:runAction() end 
function CCScrollView:setUserObject() end 
function CCScrollView:parentToNodeTransform() end 
function CCScrollView:removeChild() end 
function CCScrollView:getAnchorPointInPoints() end 
function CCScrollView:getScaleX() end 
function CCScrollView:transform() end 
function CCScrollView:getActionManager() end 
function CCScrollView:draw() end 
function CCScrollView:setScaleY() end 
function CCScrollView:unregisterScriptHandler() end 
function CCScrollView:setVertexZ() end 
function CCScrollView:setAnchorPoint() end 
function CCScrollView:getShaderProgram() end 
function CCScrollView:stopAllActions() end 
function CCScrollView:setUserData() end 
function CCScrollView:setShaderProgram() end 
function CCScrollView:getActionByTag() end 
function CCScrollView:getGLServerState() end 
function CCScrollView:getOrderOfArrival() end 
function CCScrollView:getPositionX() end 
function CCScrollView:setGLServerState() end 
function CCScrollView:setSkewY() end 
function CCScrollView:setOrderOfArrival() end 
function CCScrollView:nodeToWorldTransform() end 
function CCScrollView:getChildren() end 
function CCScrollView:transformAncestors() end 
function CCScrollView:getGrid() end 
function CCScrollView:isRunning() end 
function CCScrollView:registerScriptHandler() end 
function CCScrollView:getCamera() end 
function CCScrollView:isIgnoreAnchorPointForPosition() end 
function CCScrollView:getUserData() end 
function CCScrollView:setPositionY() end 
function CCScrollView:getZOrder() end 
function CCScrollView:isTouchEnabled() end 
function CCScrollView:unregisterScriptKeypadHandler() end 
function CCScrollView:registerScriptAccelerateHandler() end 
---
-- @return @class CCScrollView
--
function CCScrollView:create() end 
function CCScrollView:setAccelerometerEnabled() end 
function CCScrollView:registerScriptKeypadHandler() end 
function CCScrollView:setTouchMode() end 
function CCScrollView:isAccelerometerEnabled() end 
function CCScrollView:setTouchEnabled() end 
function CCScrollView:setTouchPriority() end 
function CCScrollView:unregisterScriptAccelerateHandler() end 
function CCScrollView:unregisterScriptTouchHandler() end 
function CCScrollView:setKeypadEnabled() end 
function CCScrollView:registerScriptTouchHandler() end 
function CCScrollView:getTouchPriority() end 
function CCScrollView:isKeypadEnabled() end 
function CCScrollView:getTouchMode() end 
function CCScrollView:ccTouchMoved() end 
function CCScrollView:new() end 
function CCScrollView:getScriptHandler() end 
function CCScrollView:setZoomScale() end 
function CCScrollView:delete() end 
function CCScrollView:init() end 
function CCScrollView:ccTouchEnded() end 
function CCScrollView:setDirection() end 
function CCScrollView:registerScriptHandler() end 
function CCScrollView:updateInset() end 
function CCScrollView:setViewSize() end 
function CCScrollView:setDelegate() end 
function CCScrollView:new_local() end 
function CCScrollView:unregisterScriptHandler() end 
function CCScrollView:minContainerOffset() end 
function CCScrollView:initWithViewSize() end 
function CCScrollView:setContainer() end 
function CCScrollView:setTouchEnabled() end 
function CCScrollView:ccTouchCancelled() end 
function CCScrollView:setClippingToBounds() end 
function CCScrollView:isClippingToBounds() end 
function CCScrollView:setContentOffset() end 
function CCScrollView:getContainer() end 
function CCScrollView:setBounceable() end 
function CCScrollView:addChild() end 
function CCScrollView:getViewSize() end 
function CCScrollView:setZoomScaleInDuration() end 
function CCScrollView:ccTouchBegan() end 
function CCScrollView:resume() end 
function CCScrollView:getDirection() end 
function CCScrollView:getContentSize() end 
function CCScrollView:isBounceable() end 
function CCScrollView:isTouchMoved() end 
function CCScrollView:isNodeVisible() end 
function CCScrollView:pause() end 
function CCScrollView:getZoomScale() end 
function CCScrollView:maxContainerOffset() end 
function CCScrollView:setContentOffsetInDuration() end 
function CCScrollView:registerWithTouchDispatcher() end 
function CCScrollView:getContentOffset() end 
---
-- @return @class CCScrollView
--
function CCScrollView:create() end 
function CCScrollView:isDragging() end 
