---@classdef CCScene
CCScene = {}
function CCScene:autorelease() end 
function CCScene:retain() end 
function CCScene:retainCount() end 
function CCScene:isEqual() end 
function CCScene:copy() end 
function CCScene:release() end 
function CCScene:isSingleReference() end 
function CCScene:visit() end 
function CCScene:getUserObject() end 
function CCScene:getSkewY() end 
function CCScene:convertTouchToNodeSpace() end 
function CCScene:getVertexZ() end 
function CCScene:setParent() end 
function CCScene:boundingBox() end 
function CCScene:setVisible() end 
function CCScene:stopActionByTag() end 
function CCScene:getScaleY() end 
function CCScene:setScaleX() end 
function CCScene:reorderChild() end 
function CCScene:setPositionX() end 
function CCScene:removeFromParentAndCleanup() end 
function CCScene:setTag() end 
function CCScene:getChildrenCount() end 
function CCScene:setScale() end 
function CCScene:addChild() end 
function CCScene:isVisible() end 
function CCScene:setActionManager() end 
function CCScene:setScheduler() end 
function CCScene:getContentSize() end 
function CCScene:getAnchorPoint() end 
function CCScene:getTag() end 
function CCScene:setGrid() end 
function CCScene:convertToWorldSpace() end 
function CCScene:setSkewX() end 
function CCScene:setZOrder() end 
function CCScene:worldToNodeTransform() end 
function CCScene:getPosition() end 
function CCScene:getSkewX() end 
function CCScene:getScheduler() end 
function CCScene:ignoreAnchorPointForPosition() end 
function CCScene:setPosition() end 
function CCScene:getParent() end 
function CCScene:unscheduleUpdate() end 
function CCScene:scheduleUpdateWithPriorityLua() end 
function CCScene:removeChildByTag() end 
function CCScene:convertToNodeSpaceAR() end 
function CCScene:convertTouchToNodeSpaceAR() end 
function CCScene:convertToWorldSpaceAR() end 
function CCScene:setRotation() end 
function CCScene:getComponent() end 
function CCScene:convertToNodeSpace() end 
---
-- @return @class CCScene
--
function CCScene:create() end 
function CCScene:getScale() end 
function CCScene:getPositionY() end 
function CCScene:getChildByTag() end 
function CCScene:setContentSize() end 
function CCScene:description() end 
function CCScene:cleanup() end 
function CCScene:getRotation() end 
function CCScene:nodeToParentTransform() end 
function CCScene:stopAction() end 
function CCScene:numberOfRunningActions() end 
function CCScene:removeAllChildren() end 
function CCScene:runAction() end 
function CCScene:setUserObject() end 
function CCScene:parentToNodeTransform() end 
function CCScene:removeChild() end 
function CCScene:getAnchorPointInPoints() end 
function CCScene:getScaleX() end 
function CCScene:transform() end 
function CCScene:getActionManager() end 
function CCScene:draw() end 
function CCScene:setScaleY() end 
function CCScene:unregisterScriptHandler() end 
function CCScene:setVertexZ() end 
function CCScene:setAnchorPoint() end 
function CCScene:getShaderProgram() end 
function CCScene:stopAllActions() end 
function CCScene:setUserData() end 
function CCScene:setShaderProgram() end 
function CCScene:getActionByTag() end 
function CCScene:getGLServerState() end 
function CCScene:getOrderOfArrival() end 
function CCScene:getPositionX() end 
function CCScene:setGLServerState() end 
function CCScene:setSkewY() end 
function CCScene:setOrderOfArrival() end 
function CCScene:nodeToWorldTransform() end 
function CCScene:getChildren() end 
function CCScene:transformAncestors() end 
function CCScene:getGrid() end 
function CCScene:isRunning() end 
function CCScene:registerScriptHandler() end 
function CCScene:getCamera() end 
function CCScene:isIgnoreAnchorPointForPosition() end 
function CCScene:getUserData() end 
function CCScene:setPositionY() end 
function CCScene:getZOrder() end 
---
-- @return @class CCScene
--
function CCScene:create() end 
