---@classdef CCScale9Sprite
CCScale9Sprite = {}
function CCScale9Sprite:autorelease() end 
function CCScale9Sprite:retain() end 
function CCScale9Sprite:retainCount() end 
function CCScale9Sprite:isEqual() end 
function CCScale9Sprite:copy() end 
function CCScale9Sprite:release() end 
function CCScale9Sprite:isSingleReference() end 
function CCScale9Sprite:visit() end 
function CCScale9Sprite:getUserObject() end 
function CCScale9Sprite:getSkewY() end 
function CCScale9Sprite:convertTouchToNodeSpace() end 
function CCScale9Sprite:getVertexZ() end 
function CCScale9Sprite:setParent() end 
function CCScale9Sprite:boundingBox() end 
function CCScale9Sprite:setVisible() end 
function CCScale9Sprite:stopActionByTag() end 
function CCScale9Sprite:getScaleY() end 
function CCScale9Sprite:setScaleX() end 
function CCScale9Sprite:reorderChild() end 
function CCScale9Sprite:setPositionX() end 
function CCScale9Sprite:removeFromParentAndCleanup() end 
function CCScale9Sprite:setTag() end 
function CCScale9Sprite:getChildrenCount() end 
function CCScale9Sprite:setScale() end 
function CCScale9Sprite:addChild() end 
function CCScale9Sprite:isVisible() end 
function CCScale9Sprite:setActionManager() end 
function CCScale9Sprite:setScheduler() end 
function CCScale9Sprite:getContentSize() end 
function CCScale9Sprite:getAnchorPoint() end 
function CCScale9Sprite:getTag() end 
function CCScale9Sprite:setGrid() end 
function CCScale9Sprite:convertToWorldSpace() end 
function CCScale9Sprite:setSkewX() end 
function CCScale9Sprite:setZOrder() end 
function CCScale9Sprite:worldToNodeTransform() end 
function CCScale9Sprite:getPosition() end 
function CCScale9Sprite:getSkewX() end 
function CCScale9Sprite:getScheduler() end 
function CCScale9Sprite:ignoreAnchorPointForPosition() end 
function CCScale9Sprite:setPosition() end 
function CCScale9Sprite:getParent() end 
function CCScale9Sprite:unscheduleUpdate() end 
function CCScale9Sprite:scheduleUpdateWithPriorityLua() end 
function CCScale9Sprite:removeChildByTag() end 
function CCScale9Sprite:convertToNodeSpaceAR() end 
function CCScale9Sprite:convertTouchToNodeSpaceAR() end 
function CCScale9Sprite:convertToWorldSpaceAR() end 
function CCScale9Sprite:setRotation() end 
function CCScale9Sprite:getComponent() end 
function CCScale9Sprite:convertToNodeSpace() end 
---
-- @return @class CCScale9Sprite
--
function CCScale9Sprite:create() end 
function CCScale9Sprite:getScale() end 
function CCScale9Sprite:getPositionY() end 
function CCScale9Sprite:getChildByTag() end 
function CCScale9Sprite:setContentSize() end 
function CCScale9Sprite:description() end 
function CCScale9Sprite:cleanup() end 
function CCScale9Sprite:getRotation() end 
function CCScale9Sprite:nodeToParentTransform() end 
function CCScale9Sprite:stopAction() end 
function CCScale9Sprite:numberOfRunningActions() end 
function CCScale9Sprite:removeAllChildren() end 
function CCScale9Sprite:runAction() end 
function CCScale9Sprite:setUserObject() end 
function CCScale9Sprite:parentToNodeTransform() end 
function CCScale9Sprite:removeChild() end 
function CCScale9Sprite:getAnchorPointInPoints() end 
function CCScale9Sprite:getScaleX() end 
function CCScale9Sprite:transform() end 
function CCScale9Sprite:getActionManager() end 
function CCScale9Sprite:draw() end 
function CCScale9Sprite:setScaleY() end 
function CCScale9Sprite:unregisterScriptHandler() end 
function CCScale9Sprite:setVertexZ() end 
function CCScale9Sprite:setAnchorPoint() end 
function CCScale9Sprite:getShaderProgram() end 
function CCScale9Sprite:stopAllActions() end 
function CCScale9Sprite:setUserData() end 
function CCScale9Sprite:setShaderProgram() end 
function CCScale9Sprite:getActionByTag() end 
function CCScale9Sprite:getGLServerState() end 
function CCScale9Sprite:getOrderOfArrival() end 
function CCScale9Sprite:getPositionX() end 
function CCScale9Sprite:setGLServerState() end 
function CCScale9Sprite:setSkewY() end 
function CCScale9Sprite:setOrderOfArrival() end 
function CCScale9Sprite:nodeToWorldTransform() end 
function CCScale9Sprite:getChildren() end 
function CCScale9Sprite:transformAncestors() end 
function CCScale9Sprite:getGrid() end 
function CCScale9Sprite:isRunning() end 
function CCScale9Sprite:registerScriptHandler() end 
function CCScale9Sprite:getCamera() end 
function CCScale9Sprite:isIgnoreAnchorPointForPosition() end 
function CCScale9Sprite:getUserData() end 
function CCScale9Sprite:setPositionY() end 
function CCScale9Sprite:getZOrder() end 
function CCScale9Sprite:new() end 
function CCScale9Sprite:delete() end 
function CCScale9Sprite:updateDisplayedColor() end 
function CCScale9Sprite:init() end 
function CCScale9Sprite:setColor() end 
function CCScale9Sprite:getDisplayedColor() end 
function CCScale9Sprite:setCascadeColorEnabled() end 
function CCScale9Sprite:setCascadeOpacityEnabled() end 
function CCScale9Sprite:setOpacity() end 
function CCScale9Sprite:getColor() end 
function CCScale9Sprite:updateDisplayedOpacity() end 
function CCScale9Sprite:getOpacity() end 
function CCScale9Sprite:setOpacityModifyRGB() end 
function CCScale9Sprite:isCascadeOpacityEnabled() end 
function CCScale9Sprite:isOpacityModifyRGB() end 
function CCScale9Sprite:getDisplayedOpacity() end 
function CCScale9Sprite:new_local() end 
function CCScale9Sprite:isCascadeColorEnabled() end 
function CCScale9Sprite:visit() end 
function CCScale9Sprite:getInsetRight() end 
function CCScale9Sprite:new() end 
function CCScale9Sprite:setCapInsets() end 
function CCScale9Sprite:delete() end 
function CCScale9Sprite:init() end 
function CCScale9Sprite:getInsetBottom() end 
function CCScale9Sprite:setInsetTop() end 
function CCScale9Sprite:getCapInsets() end 
function CCScale9Sprite:setColor() end 
function CCScale9Sprite:setInsetBottom() end 
function CCScale9Sprite:new_local() end 
function CCScale9Sprite:getPreferredSize() end 
function CCScale9Sprite:getInsetTop() end 
function CCScale9Sprite:setPreferredSize() end 
function CCScale9Sprite:setOpacity() end 
function CCScale9Sprite:setSpriteFrame() end 
function CCScale9Sprite:updateWithBatchNode() end 
function CCScale9Sprite:isOpacityModifyRGB() end 
function CCScale9Sprite:createWithSpriteFrame() end 
function CCScale9Sprite:createWithSpriteFrameName() end 
function CCScale9Sprite:getOriginalSize() end 
function CCScale9Sprite:setOpacityModifyRGB() end 
---
-- @return @class CCScale9Sprite
--
function CCScale9Sprite:create() end 
function CCScale9Sprite:initWithFile() end 
function CCScale9Sprite:initWithBatchNode() end 
function CCScale9Sprite:initWithSpriteFrame() end 
function CCScale9Sprite:resizableSpriteWithCapInsets() end 
function CCScale9Sprite:getInsetLeft() end 
function CCScale9Sprite:initWithSpriteFrameName() end 
function CCScale9Sprite:setInsetRight() end 
function CCScale9Sprite:setInsetLeft() end 
