---@classdef CCSkin
CCSkin = {}
function CCSkin:autorelease() end 
function CCSkin:retain() end 
function CCSkin:retainCount() end 
function CCSkin:isEqual() end 
function CCSkin:copy() end 
function CCSkin:release() end 
function CCSkin:isSingleReference() end 
function CCSkin:visit() end 
function CCSkin:getUserObject() end 
function CCSkin:getSkewY() end 
function CCSkin:convertTouchToNodeSpace() end 
function CCSkin:getVertexZ() end 
function CCSkin:setParent() end 
function CCSkin:boundingBox() end 
function CCSkin:setVisible() end 
function CCSkin:stopActionByTag() end 
function CCSkin:getScaleY() end 
function CCSkin:setScaleX() end 
function CCSkin:reorderChild() end 
function CCSkin:setPositionX() end 
function CCSkin:removeFromParentAndCleanup() end 
function CCSkin:setTag() end 
function CCSkin:getChildrenCount() end 
function CCSkin:setScale() end 
function CCSkin:addChild() end 
function CCSkin:isVisible() end 
function CCSkin:setActionManager() end 
function CCSkin:setScheduler() end 
function CCSkin:getContentSize() end 
function CCSkin:getAnchorPoint() end 
function CCSkin:getTag() end 
function CCSkin:setGrid() end 
function CCSkin:convertToWorldSpace() end 
function CCSkin:setSkewX() end 
function CCSkin:setZOrder() end 
function CCSkin:worldToNodeTransform() end 
function CCSkin:getPosition() end 
function CCSkin:getSkewX() end 
function CCSkin:getScheduler() end 
function CCSkin:ignoreAnchorPointForPosition() end 
function CCSkin:setPosition() end 
function CCSkin:getParent() end 
function CCSkin:unscheduleUpdate() end 
function CCSkin:scheduleUpdateWithPriorityLua() end 
function CCSkin:removeChildByTag() end 
function CCSkin:convertToNodeSpaceAR() end 
function CCSkin:convertTouchToNodeSpaceAR() end 
function CCSkin:convertToWorldSpaceAR() end 
function CCSkin:setRotation() end 
function CCSkin:getComponent() end 
function CCSkin:convertToNodeSpace() end 
---
-- @return @class CCSkin
--
function CCSkin:create() end 
function CCSkin:getScale() end 
function CCSkin:getPositionY() end 
function CCSkin:getChildByTag() end 
function CCSkin:setContentSize() end 
function CCSkin:description() end 
function CCSkin:cleanup() end 
function CCSkin:getRotation() end 
function CCSkin:nodeToParentTransform() end 
function CCSkin:stopAction() end 
function CCSkin:numberOfRunningActions() end 
function CCSkin:removeAllChildren() end 
function CCSkin:runAction() end 
function CCSkin:setUserObject() end 
function CCSkin:parentToNodeTransform() end 
function CCSkin:removeChild() end 
function CCSkin:getAnchorPointInPoints() end 
function CCSkin:getScaleX() end 
function CCSkin:transform() end 
function CCSkin:getActionManager() end 
function CCSkin:draw() end 
function CCSkin:setScaleY() end 
function CCSkin:unregisterScriptHandler() end 
function CCSkin:setVertexZ() end 
function CCSkin:setAnchorPoint() end 
function CCSkin:getShaderProgram() end 
function CCSkin:stopAllActions() end 
function CCSkin:setUserData() end 
function CCSkin:setShaderProgram() end 
function CCSkin:getActionByTag() end 
function CCSkin:getGLServerState() end 
function CCSkin:getOrderOfArrival() end 
function CCSkin:getPositionX() end 
function CCSkin:setGLServerState() end 
function CCSkin:setSkewY() end 
function CCSkin:setOrderOfArrival() end 
function CCSkin:nodeToWorldTransform() end 
function CCSkin:getChildren() end 
function CCSkin:transformAncestors() end 
function CCSkin:getGrid() end 
function CCSkin:isRunning() end 
function CCSkin:registerScriptHandler() end 
function CCSkin:getCamera() end 
function CCSkin:isIgnoreAnchorPointForPosition() end 
function CCSkin:getUserData() end 
function CCSkin:setPositionY() end 
function CCSkin:getZOrder() end 
function CCSkin:new() end 
function CCSkin:delete() end 
function CCSkin:updateDisplayedColor() end 
function CCSkin:init() end 
function CCSkin:setColor() end 
function CCSkin:getDisplayedColor() end 
function CCSkin:setCascadeColorEnabled() end 
function CCSkin:setCascadeOpacityEnabled() end 
function CCSkin:setOpacity() end 
function CCSkin:getColor() end 
function CCSkin:updateDisplayedOpacity() end 
function CCSkin:getOpacity() end 
function CCSkin:setOpacityModifyRGB() end 
function CCSkin:isCascadeOpacityEnabled() end 
function CCSkin:isOpacityModifyRGB() end 
function CCSkin:getDisplayedOpacity() end 
function CCSkin:new_local() end 
function CCSkin:isCascadeColorEnabled() end 
function CCSkin:getTextureRect() end 
function CCSkin:getBatchNode() end 
function CCSkin:setTextureAtlas() end 
function CCSkin:setRotation() end 
function CCSkin:setBlendFunc() end 
function CCSkin:isFlipX() end 
---
-- @return @class CCSkin
--
function CCSkin:create() end 
function CCSkin:getBlendFunc() end 
function CCSkin:createWithSpriteFrameName() end 
function CCSkin:getTexture() end 
function CCSkin:isFlipY() end 
function CCSkin:createWithSpriteFrame() end 
function CCSkin:createWithTexture() end 
function CCSkin:setVisible() end 
function CCSkin:isTextureRectRotated() end 
function CCSkin:setDisplayFrameWithAnimationName() end 
function CCSkin:setColor() end 
function CCSkin:removeAllChildren() end 
function CCSkin:setTextureRect() end 
function CCSkin:setDirty() end 
function CCSkin:reorderChild() end 
function CCSkin:displayFrame() end 
function CCSkin:setTexture() end 
function CCSkin:setDisplayFrame() end 
function CCSkin:setVertexRect() end 
function CCSkin:setFlipX() end 
function CCSkin:updateTransform() end 
function CCSkin:isFrameDisplayed() end 
function CCSkin:setVertexZ() end 
function CCSkin:isOpacityModifyRGB() end 
function CCSkin:addChild() end 
function CCSkin:getColor() end 
function CCSkin:setSkewX() end 
function CCSkin:getOpacity() end 
function CCSkin:setOpacity() end 
function CCSkin:removeChild() end 
function CCSkin:setScaleX() end 
function CCSkin:setScale() end 
function CCSkin:getTextureAtlas() end 
function CCSkin:setSkewY() end 
function CCSkin:getAtlasIndex() end 
function CCSkin:setOpacityModifyRGB() end 
function CCSkin:sortAllChildren() end 
function CCSkin:setFlipY() end 
function CCSkin:setBatchNode() end 
function CCSkin:getQuad() end 
function CCSkin:ignoreAnchorPointForPosition() end 
function CCSkin:isDirty() end 
function CCSkin:getOffsetPosition() end 
function CCSkin:setAtlasIndex() end 
function CCSkin:setScaleY() end 
function CCSkin:new() end 
---
-- @return @class CCSkin
--
function CCSkin:create() end 
function CCSkin:setBone() end 
function CCSkin:getDisplayName() end 
function CCSkin:setSkinData() end 
function CCSkin:getSkinData() end 
function CCSkin:updateArmatureTransform() end 
function CCSkin:updateTransform() end 
function CCSkin:nodeToWorldTransform() end 
function CCSkin:new_local() end 
function CCSkin:initWithFile() end 
function CCSkin:createWithSpriteFrameName() end 
function CCSkin:nodeToWorldTransformAR() end 
function CCSkin:initWithSpriteFrameName() end 
function CCSkin:getBone() end 
