---@classdef CCSprite
CCSprite = {}
function cc.Sprite:autorelease() end 
function cc.Sprite:retain() end 
function cc.Sprite:retainCount() end 
function cc.Sprite:isEqual() end 
function cc.Sprite:copy() end 
function cc.Sprite:release() end 
function cc.Sprite:isSingleReference() end 
function cc.Sprite:visit() end 
function cc.Sprite:getUserObject() end 
function cc.Sprite:getSkewY() end 
function cc.Sprite:convertTouchToNodeSpace() end 
function cc.Sprite:getVertexZ() end 
function cc.Sprite:setParent() end 
function cc.Sprite:boundingBox() end 
function cc.Sprite:setVisible() end 
function cc.Sprite:stopActionByTag() end 
function cc.Sprite:getScaleY() end 
function cc.Sprite:setScaleX() end 
function cc.Sprite:reorderChild() end 
function cc.Sprite:setPositionX() end 
function cc.Sprite:removeFromParentAndCleanup() end 
function cc.Sprite:setTag() end 
function cc.Sprite:getChildrenCount() end 
function cc.Sprite:setScale() end 
function cc.Sprite:addChild() end 
function cc.Sprite:isVisible() end 
function cc.Sprite:setActionManager() end 
function cc.Sprite:setScheduler() end 
function cc.Sprite:getContentSize() end 
function cc.Sprite:getAnchorPoint() end 
function cc.Sprite:getTag() end 
function cc.Sprite:setGrid() end 
function cc.Sprite:convertToWorldSpace() end 
function cc.Sprite:setSkewX() end 
function cc.Sprite:setZOrder() end 
function cc.Sprite:worldToNodeTransform() end 
function cc.Sprite:getPosition() end 
function cc.Sprite:getSkewX() end 
function cc.Sprite:getScheduler() end 
function cc.Sprite:ignoreAnchorPointForPosition() end 
function cc.Sprite:setPosition() end 
function cc.Sprite:getParent() end 
function cc.Sprite:unscheduleUpdate() end 
function cc.Sprite:scheduleUpdateWithPriorityLua() end 
function cc.Sprite:removeChildByTag() end 
function cc.Sprite:convertToNodeSpaceAR() end 
function cc.Sprite:convertTouchToNodeSpaceAR() end 
function cc.Sprite:convertToWorldSpaceAR() end 
function cc.Sprite:setRotation() end 
function cc.Sprite:getComponent() end 
function cc.Sprite:convertToNodeSpace() end 
---
-- @return @class CCSprite
--
function cc.Sprite:create() end 
function cc.Sprite:getScale() end 
function cc.Sprite:getPositionY() end 
function cc.Sprite:getChildByTag() end 
function cc.Sprite:setContentSize() end 
function cc.Sprite:description() end 
function cc.Sprite:cleanup() end 
function cc.Sprite:getRotation() end 
function cc.Sprite:nodeToParentTransform() end 
function cc.Sprite:stopAction() end 
function cc.Sprite:numberOfRunningActions() end 
function cc.Sprite:removeAllChildren() end 
function cc.Sprite:runAction() end 
function cc.Sprite:setUserObject() end 
function cc.Sprite:parentToNodeTransform() end 
function cc.Sprite:removeChild() end 
function cc.Sprite:getAnchorPointInPoints() end 
function cc.Sprite:getScaleX() end 
function cc.Sprite:transform() end 
function cc.Sprite:getActionManager() end 
function cc.Sprite:draw() end 
function cc.Sprite:setScaleY() end 
function cc.Sprite:unregisterScriptHandler() end 
function cc.Sprite:setVertexZ() end 
function cc.Sprite:setAnchorPoint() end 
function cc.Sprite:getShaderProgram() end 
function cc.Sprite:stopAllActions() end 
function cc.Sprite:setUserData() end 
function cc.Sprite:setShaderProgram() end 
function cc.Sprite:getActionByTag() end 
function cc.Sprite:getGLServerState() end 
function cc.Sprite:getOrderOfArrival() end 
function cc.Sprite:getPositionX() end 
function cc.Sprite:setGLServerState() end 
function cc.Sprite:setSkewY() end 
function cc.Sprite:setOrderOfArrival() end 
function cc.Sprite:nodeToWorldTransform() end 
function cc.Sprite:getChildren() end 
function cc.Sprite:transformAncestors() end 
function cc.Sprite:getGrid() end 
function cc.Sprite:isRunning() end 
function cc.Sprite:registerScriptHandler() end 
function cc.Sprite:getCamera() end 
function cc.Sprite:isIgnoreAnchorPointForPosition() end 
function cc.Sprite:getUserData() end 
function cc.Sprite:setPositionY() end 
function cc.Sprite:getZOrder() end 
function cc.Sprite:new() end 
function cc.Sprite:delete() end 
function cc.Sprite:updateDisplayedColor() end 
function cc.Sprite:init() end 
function cc.Sprite:setColor() end 
function cc.Sprite:getDisplayedColor() end 
function cc.Sprite:setCascadeColorEnabled() end 
function cc.Sprite:setCascadeOpacityEnabled() end 
function cc.Sprite:setOpacity() end 
function cc.Sprite:getColor() end 
function cc.Sprite:updateDisplayedOpacity() end 
function cc.Sprite:getOpacity() end 
function cc.Sprite:setOpacityModifyRGB() end 
function cc.Sprite:isCascadeOpacityEnabled() end 
function cc.Sprite:isOpacityModifyRGB() end 
function cc.Sprite:getDisplayedOpacity() end 
function cc.Sprite:new_local() end 
function cc.Sprite:isCascadeColorEnabled() end 
function cc.Sprite:getTextureRect() end 
function cc.Sprite:getBatchNode() end 
function cc.Sprite:setTextureAtlas() end 
function cc.Sprite:setRotation() end 
function cc.Sprite:setBlendFunc() end 
function cc.Sprite:isFlipX() end 
---
-- @return @class CCSprite
--
function cc.Sprite:create() end 
function cc.Sprite:getBlendFunc() end 
function cc.Sprite:createWithSpriteFrameName() end 
function cc.Sprite:getTexture() end 
function cc.Sprite:isFlipY() end 
function cc.Sprite:createWithSpriteFrame() end 
function cc.Sprite:createWithTexture() end 
function cc.Sprite:setVisible() end 
function cc.Sprite:isTextureRectRotated() end 
function cc.Sprite:setDisplayFrameWithAnimationName() end 
function cc.Sprite:setColor() end 
function cc.Sprite:removeAllChildren() end 
function cc.Sprite:setTextureRect() end 
function cc.Sprite:setDirty() end 
function cc.Sprite:reorderChild() end 
function cc.Sprite:displayFrame() end 
function cc.Sprite:setTexture() end 
function cc.Sprite:setDisplayFrame() end 
function cc.Sprite:setVertexRect() end 
function cc.Sprite:setFlipX() end 
function cc.Sprite:updateTransform() end 
function cc.Sprite:isFrameDisplayed() end 
function cc.Sprite:setVertexZ() end 
function cc.Sprite:isOpacityModifyRGB() end 
function cc.Sprite:addChild() end 
function cc.Sprite:getColor() end 
function cc.Sprite:setSkewX() end 
function cc.Sprite:getOpacity() end 
function cc.Sprite:setOpacity() end 
function cc.Sprite:removeChild() end 
function cc.Sprite:setScaleX() end 
function cc.Sprite:setScale() end 
function cc.Sprite:getTextureAtlas() end 
function cc.Sprite:setSkewY() end 
function cc.Sprite:getAtlasIndex() end 
function cc.Sprite:setOpacityModifyRGB() end 
function cc.Sprite:sortAllChildren() end 
function cc.Sprite:setFlipY() end 
function cc.Sprite:setBatchNode() end 
function cc.Sprite:getQuad() end 
function cc.Sprite:ignoreAnchorPointForPosition() end 
function cc.Sprite:isDirty() end 
function cc.Sprite:getOffsetPosition() end 
function cc.Sprite:setAtlasIndex() end 
function cc.Sprite:setScaleY() end 
