---@classdef CCSpriteBatchNode
CCSpriteBatchNode = {}
function CCSpriteBatchNode:autorelease() end 
function CCSpriteBatchNode:retain() end 
function CCSpriteBatchNode:retainCount() end 
function CCSpriteBatchNode:isEqual() end 
function CCSpriteBatchNode:copy() end 
function CCSpriteBatchNode:release() end 
function CCSpriteBatchNode:isSingleReference() end 
function CCSpriteBatchNode:visit() end 
function CCSpriteBatchNode:getUserObject() end 
function CCSpriteBatchNode:getSkewY() end 
function CCSpriteBatchNode:convertTouchToNodeSpace() end 
function CCSpriteBatchNode:getVertexZ() end 
function CCSpriteBatchNode:setParent() end 
function CCSpriteBatchNode:boundingBox() end 
function CCSpriteBatchNode:setVisible() end 
function CCSpriteBatchNode:stopActionByTag() end 
function CCSpriteBatchNode:getScaleY() end 
function CCSpriteBatchNode:setScaleX() end 
function CCSpriteBatchNode:reorderChild() end 
function CCSpriteBatchNode:setPositionX() end 
function CCSpriteBatchNode:removeFromParentAndCleanup() end 
function CCSpriteBatchNode:setTag() end 
function CCSpriteBatchNode:getChildrenCount() end 
function CCSpriteBatchNode:setScale() end 
function CCSpriteBatchNode:addChild() end 
function CCSpriteBatchNode:isVisible() end 
function CCSpriteBatchNode:setActionManager() end 
function CCSpriteBatchNode:setScheduler() end 
function CCSpriteBatchNode:getContentSize() end 
function CCSpriteBatchNode:getAnchorPoint() end 
function CCSpriteBatchNode:getTag() end 
function CCSpriteBatchNode:setGrid() end 
function CCSpriteBatchNode:convertToWorldSpace() end 
function CCSpriteBatchNode:setSkewX() end 
function CCSpriteBatchNode:setZOrder() end 
function CCSpriteBatchNode:worldToNodeTransform() end 
function CCSpriteBatchNode:getPosition() end 
function CCSpriteBatchNode:getSkewX() end 
function CCSpriteBatchNode:getScheduler() end 
function CCSpriteBatchNode:ignoreAnchorPointForPosition() end 
function CCSpriteBatchNode:setPosition() end 
function CCSpriteBatchNode:getParent() end 
function CCSpriteBatchNode:unscheduleUpdate() end 
function CCSpriteBatchNode:scheduleUpdateWithPriorityLua() end 
function CCSpriteBatchNode:removeChildByTag() end 
function CCSpriteBatchNode:convertToNodeSpaceAR() end 
function CCSpriteBatchNode:convertTouchToNodeSpaceAR() end 
function CCSpriteBatchNode:convertToWorldSpaceAR() end 
function CCSpriteBatchNode:setRotation() end 
function CCSpriteBatchNode:getComponent() end 
function CCSpriteBatchNode:convertToNodeSpace() end 
---
-- @return @class CCSpriteBatchNode
--
function CCSpriteBatchNode:create() end 
function CCSpriteBatchNode:getScale() end 
function CCSpriteBatchNode:getPositionY() end 
function CCSpriteBatchNode:getChildByTag() end 
function CCSpriteBatchNode:setContentSize() end 
function CCSpriteBatchNode:description() end 
function CCSpriteBatchNode:cleanup() end 
function CCSpriteBatchNode:getRotation() end 
function CCSpriteBatchNode:nodeToParentTransform() end 
function CCSpriteBatchNode:stopAction() end 
function CCSpriteBatchNode:numberOfRunningActions() end 
function CCSpriteBatchNode:removeAllChildren() end 
function CCSpriteBatchNode:runAction() end 
function CCSpriteBatchNode:setUserObject() end 
function CCSpriteBatchNode:parentToNodeTransform() end 
function CCSpriteBatchNode:removeChild() end 
function CCSpriteBatchNode:getAnchorPointInPoints() end 
function CCSpriteBatchNode:getScaleX() end 
function CCSpriteBatchNode:transform() end 
function CCSpriteBatchNode:getActionManager() end 
function CCSpriteBatchNode:draw() end 
function CCSpriteBatchNode:setScaleY() end 
function CCSpriteBatchNode:unregisterScriptHandler() end 
function CCSpriteBatchNode:setVertexZ() end 
function CCSpriteBatchNode:setAnchorPoint() end 
function CCSpriteBatchNode:getShaderProgram() end 
function CCSpriteBatchNode:stopAllActions() end 
function CCSpriteBatchNode:setUserData() end 
function CCSpriteBatchNode:setShaderProgram() end 
function CCSpriteBatchNode:getActionByTag() end 
function CCSpriteBatchNode:getGLServerState() end 
function CCSpriteBatchNode:getOrderOfArrival() end 
function CCSpriteBatchNode:getPositionX() end 
function CCSpriteBatchNode:setGLServerState() end 
function CCSpriteBatchNode:setSkewY() end 
function CCSpriteBatchNode:setOrderOfArrival() end 
function CCSpriteBatchNode:nodeToWorldTransform() end 
function CCSpriteBatchNode:getChildren() end 
function CCSpriteBatchNode:transformAncestors() end 
function CCSpriteBatchNode:getGrid() end 
function CCSpriteBatchNode:isRunning() end 
function CCSpriteBatchNode:registerScriptHandler() end 
function CCSpriteBatchNode:getCamera() end 
function CCSpriteBatchNode:isIgnoreAnchorPointForPosition() end 
function CCSpriteBatchNode:getUserData() end 
function CCSpriteBatchNode:setPositionY() end 
function CCSpriteBatchNode:getZOrder() end 
function CCSpriteBatchNode:setTextureAtlas() end 
function CCSpriteBatchNode:setBlendFunc() end 
---
-- @return @class CCSpriteBatchNode
--
function CCSpriteBatchNode:create() end 
function CCSpriteBatchNode:getTexture() end 
function CCSpriteBatchNode:appendChild() end 
function CCSpriteBatchNode:removeAllChildren() end 
function CCSpriteBatchNode:createWithTexture() end 
function CCSpriteBatchNode:removeChild() end 
function CCSpriteBatchNode:rebuildIndexInOrder() end 
function CCSpriteBatchNode:atlasIndexForChild() end 
function CCSpriteBatchNode:increaseAtlasCapacity() end 
function CCSpriteBatchNode:addChild() end 
function CCSpriteBatchNode:setTexture() end 
function CCSpriteBatchNode:getTextureAtlas() end 
function CCSpriteBatchNode:removeChildAtIndex() end 
function CCSpriteBatchNode:getDescendants() end 
function CCSpriteBatchNode:sortAllChildren() end 
function CCSpriteBatchNode:getBlendFunc() end 
function CCSpriteBatchNode:reorderBatch() end 
function CCSpriteBatchNode:insertChild() end 
function CCSpriteBatchNode:highestAtlasIndexInChild() end 
function CCSpriteBatchNode:removeSpriteFromAtlas() end 
function CCSpriteBatchNode:lowestAtlasIndexInChild() end 
function CCSpriteBatchNode:reorderChild() end 
