---@classdef CCTableViewCell
CCTableViewCell = {}
function CCTableViewCell:autorelease() end 
function CCTableViewCell:retain() end 
function CCTableViewCell:retainCount() end 
function CCTableViewCell:isEqual() end 
function CCTableViewCell:copy() end 
function CCTableViewCell:release() end 
function CCTableViewCell:isSingleReference() end 
function CCTableViewCell:visit() end 
function CCTableViewCell:getUserObject() end 
function CCTableViewCell:getSkewY() end 
function CCTableViewCell:convertTouchToNodeSpace() end 
function CCTableViewCell:getVertexZ() end 
function CCTableViewCell:setParent() end 
function CCTableViewCell:boundingBox() end 
function CCTableViewCell:setVisible() end 
function CCTableViewCell:stopActionByTag() end 
function CCTableViewCell:getScaleY() end 
function CCTableViewCell:setScaleX() end 
function CCTableViewCell:reorderChild() end 
function CCTableViewCell:setPositionX() end 
function CCTableViewCell:removeFromParentAndCleanup() end 
function CCTableViewCell:setTag() end 
function CCTableViewCell:getChildrenCount() end 
function CCTableViewCell:setScale() end 
function CCTableViewCell:addChild() end 
function CCTableViewCell:isVisible() end 
function CCTableViewCell:setActionManager() end 
function CCTableViewCell:setScheduler() end 
function CCTableViewCell:getContentSize() end 
function CCTableViewCell:getAnchorPoint() end 
function CCTableViewCell:getTag() end 
function CCTableViewCell:setGrid() end 
function CCTableViewCell:convertToWorldSpace() end 
function CCTableViewCell:setSkewX() end 
function CCTableViewCell:setZOrder() end 
function CCTableViewCell:worldToNodeTransform() end 
function CCTableViewCell:getPosition() end 
function CCTableViewCell:getSkewX() end 
function CCTableViewCell:getScheduler() end 
function CCTableViewCell:ignoreAnchorPointForPosition() end 
function CCTableViewCell:setPosition() end 
function CCTableViewCell:getParent() end 
function CCTableViewCell:unscheduleUpdate() end 
function CCTableViewCell:scheduleUpdateWithPriorityLua() end 
function CCTableViewCell:removeChildByTag() end 
function CCTableViewCell:convertToNodeSpaceAR() end 
function CCTableViewCell:convertTouchToNodeSpaceAR() end 
function CCTableViewCell:convertToWorldSpaceAR() end 
function CCTableViewCell:setRotation() end 
function CCTableViewCell:getComponent() end 
function CCTableViewCell:convertToNodeSpace() end 
---
-- @return @class CCTableViewCell
--
function CCTableViewCell:create() end 
function CCTableViewCell:getScale() end 
function CCTableViewCell:getPositionY() end 
function CCTableViewCell:getChildByTag() end 
function CCTableViewCell:setContentSize() end 
function CCTableViewCell:description() end 
function CCTableViewCell:cleanup() end 
function CCTableViewCell:getRotation() end 
function CCTableViewCell:nodeToParentTransform() end 
function CCTableViewCell:stopAction() end 
function CCTableViewCell:numberOfRunningActions() end 
function CCTableViewCell:removeAllChildren() end 
function CCTableViewCell:runAction() end 
function CCTableViewCell:setUserObject() end 
function CCTableViewCell:parentToNodeTransform() end 
function CCTableViewCell:removeChild() end 
function CCTableViewCell:getAnchorPointInPoints() end 
function CCTableViewCell:getScaleX() end 
function CCTableViewCell:transform() end 
function CCTableViewCell:getActionManager() end 
function CCTableViewCell:draw() end 
function CCTableViewCell:setScaleY() end 
function CCTableViewCell:unregisterScriptHandler() end 
function CCTableViewCell:setVertexZ() end 
function CCTableViewCell:setAnchorPoint() end 
function CCTableViewCell:getShaderProgram() end 
function CCTableViewCell:stopAllActions() end 
function CCTableViewCell:setUserData() end 
function CCTableViewCell:setShaderProgram() end 
function CCTableViewCell:getActionByTag() end 
function CCTableViewCell:getGLServerState() end 
function CCTableViewCell:getOrderOfArrival() end 
function CCTableViewCell:getPositionX() end 
function CCTableViewCell:setGLServerState() end 
function CCTableViewCell:setSkewY() end 
function CCTableViewCell:setOrderOfArrival() end 
function CCTableViewCell:nodeToWorldTransform() end 
function CCTableViewCell:getChildren() end 
function CCTableViewCell:transformAncestors() end 
function CCTableViewCell:getGrid() end 
function CCTableViewCell:isRunning() end 
function CCTableViewCell:registerScriptHandler() end 
function CCTableViewCell:getCamera() end 
function CCTableViewCell:isIgnoreAnchorPointForPosition() end 
function CCTableViewCell:getUserData() end 
function CCTableViewCell:setPositionY() end 
function CCTableViewCell:getZOrder() end 
function CCTableViewCell:new() end 
function CCTableViewCell:setObjectID() end 
function CCTableViewCell:reset() end 
function CCTableViewCell:getObjectID() end 
function CCTableViewCell:setIdx() end 
function CCTableViewCell:getIdx() end 
