---@classdef CCTableView
CCTableView = {}
function CCTableView:autorelease() end 
function CCTableView:retain() end 
function CCTableView:retainCount() end 
function CCTableView:isEqual() end 
function CCTableView:copy() end 
function CCTableView:release() end 
function CCTableView:isSingleReference() end 
function CCTableView:visit() end 
function CCTableView:getUserObject() end 
function CCTableView:getSkewY() end 
function CCTableView:convertTouchToNodeSpace() end 
function CCTableView:getVertexZ() end 
function CCTableView:setParent() end 
function CCTableView:boundingBox() end 
function CCTableView:setVisible() end 
function CCTableView:stopActionByTag() end 
function CCTableView:getScaleY() end 
function CCTableView:setScaleX() end 
function CCTableView:reorderChild() end 
function CCTableView:setPositionX() end 
function CCTableView:removeFromParentAndCleanup() end 
function CCTableView:setTag() end 
function CCTableView:getChildrenCount() end 
function CCTableView:setScale() end 
function CCTableView:addChild() end 
function CCTableView:isVisible() end 
function CCTableView:setActionManager() end 
function CCTableView:setScheduler() end 
function CCTableView:getContentSize() end 
function CCTableView:getAnchorPoint() end 
function CCTableView:getTag() end 
function CCTableView:setGrid() end 
function CCTableView:convertToWorldSpace() end 
function CCTableView:setSkewX() end 
function CCTableView:setZOrder() end 
function CCTableView:worldToNodeTransform() end 
function CCTableView:getPosition() end 
function CCTableView:getSkewX() end 
function CCTableView:getScheduler() end 
function CCTableView:ignoreAnchorPointForPosition() end 
function CCTableView:setPosition() end 
function CCTableView:getParent() end 
function CCTableView:unscheduleUpdate() end 
function CCTableView:scheduleUpdateWithPriorityLua() end 
function CCTableView:removeChildByTag() end 
function CCTableView:convertToNodeSpaceAR() end 
function CCTableView:convertTouchToNodeSpaceAR() end 
function CCTableView:convertToWorldSpaceAR() end 
function CCTableView:setRotation() end 
function CCTableView:getComponent() end 
function CCTableView:convertToNodeSpace() end 
---
-- @return @class CCTableView
--
function CCTableView:create() end 
function CCTableView:getScale() end 
function CCTableView:getPositionY() end 
function CCTableView:getChildByTag() end 
function CCTableView:setContentSize() end 
function CCTableView:description() end 
function CCTableView:cleanup() end 
function CCTableView:getRotation() end 
function CCTableView:nodeToParentTransform() end 
function CCTableView:stopAction() end 
function CCTableView:numberOfRunningActions() end 
function CCTableView:removeAllChildren() end 
function CCTableView:runAction() end 
function CCTableView:setUserObject() end 
function CCTableView:parentToNodeTransform() end 
function CCTableView:removeChild() end 
function CCTableView:getAnchorPointInPoints() end 
function CCTableView:getScaleX() end 
function CCTableView:transform() end 
function CCTableView:getActionManager() end 
function CCTableView:draw() end 
function CCTableView:setScaleY() end 
function CCTableView:unregisterScriptHandler() end 
function CCTableView:setVertexZ() end 
function CCTableView:setAnchorPoint() end 
function CCTableView:getShaderProgram() end 
function CCTableView:stopAllActions() end 
function CCTableView:setUserData() end 
function CCTableView:setShaderProgram() end 
function CCTableView:getActionByTag() end 
function CCTableView:getGLServerState() end 
function CCTableView:getOrderOfArrival() end 
function CCTableView:getPositionX() end 
function CCTableView:setGLServerState() end 
function CCTableView:setSkewY() end 
function CCTableView:setOrderOfArrival() end 
function CCTableView:nodeToWorldTransform() end 
function CCTableView:getChildren() end 
function CCTableView:transformAncestors() end 
function CCTableView:getGrid() end 
function CCTableView:isRunning() end 
function CCTableView:registerScriptHandler() end 
function CCTableView:getCamera() end 
function CCTableView:isIgnoreAnchorPointForPosition() end 
function CCTableView:getUserData() end 
function CCTableView:setPositionY() end 
function CCTableView:getZOrder() end 
function CCTableView:isTouchEnabled() end 
function CCTableView:unregisterScriptKeypadHandler() end 
function CCTableView:registerScriptAccelerateHandler() end 
---
-- @return @class CCTableView
--
function CCTableView:create() end 
function CCTableView:setAccelerometerEnabled() end 
function CCTableView:registerScriptKeypadHandler() end 
function CCTableView:setTouchMode() end 
function CCTableView:isAccelerometerEnabled() end 
function CCTableView:setTouchEnabled() end 
function CCTableView:setTouchPriority() end 
function CCTableView:unregisterScriptAccelerateHandler() end 
function CCTableView:unregisterScriptTouchHandler() end 
function CCTableView:setKeypadEnabled() end 
function CCTableView:registerScriptTouchHandler() end 
function CCTableView:getTouchPriority() end 
function CCTableView:isKeypadEnabled() end 
function CCTableView:getTouchMode() end 
function CCTableView:ccTouchMoved() end 
function CCTableView:new() end 
function CCTableView:getScriptHandler() end 
function CCTableView:setZoomScale() end 
function CCTableView:delete() end 
function CCTableView:init() end 
function CCTableView:ccTouchEnded() end 
function CCTableView:setDirection() end 
function CCTableView:registerScriptHandler() end 
function CCTableView:updateInset() end 
function CCTableView:setViewSize() end 
function CCTableView:setDelegate() end 
function CCTableView:new_local() end 
function CCTableView:unregisterScriptHandler() end 
function CCTableView:minContainerOffset() end 
function CCTableView:initWithViewSize() end 
function CCTableView:setContainer() end 
function CCTableView:setTouchEnabled() end 
function CCTableView:ccTouchCancelled() end 
function CCTableView:setClippingToBounds() end 
function CCTableView:isClippingToBounds() end 
function CCTableView:setContentOffset() end 
function CCTableView:getContainer() end 
function CCTableView:setBounceable() end 
function CCTableView:addChild() end 
function CCTableView:getViewSize() end 
function CCTableView:setZoomScaleInDuration() end 
function CCTableView:ccTouchBegan() end 
function CCTableView:resume() end 
function CCTableView:getDirection() end 
function CCTableView:getContentSize() end 
function CCTableView:isBounceable() end 
function CCTableView:isTouchMoved() end 
function CCTableView:isNodeVisible() end 
function CCTableView:pause() end 
function CCTableView:getZoomScale() end 
function CCTableView:maxContainerOffset() end 
function CCTableView:setContentOffsetInDuration() end 
function CCTableView:registerWithTouchDispatcher() end 
function CCTableView:getContentOffset() end 
---
-- @return @class CCTableView
--
function CCTableView:create() end 
function CCTableView:isDragging() end 
function CCTableView:ccTouchMoved() end 
function CCTableView:new() end 
function CCTableView:delete() end 
function CCTableView:insertCellAtIndex() end 
function CCTableView:ccTouchEnded() end 
function CCTableView:setVerticalFillOrder() end 
function CCTableView:getVerticalFillOrder() end 
function CCTableView:new_local() end 
function CCTableView:cellAtIndex() end 
function CCTableView:initWithViewSize() end 
function CCTableView:registerScriptHandler() end 
function CCTableView:updateCellAtIndex() end 
---
-- @return @class CCTableView
--
function CCTableView:create() end 
function CCTableView:setDataSource() end 
function CCTableView:setDelegate() end 
function CCTableView:unregisterAllScriptHandler() end 
function CCTableView:reloadData() end 
function CCTableView:ccTouchCancelled() end 
function CCTableView:scrollViewDidZoom() end 
function CCTableView:removeCellAtIndex() end 
function CCTableView:dequeueCell() end 
function CCTableView:ccTouchBegan() end 
function CCTableView:scrollViewDidScroll() end 
