---@classdef CCTexture2D
CCTexture2D = {}
function CCTexture2D:autorelease() end 
function CCTexture2D:retain() end 
function CCTexture2D:retainCount() end 
function CCTexture2D:isEqual() end 
function CCTexture2D:copy() end 
function CCTexture2D:release() end 
function CCTexture2D:isSingleReference() end 
function CCTexture2D:getPixelsWide() end 
function CCTexture2D:getPixelsHigh() end 
function CCTexture2D:defaultAlphaPixelFormat() end 
function CCTexture2D:hasPremultipliedAlpha() end 
function CCTexture2D:drawInRect() end 
function CCTexture2D:setMaxS() end 
function CCTexture2D:generateMipmap() end 
function CCTexture2D:getName() end 
function CCTexture2D:keepData() end 
function CCTexture2D:setAntiAliasTexParameters() end 
function CCTexture2D:setAliasTexParameters() end 
function CCTexture2D:getPixelFormat() end 
function CCTexture2D:setDefaultAlphaPixelFormat() end 
function CCTexture2D:getContentSize() end 
function CCTexture2D:releaseData() end 
function CCTexture2D:setTexParameters() end 
function CCTexture2D:hasMipmaps() end 
function CCTexture2D:setMaxT() end 
function CCTexture2D:stringForFormat() end 
function CCTexture2D:getContentSizeInPixels() end 
function CCTexture2D:bitsPerPixelForFormat() end 
function CCTexture2D:drawAtPoint() end 
function CCTexture2D:getMaxT() end 
function CCTexture2D:getMaxS() end 
