---@classdef CCTextFieldTTF
CCTextFieldTTF = {}
function CCTextFieldTTF:autorelease() end 
function CCTextFieldTTF:retain() end 
function CCTextFieldTTF:retainCount() end 
function CCTextFieldTTF:isEqual() end 
function CCTextFieldTTF:copy() end 
function CCTextFieldTTF:release() end 
function CCTextFieldTTF:isSingleReference() end 
function CCTextFieldTTF:visit() end 
function CCTextFieldTTF:getUserObject() end 
function CCTextFieldTTF:getSkewY() end 
function CCTextFieldTTF:convertTouchToNodeSpace() end 
function CCTextFieldTTF:getVertexZ() end 
function CCTextFieldTTF:setParent() end 
function CCTextFieldTTF:boundingBox() end 
function CCTextFieldTTF:setVisible() end 
function CCTextFieldTTF:stopActionByTag() end 
function CCTextFieldTTF:getScaleY() end 
function CCTextFieldTTF:setScaleX() end 
function CCTextFieldTTF:reorderChild() end 
function CCTextFieldTTF:setPositionX() end 
function CCTextFieldTTF:removeFromParentAndCleanup() end 
function CCTextFieldTTF:setTag() end 
function CCTextFieldTTF:getChildrenCount() end 
function CCTextFieldTTF:setScale() end 
function CCTextFieldTTF:addChild() end 
function CCTextFieldTTF:isVisible() end 
function CCTextFieldTTF:setActionManager() end 
function CCTextFieldTTF:setScheduler() end 
function CCTextFieldTTF:getContentSize() end 
function CCTextFieldTTF:getAnchorPoint() end 
function CCTextFieldTTF:getTag() end 
function CCTextFieldTTF:setGrid() end 
function CCTextFieldTTF:convertToWorldSpace() end 
function CCTextFieldTTF:setSkewX() end 
function CCTextFieldTTF:setZOrder() end 
function CCTextFieldTTF:worldToNodeTransform() end 
function CCTextFieldTTF:getPosition() end 
function CCTextFieldTTF:getSkewX() end 
function CCTextFieldTTF:getScheduler() end 
function CCTextFieldTTF:ignoreAnchorPointForPosition() end 
function CCTextFieldTTF:setPosition() end 
function CCTextFieldTTF:getParent() end 
function CCTextFieldTTF:unscheduleUpdate() end 
function CCTextFieldTTF:scheduleUpdateWithPriorityLua() end 
function CCTextFieldTTF:removeChildByTag() end 
function CCTextFieldTTF:convertToNodeSpaceAR() end 
function CCTextFieldTTF:convertTouchToNodeSpaceAR() end 
function CCTextFieldTTF:convertToWorldSpaceAR() end 
function CCTextFieldTTF:setRotation() end 
function CCTextFieldTTF:getComponent() end 
function CCTextFieldTTF:convertToNodeSpace() end 
---
-- @return @class CCTextFieldTTF
--
function CCTextFieldTTF:create() end 
function CCTextFieldTTF:getScale() end 
function CCTextFieldTTF:getPositionY() end 
function CCTextFieldTTF:getChildByTag() end 
function CCTextFieldTTF:setContentSize() end 
function CCTextFieldTTF:description() end 
function CCTextFieldTTF:cleanup() end 
function CCTextFieldTTF:getRotation() end 
function CCTextFieldTTF:nodeToParentTransform() end 
function CCTextFieldTTF:stopAction() end 
function CCTextFieldTTF:numberOfRunningActions() end 
function CCTextFieldTTF:removeAllChildren() end 
function CCTextFieldTTF:runAction() end 
function CCTextFieldTTF:setUserObject() end 
function CCTextFieldTTF:parentToNodeTransform() end 
function CCTextFieldTTF:removeChild() end 
function CCTextFieldTTF:getAnchorPointInPoints() end 
function CCTextFieldTTF:getScaleX() end 
function CCTextFieldTTF:transform() end 
function CCTextFieldTTF:getActionManager() end 
function CCTextFieldTTF:draw() end 
function CCTextFieldTTF:setScaleY() end 
function CCTextFieldTTF:unregisterScriptHandler() end 
function CCTextFieldTTF:setVertexZ() end 
function CCTextFieldTTF:setAnchorPoint() end 
function CCTextFieldTTF:getShaderProgram() end 
function CCTextFieldTTF:stopAllActions() end 
function CCTextFieldTTF:setUserData() end 
function CCTextFieldTTF:setShaderProgram() end 
function CCTextFieldTTF:getActionByTag() end 
function CCTextFieldTTF:getGLServerState() end 
function CCTextFieldTTF:getOrderOfArrival() end 
function CCTextFieldTTF:getPositionX() end 
function CCTextFieldTTF:setGLServerState() end 
function CCTextFieldTTF:setSkewY() end 
function CCTextFieldTTF:setOrderOfArrival() end 
function CCTextFieldTTF:nodeToWorldTransform() end 
function CCTextFieldTTF:getChildren() end 
function CCTextFieldTTF:transformAncestors() end 
function CCTextFieldTTF:getGrid() end 
function CCTextFieldTTF:isRunning() end 
function CCTextFieldTTF:registerScriptHandler() end 
function CCTextFieldTTF:getCamera() end 
function CCTextFieldTTF:isIgnoreAnchorPointForPosition() end 
function CCTextFieldTTF:getUserData() end 
function CCTextFieldTTF:setPositionY() end 
function CCTextFieldTTF:getZOrder() end 
function CCTextFieldTTF:new() end 
function CCTextFieldTTF:delete() end 
function CCTextFieldTTF:updateDisplayedColor() end 
function CCTextFieldTTF:init() end 
function CCTextFieldTTF:setColor() end 
function CCTextFieldTTF:getDisplayedColor() end 
function CCTextFieldTTF:setCascadeColorEnabled() end 
function CCTextFieldTTF:setCascadeOpacityEnabled() end 
function CCTextFieldTTF:setOpacity() end 
function CCTextFieldTTF:getColor() end 
function CCTextFieldTTF:updateDisplayedOpacity() end 
function CCTextFieldTTF:getOpacity() end 
function CCTextFieldTTF:setOpacityModifyRGB() end 
function CCTextFieldTTF:isCascadeOpacityEnabled() end 
function CCTextFieldTTF:isOpacityModifyRGB() end 
function CCTextFieldTTF:getDisplayedOpacity() end 
function CCTextFieldTTF:new_local() end 
function CCTextFieldTTF:isCascadeColorEnabled() end 
function CCTextFieldTTF:getTextureRect() end 
function CCTextFieldTTF:getBatchNode() end 
function CCTextFieldTTF:setTextureAtlas() end 
function CCTextFieldTTF:setRotation() end 
function CCTextFieldTTF:setBlendFunc() end 
function CCTextFieldTTF:isFlipX() end 
---
-- @return @class CCTextFieldTTF
--
function CCTextFieldTTF:create() end 
function CCTextFieldTTF:getBlendFunc() end 
function CCTextFieldTTF:createWithSpriteFrameName() end 
function CCTextFieldTTF:getTexture() end 
function CCTextFieldTTF:isFlipY() end 
function CCTextFieldTTF:createWithSpriteFrame() end 
function CCTextFieldTTF:createWithTexture() end 
function CCTextFieldTTF:setVisible() end 
function CCTextFieldTTF:isTextureRectRotated() end 
function CCTextFieldTTF:setDisplayFrameWithAnimationName() end 
function CCTextFieldTTF:setColor() end 
function CCTextFieldTTF:removeAllChildren() end 
function CCTextFieldTTF:setTextureRect() end 
function CCTextFieldTTF:setDirty() end 
function CCTextFieldTTF:reorderChild() end 
function CCTextFieldTTF:displayFrame() end 
function CCTextFieldTTF:setTexture() end 
function CCTextFieldTTF:setDisplayFrame() end 
function CCTextFieldTTF:setVertexRect() end 
function CCTextFieldTTF:setFlipX() end 
function CCTextFieldTTF:updateTransform() end 
function CCTextFieldTTF:isFrameDisplayed() end 
function CCTextFieldTTF:setVertexZ() end 
function CCTextFieldTTF:isOpacityModifyRGB() end 
function CCTextFieldTTF:addChild() end 
function CCTextFieldTTF:getColor() end 
function CCTextFieldTTF:setSkewX() end 
function CCTextFieldTTF:getOpacity() end 
function CCTextFieldTTF:setOpacity() end 
function CCTextFieldTTF:removeChild() end 
function CCTextFieldTTF:setScaleX() end 
function CCTextFieldTTF:setScale() end 
function CCTextFieldTTF:getTextureAtlas() end 
function CCTextFieldTTF:setSkewY() end 
function CCTextFieldTTF:getAtlasIndex() end 
function CCTextFieldTTF:setOpacityModifyRGB() end 
function CCTextFieldTTF:sortAllChildren() end 
function CCTextFieldTTF:setFlipY() end 
function CCTextFieldTTF:setBatchNode() end 
function CCTextFieldTTF:getQuad() end 
function CCTextFieldTTF:ignoreAnchorPointForPosition() end 
function CCTextFieldTTF:isDirty() end 
function CCTextFieldTTF:getOffsetPosition() end 
function CCTextFieldTTF:setAtlasIndex() end 
function CCTextFieldTTF:setScaleY() end 
function CCTextFieldTTF:getVerticalAlignment() end 
function CCTextFieldTTF:new() end 
function CCTextFieldTTF:setFontName() end 
function CCTextFieldTTF:delete() end 
function CCTextFieldTTF:getFontName() end 
function CCTextFieldTTF:getString() end 
---
-- @return @class CCTextFieldTTF
--
function CCTextFieldTTF:create() end 
function CCTextFieldTTF:setVerticalAlignment() end 
function CCTextFieldTTF:setFontSize() end 
function CCTextFieldTTF:getFontSize() end 
function CCTextFieldTTF:init() end 
function CCTextFieldTTF:getDimensions() end 
function CCTextFieldTTF:new_local() end 
function CCTextFieldTTF:setHorizontalAlignment() end 
function CCTextFieldTTF:setString() end 
function CCTextFieldTTF:getHorizontalAlignment() end 
function CCTextFieldTTF:setDimensions() end 
function CCTextFieldTTF:setColorSpaceHolder() end 
function CCTextFieldTTF:getCharCount() end 
function CCTextFieldTTF:getString() end 
function CCTextFieldTTF:getColorSpaceHolder() end 
function CCTextFieldTTF:textFieldWithPlaceHolder() end 
function CCTextFieldTTF:getPlaceHolder() end 
function CCTextFieldTTF:setString() end 
function CCTextFieldTTF:setPlaceHolder() end 
function CCTextFieldTTF:attachWithIME() end 
function CCTextFieldTTF:detachWithIME() end 
