---@classdef CCTileMapAtlas
CCTileMapAtlas = {}
function CCTileMapAtlas:autorelease() end 
function CCTileMapAtlas:retain() end 
function CCTileMapAtlas:retainCount() end 
function CCTileMapAtlas:isEqual() end 
function CCTileMapAtlas:copy() end 
function CCTileMapAtlas:release() end 
function CCTileMapAtlas:isSingleReference() end 
function CCTileMapAtlas:visit() end 
function CCTileMapAtlas:getUserObject() end 
function CCTileMapAtlas:getSkewY() end 
function CCTileMapAtlas:convertTouchToNodeSpace() end 
function CCTileMapAtlas:getVertexZ() end 
function CCTileMapAtlas:setParent() end 
function CCTileMapAtlas:boundingBox() end 
function CCTileMapAtlas:setVisible() end 
function CCTileMapAtlas:stopActionByTag() end 
function CCTileMapAtlas:getScaleY() end 
function CCTileMapAtlas:setScaleX() end 
function CCTileMapAtlas:reorderChild() end 
function CCTileMapAtlas:setPositionX() end 
function CCTileMapAtlas:removeFromParentAndCleanup() end 
function CCTileMapAtlas:setTag() end 
function CCTileMapAtlas:getChildrenCount() end 
function CCTileMapAtlas:setScale() end 
function CCTileMapAtlas:addChild() end 
function CCTileMapAtlas:isVisible() end 
function CCTileMapAtlas:setActionManager() end 
function CCTileMapAtlas:setScheduler() end 
function CCTileMapAtlas:getContentSize() end 
function CCTileMapAtlas:getAnchorPoint() end 
function CCTileMapAtlas:getTag() end 
function CCTileMapAtlas:setGrid() end 
function CCTileMapAtlas:convertToWorldSpace() end 
function CCTileMapAtlas:setSkewX() end 
function CCTileMapAtlas:setZOrder() end 
function CCTileMapAtlas:worldToNodeTransform() end 
function CCTileMapAtlas:getPosition() end 
function CCTileMapAtlas:getSkewX() end 
function CCTileMapAtlas:getScheduler() end 
function CCTileMapAtlas:ignoreAnchorPointForPosition() end 
function CCTileMapAtlas:setPosition() end 
function CCTileMapAtlas:getParent() end 
function CCTileMapAtlas:unscheduleUpdate() end 
function CCTileMapAtlas:scheduleUpdateWithPriorityLua() end 
function CCTileMapAtlas:removeChildByTag() end 
function CCTileMapAtlas:convertToNodeSpaceAR() end 
function CCTileMapAtlas:convertTouchToNodeSpaceAR() end 
function CCTileMapAtlas:convertToWorldSpaceAR() end 
function CCTileMapAtlas:setRotation() end 
function CCTileMapAtlas:getComponent() end 
function CCTileMapAtlas:convertToNodeSpace() end 
---
-- @return @class CCTileMapAtlas
--
function CCTileMapAtlas:create() end 
function CCTileMapAtlas:getScale() end 
function CCTileMapAtlas:getPositionY() end 
function CCTileMapAtlas:getChildByTag() end 
function CCTileMapAtlas:setContentSize() end 
function CCTileMapAtlas:description() end 
function CCTileMapAtlas:cleanup() end 
function CCTileMapAtlas:getRotation() end 
function CCTileMapAtlas:nodeToParentTransform() end 
function CCTileMapAtlas:stopAction() end 
function CCTileMapAtlas:numberOfRunningActions() end 
function CCTileMapAtlas:removeAllChildren() end 
function CCTileMapAtlas:runAction() end 
function CCTileMapAtlas:setUserObject() end 
function CCTileMapAtlas:parentToNodeTransform() end 
function CCTileMapAtlas:removeChild() end 
function CCTileMapAtlas:getAnchorPointInPoints() end 
function CCTileMapAtlas:getScaleX() end 
function CCTileMapAtlas:transform() end 
function CCTileMapAtlas:getActionManager() end 
function CCTileMapAtlas:draw() end 
function CCTileMapAtlas:setScaleY() end 
function CCTileMapAtlas:unregisterScriptHandler() end 
function CCTileMapAtlas:setVertexZ() end 
function CCTileMapAtlas:setAnchorPoint() end 
function CCTileMapAtlas:getShaderProgram() end 
function CCTileMapAtlas:stopAllActions() end 
function CCTileMapAtlas:setUserData() end 
function CCTileMapAtlas:setShaderProgram() end 
function CCTileMapAtlas:getActionByTag() end 
function CCTileMapAtlas:getGLServerState() end 
function CCTileMapAtlas:getOrderOfArrival() end 
function CCTileMapAtlas:getPositionX() end 
function CCTileMapAtlas:setGLServerState() end 
function CCTileMapAtlas:setSkewY() end 
function CCTileMapAtlas:setOrderOfArrival() end 
function CCTileMapAtlas:nodeToWorldTransform() end 
function CCTileMapAtlas:getChildren() end 
function CCTileMapAtlas:transformAncestors() end 
function CCTileMapAtlas:getGrid() end 
function CCTileMapAtlas:isRunning() end 
function CCTileMapAtlas:registerScriptHandler() end 
function CCTileMapAtlas:getCamera() end 
function CCTileMapAtlas:isIgnoreAnchorPointForPosition() end 
function CCTileMapAtlas:getUserData() end 
function CCTileMapAtlas:setPositionY() end 
function CCTileMapAtlas:getZOrder() end 
function CCTileMapAtlas:new() end 
function CCTileMapAtlas:delete() end 
function CCTileMapAtlas:updateDisplayedColor() end 
function CCTileMapAtlas:init() end 
function CCTileMapAtlas:setColor() end 
function CCTileMapAtlas:getDisplayedColor() end 
function CCTileMapAtlas:setCascadeColorEnabled() end 
function CCTileMapAtlas:setCascadeOpacityEnabled() end 
function CCTileMapAtlas:setOpacity() end 
function CCTileMapAtlas:getColor() end 
function CCTileMapAtlas:updateDisplayedOpacity() end 
function CCTileMapAtlas:getOpacity() end 
function CCTileMapAtlas:setOpacityModifyRGB() end 
function CCTileMapAtlas:isCascadeOpacityEnabled() end 
function CCTileMapAtlas:isOpacityModifyRGB() end 
function CCTileMapAtlas:getDisplayedOpacity() end 
function CCTileMapAtlas:new_local() end 
function CCTileMapAtlas:isCascadeColorEnabled() end 
function CCTileMapAtlas:setTextureAtlas() end 
function CCTileMapAtlas:setTexture() end 
function CCTileMapAtlas:getTexture() end 
function CCTileMapAtlas:getTextureAtlas() end 
---
-- @return @class CCTileMapAtlas
--
function CCTileMapAtlas:create() end 
function CCTileMapAtlas:setOpacityModifyRGB() end 
function CCTileMapAtlas:setColor() end 
function CCTileMapAtlas:setQuadsToDraw() end 
function CCTileMapAtlas:isOpacityModifyRGB() end 
function CCTileMapAtlas:setOpacity() end 
function CCTileMapAtlas:getOpacity() end 
function CCTileMapAtlas:updateAtlasValues() end 
function CCTileMapAtlas:getColor() end 
function CCTileMapAtlas:getQuadsToDraw() end 
function CCTileMapAtlas:setTile() end 
function CCTileMapAtlas:releaseMap() end 
---
-- @return @class CCTileMapAtlas
--
function CCTileMapAtlas:create() end 
function CCTileMapAtlas:tileAt() end 
