---@classdef CCTMXTiledMap
CCTMXTiledMap = {}
function CCTMXTiledMap:autorelease() end 
function CCTMXTiledMap:retain() end 
function CCTMXTiledMap:retainCount() end 
function CCTMXTiledMap:isEqual() end 
function CCTMXTiledMap:copy() end 
function CCTMXTiledMap:release() end 
function CCTMXTiledMap:isSingleReference() end 
function CCTMXTiledMap:visit() end 
function CCTMXTiledMap:getUserObject() end 
function CCTMXTiledMap:getSkewY() end 
function CCTMXTiledMap:convertTouchToNodeSpace() end 
function CCTMXTiledMap:getVertexZ() end 
function CCTMXTiledMap:setParent() end 
function CCTMXTiledMap:boundingBox() end 
function CCTMXTiledMap:setVisible() end 
function CCTMXTiledMap:stopActionByTag() end 
function CCTMXTiledMap:getScaleY() end 
function CCTMXTiledMap:setScaleX() end 
function CCTMXTiledMap:reorderChild() end 
function CCTMXTiledMap:setPositionX() end 
function CCTMXTiledMap:removeFromParentAndCleanup() end 
function CCTMXTiledMap:setTag() end 
function CCTMXTiledMap:getChildrenCount() end 
function CCTMXTiledMap:setScale() end 
function CCTMXTiledMap:addChild() end 
function CCTMXTiledMap:isVisible() end 
function CCTMXTiledMap:setActionManager() end 
function CCTMXTiledMap:setScheduler() end 
function CCTMXTiledMap:getContentSize() end 
function CCTMXTiledMap:getAnchorPoint() end 
function CCTMXTiledMap:getTag() end 
function CCTMXTiledMap:setGrid() end 
function CCTMXTiledMap:convertToWorldSpace() end 
function CCTMXTiledMap:setSkewX() end 
function CCTMXTiledMap:setZOrder() end 
function CCTMXTiledMap:worldToNodeTransform() end 
function CCTMXTiledMap:getPosition() end 
function CCTMXTiledMap:getSkewX() end 
function CCTMXTiledMap:getScheduler() end 
function CCTMXTiledMap:ignoreAnchorPointForPosition() end 
function CCTMXTiledMap:setPosition() end 
function CCTMXTiledMap:getParent() end 
function CCTMXTiledMap:unscheduleUpdate() end 
function CCTMXTiledMap:scheduleUpdateWithPriorityLua() end 
function CCTMXTiledMap:removeChildByTag() end 
function CCTMXTiledMap:convertToNodeSpaceAR() end 
function CCTMXTiledMap:convertTouchToNodeSpaceAR() end 
function CCTMXTiledMap:convertToWorldSpaceAR() end 
function CCTMXTiledMap:setRotation() end 
function CCTMXTiledMap:getComponent() end 
function CCTMXTiledMap:convertToNodeSpace() end 
---
-- @return @class CCTMXTiledMap
--
function CCTMXTiledMap:create() end 
function CCTMXTiledMap:getScale() end 
function CCTMXTiledMap:getPositionY() end 
function CCTMXTiledMap:getChildByTag() end 
function CCTMXTiledMap:setContentSize() end 
function CCTMXTiledMap:description() end 
function CCTMXTiledMap:cleanup() end 
function CCTMXTiledMap:getRotation() end 
function CCTMXTiledMap:nodeToParentTransform() end 
function CCTMXTiledMap:stopAction() end 
function CCTMXTiledMap:numberOfRunningActions() end 
function CCTMXTiledMap:removeAllChildren() end 
function CCTMXTiledMap:runAction() end 
function CCTMXTiledMap:setUserObject() end 
function CCTMXTiledMap:parentToNodeTransform() end 
function CCTMXTiledMap:removeChild() end 
function CCTMXTiledMap:getAnchorPointInPoints() end 
function CCTMXTiledMap:getScaleX() end 
function CCTMXTiledMap:transform() end 
function CCTMXTiledMap:getActionManager() end 
function CCTMXTiledMap:draw() end 
function CCTMXTiledMap:setScaleY() end 
function CCTMXTiledMap:unregisterScriptHandler() end 
function CCTMXTiledMap:setVertexZ() end 
function CCTMXTiledMap:setAnchorPoint() end 
function CCTMXTiledMap:getShaderProgram() end 
function CCTMXTiledMap:stopAllActions() end 
function CCTMXTiledMap:setUserData() end 
function CCTMXTiledMap:setShaderProgram() end 
function CCTMXTiledMap:getActionByTag() end 
function CCTMXTiledMap:getGLServerState() end 
function CCTMXTiledMap:getOrderOfArrival() end 
function CCTMXTiledMap:getPositionX() end 
function CCTMXTiledMap:setGLServerState() end 
function CCTMXTiledMap:setSkewY() end 
function CCTMXTiledMap:setOrderOfArrival() end 
function CCTMXTiledMap:nodeToWorldTransform() end 
function CCTMXTiledMap:getChildren() end 
function CCTMXTiledMap:transformAncestors() end 
function CCTMXTiledMap:getGrid() end 
function CCTMXTiledMap:isRunning() end 
function CCTMXTiledMap:registerScriptHandler() end 
function CCTMXTiledMap:getCamera() end 
function CCTMXTiledMap:isIgnoreAnchorPointForPosition() end 
function CCTMXTiledMap:getUserData() end 
function CCTMXTiledMap:setPositionY() end 
function CCTMXTiledMap:getZOrder() end 
function CCTMXTiledMap:getObjectGroups() end 
function CCTMXTiledMap:createWithXML() end 
---
-- @return @class CCTMXTiledMap
--
function CCTMXTiledMap:create() end 
function CCTMXTiledMap:propertiesForGID() end 
function CCTMXTiledMap:propertyNamed() end 
function CCTMXTiledMap:setTileSize() end 
function CCTMXTiledMap:objectGroupNamed() end 
function CCTMXTiledMap:getTileSize() end 
function CCTMXTiledMap:layerNamed() end 
function CCTMXTiledMap:setMapOrientation() end 
function CCTMXTiledMap:getProperties() end 
function CCTMXTiledMap:setProperties() end 
function CCTMXTiledMap:setObjectGroups() end 
function CCTMXTiledMap:setMapSize() end 
function CCTMXTiledMap:getMapOrientation() end 
function CCTMXTiledMap:getMapSize() end 
