---@classdef CCTMXLayer
CCTMXLayer = {}
function CCTMXLayer:autorelease() end 
function CCTMXLayer:retain() end 
function CCTMXLayer:retainCount() end 
function CCTMXLayer:isEqual() end 
function CCTMXLayer:copy() end 
function CCTMXLayer:release() end 
function CCTMXLayer:isSingleReference() end 
function CCTMXLayer:visit() end 
function CCTMXLayer:getUserObject() end 
function CCTMXLayer:getSkewY() end 
function CCTMXLayer:convertTouchToNodeSpace() end 
function CCTMXLayer:getVertexZ() end 
function CCTMXLayer:setParent() end 
function CCTMXLayer:boundingBox() end 
function CCTMXLayer:setVisible() end 
function CCTMXLayer:stopActionByTag() end 
function CCTMXLayer:getScaleY() end 
function CCTMXLayer:setScaleX() end 
function CCTMXLayer:reorderChild() end 
function CCTMXLayer:setPositionX() end 
function CCTMXLayer:removeFromParentAndCleanup() end 
function CCTMXLayer:setTag() end 
function CCTMXLayer:getChildrenCount() end 
function CCTMXLayer:setScale() end 
function CCTMXLayer:addChild() end 
function CCTMXLayer:isVisible() end 
function CCTMXLayer:setActionManager() end 
function CCTMXLayer:setScheduler() end 
function CCTMXLayer:getContentSize() end 
function CCTMXLayer:getAnchorPoint() end 
function CCTMXLayer:getTag() end 
function CCTMXLayer:setGrid() end 
function CCTMXLayer:convertToWorldSpace() end 
function CCTMXLayer:setSkewX() end 
function CCTMXLayer:setZOrder() end 
function CCTMXLayer:worldToNodeTransform() end 
function CCTMXLayer:getPosition() end 
function CCTMXLayer:getSkewX() end 
function CCTMXLayer:getScheduler() end 
function CCTMXLayer:ignoreAnchorPointForPosition() end 
function CCTMXLayer:setPosition() end 
function CCTMXLayer:getParent() end 
function CCTMXLayer:unscheduleUpdate() end 
function CCTMXLayer:scheduleUpdateWithPriorityLua() end 
function CCTMXLayer:removeChildByTag() end 
function CCTMXLayer:convertToNodeSpaceAR() end 
function CCTMXLayer:convertTouchToNodeSpaceAR() end 
function CCTMXLayer:convertToWorldSpaceAR() end 
function CCTMXLayer:setRotation() end 
function CCTMXLayer:getComponent() end 
function CCTMXLayer:convertToNodeSpace() end 
---
-- @return @class CCTMXLayer
--
function CCTMXLayer:create() end 
function CCTMXLayer:getScale() end 
function CCTMXLayer:getPositionY() end 
function CCTMXLayer:getChildByTag() end 
function CCTMXLayer:setContentSize() end 
function CCTMXLayer:description() end 
function CCTMXLayer:cleanup() end 
function CCTMXLayer:getRotation() end 
function CCTMXLayer:nodeToParentTransform() end 
function CCTMXLayer:stopAction() end 
function CCTMXLayer:numberOfRunningActions() end 
function CCTMXLayer:removeAllChildren() end 
function CCTMXLayer:runAction() end 
function CCTMXLayer:setUserObject() end 
function CCTMXLayer:parentToNodeTransform() end 
function CCTMXLayer:removeChild() end 
function CCTMXLayer:getAnchorPointInPoints() end 
function CCTMXLayer:getScaleX() end 
function CCTMXLayer:transform() end 
function CCTMXLayer:getActionManager() end 
function CCTMXLayer:draw() end 
function CCTMXLayer:setScaleY() end 
function CCTMXLayer:unregisterScriptHandler() end 
function CCTMXLayer:setVertexZ() end 
function CCTMXLayer:setAnchorPoint() end 
function CCTMXLayer:getShaderProgram() end 
function CCTMXLayer:stopAllActions() end 
function CCTMXLayer:setUserData() end 
function CCTMXLayer:setShaderProgram() end 
function CCTMXLayer:getActionByTag() end 
function CCTMXLayer:getGLServerState() end 
function CCTMXLayer:getOrderOfArrival() end 
function CCTMXLayer:getPositionX() end 
function CCTMXLayer:setGLServerState() end 
function CCTMXLayer:setSkewY() end 
function CCTMXLayer:setOrderOfArrival() end 
function CCTMXLayer:nodeToWorldTransform() end 
function CCTMXLayer:getChildren() end 
function CCTMXLayer:transformAncestors() end 
function CCTMXLayer:getGrid() end 
function CCTMXLayer:isRunning() end 
function CCTMXLayer:registerScriptHandler() end 
function CCTMXLayer:getCamera() end 
function CCTMXLayer:isIgnoreAnchorPointForPosition() end 
function CCTMXLayer:getUserData() end 
function CCTMXLayer:setPositionY() end 
function CCTMXLayer:getZOrder() end 
function CCTMXLayer:setTextureAtlas() end 
function CCTMXLayer:setBlendFunc() end 
---
-- @return @class CCTMXLayer
--
function CCTMXLayer:create() end 
function CCTMXLayer:getTexture() end 
function CCTMXLayer:appendChild() end 
function CCTMXLayer:removeAllChildren() end 
function CCTMXLayer:createWithTexture() end 
function CCTMXLayer:removeChild() end 
function CCTMXLayer:rebuildIndexInOrder() end 
function CCTMXLayer:atlasIndexForChild() end 
function CCTMXLayer:increaseAtlasCapacity() end 
function CCTMXLayer:addChild() end 
function CCTMXLayer:setTexture() end 
function CCTMXLayer:getTextureAtlas() end 
function CCTMXLayer:removeChildAtIndex() end 
function CCTMXLayer:getDescendants() end 
function CCTMXLayer:sortAllChildren() end 
function CCTMXLayer:getBlendFunc() end 
function CCTMXLayer:reorderBatch() end 
function CCTMXLayer:insertChild() end 
function CCTMXLayer:highestAtlasIndexInChild() end 
function CCTMXLayer:removeSpriteFromAtlas() end 
function CCTMXLayer:lowestAtlasIndexInChild() end 
function CCTMXLayer:reorderChild() end 
function CCTMXLayer:setProperties() end 
function CCTMXLayer:setLayerSize() end 
---
-- @return @class CCTMXLayer
--
function CCTMXLayer:create() end 
function CCTMXLayer:removeTileAt() end 
function CCTMXLayer:setTileGID() end 
function CCTMXLayer:setTiles() end 
function CCTMXLayer:setMapTileSize() end 
function CCTMXLayer:tileGIDAt() end 
function CCTMXLayer:positionAt() end 
function CCTMXLayer:releaseMap() end 
function CCTMXLayer:propertyNamed() end 
function CCTMXLayer:getTiles() end 
function CCTMXLayer:getLayerSize() end 
function CCTMXLayer:tileAt() end 
function CCTMXLayer:setLayerOrientation() end 
function CCTMXLayer:getLayerName() end 
function CCTMXLayer:setLayerName() end 
function CCTMXLayer:getMapTileSize() end 
function CCTMXLayer:setupTiles() end 
function CCTMXLayer:setTileSet() end 
function CCTMXLayer:getTileSet() end 
function CCTMXLayer:getLayerOrientation() end 
function CCTMXLayer:getProperties() end 
