---@classdef CCTMXMapInfo
CCTMXMapInfo = {}
function CCTMXMapInfo:autorelease() end 
function CCTMXMapInfo:retain() end 
function CCTMXMapInfo:retainCount() end 
function CCTMXMapInfo:isEqual() end 
function CCTMXMapInfo:copy() end 
function CCTMXMapInfo:release() end 
function CCTMXMapInfo:isSingleReference() end 
function CCTMXMapInfo:setProperties() end 
function CCTMXMapInfo:setLayerAttribs() end 
function CCTMXMapInfo:getCurrentString() end 
function CCTMXMapInfo:setLayers() end 
function CCTMXMapInfo:setParentGID() end 
function CCTMXMapInfo:parseXMLString() end 
function CCTMXMapInfo:textHandler() end 
function CCTMXMapInfo:setTilesets() end 
function CCTMXMapInfo:getMapSize() end 
function CCTMXMapInfo:getTilesets() end 
function CCTMXMapInfo:setParentElement() end 
function CCTMXMapInfo:setObjectGroups() end 
function CCTMXMapInfo:setMapSize() end 
function CCTMXMapInfo:getParentGID() end 
function CCTMXMapInfo:formatWithXML() end 
function CCTMXMapInfo:getObjectGroups() end 
function CCTMXMapInfo:formatWithTMXFile() end 
function CCTMXMapInfo:parseXMLFile() end 
function CCTMXMapInfo:getLayers() end 
function CCTMXMapInfo:endElement() end 
function CCTMXMapInfo:getStoringCharacters() end 
function CCTMXMapInfo:setTMXFileName() end 
function CCTMXMapInfo:getLayerAttribs() end 
function CCTMXMapInfo:getTileSize() end 
function CCTMXMapInfo:getTMXFileName() end 
function CCTMXMapInfo:setTileSize() end 
function CCTMXMapInfo:setTileProperties() end 
function CCTMXMapInfo:getProperties() end 
function CCTMXMapInfo:setStoringCharacters() end 
function CCTMXMapInfo:setCurrentString() end 
function CCTMXMapInfo:getOrientation() end 
function CCTMXMapInfo:startElement() end 
function CCTMXMapInfo:getTileProperties() end 
function CCTMXMapInfo:getParentElement() end 
function CCTMXMapInfo:setOrientation() end 
