---@classdef CCTransitionSplitCols
CCTransitionSplitCols = {}
function CCTransitionSplitCols:autorelease() end 
function CCTransitionSplitCols:retain() end 
function CCTransitionSplitCols:retainCount() end 
function CCTransitionSplitCols:isEqual() end 
function CCTransitionSplitCols:copy() end 
function CCTransitionSplitCols:release() end 
function CCTransitionSplitCols:isSingleReference() end 
function CCTransitionSplitCols:visit() end 
function CCTransitionSplitCols:getUserObject() end 
function CCTransitionSplitCols:getSkewY() end 
function CCTransitionSplitCols:convertTouchToNodeSpace() end 
function CCTransitionSplitCols:getVertexZ() end 
function CCTransitionSplitCols:setParent() end 
function CCTransitionSplitCols:boundingBox() end 
function CCTransitionSplitCols:setVisible() end 
function CCTransitionSplitCols:stopActionByTag() end 
function CCTransitionSplitCols:getScaleY() end 
function CCTransitionSplitCols:setScaleX() end 
function CCTransitionSplitCols:reorderChild() end 
function CCTransitionSplitCols:setPositionX() end 
function CCTransitionSplitCols:removeFromParentAndCleanup() end 
function CCTransitionSplitCols:setTag() end 
function CCTransitionSplitCols:getChildrenCount() end 
function CCTransitionSplitCols:setScale() end 
function CCTransitionSplitCols:addChild() end 
function CCTransitionSplitCols:isVisible() end 
function CCTransitionSplitCols:setActionManager() end 
function CCTransitionSplitCols:setScheduler() end 
function CCTransitionSplitCols:getContentSize() end 
function CCTransitionSplitCols:getAnchorPoint() end 
function CCTransitionSplitCols:getTag() end 
function CCTransitionSplitCols:setGrid() end 
function CCTransitionSplitCols:convertToWorldSpace() end 
function CCTransitionSplitCols:setSkewX() end 
function CCTransitionSplitCols:setZOrder() end 
function CCTransitionSplitCols:worldToNodeTransform() end 
function CCTransitionSplitCols:getPosition() end 
function CCTransitionSplitCols:getSkewX() end 
function CCTransitionSplitCols:getScheduler() end 
function CCTransitionSplitCols:ignoreAnchorPointForPosition() end 
function CCTransitionSplitCols:setPosition() end 
function CCTransitionSplitCols:getParent() end 
function CCTransitionSplitCols:unscheduleUpdate() end 
function CCTransitionSplitCols:scheduleUpdateWithPriorityLua() end 
function CCTransitionSplitCols:removeChildByTag() end 
function CCTransitionSplitCols:convertToNodeSpaceAR() end 
function CCTransitionSplitCols:convertTouchToNodeSpaceAR() end 
function CCTransitionSplitCols:convertToWorldSpaceAR() end 
function CCTransitionSplitCols:setRotation() end 
function CCTransitionSplitCols:getComponent() end 
function CCTransitionSplitCols:convertToNodeSpace() end 
---
-- @return @class CCTransitionSplitCols
--
function CCTransitionSplitCols:create() end 
function CCTransitionSplitCols:getScale() end 
function CCTransitionSplitCols:getPositionY() end 
function CCTransitionSplitCols:getChildByTag() end 
function CCTransitionSplitCols:setContentSize() end 
function CCTransitionSplitCols:description() end 
function CCTransitionSplitCols:cleanup() end 
function CCTransitionSplitCols:getRotation() end 
function CCTransitionSplitCols:nodeToParentTransform() end 
function CCTransitionSplitCols:stopAction() end 
function CCTransitionSplitCols:numberOfRunningActions() end 
function CCTransitionSplitCols:removeAllChildren() end 
function CCTransitionSplitCols:runAction() end 
function CCTransitionSplitCols:setUserObject() end 
function CCTransitionSplitCols:parentToNodeTransform() end 
function CCTransitionSplitCols:removeChild() end 
function CCTransitionSplitCols:getAnchorPointInPoints() end 
function CCTransitionSplitCols:getScaleX() end 
function CCTransitionSplitCols:transform() end 
function CCTransitionSplitCols:getActionManager() end 
function CCTransitionSplitCols:draw() end 
function CCTransitionSplitCols:setScaleY() end 
function CCTransitionSplitCols:unregisterScriptHandler() end 
function CCTransitionSplitCols:setVertexZ() end 
function CCTransitionSplitCols:setAnchorPoint() end 
function CCTransitionSplitCols:getShaderProgram() end 
function CCTransitionSplitCols:stopAllActions() end 
function CCTransitionSplitCols:setUserData() end 
function CCTransitionSplitCols:setShaderProgram() end 
function CCTransitionSplitCols:getActionByTag() end 
function CCTransitionSplitCols:getGLServerState() end 
function CCTransitionSplitCols:getOrderOfArrival() end 
function CCTransitionSplitCols:getPositionX() end 
function CCTransitionSplitCols:setGLServerState() end 
function CCTransitionSplitCols:setSkewY() end 
function CCTransitionSplitCols:setOrderOfArrival() end 
function CCTransitionSplitCols:nodeToWorldTransform() end 
function CCTransitionSplitCols:getChildren() end 
function CCTransitionSplitCols:transformAncestors() end 
function CCTransitionSplitCols:getGrid() end 
function CCTransitionSplitCols:isRunning() end 
function CCTransitionSplitCols:registerScriptHandler() end 
function CCTransitionSplitCols:getCamera() end 
function CCTransitionSplitCols:isIgnoreAnchorPointForPosition() end 
function CCTransitionSplitCols:getUserData() end 
function CCTransitionSplitCols:setPositionY() end 
function CCTransitionSplitCols:getZOrder() end 
---
-- @return @class CCTransitionSplitCols
--
function CCTransitionSplitCols:create() end 
---
-- @return @class CCTransitionSplitCols
--
function CCTransitionSplitCols:create() end 
