---@classdef CCTransitionFadeBL
CCTransitionFadeBL = {}
function CCTransitionFadeBL:autorelease() end 
function CCTransitionFadeBL:retain() end 
function CCTransitionFadeBL:retainCount() end 
function CCTransitionFadeBL:isEqual() end 
function CCTransitionFadeBL:copy() end 
function CCTransitionFadeBL:release() end 
function CCTransitionFadeBL:isSingleReference() end 
function CCTransitionFadeBL:visit() end 
function CCTransitionFadeBL:getUserObject() end 
function CCTransitionFadeBL:getSkewY() end 
function CCTransitionFadeBL:convertTouchToNodeSpace() end 
function CCTransitionFadeBL:getVertexZ() end 
function CCTransitionFadeBL:setParent() end 
function CCTransitionFadeBL:boundingBox() end 
function CCTransitionFadeBL:setVisible() end 
function CCTransitionFadeBL:stopActionByTag() end 
function CCTransitionFadeBL:getScaleY() end 
function CCTransitionFadeBL:setScaleX() end 
function CCTransitionFadeBL:reorderChild() end 
function CCTransitionFadeBL:setPositionX() end 
function CCTransitionFadeBL:removeFromParentAndCleanup() end 
function CCTransitionFadeBL:setTag() end 
function CCTransitionFadeBL:getChildrenCount() end 
function CCTransitionFadeBL:setScale() end 
function CCTransitionFadeBL:addChild() end 
function CCTransitionFadeBL:isVisible() end 
function CCTransitionFadeBL:setActionManager() end 
function CCTransitionFadeBL:setScheduler() end 
function CCTransitionFadeBL:getContentSize() end 
function CCTransitionFadeBL:getAnchorPoint() end 
function CCTransitionFadeBL:getTag() end 
function CCTransitionFadeBL:setGrid() end 
function CCTransitionFadeBL:convertToWorldSpace() end 
function CCTransitionFadeBL:setSkewX() end 
function CCTransitionFadeBL:setZOrder() end 
function CCTransitionFadeBL:worldToNodeTransform() end 
function CCTransitionFadeBL:getPosition() end 
function CCTransitionFadeBL:getSkewX() end 
function CCTransitionFadeBL:getScheduler() end 
function CCTransitionFadeBL:ignoreAnchorPointForPosition() end 
function CCTransitionFadeBL:setPosition() end 
function CCTransitionFadeBL:getParent() end 
function CCTransitionFadeBL:unscheduleUpdate() end 
function CCTransitionFadeBL:scheduleUpdateWithPriorityLua() end 
function CCTransitionFadeBL:removeChildByTag() end 
function CCTransitionFadeBL:convertToNodeSpaceAR() end 
function CCTransitionFadeBL:convertTouchToNodeSpaceAR() end 
function CCTransitionFadeBL:convertToWorldSpaceAR() end 
function CCTransitionFadeBL:setRotation() end 
function CCTransitionFadeBL:getComponent() end 
function CCTransitionFadeBL:convertToNodeSpace() end 
---
-- @return @class CCTransitionFadeBL
--
function CCTransitionFadeBL:create() end 
function CCTransitionFadeBL:getScale() end 
function CCTransitionFadeBL:getPositionY() end 
function CCTransitionFadeBL:getChildByTag() end 
function CCTransitionFadeBL:setContentSize() end 
function CCTransitionFadeBL:description() end 
function CCTransitionFadeBL:cleanup() end 
function CCTransitionFadeBL:getRotation() end 
function CCTransitionFadeBL:nodeToParentTransform() end 
function CCTransitionFadeBL:stopAction() end 
function CCTransitionFadeBL:numberOfRunningActions() end 
function CCTransitionFadeBL:removeAllChildren() end 
function CCTransitionFadeBL:runAction() end 
function CCTransitionFadeBL:setUserObject() end 
function CCTransitionFadeBL:parentToNodeTransform() end 
function CCTransitionFadeBL:removeChild() end 
function CCTransitionFadeBL:getAnchorPointInPoints() end 
function CCTransitionFadeBL:getScaleX() end 
function CCTransitionFadeBL:transform() end 
function CCTransitionFadeBL:getActionManager() end 
function CCTransitionFadeBL:draw() end 
function CCTransitionFadeBL:setScaleY() end 
function CCTransitionFadeBL:unregisterScriptHandler() end 
function CCTransitionFadeBL:setVertexZ() end 
function CCTransitionFadeBL:setAnchorPoint() end 
function CCTransitionFadeBL:getShaderProgram() end 
function CCTransitionFadeBL:stopAllActions() end 
function CCTransitionFadeBL:setUserData() end 
function CCTransitionFadeBL:setShaderProgram() end 
function CCTransitionFadeBL:getActionByTag() end 
function CCTransitionFadeBL:getGLServerState() end 
function CCTransitionFadeBL:getOrderOfArrival() end 
function CCTransitionFadeBL:getPositionX() end 
function CCTransitionFadeBL:setGLServerState() end 
function CCTransitionFadeBL:setSkewY() end 
function CCTransitionFadeBL:setOrderOfArrival() end 
function CCTransitionFadeBL:nodeToWorldTransform() end 
function CCTransitionFadeBL:getChildren() end 
function CCTransitionFadeBL:transformAncestors() end 
function CCTransitionFadeBL:getGrid() end 
function CCTransitionFadeBL:isRunning() end 
function CCTransitionFadeBL:registerScriptHandler() end 
function CCTransitionFadeBL:getCamera() end 
function CCTransitionFadeBL:isIgnoreAnchorPointForPosition() end 
function CCTransitionFadeBL:getUserData() end 
function CCTransitionFadeBL:setPositionY() end 
function CCTransitionFadeBL:getZOrder() end 
---
-- @return @class CCTransitionFadeBL
--
function CCTransitionFadeBL:create() end 
---
-- @return @class CCTransitionFadeBL
--
function CCTransitionFadeBL:create() end 
