---@classdef CCTransitionSceneOriented
CCTransitionSceneOriented = {}
function CCTransitionSceneOriented:autorelease() end 
function CCTransitionSceneOriented:retain() end 
function CCTransitionSceneOriented:retainCount() end 
function CCTransitionSceneOriented:isEqual() end 
function CCTransitionSceneOriented:copy() end 
function CCTransitionSceneOriented:release() end 
function CCTransitionSceneOriented:isSingleReference() end 
function CCTransitionSceneOriented:visit() end 
function CCTransitionSceneOriented:getUserObject() end 
function CCTransitionSceneOriented:getSkewY() end 
function CCTransitionSceneOriented:convertTouchToNodeSpace() end 
function CCTransitionSceneOriented:getVertexZ() end 
function CCTransitionSceneOriented:setParent() end 
function CCTransitionSceneOriented:boundingBox() end 
function CCTransitionSceneOriented:setVisible() end 
function CCTransitionSceneOriented:stopActionByTag() end 
function CCTransitionSceneOriented:getScaleY() end 
function CCTransitionSceneOriented:setScaleX() end 
function CCTransitionSceneOriented:reorderChild() end 
function CCTransitionSceneOriented:setPositionX() end 
function CCTransitionSceneOriented:removeFromParentAndCleanup() end 
function CCTransitionSceneOriented:setTag() end 
function CCTransitionSceneOriented:getChildrenCount() end 
function CCTransitionSceneOriented:setScale() end 
function CCTransitionSceneOriented:addChild() end 
function CCTransitionSceneOriented:isVisible() end 
function CCTransitionSceneOriented:setActionManager() end 
function CCTransitionSceneOriented:setScheduler() end 
function CCTransitionSceneOriented:getContentSize() end 
function CCTransitionSceneOriented:getAnchorPoint() end 
function CCTransitionSceneOriented:getTag() end 
function CCTransitionSceneOriented:setGrid() end 
function CCTransitionSceneOriented:convertToWorldSpace() end 
function CCTransitionSceneOriented:setSkewX() end 
function CCTransitionSceneOriented:setZOrder() end 
function CCTransitionSceneOriented:worldToNodeTransform() end 
function CCTransitionSceneOriented:getPosition() end 
function CCTransitionSceneOriented:getSkewX() end 
function CCTransitionSceneOriented:getScheduler() end 
function CCTransitionSceneOriented:ignoreAnchorPointForPosition() end 
function CCTransitionSceneOriented:setPosition() end 
function CCTransitionSceneOriented:getParent() end 
function CCTransitionSceneOriented:unscheduleUpdate() end 
function CCTransitionSceneOriented:scheduleUpdateWithPriorityLua() end 
function CCTransitionSceneOriented:removeChildByTag() end 
function CCTransitionSceneOriented:convertToNodeSpaceAR() end 
function CCTransitionSceneOriented:convertTouchToNodeSpaceAR() end 
function CCTransitionSceneOriented:convertToWorldSpaceAR() end 
function CCTransitionSceneOriented:setRotation() end 
function CCTransitionSceneOriented:getComponent() end 
function CCTransitionSceneOriented:convertToNodeSpace() end 
---
-- @return @class CCTransitionSceneOriented
--
function CCTransitionSceneOriented:create() end 
function CCTransitionSceneOriented:getScale() end 
function CCTransitionSceneOriented:getPositionY() end 
function CCTransitionSceneOriented:getChildByTag() end 
function CCTransitionSceneOriented:setContentSize() end 
function CCTransitionSceneOriented:description() end 
function CCTransitionSceneOriented:cleanup() end 
function CCTransitionSceneOriented:getRotation() end 
function CCTransitionSceneOriented:nodeToParentTransform() end 
function CCTransitionSceneOriented:stopAction() end 
function CCTransitionSceneOriented:numberOfRunningActions() end 
function CCTransitionSceneOriented:removeAllChildren() end 
function CCTransitionSceneOriented:runAction() end 
function CCTransitionSceneOriented:setUserObject() end 
function CCTransitionSceneOriented:parentToNodeTransform() end 
function CCTransitionSceneOriented:removeChild() end 
function CCTransitionSceneOriented:getAnchorPointInPoints() end 
function CCTransitionSceneOriented:getScaleX() end 
function CCTransitionSceneOriented:transform() end 
function CCTransitionSceneOriented:getActionManager() end 
function CCTransitionSceneOriented:draw() end 
function CCTransitionSceneOriented:setScaleY() end 
function CCTransitionSceneOriented:unregisterScriptHandler() end 
function CCTransitionSceneOriented:setVertexZ() end 
function CCTransitionSceneOriented:setAnchorPoint() end 
function CCTransitionSceneOriented:getShaderProgram() end 
function CCTransitionSceneOriented:stopAllActions() end 
function CCTransitionSceneOriented:setUserData() end 
function CCTransitionSceneOriented:setShaderProgram() end 
function CCTransitionSceneOriented:getActionByTag() end 
function CCTransitionSceneOriented:getGLServerState() end 
function CCTransitionSceneOriented:getOrderOfArrival() end 
function CCTransitionSceneOriented:getPositionX() end 
function CCTransitionSceneOriented:setGLServerState() end 
function CCTransitionSceneOriented:setSkewY() end 
function CCTransitionSceneOriented:setOrderOfArrival() end 
function CCTransitionSceneOriented:nodeToWorldTransform() end 
function CCTransitionSceneOriented:getChildren() end 
function CCTransitionSceneOriented:transformAncestors() end 
function CCTransitionSceneOriented:getGrid() end 
function CCTransitionSceneOriented:isRunning() end 
function CCTransitionSceneOriented:registerScriptHandler() end 
function CCTransitionSceneOriented:getCamera() end 
function CCTransitionSceneOriented:isIgnoreAnchorPointForPosition() end 
function CCTransitionSceneOriented:getUserData() end 
function CCTransitionSceneOriented:setPositionY() end 
function CCTransitionSceneOriented:getZOrder() end 
---
-- @return @class CCTransitionSceneOriented
--
function CCTransitionSceneOriented:create() end 
---
-- @return @class CCTransitionSceneOriented
--
function CCTransitionSceneOriented:create() end 
