---@classdef CCTransitionSlideInR
CCTransitionSlideInR = {}
function CCTransitionSlideInR:autorelease() end 
function CCTransitionSlideInR:retain() end 
function CCTransitionSlideInR:retainCount() end 
function CCTransitionSlideInR:isEqual() end 
function CCTransitionSlideInR:copy() end 
function CCTransitionSlideInR:release() end 
function CCTransitionSlideInR:isSingleReference() end 
function CCTransitionSlideInR:visit() end 
function CCTransitionSlideInR:getUserObject() end 
function CCTransitionSlideInR:getSkewY() end 
function CCTransitionSlideInR:convertTouchToNodeSpace() end 
function CCTransitionSlideInR:getVertexZ() end 
function CCTransitionSlideInR:setParent() end 
function CCTransitionSlideInR:boundingBox() end 
function CCTransitionSlideInR:setVisible() end 
function CCTransitionSlideInR:stopActionByTag() end 
function CCTransitionSlideInR:getScaleY() end 
function CCTransitionSlideInR:setScaleX() end 
function CCTransitionSlideInR:reorderChild() end 
function CCTransitionSlideInR:setPositionX() end 
function CCTransitionSlideInR:removeFromParentAndCleanup() end 
function CCTransitionSlideInR:setTag() end 
function CCTransitionSlideInR:getChildrenCount() end 
function CCTransitionSlideInR:setScale() end 
function CCTransitionSlideInR:addChild() end 
function CCTransitionSlideInR:isVisible() end 
function CCTransitionSlideInR:setActionManager() end 
function CCTransitionSlideInR:setScheduler() end 
function CCTransitionSlideInR:getContentSize() end 
function CCTransitionSlideInR:getAnchorPoint() end 
function CCTransitionSlideInR:getTag() end 
function CCTransitionSlideInR:setGrid() end 
function CCTransitionSlideInR:convertToWorldSpace() end 
function CCTransitionSlideInR:setSkewX() end 
function CCTransitionSlideInR:setZOrder() end 
function CCTransitionSlideInR:worldToNodeTransform() end 
function CCTransitionSlideInR:getPosition() end 
function CCTransitionSlideInR:getSkewX() end 
function CCTransitionSlideInR:getScheduler() end 
function CCTransitionSlideInR:ignoreAnchorPointForPosition() end 
function CCTransitionSlideInR:setPosition() end 
function CCTransitionSlideInR:getParent() end 
function CCTransitionSlideInR:unscheduleUpdate() end 
function CCTransitionSlideInR:scheduleUpdateWithPriorityLua() end 
function CCTransitionSlideInR:removeChildByTag() end 
function CCTransitionSlideInR:convertToNodeSpaceAR() end 
function CCTransitionSlideInR:convertTouchToNodeSpaceAR() end 
function CCTransitionSlideInR:convertToWorldSpaceAR() end 
function CCTransitionSlideInR:setRotation() end 
function CCTransitionSlideInR:getComponent() end 
function CCTransitionSlideInR:convertToNodeSpace() end 
---
-- @return @class CCTransitionSlideInR
--
function CCTransitionSlideInR:create() end 
function CCTransitionSlideInR:getScale() end 
function CCTransitionSlideInR:getPositionY() end 
function CCTransitionSlideInR:getChildByTag() end 
function CCTransitionSlideInR:setContentSize() end 
function CCTransitionSlideInR:description() end 
function CCTransitionSlideInR:cleanup() end 
function CCTransitionSlideInR:getRotation() end 
function CCTransitionSlideInR:nodeToParentTransform() end 
function CCTransitionSlideInR:stopAction() end 
function CCTransitionSlideInR:numberOfRunningActions() end 
function CCTransitionSlideInR:removeAllChildren() end 
function CCTransitionSlideInR:runAction() end 
function CCTransitionSlideInR:setUserObject() end 
function CCTransitionSlideInR:parentToNodeTransform() end 
function CCTransitionSlideInR:removeChild() end 
function CCTransitionSlideInR:getAnchorPointInPoints() end 
function CCTransitionSlideInR:getScaleX() end 
function CCTransitionSlideInR:transform() end 
function CCTransitionSlideInR:getActionManager() end 
function CCTransitionSlideInR:draw() end 
function CCTransitionSlideInR:setScaleY() end 
function CCTransitionSlideInR:unregisterScriptHandler() end 
function CCTransitionSlideInR:setVertexZ() end 
function CCTransitionSlideInR:setAnchorPoint() end 
function CCTransitionSlideInR:getShaderProgram() end 
function CCTransitionSlideInR:stopAllActions() end 
function CCTransitionSlideInR:setUserData() end 
function CCTransitionSlideInR:setShaderProgram() end 
function CCTransitionSlideInR:getActionByTag() end 
function CCTransitionSlideInR:getGLServerState() end 
function CCTransitionSlideInR:getOrderOfArrival() end 
function CCTransitionSlideInR:getPositionX() end 
function CCTransitionSlideInR:setGLServerState() end 
function CCTransitionSlideInR:setSkewY() end 
function CCTransitionSlideInR:setOrderOfArrival() end 
function CCTransitionSlideInR:nodeToWorldTransform() end 
function CCTransitionSlideInR:getChildren() end 
function CCTransitionSlideInR:transformAncestors() end 
function CCTransitionSlideInR:getGrid() end 
function CCTransitionSlideInR:isRunning() end 
function CCTransitionSlideInR:registerScriptHandler() end 
function CCTransitionSlideInR:getCamera() end 
function CCTransitionSlideInR:isIgnoreAnchorPointForPosition() end 
function CCTransitionSlideInR:getUserData() end 
function CCTransitionSlideInR:setPositionY() end 
function CCTransitionSlideInR:getZOrder() end 
---
-- @return @class CCTransitionSlideInR
--
function CCTransitionSlideInR:create() end 
---
-- @return @class CCTransitionSlideInR
--
function CCTransitionSlideInR:create() end 
