---@classdef CCTransitionPageTurn
CCTransitionPageTurn = {}
function CCTransitionPageTurn:autorelease() end 
function CCTransitionPageTurn:retain() end 
function CCTransitionPageTurn:retainCount() end 
function CCTransitionPageTurn:isEqual() end 
function CCTransitionPageTurn:copy() end 
function CCTransitionPageTurn:release() end 
function CCTransitionPageTurn:isSingleReference() end 
function CCTransitionPageTurn:visit() end 
function CCTransitionPageTurn:getUserObject() end 
function CCTransitionPageTurn:getSkewY() end 
function CCTransitionPageTurn:convertTouchToNodeSpace() end 
function CCTransitionPageTurn:getVertexZ() end 
function CCTransitionPageTurn:setParent() end 
function CCTransitionPageTurn:boundingBox() end 
function CCTransitionPageTurn:setVisible() end 
function CCTransitionPageTurn:stopActionByTag() end 
function CCTransitionPageTurn:getScaleY() end 
function CCTransitionPageTurn:setScaleX() end 
function CCTransitionPageTurn:reorderChild() end 
function CCTransitionPageTurn:setPositionX() end 
function CCTransitionPageTurn:removeFromParentAndCleanup() end 
function CCTransitionPageTurn:setTag() end 
function CCTransitionPageTurn:getChildrenCount() end 
function CCTransitionPageTurn:setScale() end 
function CCTransitionPageTurn:addChild() end 
function CCTransitionPageTurn:isVisible() end 
function CCTransitionPageTurn:setActionManager() end 
function CCTransitionPageTurn:setScheduler() end 
function CCTransitionPageTurn:getContentSize() end 
function CCTransitionPageTurn:getAnchorPoint() end 
function CCTransitionPageTurn:getTag() end 
function CCTransitionPageTurn:setGrid() end 
function CCTransitionPageTurn:convertToWorldSpace() end 
function CCTransitionPageTurn:setSkewX() end 
function CCTransitionPageTurn:setZOrder() end 
function CCTransitionPageTurn:worldToNodeTransform() end 
function CCTransitionPageTurn:getPosition() end 
function CCTransitionPageTurn:getSkewX() end 
function CCTransitionPageTurn:getScheduler() end 
function CCTransitionPageTurn:ignoreAnchorPointForPosition() end 
function CCTransitionPageTurn:setPosition() end 
function CCTransitionPageTurn:getParent() end 
function CCTransitionPageTurn:unscheduleUpdate() end 
function CCTransitionPageTurn:scheduleUpdateWithPriorityLua() end 
function CCTransitionPageTurn:removeChildByTag() end 
function CCTransitionPageTurn:convertToNodeSpaceAR() end 
function CCTransitionPageTurn:convertTouchToNodeSpaceAR() end 
function CCTransitionPageTurn:convertToWorldSpaceAR() end 
function CCTransitionPageTurn:setRotation() end 
function CCTransitionPageTurn:getComponent() end 
function CCTransitionPageTurn:convertToNodeSpace() end 
---
-- @return @class CCTransitionPageTurn
--
function CCTransitionPageTurn:create() end 
function CCTransitionPageTurn:getScale() end 
function CCTransitionPageTurn:getPositionY() end 
function CCTransitionPageTurn:getChildByTag() end 
function CCTransitionPageTurn:setContentSize() end 
function CCTransitionPageTurn:description() end 
function CCTransitionPageTurn:cleanup() end 
function CCTransitionPageTurn:getRotation() end 
function CCTransitionPageTurn:nodeToParentTransform() end 
function CCTransitionPageTurn:stopAction() end 
function CCTransitionPageTurn:numberOfRunningActions() end 
function CCTransitionPageTurn:removeAllChildren() end 
function CCTransitionPageTurn:runAction() end 
function CCTransitionPageTurn:setUserObject() end 
function CCTransitionPageTurn:parentToNodeTransform() end 
function CCTransitionPageTurn:removeChild() end 
function CCTransitionPageTurn:getAnchorPointInPoints() end 
function CCTransitionPageTurn:getScaleX() end 
function CCTransitionPageTurn:transform() end 
function CCTransitionPageTurn:getActionManager() end 
function CCTransitionPageTurn:draw() end 
function CCTransitionPageTurn:setScaleY() end 
function CCTransitionPageTurn:unregisterScriptHandler() end 
function CCTransitionPageTurn:setVertexZ() end 
function CCTransitionPageTurn:setAnchorPoint() end 
function CCTransitionPageTurn:getShaderProgram() end 
function CCTransitionPageTurn:stopAllActions() end 
function CCTransitionPageTurn:setUserData() end 
function CCTransitionPageTurn:setShaderProgram() end 
function CCTransitionPageTurn:getActionByTag() end 
function CCTransitionPageTurn:getGLServerState() end 
function CCTransitionPageTurn:getOrderOfArrival() end 
function CCTransitionPageTurn:getPositionX() end 
function CCTransitionPageTurn:setGLServerState() end 
function CCTransitionPageTurn:setSkewY() end 
function CCTransitionPageTurn:setOrderOfArrival() end 
function CCTransitionPageTurn:nodeToWorldTransform() end 
function CCTransitionPageTurn:getChildren() end 
function CCTransitionPageTurn:transformAncestors() end 
function CCTransitionPageTurn:getGrid() end 
function CCTransitionPageTurn:isRunning() end 
function CCTransitionPageTurn:registerScriptHandler() end 
function CCTransitionPageTurn:getCamera() end 
function CCTransitionPageTurn:isIgnoreAnchorPointForPosition() end 
function CCTransitionPageTurn:getUserData() end 
function CCTransitionPageTurn:setPositionY() end 
function CCTransitionPageTurn:getZOrder() end 
---
-- @return @class CCTransitionPageTurn
--
function CCTransitionPageTurn:create() end 
---
-- @return @class CCTransitionPageTurn
--
function CCTransitionPageTurn:create() end 
function CCTransitionPageTurn:actionWithSize() end 
