---@classdef CCTransitionFadeUp
CCTransitionFadeUp = {}
function CCTransitionFadeUp:autorelease() end 
function CCTransitionFadeUp:retain() end 
function CCTransitionFadeUp:retainCount() end 
function CCTransitionFadeUp:isEqual() end 
function CCTransitionFadeUp:copy() end 
function CCTransitionFadeUp:release() end 
function CCTransitionFadeUp:isSingleReference() end 
function CCTransitionFadeUp:visit() end 
function CCTransitionFadeUp:getUserObject() end 
function CCTransitionFadeUp:getSkewY() end 
function CCTransitionFadeUp:convertTouchToNodeSpace() end 
function CCTransitionFadeUp:getVertexZ() end 
function CCTransitionFadeUp:setParent() end 
function CCTransitionFadeUp:boundingBox() end 
function CCTransitionFadeUp:setVisible() end 
function CCTransitionFadeUp:stopActionByTag() end 
function CCTransitionFadeUp:getScaleY() end 
function CCTransitionFadeUp:setScaleX() end 
function CCTransitionFadeUp:reorderChild() end 
function CCTransitionFadeUp:setPositionX() end 
function CCTransitionFadeUp:removeFromParentAndCleanup() end 
function CCTransitionFadeUp:setTag() end 
function CCTransitionFadeUp:getChildrenCount() end 
function CCTransitionFadeUp:setScale() end 
function CCTransitionFadeUp:addChild() end 
function CCTransitionFadeUp:isVisible() end 
function CCTransitionFadeUp:setActionManager() end 
function CCTransitionFadeUp:setScheduler() end 
function CCTransitionFadeUp:getContentSize() end 
function CCTransitionFadeUp:getAnchorPoint() end 
function CCTransitionFadeUp:getTag() end 
function CCTransitionFadeUp:setGrid() end 
function CCTransitionFadeUp:convertToWorldSpace() end 
function CCTransitionFadeUp:setSkewX() end 
function CCTransitionFadeUp:setZOrder() end 
function CCTransitionFadeUp:worldToNodeTransform() end 
function CCTransitionFadeUp:getPosition() end 
function CCTransitionFadeUp:getSkewX() end 
function CCTransitionFadeUp:getScheduler() end 
function CCTransitionFadeUp:ignoreAnchorPointForPosition() end 
function CCTransitionFadeUp:setPosition() end 
function CCTransitionFadeUp:getParent() end 
function CCTransitionFadeUp:unscheduleUpdate() end 
function CCTransitionFadeUp:scheduleUpdateWithPriorityLua() end 
function CCTransitionFadeUp:removeChildByTag() end 
function CCTransitionFadeUp:convertToNodeSpaceAR() end 
function CCTransitionFadeUp:convertTouchToNodeSpaceAR() end 
function CCTransitionFadeUp:convertToWorldSpaceAR() end 
function CCTransitionFadeUp:setRotation() end 
function CCTransitionFadeUp:getComponent() end 
function CCTransitionFadeUp:convertToNodeSpace() end 
---
-- @return @class CCTransitionFadeUp
--
function CCTransitionFadeUp:create() end 
function CCTransitionFadeUp:getScale() end 
function CCTransitionFadeUp:getPositionY() end 
function CCTransitionFadeUp:getChildByTag() end 
function CCTransitionFadeUp:setContentSize() end 
function CCTransitionFadeUp:description() end 
function CCTransitionFadeUp:cleanup() end 
function CCTransitionFadeUp:getRotation() end 
function CCTransitionFadeUp:nodeToParentTransform() end 
function CCTransitionFadeUp:stopAction() end 
function CCTransitionFadeUp:numberOfRunningActions() end 
function CCTransitionFadeUp:removeAllChildren() end 
function CCTransitionFadeUp:runAction() end 
function CCTransitionFadeUp:setUserObject() end 
function CCTransitionFadeUp:parentToNodeTransform() end 
function CCTransitionFadeUp:removeChild() end 
function CCTransitionFadeUp:getAnchorPointInPoints() end 
function CCTransitionFadeUp:getScaleX() end 
function CCTransitionFadeUp:transform() end 
function CCTransitionFadeUp:getActionManager() end 
function CCTransitionFadeUp:draw() end 
function CCTransitionFadeUp:setScaleY() end 
function CCTransitionFadeUp:unregisterScriptHandler() end 
function CCTransitionFadeUp:setVertexZ() end 
function CCTransitionFadeUp:setAnchorPoint() end 
function CCTransitionFadeUp:getShaderProgram() end 
function CCTransitionFadeUp:stopAllActions() end 
function CCTransitionFadeUp:setUserData() end 
function CCTransitionFadeUp:setShaderProgram() end 
function CCTransitionFadeUp:getActionByTag() end 
function CCTransitionFadeUp:getGLServerState() end 
function CCTransitionFadeUp:getOrderOfArrival() end 
function CCTransitionFadeUp:getPositionX() end 
function CCTransitionFadeUp:setGLServerState() end 
function CCTransitionFadeUp:setSkewY() end 
function CCTransitionFadeUp:setOrderOfArrival() end 
function CCTransitionFadeUp:nodeToWorldTransform() end 
function CCTransitionFadeUp:getChildren() end 
function CCTransitionFadeUp:transformAncestors() end 
function CCTransitionFadeUp:getGrid() end 
function CCTransitionFadeUp:isRunning() end 
function CCTransitionFadeUp:registerScriptHandler() end 
function CCTransitionFadeUp:getCamera() end 
function CCTransitionFadeUp:isIgnoreAnchorPointForPosition() end 
function CCTransitionFadeUp:getUserData() end 
function CCTransitionFadeUp:setPositionY() end 
function CCTransitionFadeUp:getZOrder() end 
---
-- @return @class CCTransitionFadeUp
--
function CCTransitionFadeUp:create() end 
---
-- @return @class CCTransitionFadeUp
--
function CCTransitionFadeUp:create() end 
