---@classdef CCTransitionZoomFlipAngular
CCTransitionZoomFlipAngular = {}
function CCTransitionZoomFlipAngular:autorelease() end 
function CCTransitionZoomFlipAngular:retain() end 
function CCTransitionZoomFlipAngular:retainCount() end 
function CCTransitionZoomFlipAngular:isEqual() end 
function CCTransitionZoomFlipAngular:copy() end 
function CCTransitionZoomFlipAngular:release() end 
function CCTransitionZoomFlipAngular:isSingleReference() end 
function CCTransitionZoomFlipAngular:visit() end 
function CCTransitionZoomFlipAngular:getUserObject() end 
function CCTransitionZoomFlipAngular:getSkewY() end 
function CCTransitionZoomFlipAngular:convertTouchToNodeSpace() end 
function CCTransitionZoomFlipAngular:getVertexZ() end 
function CCTransitionZoomFlipAngular:setParent() end 
function CCTransitionZoomFlipAngular:boundingBox() end 
function CCTransitionZoomFlipAngular:setVisible() end 
function CCTransitionZoomFlipAngular:stopActionByTag() end 
function CCTransitionZoomFlipAngular:getScaleY() end 
function CCTransitionZoomFlipAngular:setScaleX() end 
function CCTransitionZoomFlipAngular:reorderChild() end 
function CCTransitionZoomFlipAngular:setPositionX() end 
function CCTransitionZoomFlipAngular:removeFromParentAndCleanup() end 
function CCTransitionZoomFlipAngular:setTag() end 
function CCTransitionZoomFlipAngular:getChildrenCount() end 
function CCTransitionZoomFlipAngular:setScale() end 
function CCTransitionZoomFlipAngular:addChild() end 
function CCTransitionZoomFlipAngular:isVisible() end 
function CCTransitionZoomFlipAngular:setActionManager() end 
function CCTransitionZoomFlipAngular:setScheduler() end 
function CCTransitionZoomFlipAngular:getContentSize() end 
function CCTransitionZoomFlipAngular:getAnchorPoint() end 
function CCTransitionZoomFlipAngular:getTag() end 
function CCTransitionZoomFlipAngular:setGrid() end 
function CCTransitionZoomFlipAngular:convertToWorldSpace() end 
function CCTransitionZoomFlipAngular:setSkewX() end 
function CCTransitionZoomFlipAngular:setZOrder() end 
function CCTransitionZoomFlipAngular:worldToNodeTransform() end 
function CCTransitionZoomFlipAngular:getPosition() end 
function CCTransitionZoomFlipAngular:getSkewX() end 
function CCTransitionZoomFlipAngular:getScheduler() end 
function CCTransitionZoomFlipAngular:ignoreAnchorPointForPosition() end 
function CCTransitionZoomFlipAngular:setPosition() end 
function CCTransitionZoomFlipAngular:getParent() end 
function CCTransitionZoomFlipAngular:unscheduleUpdate() end 
function CCTransitionZoomFlipAngular:scheduleUpdateWithPriorityLua() end 
function CCTransitionZoomFlipAngular:removeChildByTag() end 
function CCTransitionZoomFlipAngular:convertToNodeSpaceAR() end 
function CCTransitionZoomFlipAngular:convertTouchToNodeSpaceAR() end 
function CCTransitionZoomFlipAngular:convertToWorldSpaceAR() end 
function CCTransitionZoomFlipAngular:setRotation() end 
function CCTransitionZoomFlipAngular:getComponent() end 
function CCTransitionZoomFlipAngular:convertToNodeSpace() end 
---
-- @return @class CCTransitionZoomFlipAngular
--
function CCTransitionZoomFlipAngular:create() end 
function CCTransitionZoomFlipAngular:getScale() end 
function CCTransitionZoomFlipAngular:getPositionY() end 
function CCTransitionZoomFlipAngular:getChildByTag() end 
function CCTransitionZoomFlipAngular:setContentSize() end 
function CCTransitionZoomFlipAngular:description() end 
function CCTransitionZoomFlipAngular:cleanup() end 
function CCTransitionZoomFlipAngular:getRotation() end 
function CCTransitionZoomFlipAngular:nodeToParentTransform() end 
function CCTransitionZoomFlipAngular:stopAction() end 
function CCTransitionZoomFlipAngular:numberOfRunningActions() end 
function CCTransitionZoomFlipAngular:removeAllChildren() end 
function CCTransitionZoomFlipAngular:runAction() end 
function CCTransitionZoomFlipAngular:setUserObject() end 
function CCTransitionZoomFlipAngular:parentToNodeTransform() end 
function CCTransitionZoomFlipAngular:removeChild() end 
function CCTransitionZoomFlipAngular:getAnchorPointInPoints() end 
function CCTransitionZoomFlipAngular:getScaleX() end 
function CCTransitionZoomFlipAngular:transform() end 
function CCTransitionZoomFlipAngular:getActionManager() end 
function CCTransitionZoomFlipAngular:draw() end 
function CCTransitionZoomFlipAngular:setScaleY() end 
function CCTransitionZoomFlipAngular:unregisterScriptHandler() end 
function CCTransitionZoomFlipAngular:setVertexZ() end 
function CCTransitionZoomFlipAngular:setAnchorPoint() end 
function CCTransitionZoomFlipAngular:getShaderProgram() end 
function CCTransitionZoomFlipAngular:stopAllActions() end 
function CCTransitionZoomFlipAngular:setUserData() end 
function CCTransitionZoomFlipAngular:setShaderProgram() end 
function CCTransitionZoomFlipAngular:getActionByTag() end 
function CCTransitionZoomFlipAngular:getGLServerState() end 
function CCTransitionZoomFlipAngular:getOrderOfArrival() end 
function CCTransitionZoomFlipAngular:getPositionX() end 
function CCTransitionZoomFlipAngular:setGLServerState() end 
function CCTransitionZoomFlipAngular:setSkewY() end 
function CCTransitionZoomFlipAngular:setOrderOfArrival() end 
function CCTransitionZoomFlipAngular:nodeToWorldTransform() end 
function CCTransitionZoomFlipAngular:getChildren() end 
function CCTransitionZoomFlipAngular:transformAncestors() end 
function CCTransitionZoomFlipAngular:getGrid() end 
function CCTransitionZoomFlipAngular:isRunning() end 
function CCTransitionZoomFlipAngular:registerScriptHandler() end 
function CCTransitionZoomFlipAngular:getCamera() end 
function CCTransitionZoomFlipAngular:isIgnoreAnchorPointForPosition() end 
function CCTransitionZoomFlipAngular:getUserData() end 
function CCTransitionZoomFlipAngular:setPositionY() end 
function CCTransitionZoomFlipAngular:getZOrder() end 
---
-- @return @class CCTransitionZoomFlipAngular
--
function CCTransitionZoomFlipAngular:create() end 
---
-- @return @class CCTransitionZoomFlipAngular
--
function CCTransitionZoomFlipAngular:create() end 
