---@classdef CCTransitionMoveInL
CCTransitionMoveInL = {}
function CCTransitionMoveInL:autorelease() end 
function CCTransitionMoveInL:retain() end 
function CCTransitionMoveInL:retainCount() end 
function CCTransitionMoveInL:isEqual() end 
function CCTransitionMoveInL:copy() end 
function CCTransitionMoveInL:release() end 
function CCTransitionMoveInL:isSingleReference() end 
function CCTransitionMoveInL:visit() end 
function CCTransitionMoveInL:getUserObject() end 
function CCTransitionMoveInL:getSkewY() end 
function CCTransitionMoveInL:convertTouchToNodeSpace() end 
function CCTransitionMoveInL:getVertexZ() end 
function CCTransitionMoveInL:setParent() end 
function CCTransitionMoveInL:boundingBox() end 
function CCTransitionMoveInL:setVisible() end 
function CCTransitionMoveInL:stopActionByTag() end 
function CCTransitionMoveInL:getScaleY() end 
function CCTransitionMoveInL:setScaleX() end 
function CCTransitionMoveInL:reorderChild() end 
function CCTransitionMoveInL:setPositionX() end 
function CCTransitionMoveInL:removeFromParentAndCleanup() end 
function CCTransitionMoveInL:setTag() end 
function CCTransitionMoveInL:getChildrenCount() end 
function CCTransitionMoveInL:setScale() end 
function CCTransitionMoveInL:addChild() end 
function CCTransitionMoveInL:isVisible() end 
function CCTransitionMoveInL:setActionManager() end 
function CCTransitionMoveInL:setScheduler() end 
function CCTransitionMoveInL:getContentSize() end 
function CCTransitionMoveInL:getAnchorPoint() end 
function CCTransitionMoveInL:getTag() end 
function CCTransitionMoveInL:setGrid() end 
function CCTransitionMoveInL:convertToWorldSpace() end 
function CCTransitionMoveInL:setSkewX() end 
function CCTransitionMoveInL:setZOrder() end 
function CCTransitionMoveInL:worldToNodeTransform() end 
function CCTransitionMoveInL:getPosition() end 
function CCTransitionMoveInL:getSkewX() end 
function CCTransitionMoveInL:getScheduler() end 
function CCTransitionMoveInL:ignoreAnchorPointForPosition() end 
function CCTransitionMoveInL:setPosition() end 
function CCTransitionMoveInL:getParent() end 
function CCTransitionMoveInL:unscheduleUpdate() end 
function CCTransitionMoveInL:scheduleUpdateWithPriorityLua() end 
function CCTransitionMoveInL:removeChildByTag() end 
function CCTransitionMoveInL:convertToNodeSpaceAR() end 
function CCTransitionMoveInL:convertTouchToNodeSpaceAR() end 
function CCTransitionMoveInL:convertToWorldSpaceAR() end 
function CCTransitionMoveInL:setRotation() end 
function CCTransitionMoveInL:getComponent() end 
function CCTransitionMoveInL:convertToNodeSpace() end 
---
-- @return @class CCTransitionMoveInL
--
function CCTransitionMoveInL:create() end 
function CCTransitionMoveInL:getScale() end 
function CCTransitionMoveInL:getPositionY() end 
function CCTransitionMoveInL:getChildByTag() end 
function CCTransitionMoveInL:setContentSize() end 
function CCTransitionMoveInL:description() end 
function CCTransitionMoveInL:cleanup() end 
function CCTransitionMoveInL:getRotation() end 
function CCTransitionMoveInL:nodeToParentTransform() end 
function CCTransitionMoveInL:stopAction() end 
function CCTransitionMoveInL:numberOfRunningActions() end 
function CCTransitionMoveInL:removeAllChildren() end 
function CCTransitionMoveInL:runAction() end 
function CCTransitionMoveInL:setUserObject() end 
function CCTransitionMoveInL:parentToNodeTransform() end 
function CCTransitionMoveInL:removeChild() end 
function CCTransitionMoveInL:getAnchorPointInPoints() end 
function CCTransitionMoveInL:getScaleX() end 
function CCTransitionMoveInL:transform() end 
function CCTransitionMoveInL:getActionManager() end 
function CCTransitionMoveInL:draw() end 
function CCTransitionMoveInL:setScaleY() end 
function CCTransitionMoveInL:unregisterScriptHandler() end 
function CCTransitionMoveInL:setVertexZ() end 
function CCTransitionMoveInL:setAnchorPoint() end 
function CCTransitionMoveInL:getShaderProgram() end 
function CCTransitionMoveInL:stopAllActions() end 
function CCTransitionMoveInL:setUserData() end 
function CCTransitionMoveInL:setShaderProgram() end 
function CCTransitionMoveInL:getActionByTag() end 
function CCTransitionMoveInL:getGLServerState() end 
function CCTransitionMoveInL:getOrderOfArrival() end 
function CCTransitionMoveInL:getPositionX() end 
function CCTransitionMoveInL:setGLServerState() end 
function CCTransitionMoveInL:setSkewY() end 
function CCTransitionMoveInL:setOrderOfArrival() end 
function CCTransitionMoveInL:nodeToWorldTransform() end 
function CCTransitionMoveInL:getChildren() end 
function CCTransitionMoveInL:transformAncestors() end 
function CCTransitionMoveInL:getGrid() end 
function CCTransitionMoveInL:isRunning() end 
function CCTransitionMoveInL:registerScriptHandler() end 
function CCTransitionMoveInL:getCamera() end 
function CCTransitionMoveInL:isIgnoreAnchorPointForPosition() end 
function CCTransitionMoveInL:getUserData() end 
function CCTransitionMoveInL:setPositionY() end 
function CCTransitionMoveInL:getZOrder() end 
---
-- @return @class CCTransitionMoveInL
--
function CCTransitionMoveInL:create() end 
---
-- @return @class CCTransitionMoveInL
--
function CCTransitionMoveInL:create() end 
