---@classdef CCTransitionScene
CCTransitionScene = {}
function CCTransitionScene:autorelease() end 
function CCTransitionScene:retain() end 
function CCTransitionScene:retainCount() end 
function CCTransitionScene:isEqual() end 
function CCTransitionScene:copy() end 
function CCTransitionScene:release() end 
function CCTransitionScene:isSingleReference() end 
function CCTransitionScene:visit() end 
function CCTransitionScene:getUserObject() end 
function CCTransitionScene:getSkewY() end 
function CCTransitionScene:convertTouchToNodeSpace() end 
function CCTransitionScene:getVertexZ() end 
function CCTransitionScene:setParent() end 
function CCTransitionScene:boundingBox() end 
function CCTransitionScene:setVisible() end 
function CCTransitionScene:stopActionByTag() end 
function CCTransitionScene:getScaleY() end 
function CCTransitionScene:setScaleX() end 
function CCTransitionScene:reorderChild() end 
function CCTransitionScene:setPositionX() end 
function CCTransitionScene:removeFromParentAndCleanup() end 
function CCTransitionScene:setTag() end 
function CCTransitionScene:getChildrenCount() end 
function CCTransitionScene:setScale() end 
function CCTransitionScene:addChild() end 
function CCTransitionScene:isVisible() end 
function CCTransitionScene:setActionManager() end 
function CCTransitionScene:setScheduler() end 
function CCTransitionScene:getContentSize() end 
function CCTransitionScene:getAnchorPoint() end 
function CCTransitionScene:getTag() end 
function CCTransitionScene:setGrid() end 
function CCTransitionScene:convertToWorldSpace() end 
function CCTransitionScene:setSkewX() end 
function CCTransitionScene:setZOrder() end 
function CCTransitionScene:worldToNodeTransform() end 
function CCTransitionScene:getPosition() end 
function CCTransitionScene:getSkewX() end 
function CCTransitionScene:getScheduler() end 
function CCTransitionScene:ignoreAnchorPointForPosition() end 
function CCTransitionScene:setPosition() end 
function CCTransitionScene:getParent() end 
function CCTransitionScene:unscheduleUpdate() end 
function CCTransitionScene:scheduleUpdateWithPriorityLua() end 
function CCTransitionScene:removeChildByTag() end 
function CCTransitionScene:convertToNodeSpaceAR() end 
function CCTransitionScene:convertTouchToNodeSpaceAR() end 
function CCTransitionScene:convertToWorldSpaceAR() end 
function CCTransitionScene:setRotation() end 
function CCTransitionScene:getComponent() end 
function CCTransitionScene:convertToNodeSpace() end 
---
-- @return @class CCTransitionScene
--
function CCTransitionScene:create() end 
function CCTransitionScene:getScale() end 
function CCTransitionScene:getPositionY() end 
function CCTransitionScene:getChildByTag() end 
function CCTransitionScene:setContentSize() end 
function CCTransitionScene:description() end 
function CCTransitionScene:cleanup() end 
function CCTransitionScene:getRotation() end 
function CCTransitionScene:nodeToParentTransform() end 
function CCTransitionScene:stopAction() end 
function CCTransitionScene:numberOfRunningActions() end 
function CCTransitionScene:removeAllChildren() end 
function CCTransitionScene:runAction() end 
function CCTransitionScene:setUserObject() end 
function CCTransitionScene:parentToNodeTransform() end 
function CCTransitionScene:removeChild() end 
function CCTransitionScene:getAnchorPointInPoints() end 
function CCTransitionScene:getScaleX() end 
function CCTransitionScene:transform() end 
function CCTransitionScene:getActionManager() end 
function CCTransitionScene:draw() end 
function CCTransitionScene:setScaleY() end 
function CCTransitionScene:unregisterScriptHandler() end 
function CCTransitionScene:setVertexZ() end 
function CCTransitionScene:setAnchorPoint() end 
function CCTransitionScene:getShaderProgram() end 
function CCTransitionScene:stopAllActions() end 
function CCTransitionScene:setUserData() end 
function CCTransitionScene:setShaderProgram() end 
function CCTransitionScene:getActionByTag() end 
function CCTransitionScene:getGLServerState() end 
function CCTransitionScene:getOrderOfArrival() end 
function CCTransitionScene:getPositionX() end 
function CCTransitionScene:setGLServerState() end 
function CCTransitionScene:setSkewY() end 
function CCTransitionScene:setOrderOfArrival() end 
function CCTransitionScene:nodeToWorldTransform() end 
function CCTransitionScene:getChildren() end 
function CCTransitionScene:transformAncestors() end 
function CCTransitionScene:getGrid() end 
function CCTransitionScene:isRunning() end 
function CCTransitionScene:registerScriptHandler() end 
function CCTransitionScene:getCamera() end 
function CCTransitionScene:isIgnoreAnchorPointForPosition() end 
function CCTransitionScene:getUserData() end 
function CCTransitionScene:setPositionY() end 
function CCTransitionScene:getZOrder() end 
---
-- @return @class CCTransitionScene
--
function CCTransitionScene:create() end 
---
-- @return @class CCTransitionScene
--
function CCTransitionScene:create() end 
