---@classdef CCTransitionZoomFlipY
CCTransitionZoomFlipY = {}
function CCTransitionZoomFlipY:autorelease() end 
function CCTransitionZoomFlipY:retain() end 
function CCTransitionZoomFlipY:retainCount() end 
function CCTransitionZoomFlipY:isEqual() end 
function CCTransitionZoomFlipY:copy() end 
function CCTransitionZoomFlipY:release() end 
function CCTransitionZoomFlipY:isSingleReference() end 
function CCTransitionZoomFlipY:visit() end 
function CCTransitionZoomFlipY:getUserObject() end 
function CCTransitionZoomFlipY:getSkewY() end 
function CCTransitionZoomFlipY:convertTouchToNodeSpace() end 
function CCTransitionZoomFlipY:getVertexZ() end 
function CCTransitionZoomFlipY:setParent() end 
function CCTransitionZoomFlipY:boundingBox() end 
function CCTransitionZoomFlipY:setVisible() end 
function CCTransitionZoomFlipY:stopActionByTag() end 
function CCTransitionZoomFlipY:getScaleY() end 
function CCTransitionZoomFlipY:setScaleX() end 
function CCTransitionZoomFlipY:reorderChild() end 
function CCTransitionZoomFlipY:setPositionX() end 
function CCTransitionZoomFlipY:removeFromParentAndCleanup() end 
function CCTransitionZoomFlipY:setTag() end 
function CCTransitionZoomFlipY:getChildrenCount() end 
function CCTransitionZoomFlipY:setScale() end 
function CCTransitionZoomFlipY:addChild() end 
function CCTransitionZoomFlipY:isVisible() end 
function CCTransitionZoomFlipY:setActionManager() end 
function CCTransitionZoomFlipY:setScheduler() end 
function CCTransitionZoomFlipY:getContentSize() end 
function CCTransitionZoomFlipY:getAnchorPoint() end 
function CCTransitionZoomFlipY:getTag() end 
function CCTransitionZoomFlipY:setGrid() end 
function CCTransitionZoomFlipY:convertToWorldSpace() end 
function CCTransitionZoomFlipY:setSkewX() end 
function CCTransitionZoomFlipY:setZOrder() end 
function CCTransitionZoomFlipY:worldToNodeTransform() end 
function CCTransitionZoomFlipY:getPosition() end 
function CCTransitionZoomFlipY:getSkewX() end 
function CCTransitionZoomFlipY:getScheduler() end 
function CCTransitionZoomFlipY:ignoreAnchorPointForPosition() end 
function CCTransitionZoomFlipY:setPosition() end 
function CCTransitionZoomFlipY:getParent() end 
function CCTransitionZoomFlipY:unscheduleUpdate() end 
function CCTransitionZoomFlipY:scheduleUpdateWithPriorityLua() end 
function CCTransitionZoomFlipY:removeChildByTag() end 
function CCTransitionZoomFlipY:convertToNodeSpaceAR() end 
function CCTransitionZoomFlipY:convertTouchToNodeSpaceAR() end 
function CCTransitionZoomFlipY:convertToWorldSpaceAR() end 
function CCTransitionZoomFlipY:setRotation() end 
function CCTransitionZoomFlipY:getComponent() end 
function CCTransitionZoomFlipY:convertToNodeSpace() end 
---
-- @return @class CCTransitionZoomFlipY
--
function CCTransitionZoomFlipY:create() end 
function CCTransitionZoomFlipY:getScale() end 
function CCTransitionZoomFlipY:getPositionY() end 
function CCTransitionZoomFlipY:getChildByTag() end 
function CCTransitionZoomFlipY:setContentSize() end 
function CCTransitionZoomFlipY:description() end 
function CCTransitionZoomFlipY:cleanup() end 
function CCTransitionZoomFlipY:getRotation() end 
function CCTransitionZoomFlipY:nodeToParentTransform() end 
function CCTransitionZoomFlipY:stopAction() end 
function CCTransitionZoomFlipY:numberOfRunningActions() end 
function CCTransitionZoomFlipY:removeAllChildren() end 
function CCTransitionZoomFlipY:runAction() end 
function CCTransitionZoomFlipY:setUserObject() end 
function CCTransitionZoomFlipY:parentToNodeTransform() end 
function CCTransitionZoomFlipY:removeChild() end 
function CCTransitionZoomFlipY:getAnchorPointInPoints() end 
function CCTransitionZoomFlipY:getScaleX() end 
function CCTransitionZoomFlipY:transform() end 
function CCTransitionZoomFlipY:getActionManager() end 
function CCTransitionZoomFlipY:draw() end 
function CCTransitionZoomFlipY:setScaleY() end 
function CCTransitionZoomFlipY:unregisterScriptHandler() end 
function CCTransitionZoomFlipY:setVertexZ() end 
function CCTransitionZoomFlipY:setAnchorPoint() end 
function CCTransitionZoomFlipY:getShaderProgram() end 
function CCTransitionZoomFlipY:stopAllActions() end 
function CCTransitionZoomFlipY:setUserData() end 
function CCTransitionZoomFlipY:setShaderProgram() end 
function CCTransitionZoomFlipY:getActionByTag() end 
function CCTransitionZoomFlipY:getGLServerState() end 
function CCTransitionZoomFlipY:getOrderOfArrival() end 
function CCTransitionZoomFlipY:getPositionX() end 
function CCTransitionZoomFlipY:setGLServerState() end 
function CCTransitionZoomFlipY:setSkewY() end 
function CCTransitionZoomFlipY:setOrderOfArrival() end 
function CCTransitionZoomFlipY:nodeToWorldTransform() end 
function CCTransitionZoomFlipY:getChildren() end 
function CCTransitionZoomFlipY:transformAncestors() end 
function CCTransitionZoomFlipY:getGrid() end 
function CCTransitionZoomFlipY:isRunning() end 
function CCTransitionZoomFlipY:registerScriptHandler() end 
function CCTransitionZoomFlipY:getCamera() end 
function CCTransitionZoomFlipY:isIgnoreAnchorPointForPosition() end 
function CCTransitionZoomFlipY:getUserData() end 
function CCTransitionZoomFlipY:setPositionY() end 
function CCTransitionZoomFlipY:getZOrder() end 
---
-- @return @class CCTransitionZoomFlipY
--
function CCTransitionZoomFlipY:create() end 
---
-- @return @class CCTransitionZoomFlipY
--
function CCTransitionZoomFlipY:create() end 
