---@classdef CCTransitionFade
CCTransitionFade = {}
function CCTransitionFade:autorelease() end 
function CCTransitionFade:retain() end 
function CCTransitionFade:retainCount() end 
function CCTransitionFade:isEqual() end 
function CCTransitionFade:copy() end 
function CCTransitionFade:release() end 
function CCTransitionFade:isSingleReference() end 
function CCTransitionFade:visit() end 
function CCTransitionFade:getUserObject() end 
function CCTransitionFade:getSkewY() end 
function CCTransitionFade:convertTouchToNodeSpace() end 
function CCTransitionFade:getVertexZ() end 
function CCTransitionFade:setParent() end 
function CCTransitionFade:boundingBox() end 
function CCTransitionFade:setVisible() end 
function CCTransitionFade:stopActionByTag() end 
function CCTransitionFade:getScaleY() end 
function CCTransitionFade:setScaleX() end 
function CCTransitionFade:reorderChild() end 
function CCTransitionFade:setPositionX() end 
function CCTransitionFade:removeFromParentAndCleanup() end 
function CCTransitionFade:setTag() end 
function CCTransitionFade:getChildrenCount() end 
function CCTransitionFade:setScale() end 
function CCTransitionFade:addChild() end 
function CCTransitionFade:isVisible() end 
function CCTransitionFade:setActionManager() end 
function CCTransitionFade:setScheduler() end 
function CCTransitionFade:getContentSize() end 
function CCTransitionFade:getAnchorPoint() end 
function CCTransitionFade:getTag() end 
function CCTransitionFade:setGrid() end 
function CCTransitionFade:convertToWorldSpace() end 
function CCTransitionFade:setSkewX() end 
function CCTransitionFade:setZOrder() end 
function CCTransitionFade:worldToNodeTransform() end 
function CCTransitionFade:getPosition() end 
function CCTransitionFade:getSkewX() end 
function CCTransitionFade:getScheduler() end 
function CCTransitionFade:ignoreAnchorPointForPosition() end 
function CCTransitionFade:setPosition() end 
function CCTransitionFade:getParent() end 
function CCTransitionFade:unscheduleUpdate() end 
function CCTransitionFade:scheduleUpdateWithPriorityLua() end 
function CCTransitionFade:removeChildByTag() end 
function CCTransitionFade:convertToNodeSpaceAR() end 
function CCTransitionFade:convertTouchToNodeSpaceAR() end 
function CCTransitionFade:convertToWorldSpaceAR() end 
function CCTransitionFade:setRotation() end 
function CCTransitionFade:getComponent() end 
function CCTransitionFade:convertToNodeSpace() end 
---
-- @return @class CCTransitionFade
--
function CCTransitionFade:create() end 
function CCTransitionFade:getScale() end 
function CCTransitionFade:getPositionY() end 
function CCTransitionFade:getChildByTag() end 
function CCTransitionFade:setContentSize() end 
function CCTransitionFade:description() end 
function CCTransitionFade:cleanup() end 
function CCTransitionFade:getRotation() end 
function CCTransitionFade:nodeToParentTransform() end 
function CCTransitionFade:stopAction() end 
function CCTransitionFade:numberOfRunningActions() end 
function CCTransitionFade:removeAllChildren() end 
function CCTransitionFade:runAction() end 
function CCTransitionFade:setUserObject() end 
function CCTransitionFade:parentToNodeTransform() end 
function CCTransitionFade:removeChild() end 
function CCTransitionFade:getAnchorPointInPoints() end 
function CCTransitionFade:getScaleX() end 
function CCTransitionFade:transform() end 
function CCTransitionFade:getActionManager() end 
function CCTransitionFade:draw() end 
function CCTransitionFade:setScaleY() end 
function CCTransitionFade:unregisterScriptHandler() end 
function CCTransitionFade:setVertexZ() end 
function CCTransitionFade:setAnchorPoint() end 
function CCTransitionFade:getShaderProgram() end 
function CCTransitionFade:stopAllActions() end 
function CCTransitionFade:setUserData() end 
function CCTransitionFade:setShaderProgram() end 
function CCTransitionFade:getActionByTag() end 
function CCTransitionFade:getGLServerState() end 
function CCTransitionFade:getOrderOfArrival() end 
function CCTransitionFade:getPositionX() end 
function CCTransitionFade:setGLServerState() end 
function CCTransitionFade:setSkewY() end 
function CCTransitionFade:setOrderOfArrival() end 
function CCTransitionFade:nodeToWorldTransform() end 
function CCTransitionFade:getChildren() end 
function CCTransitionFade:transformAncestors() end 
function CCTransitionFade:getGrid() end 
function CCTransitionFade:isRunning() end 
function CCTransitionFade:registerScriptHandler() end 
function CCTransitionFade:getCamera() end 
function CCTransitionFade:isIgnoreAnchorPointForPosition() end 
function CCTransitionFade:getUserData() end 
function CCTransitionFade:setPositionY() end 
function CCTransitionFade:getZOrder() end 
---
-- @return @class CCTransitionFade
--
function CCTransitionFade:create() end 
---
-- @return @class CCTransitionFade
--
function CCTransitionFade:create() end 
