---@classdef CCTransitionMoveInB
CCTransitionMoveInB = {}
function CCTransitionMoveInB:autorelease() end 
function CCTransitionMoveInB:retain() end 
function CCTransitionMoveInB:retainCount() end 
function CCTransitionMoveInB:isEqual() end 
function CCTransitionMoveInB:copy() end 
function CCTransitionMoveInB:release() end 
function CCTransitionMoveInB:isSingleReference() end 
function CCTransitionMoveInB:visit() end 
function CCTransitionMoveInB:getUserObject() end 
function CCTransitionMoveInB:getSkewY() end 
function CCTransitionMoveInB:convertTouchToNodeSpace() end 
function CCTransitionMoveInB:getVertexZ() end 
function CCTransitionMoveInB:setParent() end 
function CCTransitionMoveInB:boundingBox() end 
function CCTransitionMoveInB:setVisible() end 
function CCTransitionMoveInB:stopActionByTag() end 
function CCTransitionMoveInB:getScaleY() end 
function CCTransitionMoveInB:setScaleX() end 
function CCTransitionMoveInB:reorderChild() end 
function CCTransitionMoveInB:setPositionX() end 
function CCTransitionMoveInB:removeFromParentAndCleanup() end 
function CCTransitionMoveInB:setTag() end 
function CCTransitionMoveInB:getChildrenCount() end 
function CCTransitionMoveInB:setScale() end 
function CCTransitionMoveInB:addChild() end 
function CCTransitionMoveInB:isVisible() end 
function CCTransitionMoveInB:setActionManager() end 
function CCTransitionMoveInB:setScheduler() end 
function CCTransitionMoveInB:getContentSize() end 
function CCTransitionMoveInB:getAnchorPoint() end 
function CCTransitionMoveInB:getTag() end 
function CCTransitionMoveInB:setGrid() end 
function CCTransitionMoveInB:convertToWorldSpace() end 
function CCTransitionMoveInB:setSkewX() end 
function CCTransitionMoveInB:setZOrder() end 
function CCTransitionMoveInB:worldToNodeTransform() end 
function CCTransitionMoveInB:getPosition() end 
function CCTransitionMoveInB:getSkewX() end 
function CCTransitionMoveInB:getScheduler() end 
function CCTransitionMoveInB:ignoreAnchorPointForPosition() end 
function CCTransitionMoveInB:setPosition() end 
function CCTransitionMoveInB:getParent() end 
function CCTransitionMoveInB:unscheduleUpdate() end 
function CCTransitionMoveInB:scheduleUpdateWithPriorityLua() end 
function CCTransitionMoveInB:removeChildByTag() end 
function CCTransitionMoveInB:convertToNodeSpaceAR() end 
function CCTransitionMoveInB:convertTouchToNodeSpaceAR() end 
function CCTransitionMoveInB:convertToWorldSpaceAR() end 
function CCTransitionMoveInB:setRotation() end 
function CCTransitionMoveInB:getComponent() end 
function CCTransitionMoveInB:convertToNodeSpace() end 
---
-- @return @class CCTransitionMoveInB
--
function CCTransitionMoveInB:create() end 
function CCTransitionMoveInB:getScale() end 
function CCTransitionMoveInB:getPositionY() end 
function CCTransitionMoveInB:getChildByTag() end 
function CCTransitionMoveInB:setContentSize() end 
function CCTransitionMoveInB:description() end 
function CCTransitionMoveInB:cleanup() end 
function CCTransitionMoveInB:getRotation() end 
function CCTransitionMoveInB:nodeToParentTransform() end 
function CCTransitionMoveInB:stopAction() end 
function CCTransitionMoveInB:numberOfRunningActions() end 
function CCTransitionMoveInB:removeAllChildren() end 
function CCTransitionMoveInB:runAction() end 
function CCTransitionMoveInB:setUserObject() end 
function CCTransitionMoveInB:parentToNodeTransform() end 
function CCTransitionMoveInB:removeChild() end 
function CCTransitionMoveInB:getAnchorPointInPoints() end 
function CCTransitionMoveInB:getScaleX() end 
function CCTransitionMoveInB:transform() end 
function CCTransitionMoveInB:getActionManager() end 
function CCTransitionMoveInB:draw() end 
function CCTransitionMoveInB:setScaleY() end 
function CCTransitionMoveInB:unregisterScriptHandler() end 
function CCTransitionMoveInB:setVertexZ() end 
function CCTransitionMoveInB:setAnchorPoint() end 
function CCTransitionMoveInB:getShaderProgram() end 
function CCTransitionMoveInB:stopAllActions() end 
function CCTransitionMoveInB:setUserData() end 
function CCTransitionMoveInB:setShaderProgram() end 
function CCTransitionMoveInB:getActionByTag() end 
function CCTransitionMoveInB:getGLServerState() end 
function CCTransitionMoveInB:getOrderOfArrival() end 
function CCTransitionMoveInB:getPositionX() end 
function CCTransitionMoveInB:setGLServerState() end 
function CCTransitionMoveInB:setSkewY() end 
function CCTransitionMoveInB:setOrderOfArrival() end 
function CCTransitionMoveInB:nodeToWorldTransform() end 
function CCTransitionMoveInB:getChildren() end 
function CCTransitionMoveInB:transformAncestors() end 
function CCTransitionMoveInB:getGrid() end 
function CCTransitionMoveInB:isRunning() end 
function CCTransitionMoveInB:registerScriptHandler() end 
function CCTransitionMoveInB:getCamera() end 
function CCTransitionMoveInB:isIgnoreAnchorPointForPosition() end 
function CCTransitionMoveInB:getUserData() end 
function CCTransitionMoveInB:setPositionY() end 
function CCTransitionMoveInB:getZOrder() end 
---
-- @return @class CCTransitionMoveInB
--
function CCTransitionMoveInB:create() end 
---
-- @return @class CCTransitionMoveInB
--
function CCTransitionMoveInB:create() end 
