---@classdef CheckBox
CheckBox = {}
function CheckBox:autorelease() end 
function CheckBox:retain() end 
function CheckBox:retainCount() end 
function CheckBox:isEqual() end 
function CheckBox:copy() end 
function CheckBox:release() end 
function CheckBox:isSingleReference() end 
function CheckBox:visit() end 
function CheckBox:getUserObject() end 
function CheckBox:getSkewY() end 
function CheckBox:convertTouchToNodeSpace() end 
function CheckBox:getVertexZ() end 
function CheckBox:setParent() end 
function CheckBox:boundingBox() end 
function CheckBox:setVisible() end 
function CheckBox:stopActionByTag() end 
function CheckBox:getScaleY() end 
function CheckBox:setScaleX() end 
function CheckBox:reorderChild() end 
function CheckBox:setPositionX() end 
function CheckBox:removeFromParentAndCleanup() end 
function CheckBox:setTag() end 
function CheckBox:getChildrenCount() end 
function CheckBox:setScale() end 
function CheckBox:addChild() end 
function CheckBox:isVisible() end 
function CheckBox:setActionManager() end 
function CheckBox:setScheduler() end 
function CheckBox:getContentSize() end 
function CheckBox:getAnchorPoint() end 
function CheckBox:getTag() end 
function CheckBox:setGrid() end 
function CheckBox:convertToWorldSpace() end 
function CheckBox:setSkewX() end 
function CheckBox:setZOrder() end 
function CheckBox:worldToNodeTransform() end 
function CheckBox:getPosition() end 
function CheckBox:getSkewX() end 
function CheckBox:getScheduler() end 
function CheckBox:ignoreAnchorPointForPosition() end 
function CheckBox:setPosition() end 
function CheckBox:getParent() end 
function CheckBox:unscheduleUpdate() end 
function CheckBox:scheduleUpdateWithPriorityLua() end 
function CheckBox:removeChildByTag() end 
function CheckBox:convertToNodeSpaceAR() end 
function CheckBox:convertTouchToNodeSpaceAR() end 
function CheckBox:convertToWorldSpaceAR() end 
function CheckBox:setRotation() end 
function CheckBox:getComponent() end 
function CheckBox:convertToNodeSpace() end 
---
-- @return @class CheckBox
--
function CheckBox:create() end 
function CheckBox:getScale() end 
function CheckBox:getPositionY() end 
function CheckBox:getChildByTag() end 
function CheckBox:setContentSize() end 
function CheckBox:description() end 
function CheckBox:cleanup() end 
function CheckBox:getRotation() end 
function CheckBox:nodeToParentTransform() end 
function CheckBox:stopAction() end 
function CheckBox:numberOfRunningActions() end 
function CheckBox:removeAllChildren() end 
function CheckBox:runAction() end 
function CheckBox:setUserObject() end 
function CheckBox:parentToNodeTransform() end 
function CheckBox:removeChild() end 
function CheckBox:getAnchorPointInPoints() end 
function CheckBox:getScaleX() end 
function CheckBox:transform() end 
function CheckBox:getActionManager() end 
function CheckBox:draw() end 
function CheckBox:setScaleY() end 
function CheckBox:unregisterScriptHandler() end 
function CheckBox:setVertexZ() end 
function CheckBox:setAnchorPoint() end 
function CheckBox:getShaderProgram() end 
function CheckBox:stopAllActions() end 
function CheckBox:setUserData() end 
function CheckBox:setShaderProgram() end 
function CheckBox:getActionByTag() end 
function CheckBox:getGLServerState() end 
function CheckBox:getOrderOfArrival() end 
function CheckBox:getPositionX() end 
function CheckBox:setGLServerState() end 
function CheckBox:setSkewY() end 
function CheckBox:setOrderOfArrival() end 
function CheckBox:nodeToWorldTransform() end 
function CheckBox:getChildren() end 
function CheckBox:transformAncestors() end 
function CheckBox:getGrid() end 
function CheckBox:isRunning() end 
function CheckBox:registerScriptHandler() end 
function CheckBox:getCamera() end 
function CheckBox:isIgnoreAnchorPointForPosition() end 
function CheckBox:getUserData() end 
function CheckBox:setPositionY() end 
function CheckBox:getZOrder() end 
function CheckBox:removeNode() end 
function CheckBox:onTouchBegan() end 
function CheckBox:addNode() end 
function CheckBox:setLayoutParameter() end 
function CheckBox:isFlipX() end 
function CheckBox:getSizePercent() end 
function CheckBox:getLeftInParent() end 
function CheckBox:getPositionPercent() end 
function CheckBox:onTouchEnded() end 
function CheckBox:new_local() end 
function CheckBox:getRightInParent() end 
function CheckBox:checkChildInfo() end 
function CheckBox:isEnabled() end 
function CheckBox:setSizePercent() end 
function CheckBox:removeFromParentAndCleanup() end 
function CheckBox:setFlipX() end 
function CheckBox:getChildrenCount() end 
function CheckBox:isBright() end 
function CheckBox:setPositionPercent() end 
function CheckBox:addChild() end 
function CheckBox:getBottomInParent() end 
function CheckBox:setBright() end 
function CheckBox:getTouchStartPos() end 
function CheckBox:removeAllChildren() end 
function CheckBox:setPositionType() end 
function CheckBox:removeNodeByTag() end 
function CheckBox:getContentSize() end 
function CheckBox:clone() end 
function CheckBox:setFlipY() end 
function CheckBox:getTouchEndPos() end 
function CheckBox:setName() end 
function CheckBox:setPosition() end 
function CheckBox:setFocused() end 
function CheckBox:setSizeType() end 
function CheckBox:hitTest() end 
function CheckBox:addTouchEventListener() end 
function CheckBox:getCustomSize() end 
function CheckBox:isTouchEnabled() end 
function CheckBox:new() end 
function CheckBox:removeFromParent() end 
---
-- @return @class CheckBox
--
function CheckBox:create() end 
function CheckBox:delete() end 
function CheckBox:getChildByTag() end 
function CheckBox:isFocused() end 
function CheckBox:getTopInParent() end 
function CheckBox:isFlipY() end 
function CheckBox:setColor() end 
function CheckBox:removeAllChildren() end 
function CheckBox:updateSizeAndPosition() end 
function CheckBox:getLayoutParameter() end 
function CheckBox:getName() end 
function CheckBox:removeChild() end 
function CheckBox:onEnter() end 
function CheckBox:getVirtualRenderer() end 
function CheckBox:getDescription() end 
function CheckBox:getChildByName() end 
function CheckBox:isIgnoreContentAdaptWithSize() end 
function CheckBox:ignoreContentAdaptWithSize() end 
function CheckBox:onExit() end 
function CheckBox:visit() end 
function CheckBox:getChildren() end 
function CheckBox:onTouchMoved() end 
function CheckBox:getLayoutSize() end 
function CheckBox:getColor() end 
function CheckBox:getPositionType() end 
function CheckBox:getTouchMovePos() end 
function CheckBox:getSize() end 
function CheckBox:getSizeType() end 
function CheckBox:setSize() end 
function CheckBox:getWidgetType() end 
function CheckBox:getOpacity() end 
function CheckBox:clippingParentAreaContainPoint() end 
function CheckBox:setTouchEnabled() end 
function CheckBox:setEnabled() end 
function CheckBox:setActionTag() end 
function CheckBox:getWorldPosition() end 
function CheckBox:didNotSelectSelf() end 
function CheckBox:sortAllChildren() end 
function CheckBox:getNodeByTag() end 
function CheckBox:onTouchCancelled() end 
function CheckBox:getNodes() end 
function CheckBox:removeAllNodes() end 
function CheckBox:setBrightStyle() end 
function CheckBox:removeChildByTag() end 
function CheckBox:getActionTag() end 
function CheckBox:setOpacity() end 
function CheckBox:addEventListenerCheckBox() end 
function CheckBox:loadTextureBackGroundDisabled() end 
function CheckBox:new() end 
---
-- @return @class CheckBox
--
function CheckBox:create() end 
function CheckBox:delete() end 
function CheckBox:getVirtualRenderer() end 
function CheckBox:getContentSize() end 
function CheckBox:setAnchorPoint() end 
function CheckBox:setSelectedState() end 
function CheckBox:onTouchEnded() end 
function CheckBox:loadTextureBackGround() end 
function CheckBox:getSelectedState() end 
function CheckBox:loadTextures() end 
function CheckBox:new_local() end 
function CheckBox:loadTextureFrontCross() end 
function CheckBox:loadTextureFrontCrossDisabled() end 
function CheckBox:getDescription() end 
function CheckBox:loadTextureBackGroundSelected() end 
