---@classdef GUIReader
GUIReader = {}
function GUIReader:autorelease() end 
function GUIReader:retain() end 
function GUIReader:retainCount() end 
function GUIReader:isEqual() end 
function GUIReader:copy() end 
function GUIReader:release() end 
function GUIReader:isSingleReference() end 
function GUIReader:new() end 
function GUIReader:delete() end 
function GUIReader:getFileDesignSize() end 
function GUIReader:getFilePath() end 
function GUIReader:storeFileDesignSize() end 
function GUIReader:new_local() end 
function GUIReader:purge() end 
function GUIReader:getVersionInteger() end 
function GUIReader:shareReader() end 
function GUIReader:widgetFromJsonFile() end 
