---@classdef ImageView
ImageView = {}
function ImageView:autorelease() end 
function ImageView:retain() end 
function ImageView:retainCount() end 
function ImageView:isEqual() end 
function ImageView:copy() end 
function ImageView:release() end 
function ImageView:isSingleReference() end 
function ImageView:visit() end 
function ImageView:getUserObject() end 
function ImageView:getSkewY() end 
function ImageView:convertTouchToNodeSpace() end 
function ImageView:getVertexZ() end 
function ImageView:setParent() end 
function ImageView:boundingBox() end 
function ImageView:setVisible() end 
function ImageView:stopActionByTag() end 
function ImageView:getScaleY() end 
function ImageView:setScaleX() end 
function ImageView:reorderChild() end 
function ImageView:setPositionX() end 
function ImageView:removeFromParentAndCleanup() end 
function ImageView:setTag() end 
function ImageView:getChildrenCount() end 
function ImageView:setScale() end 
function ImageView:addChild() end 
function ImageView:isVisible() end 
function ImageView:setActionManager() end 
function ImageView:setScheduler() end 
function ImageView:getContentSize() end 
function ImageView:getAnchorPoint() end 
function ImageView:getTag() end 
function ImageView:setGrid() end 
function ImageView:convertToWorldSpace() end 
function ImageView:setSkewX() end 
function ImageView:setZOrder() end 
function ImageView:worldToNodeTransform() end 
function ImageView:getPosition() end 
function ImageView:getSkewX() end 
function ImageView:getScheduler() end 
function ImageView:ignoreAnchorPointForPosition() end 
function ImageView:setPosition() end 
function ImageView:getParent() end 
function ImageView:unscheduleUpdate() end 
function ImageView:scheduleUpdateWithPriorityLua() end 
function ImageView:removeChildByTag() end 
function ImageView:convertToNodeSpaceAR() end 
function ImageView:convertTouchToNodeSpaceAR() end 
function ImageView:convertToWorldSpaceAR() end 
function ImageView:setRotation() end 
function ImageView:getComponent() end 
function ImageView:convertToNodeSpace() end 
---
-- @return @class ImageView
--
function ImageView:create() end 
function ImageView:getScale() end 
function ImageView:getPositionY() end 
function ImageView:getChildByTag() end 
function ImageView:setContentSize() end 
function ImageView:description() end 
function ImageView:cleanup() end 
function ImageView:getRotation() end 
function ImageView:nodeToParentTransform() end 
function ImageView:stopAction() end 
function ImageView:numberOfRunningActions() end 
function ImageView:removeAllChildren() end 
function ImageView:runAction() end 
function ImageView:setUserObject() end 
function ImageView:parentToNodeTransform() end 
function ImageView:removeChild() end 
function ImageView:getAnchorPointInPoints() end 
function ImageView:getScaleX() end 
function ImageView:transform() end 
function ImageView:getActionManager() end 
function ImageView:draw() end 
function ImageView:setScaleY() end 
function ImageView:unregisterScriptHandler() end 
function ImageView:setVertexZ() end 
function ImageView:setAnchorPoint() end 
function ImageView:getShaderProgram() end 
function ImageView:stopAllActions() end 
function ImageView:setUserData() end 
function ImageView:setShaderProgram() end 
function ImageView:getActionByTag() end 
function ImageView:getGLServerState() end 
function ImageView:getOrderOfArrival() end 
function ImageView:getPositionX() end 
function ImageView:setGLServerState() end 
function ImageView:setSkewY() end 
function ImageView:setOrderOfArrival() end 
function ImageView:nodeToWorldTransform() end 
function ImageView:getChildren() end 
function ImageView:transformAncestors() end 
function ImageView:getGrid() end 
function ImageView:isRunning() end 
function ImageView:registerScriptHandler() end 
function ImageView:getCamera() end 
function ImageView:isIgnoreAnchorPointForPosition() end 
function ImageView:getUserData() end 
function ImageView:setPositionY() end 
function ImageView:getZOrder() end 
function ImageView:removeNode() end 
function ImageView:onTouchBegan() end 
function ImageView:addNode() end 
function ImageView:setLayoutParameter() end 
function ImageView:isFlipX() end 
function ImageView:getSizePercent() end 
function ImageView:getLeftInParent() end 
function ImageView:getPositionPercent() end 
function ImageView:onTouchEnded() end 
function ImageView:new_local() end 
function ImageView:getRightInParent() end 
function ImageView:checkChildInfo() end 
function ImageView:isEnabled() end 
function ImageView:setSizePercent() end 
function ImageView:removeFromParentAndCleanup() end 
function ImageView:setFlipX() end 
function ImageView:getChildrenCount() end 
function ImageView:isBright() end 
function ImageView:setPositionPercent() end 
function ImageView:addChild() end 
function ImageView:getBottomInParent() end 
function ImageView:setBright() end 
function ImageView:getTouchStartPos() end 
function ImageView:removeAllChildren() end 
function ImageView:setPositionType() end 
function ImageView:removeNodeByTag() end 
function ImageView:getContentSize() end 
function ImageView:clone() end 
function ImageView:setFlipY() end 
function ImageView:getTouchEndPos() end 
function ImageView:setName() end 
function ImageView:setPosition() end 
function ImageView:setFocused() end 
function ImageView:setSizeType() end 
function ImageView:hitTest() end 
function ImageView:addTouchEventListener() end 
function ImageView:getCustomSize() end 
function ImageView:isTouchEnabled() end 
function ImageView:new() end 
function ImageView:removeFromParent() end 
---
-- @return @class ImageView
--
function ImageView:create() end 
function ImageView:delete() end 
function ImageView:getChildByTag() end 
function ImageView:isFocused() end 
function ImageView:getTopInParent() end 
function ImageView:isFlipY() end 
function ImageView:setColor() end 
function ImageView:removeAllChildren() end 
function ImageView:updateSizeAndPosition() end 
function ImageView:getLayoutParameter() end 
function ImageView:getName() end 
function ImageView:removeChild() end 
function ImageView:onEnter() end 
function ImageView:getVirtualRenderer() end 
function ImageView:getDescription() end 
function ImageView:getChildByName() end 
function ImageView:isIgnoreContentAdaptWithSize() end 
function ImageView:ignoreContentAdaptWithSize() end 
function ImageView:onExit() end 
function ImageView:visit() end 
function ImageView:getChildren() end 
function ImageView:onTouchMoved() end 
function ImageView:getLayoutSize() end 
function ImageView:getColor() end 
function ImageView:getPositionType() end 
function ImageView:getTouchMovePos() end 
function ImageView:getSize() end 
function ImageView:getSizeType() end 
function ImageView:setSize() end 
function ImageView:getWidgetType() end 
function ImageView:getOpacity() end 
function ImageView:clippingParentAreaContainPoint() end 
function ImageView:setTouchEnabled() end 
function ImageView:setEnabled() end 
function ImageView:setActionTag() end 
function ImageView:getWorldPosition() end 
function ImageView:didNotSelectSelf() end 
function ImageView:sortAllChildren() end 
function ImageView:getNodeByTag() end 
function ImageView:onTouchCancelled() end 
function ImageView:getNodes() end 
function ImageView:removeAllNodes() end 
function ImageView:setBrightStyle() end 
function ImageView:removeChildByTag() end 
function ImageView:getActionTag() end 
function ImageView:setOpacity() end 
function ImageView:getVirtualRenderer() end 
function ImageView:new() end 
function ImageView:setCapInsets() end 
function ImageView:delete() end 
function ImageView:ignoreContentAdaptWithSize() end 
---
-- @return @class ImageView
--
function ImageView:create() end 
function ImageView:loadTexture() end 
function ImageView:getContentSize() end 
function ImageView:setAnchorPoint() end 
function ImageView:isFlipY() end 
function ImageView:isFlipX() end 
function ImageView:setFlipY() end 
function ImageView:new_local() end 
function ImageView:setScale9Enabled() end 
function ImageView:setTextureRect() end 
function ImageView:getDescription() end 
function ImageView:setFlipX() end 
