---@classdef LabelBMFont
LabelBMFont = {}
function LabelBMFont:autorelease() end 
function LabelBMFont:retain() end 
function LabelBMFont:retainCount() end 
function LabelBMFont:isEqual() end 
function LabelBMFont:copy() end 
function LabelBMFont:release() end 
function LabelBMFont:isSingleReference() end 
function LabelBMFont:visit() end 
function LabelBMFont:getUserObject() end 
function LabelBMFont:getSkewY() end 
function LabelBMFont:convertTouchToNodeSpace() end 
function LabelBMFont:getVertexZ() end 
function LabelBMFont:setParent() end 
function LabelBMFont:boundingBox() end 
function LabelBMFont:setVisible() end 
function LabelBMFont:stopActionByTag() end 
function LabelBMFont:getScaleY() end 
function LabelBMFont:setScaleX() end 
function LabelBMFont:reorderChild() end 
function LabelBMFont:setPositionX() end 
function LabelBMFont:removeFromParentAndCleanup() end 
function LabelBMFont:setTag() end 
function LabelBMFont:getChildrenCount() end 
function LabelBMFont:setScale() end 
function LabelBMFont:addChild() end 
function LabelBMFont:isVisible() end 
function LabelBMFont:setActionManager() end 
function LabelBMFont:setScheduler() end 
function LabelBMFont:getContentSize() end 
function LabelBMFont:getAnchorPoint() end 
function LabelBMFont:getTag() end 
function LabelBMFont:setGrid() end 
function LabelBMFont:convertToWorldSpace() end 
function LabelBMFont:setSkewX() end 
function LabelBMFont:setZOrder() end 
function LabelBMFont:worldToNodeTransform() end 
function LabelBMFont:getPosition() end 
function LabelBMFont:getSkewX() end 
function LabelBMFont:getScheduler() end 
function LabelBMFont:ignoreAnchorPointForPosition() end 
function LabelBMFont:setPosition() end 
function LabelBMFont:getParent() end 
function LabelBMFont:unscheduleUpdate() end 
function LabelBMFont:scheduleUpdateWithPriorityLua() end 
function LabelBMFont:removeChildByTag() end 
function LabelBMFont:convertToNodeSpaceAR() end 
function LabelBMFont:convertTouchToNodeSpaceAR() end 
function LabelBMFont:convertToWorldSpaceAR() end 
function LabelBMFont:setRotation() end 
function LabelBMFont:getComponent() end 
function LabelBMFont:convertToNodeSpace() end 
---
-- @return @class LabelBMFont
--
function LabelBMFont:create() end 
function LabelBMFont:getScale() end 
function LabelBMFont:getPositionY() end 
function LabelBMFont:getChildByTag() end 
function LabelBMFont:setContentSize() end 
function LabelBMFont:description() end 
function LabelBMFont:cleanup() end 
function LabelBMFont:getRotation() end 
function LabelBMFont:nodeToParentTransform() end 
function LabelBMFont:stopAction() end 
function LabelBMFont:numberOfRunningActions() end 
function LabelBMFont:removeAllChildren() end 
function LabelBMFont:runAction() end 
function LabelBMFont:setUserObject() end 
function LabelBMFont:parentToNodeTransform() end 
function LabelBMFont:removeChild() end 
function LabelBMFont:getAnchorPointInPoints() end 
function LabelBMFont:getScaleX() end 
function LabelBMFont:transform() end 
function LabelBMFont:getActionManager() end 
function LabelBMFont:draw() end 
function LabelBMFont:setScaleY() end 
function LabelBMFont:unregisterScriptHandler() end 
function LabelBMFont:setVertexZ() end 
function LabelBMFont:setAnchorPoint() end 
function LabelBMFont:getShaderProgram() end 
function LabelBMFont:stopAllActions() end 
function LabelBMFont:setUserData() end 
function LabelBMFont:setShaderProgram() end 
function LabelBMFont:getActionByTag() end 
function LabelBMFont:getGLServerState() end 
function LabelBMFont:getOrderOfArrival() end 
function LabelBMFont:getPositionX() end 
function LabelBMFont:setGLServerState() end 
function LabelBMFont:setSkewY() end 
function LabelBMFont:setOrderOfArrival() end 
function LabelBMFont:nodeToWorldTransform() end 
function LabelBMFont:getChildren() end 
function LabelBMFont:transformAncestors() end 
function LabelBMFont:getGrid() end 
function LabelBMFont:isRunning() end 
function LabelBMFont:registerScriptHandler() end 
function LabelBMFont:getCamera() end 
function LabelBMFont:isIgnoreAnchorPointForPosition() end 
function LabelBMFont:getUserData() end 
function LabelBMFont:setPositionY() end 
function LabelBMFont:getZOrder() end 
function LabelBMFont:removeNode() end 
function LabelBMFont:onTouchBegan() end 
function LabelBMFont:addNode() end 
function LabelBMFont:setLayoutParameter() end 
function LabelBMFont:isFlipX() end 
function LabelBMFont:getSizePercent() end 
function LabelBMFont:getLeftInParent() end 
function LabelBMFont:getPositionPercent() end 
function LabelBMFont:onTouchEnded() end 
function LabelBMFont:new_local() end 
function LabelBMFont:getRightInParent() end 
function LabelBMFont:checkChildInfo() end 
function LabelBMFont:isEnabled() end 
function LabelBMFont:setSizePercent() end 
function LabelBMFont:removeFromParentAndCleanup() end 
function LabelBMFont:setFlipX() end 
function LabelBMFont:getChildrenCount() end 
function LabelBMFont:isBright() end 
function LabelBMFont:setPositionPercent() end 
function LabelBMFont:addChild() end 
function LabelBMFont:getBottomInParent() end 
function LabelBMFont:setBright() end 
function LabelBMFont:getTouchStartPos() end 
function LabelBMFont:removeAllChildren() end 
function LabelBMFont:setPositionType() end 
function LabelBMFont:removeNodeByTag() end 
function LabelBMFont:getContentSize() end 
function LabelBMFont:clone() end 
function LabelBMFont:setFlipY() end 
function LabelBMFont:getTouchEndPos() end 
function LabelBMFont:setName() end 
function LabelBMFont:setPosition() end 
function LabelBMFont:setFocused() end 
function LabelBMFont:setSizeType() end 
function LabelBMFont:hitTest() end 
function LabelBMFont:addTouchEventListener() end 
function LabelBMFont:getCustomSize() end 
function LabelBMFont:isTouchEnabled() end 
function LabelBMFont:new() end 
function LabelBMFont:removeFromParent() end 
---
-- @return @class LabelBMFont
--
function LabelBMFont:create() end 
function LabelBMFont:delete() end 
function LabelBMFont:getChildByTag() end 
function LabelBMFont:isFocused() end 
function LabelBMFont:getTopInParent() end 
function LabelBMFont:isFlipY() end 
function LabelBMFont:setColor() end 
function LabelBMFont:removeAllChildren() end 
function LabelBMFont:updateSizeAndPosition() end 
function LabelBMFont:getLayoutParameter() end 
function LabelBMFont:getName() end 
function LabelBMFont:removeChild() end 
function LabelBMFont:onEnter() end 
function LabelBMFont:getVirtualRenderer() end 
function LabelBMFont:getDescription() end 
function LabelBMFont:getChildByName() end 
function LabelBMFont:isIgnoreContentAdaptWithSize() end 
function LabelBMFont:ignoreContentAdaptWithSize() end 
function LabelBMFont:onExit() end 
function LabelBMFont:visit() end 
function LabelBMFont:getChildren() end 
function LabelBMFont:onTouchMoved() end 
function LabelBMFont:getLayoutSize() end 
function LabelBMFont:getColor() end 
function LabelBMFont:getPositionType() end 
function LabelBMFont:getTouchMovePos() end 
function LabelBMFont:getSize() end 
function LabelBMFont:getSizeType() end 
function LabelBMFont:setSize() end 
function LabelBMFont:getWidgetType() end 
function LabelBMFont:getOpacity() end 
function LabelBMFont:clippingParentAreaContainPoint() end 
function LabelBMFont:setTouchEnabled() end 
function LabelBMFont:setEnabled() end 
function LabelBMFont:setActionTag() end 
function LabelBMFont:getWorldPosition() end 
function LabelBMFont:didNotSelectSelf() end 
function LabelBMFont:sortAllChildren() end 
function LabelBMFont:getNodeByTag() end 
function LabelBMFont:onTouchCancelled() end 
function LabelBMFont:getNodes() end 
function LabelBMFont:removeAllNodes() end 
function LabelBMFont:setBrightStyle() end 
function LabelBMFont:removeChildByTag() end 
function LabelBMFont:getActionTag() end 
function LabelBMFont:setOpacity() end 
function LabelBMFont:new() end 
function LabelBMFont:delete() end 
function LabelBMFont:setText() end 
function LabelBMFont:getContentSize() end 
function LabelBMFont:getStringValue() end 
---
-- @return @class LabelBMFont
--
function LabelBMFont:create() end 
function LabelBMFont:new_local() end 
function LabelBMFont:getVirtualRenderer() end 
function LabelBMFont:setAnchorPoint() end 
function LabelBMFont:setFntFile() end 
function LabelBMFont:getDescription() end 
