---@classdef LabelAtlas
LabelAtlas = {}
function LabelAtlas:autorelease() end 
function LabelAtlas:retain() end 
function LabelAtlas:retainCount() end 
function LabelAtlas:isEqual() end 
function LabelAtlas:copy() end 
function LabelAtlas:release() end 
function LabelAtlas:isSingleReference() end 
function LabelAtlas:visit() end 
function LabelAtlas:getUserObject() end 
function LabelAtlas:getSkewY() end 
function LabelAtlas:convertTouchToNodeSpace() end 
function LabelAtlas:getVertexZ() end 
function LabelAtlas:setParent() end 
function LabelAtlas:boundingBox() end 
function LabelAtlas:setVisible() end 
function LabelAtlas:stopActionByTag() end 
function LabelAtlas:getScaleY() end 
function LabelAtlas:setScaleX() end 
function LabelAtlas:reorderChild() end 
function LabelAtlas:setPositionX() end 
function LabelAtlas:removeFromParentAndCleanup() end 
function LabelAtlas:setTag() end 
function LabelAtlas:getChildrenCount() end 
function LabelAtlas:setScale() end 
function LabelAtlas:addChild() end 
function LabelAtlas:isVisible() end 
function LabelAtlas:setActionManager() end 
function LabelAtlas:setScheduler() end 
function LabelAtlas:getContentSize() end 
function LabelAtlas:getAnchorPoint() end 
function LabelAtlas:getTag() end 
function LabelAtlas:setGrid() end 
function LabelAtlas:convertToWorldSpace() end 
function LabelAtlas:setSkewX() end 
function LabelAtlas:setZOrder() end 
function LabelAtlas:worldToNodeTransform() end 
function LabelAtlas:getPosition() end 
function LabelAtlas:getSkewX() end 
function LabelAtlas:getScheduler() end 
function LabelAtlas:ignoreAnchorPointForPosition() end 
function LabelAtlas:setPosition() end 
function LabelAtlas:getParent() end 
function LabelAtlas:unscheduleUpdate() end 
function LabelAtlas:scheduleUpdateWithPriorityLua() end 
function LabelAtlas:removeChildByTag() end 
function LabelAtlas:convertToNodeSpaceAR() end 
function LabelAtlas:convertTouchToNodeSpaceAR() end 
function LabelAtlas:convertToWorldSpaceAR() end 
function LabelAtlas:setRotation() end 
function LabelAtlas:getComponent() end 
function LabelAtlas:convertToNodeSpace() end 
---
-- @return @class LabelAtlas
--
function LabelAtlas:create() end 
function LabelAtlas:getScale() end 
function LabelAtlas:getPositionY() end 
function LabelAtlas:getChildByTag() end 
function LabelAtlas:setContentSize() end 
function LabelAtlas:description() end 
function LabelAtlas:cleanup() end 
function LabelAtlas:getRotation() end 
function LabelAtlas:nodeToParentTransform() end 
function LabelAtlas:stopAction() end 
function LabelAtlas:numberOfRunningActions() end 
function LabelAtlas:removeAllChildren() end 
function LabelAtlas:runAction() end 
function LabelAtlas:setUserObject() end 
function LabelAtlas:parentToNodeTransform() end 
function LabelAtlas:removeChild() end 
function LabelAtlas:getAnchorPointInPoints() end 
function LabelAtlas:getScaleX() end 
function LabelAtlas:transform() end 
function LabelAtlas:getActionManager() end 
function LabelAtlas:draw() end 
function LabelAtlas:setScaleY() end 
function LabelAtlas:unregisterScriptHandler() end 
function LabelAtlas:setVertexZ() end 
function LabelAtlas:setAnchorPoint() end 
function LabelAtlas:getShaderProgram() end 
function LabelAtlas:stopAllActions() end 
function LabelAtlas:setUserData() end 
function LabelAtlas:setShaderProgram() end 
function LabelAtlas:getActionByTag() end 
function LabelAtlas:getGLServerState() end 
function LabelAtlas:getOrderOfArrival() end 
function LabelAtlas:getPositionX() end 
function LabelAtlas:setGLServerState() end 
function LabelAtlas:setSkewY() end 
function LabelAtlas:setOrderOfArrival() end 
function LabelAtlas:nodeToWorldTransform() end 
function LabelAtlas:getChildren() end 
function LabelAtlas:transformAncestors() end 
function LabelAtlas:getGrid() end 
function LabelAtlas:isRunning() end 
function LabelAtlas:registerScriptHandler() end 
function LabelAtlas:getCamera() end 
function LabelAtlas:isIgnoreAnchorPointForPosition() end 
function LabelAtlas:getUserData() end 
function LabelAtlas:setPositionY() end 
function LabelAtlas:getZOrder() end 
function LabelAtlas:removeNode() end 
function LabelAtlas:onTouchBegan() end 
function LabelAtlas:addNode() end 
function LabelAtlas:setLayoutParameter() end 
function LabelAtlas:isFlipX() end 
function LabelAtlas:getSizePercent() end 
function LabelAtlas:getLeftInParent() end 
function LabelAtlas:getPositionPercent() end 
function LabelAtlas:onTouchEnded() end 
function LabelAtlas:new_local() end 
function LabelAtlas:getRightInParent() end 
function LabelAtlas:checkChildInfo() end 
function LabelAtlas:isEnabled() end 
function LabelAtlas:setSizePercent() end 
function LabelAtlas:removeFromParentAndCleanup() end 
function LabelAtlas:setFlipX() end 
function LabelAtlas:getChildrenCount() end 
function LabelAtlas:isBright() end 
function LabelAtlas:setPositionPercent() end 
function LabelAtlas:addChild() end 
function LabelAtlas:getBottomInParent() end 
function LabelAtlas:setBright() end 
function LabelAtlas:getTouchStartPos() end 
function LabelAtlas:removeAllChildren() end 
function LabelAtlas:setPositionType() end 
function LabelAtlas:removeNodeByTag() end 
function LabelAtlas:getContentSize() end 
function LabelAtlas:clone() end 
function LabelAtlas:setFlipY() end 
function LabelAtlas:getTouchEndPos() end 
function LabelAtlas:setName() end 
function LabelAtlas:setPosition() end 
function LabelAtlas:setFocused() end 
function LabelAtlas:setSizeType() end 
function LabelAtlas:hitTest() end 
function LabelAtlas:addTouchEventListener() end 
function LabelAtlas:getCustomSize() end 
function LabelAtlas:isTouchEnabled() end 
function LabelAtlas:new() end 
function LabelAtlas:removeFromParent() end 
---
-- @return @class LabelAtlas
--
function LabelAtlas:create() end 
function LabelAtlas:delete() end 
function LabelAtlas:getChildByTag() end 
function LabelAtlas:isFocused() end 
function LabelAtlas:getTopInParent() end 
function LabelAtlas:isFlipY() end 
function LabelAtlas:setColor() end 
function LabelAtlas:removeAllChildren() end 
function LabelAtlas:updateSizeAndPosition() end 
function LabelAtlas:getLayoutParameter() end 
function LabelAtlas:getName() end 
function LabelAtlas:removeChild() end 
function LabelAtlas:onEnter() end 
function LabelAtlas:getVirtualRenderer() end 
function LabelAtlas:getDescription() end 
function LabelAtlas:getChildByName() end 
function LabelAtlas:isIgnoreContentAdaptWithSize() end 
function LabelAtlas:ignoreContentAdaptWithSize() end 
function LabelAtlas:onExit() end 
function LabelAtlas:visit() end 
function LabelAtlas:getChildren() end 
function LabelAtlas:onTouchMoved() end 
function LabelAtlas:getLayoutSize() end 
function LabelAtlas:getColor() end 
function LabelAtlas:getPositionType() end 
function LabelAtlas:getTouchMovePos() end 
function LabelAtlas:getSize() end 
function LabelAtlas:getSizeType() end 
function LabelAtlas:setSize() end 
function LabelAtlas:getWidgetType() end 
function LabelAtlas:getOpacity() end 
function LabelAtlas:clippingParentAreaContainPoint() end 
function LabelAtlas:setTouchEnabled() end 
function LabelAtlas:setEnabled() end 
function LabelAtlas:setActionTag() end 
function LabelAtlas:getWorldPosition() end 
function LabelAtlas:didNotSelectSelf() end 
function LabelAtlas:sortAllChildren() end 
function LabelAtlas:getNodeByTag() end 
function LabelAtlas:onTouchCancelled() end 
function LabelAtlas:getNodes() end 
function LabelAtlas:removeAllNodes() end 
function LabelAtlas:setBrightStyle() end 
function LabelAtlas:removeChildByTag() end 
function LabelAtlas:getActionTag() end 
function LabelAtlas:setOpacity() end 
function LabelAtlas:new() end 
function LabelAtlas:delete() end 
function LabelAtlas:getContentSize() end 
function LabelAtlas:getStringValue() end 
---
-- @return @class LabelAtlas
--
function LabelAtlas:create() end 
function LabelAtlas:getVirtualRenderer() end 
function LabelAtlas:new_local() end 
function LabelAtlas:setStringValue() end 
function LabelAtlas:setAnchorPoint() end 
function LabelAtlas:setProperty() end 
function LabelAtlas:getDescription() end 
