---@classdef Label
Label = {}
function Label:autorelease() end 
function Label:retain() end 
function Label:retainCount() end 
function Label:isEqual() end 
function Label:copy() end 
function Label:release() end 
function Label:isSingleReference() end 
function Label:visit() end 
function Label:getUserObject() end 
function Label:getSkewY() end 
function Label:convertTouchToNodeSpace() end 
function Label:getVertexZ() end 
function Label:setParent() end 
function Label:boundingBox() end 
function Label:setVisible() end 
function Label:stopActionByTag() end 
function Label:getScaleY() end 
function Label:setScaleX() end 
function Label:reorderChild() end 
function Label:setPositionX() end 
function Label:removeFromParentAndCleanup() end 
function Label:setTag() end 
function Label:getChildrenCount() end 
function Label:setScale() end 
function Label:addChild() end 
function Label:isVisible() end 
function Label:setActionManager() end 
function Label:setScheduler() end 
function Label:getContentSize() end 
function Label:getAnchorPoint() end 
function Label:getTag() end 
function Label:setGrid() end 
function Label:convertToWorldSpace() end 
function Label:setSkewX() end 
function Label:setZOrder() end 
function Label:worldToNodeTransform() end 
function Label:getPosition() end 
function Label:getSkewX() end 
function Label:getScheduler() end 
function Label:ignoreAnchorPointForPosition() end 
function Label:setPosition() end 
function Label:getParent() end 
function Label:unscheduleUpdate() end 
function Label:scheduleUpdateWithPriorityLua() end 
function Label:removeChildByTag() end 
function Label:convertToNodeSpaceAR() end 
function Label:convertTouchToNodeSpaceAR() end 
function Label:convertToWorldSpaceAR() end 
function Label:setRotation() end 
function Label:getComponent() end 
function Label:convertToNodeSpace() end 
---
-- @return @class Label
--
function Label:create() end 
function Label:getScale() end 
function Label:getPositionY() end 
function Label:getChildByTag() end 
function Label:setContentSize() end 
function Label:description() end 
function Label:cleanup() end 
function Label:getRotation() end 
function Label:nodeToParentTransform() end 
function Label:stopAction() end 
function Label:numberOfRunningActions() end 
function Label:removeAllChildren() end 
function Label:runAction() end 
function Label:setUserObject() end 
function Label:parentToNodeTransform() end 
function Label:removeChild() end 
function Label:getAnchorPointInPoints() end 
function Label:getScaleX() end 
function Label:transform() end 
function Label:getActionManager() end 
function Label:draw() end 
function Label:setScaleY() end 
function Label:unregisterScriptHandler() end 
function Label:setVertexZ() end 
function Label:setAnchorPoint() end 
function Label:getShaderProgram() end 
function Label:stopAllActions() end 
function Label:setUserData() end 
function Label:setShaderProgram() end 
function Label:getActionByTag() end 
function Label:getGLServerState() end 
function Label:getOrderOfArrival() end 
function Label:getPositionX() end 
function Label:setGLServerState() end 
function Label:setSkewY() end 
function Label:setOrderOfArrival() end 
function Label:nodeToWorldTransform() end 
function Label:getChildren() end 
function Label:transformAncestors() end 
function Label:getGrid() end 
function Label:isRunning() end 
function Label:registerScriptHandler() end 
function Label:getCamera() end 
function Label:isIgnoreAnchorPointForPosition() end 
function Label:getUserData() end 
function Label:setPositionY() end 
function Label:getZOrder() end 
function Label:removeNode() end 
function Label:onTouchBegan() end 
function Label:addNode() end 
function Label:setLayoutParameter() end 
function Label:isFlipX() end 
function Label:getSizePercent() end 
function Label:getLeftInParent() end 
function Label:getPositionPercent() end 
function Label:onTouchEnded() end 
function Label:new_local() end 
function Label:getRightInParent() end 
function Label:checkChildInfo() end 
function Label:isEnabled() end 
function Label:setSizePercent() end 
function Label:removeFromParentAndCleanup() end 
function Label:setFlipX() end 
function Label:getChildrenCount() end 
function Label:isBright() end 
function Label:setPositionPercent() end 
function Label:addChild() end 
function Label:getBottomInParent() end 
function Label:setBright() end 
function Label:getTouchStartPos() end 
function Label:removeAllChildren() end 
function Label:setPositionType() end 
function Label:removeNodeByTag() end 
function Label:getContentSize() end 
function Label:clone() end 
function Label:setFlipY() end 
function Label:getTouchEndPos() end 
function Label:setName() end 
function Label:setPosition() end 
function Label:setFocused() end 
function Label:setSizeType() end 
function Label:hitTest() end 
function Label:addTouchEventListener() end 
function Label:getCustomSize() end 
function Label:isTouchEnabled() end 
function Label:new() end 
function Label:removeFromParent() end 
---
-- @return @class Label
--
function Label:create() end 
function Label:delete() end 
function Label:getChildByTag() end 
function Label:isFocused() end 
function Label:getTopInParent() end 
function Label:isFlipY() end 
function Label:setColor() end 
function Label:removeAllChildren() end 
function Label:updateSizeAndPosition() end 
function Label:getLayoutParameter() end 
function Label:getName() end 
function Label:removeChild() end 
function Label:onEnter() end 
function Label:getVirtualRenderer() end 
function Label:getDescription() end 
function Label:getChildByName() end 
function Label:isIgnoreContentAdaptWithSize() end 
function Label:ignoreContentAdaptWithSize() end 
function Label:onExit() end 
function Label:visit() end 
function Label:getChildren() end 
function Label:onTouchMoved() end 
function Label:getLayoutSize() end 
function Label:getColor() end 
function Label:getPositionType() end 
function Label:getTouchMovePos() end 
function Label:getSize() end 
function Label:getSizeType() end 
function Label:setSize() end 
function Label:getWidgetType() end 
function Label:getOpacity() end 
function Label:clippingParentAreaContainPoint() end 
function Label:setTouchEnabled() end 
function Label:setEnabled() end 
function Label:setActionTag() end 
function Label:getWorldPosition() end 
function Label:didNotSelectSelf() end 
function Label:sortAllChildren() end 
function Label:getNodeByTag() end 
function Label:onTouchCancelled() end 
function Label:getNodes() end 
function Label:removeAllNodes() end 
function Label:setBrightStyle() end 
function Label:removeChildByTag() end 
function Label:getActionTag() end 
function Label:setOpacity() end 
function Label:new() end 
function Label:delete() end 
function Label:getFontName() end 
function Label:getStringValue() end 
function Label:new_local() end 
function Label:getTextHorizontalAlignment() end 
function Label:getVirtualRenderer() end 
function Label:getDescription() end 
function Label:setAnchorPoint() end 
function Label:setFontName() end 
function Label:getTextAreaSize() end 
function Label:setText() end 
function Label:getStringLength() end 
function Label:getContentSize() end 
function Label:isTouchScaleChangeEnabled() end 
function Label:getTextVerticalAlignment() end 
function Label:setFontSize() end 
function Label:setTextHorizontalAlignment() end 
function Label:setTextAreaSize() end 
function Label:setTouchScaleChangeEnabled() end 
function Label:setTextVerticalAlignment() end 
function Label:getFontSize() end 
---
-- @return @class Label
--
function Label:create() end 
