---@classdef Layout
Layout = {}
function Layout:autorelease() end 
function Layout:retain() end 
function Layout:retainCount() end 
function Layout:isEqual() end 
function Layout:copy() end 
function Layout:release() end 
function Layout:isSingleReference() end 
function Layout:visit() end 
function Layout:getUserObject() end 
function Layout:getSkewY() end 
function Layout:convertTouchToNodeSpace() end 
function Layout:getVertexZ() end 
function Layout:setParent() end 
function Layout:boundingBox() end 
function Layout:setVisible() end 
function Layout:stopActionByTag() end 
function Layout:getScaleY() end 
function Layout:setScaleX() end 
function Layout:reorderChild() end 
function Layout:setPositionX() end 
function Layout:removeFromParentAndCleanup() end 
function Layout:setTag() end 
function Layout:getChildrenCount() end 
function Layout:setScale() end 
function Layout:addChild() end 
function Layout:isVisible() end 
function Layout:setActionManager() end 
function Layout:setScheduler() end 
function Layout:getContentSize() end 
function Layout:getAnchorPoint() end 
function Layout:getTag() end 
function Layout:setGrid() end 
function Layout:convertToWorldSpace() end 
function Layout:setSkewX() end 
function Layout:setZOrder() end 
function Layout:worldToNodeTransform() end 
function Layout:getPosition() end 
function Layout:getSkewX() end 
function Layout:getScheduler() end 
function Layout:ignoreAnchorPointForPosition() end 
function Layout:setPosition() end 
function Layout:getParent() end 
function Layout:unscheduleUpdate() end 
function Layout:scheduleUpdateWithPriorityLua() end 
function Layout:removeChildByTag() end 
function Layout:convertToNodeSpaceAR() end 
function Layout:convertTouchToNodeSpaceAR() end 
function Layout:convertToWorldSpaceAR() end 
function Layout:setRotation() end 
function Layout:getComponent() end 
function Layout:convertToNodeSpace() end 
---
-- @return @class Layout
--
function Layout:create() end 
function Layout:getScale() end 
function Layout:getPositionY() end 
function Layout:getChildByTag() end 
function Layout:setContentSize() end 
function Layout:description() end 
function Layout:cleanup() end 
function Layout:getRotation() end 
function Layout:nodeToParentTransform() end 
function Layout:stopAction() end 
function Layout:numberOfRunningActions() end 
function Layout:removeAllChildren() end 
function Layout:runAction() end 
function Layout:setUserObject() end 
function Layout:parentToNodeTransform() end 
function Layout:removeChild() end 
function Layout:getAnchorPointInPoints() end 
function Layout:getScaleX() end 
function Layout:transform() end 
function Layout:getActionManager() end 
function Layout:draw() end 
function Layout:setScaleY() end 
function Layout:unregisterScriptHandler() end 
function Layout:setVertexZ() end 
function Layout:setAnchorPoint() end 
function Layout:getShaderProgram() end 
function Layout:stopAllActions() end 
function Layout:setUserData() end 
function Layout:setShaderProgram() end 
function Layout:getActionByTag() end 
function Layout:getGLServerState() end 
function Layout:getOrderOfArrival() end 
function Layout:getPositionX() end 
function Layout:setGLServerState() end 
function Layout:setSkewY() end 
function Layout:setOrderOfArrival() end 
function Layout:nodeToWorldTransform() end 
function Layout:getChildren() end 
function Layout:transformAncestors() end 
function Layout:getGrid() end 
function Layout:isRunning() end 
function Layout:registerScriptHandler() end 
function Layout:getCamera() end 
function Layout:isIgnoreAnchorPointForPosition() end 
function Layout:getUserData() end 
function Layout:setPositionY() end 
function Layout:getZOrder() end 
function Layout:removeNode() end 
function Layout:onTouchBegan() end 
function Layout:addNode() end 
function Layout:setLayoutParameter() end 
function Layout:isFlipX() end 
function Layout:getSizePercent() end 
function Layout:getLeftInParent() end 
function Layout:getPositionPercent() end 
function Layout:onTouchEnded() end 
function Layout:new_local() end 
function Layout:getRightInParent() end 
function Layout:checkChildInfo() end 
function Layout:isEnabled() end 
function Layout:setSizePercent() end 
function Layout:removeFromParentAndCleanup() end 
function Layout:setFlipX() end 
function Layout:getChildrenCount() end 
function Layout:isBright() end 
function Layout:setPositionPercent() end 
function Layout:addChild() end 
function Layout:getBottomInParent() end 
function Layout:setBright() end 
function Layout:getTouchStartPos() end 
function Layout:removeAllChildren() end 
function Layout:setPositionType() end 
function Layout:removeNodeByTag() end 
function Layout:getContentSize() end 
function Layout:clone() end 
function Layout:setFlipY() end 
function Layout:getTouchEndPos() end 
function Layout:setName() end 
function Layout:setPosition() end 
function Layout:setFocused() end 
function Layout:setSizeType() end 
function Layout:hitTest() end 
function Layout:addTouchEventListener() end 
function Layout:getCustomSize() end 
function Layout:isTouchEnabled() end 
function Layout:new() end 
function Layout:removeFromParent() end 
---
-- @return @class Layout
--
function Layout:create() end 
function Layout:delete() end 
function Layout:getChildByTag() end 
function Layout:isFocused() end 
function Layout:getTopInParent() end 
function Layout:isFlipY() end 
function Layout:setColor() end 
function Layout:removeAllChildren() end 
function Layout:updateSizeAndPosition() end 
function Layout:getLayoutParameter() end 
function Layout:getName() end 
function Layout:removeChild() end 
function Layout:onEnter() end 
function Layout:getVirtualRenderer() end 
function Layout:getDescription() end 
function Layout:getChildByName() end 
function Layout:isIgnoreContentAdaptWithSize() end 
function Layout:ignoreContentAdaptWithSize() end 
function Layout:onExit() end 
function Layout:visit() end 
function Layout:getChildren() end 
function Layout:onTouchMoved() end 
function Layout:getLayoutSize() end 
function Layout:getColor() end 
function Layout:getPositionType() end 
function Layout:getTouchMovePos() end 
function Layout:getSize() end 
function Layout:getSizeType() end 
function Layout:setSize() end 
function Layout:getWidgetType() end 
function Layout:getOpacity() end 
function Layout:clippingParentAreaContainPoint() end 
function Layout:setTouchEnabled() end 
function Layout:setEnabled() end 
function Layout:setActionTag() end 
function Layout:getWorldPosition() end 
function Layout:didNotSelectSelf() end 
function Layout:sortAllChildren() end 
function Layout:getNodeByTag() end 
function Layout:onTouchCancelled() end 
function Layout:getNodes() end 
function Layout:removeAllNodes() end 
function Layout:setBrightStyle() end 
function Layout:removeChildByTag() end 
function Layout:getActionTag() end 
function Layout:setOpacity() end 
function Layout:visit() end 
function Layout:onEnter() end 
function Layout:getBackGroundColorOpacity() end 
function Layout:new() end 
function Layout:setBackGroundImageOpacity() end 
function Layout:delete() end 
function Layout:requestDoLayout() end 
function Layout:setBackGroundImage() end 
function Layout:setBackGroundColor() end 
function Layout:removeAllChildren() end 
function Layout:new_local() end 
function Layout:removeChild() end 
function Layout:onExit() end 
function Layout:isBackGroundImageScale9Enabled() end 
function Layout:getDescription() end 
function Layout:sortAllChildren() end 
function Layout:removeAllChildren() end 
function Layout:setBackGroundColorVector() end 
function Layout:setLayoutType() end 
function Layout:getLayoutType() end 
function Layout:getBackGroundColorVector() end 
function Layout:addChild() end 
function Layout:isClippingEnabled() end 
function Layout:getClippingType() end 
function Layout:setBackGroundImageScale9Enabled() end 
function Layout:setBackGroundImageColor() end 
function Layout:removeBackGroundImage() end 
function Layout:setClippingType() end 
function Layout:setClippingEnabled() end 
function Layout:getBackGroundColorType() end 
function Layout:getBackGroundImageTextureSize() end 
function Layout:getBackGroundImageCapInsets() end 
function Layout:getBackGroundImageColor() end 
function Layout:getBackGroundStartColor() end 
function Layout:getBackGroundColor() end 
function Layout:getBackGroundImageOpacity() end 
function Layout:setBackGroundColorType() end 
function Layout:setBackGroundImageCapInsets() end 
function Layout:getBackGroundEndColor() end 
---
-- @return @class Layout
--
function Layout:create() end 
function Layout:setBackGroundColorOpacity() end 
function Layout:hitTest() end 
