---@classdef ListView
ListView = {}
function ListView:autorelease() end 
function ListView:retain() end 
function ListView:retainCount() end 
function ListView:isEqual() end 
function ListView:copy() end 
function ListView:release() end 
function ListView:isSingleReference() end 
function ListView:visit() end 
function ListView:getUserObject() end 
function ListView:getSkewY() end 
function ListView:convertTouchToNodeSpace() end 
function ListView:getVertexZ() end 
function ListView:setParent() end 
function ListView:boundingBox() end 
function ListView:setVisible() end 
function ListView:stopActionByTag() end 
function ListView:getScaleY() end 
function ListView:setScaleX() end 
function ListView:reorderChild() end 
function ListView:setPositionX() end 
function ListView:removeFromParentAndCleanup() end 
function ListView:setTag() end 
function ListView:getChildrenCount() end 
function ListView:setScale() end 
function ListView:addChild() end 
function ListView:isVisible() end 
function ListView:setActionManager() end 
function ListView:setScheduler() end 
function ListView:getContentSize() end 
function ListView:getAnchorPoint() end 
function ListView:getTag() end 
function ListView:setGrid() end 
function ListView:convertToWorldSpace() end 
function ListView:setSkewX() end 
function ListView:setZOrder() end 
function ListView:worldToNodeTransform() end 
function ListView:getPosition() end 
function ListView:getSkewX() end 
function ListView:getScheduler() end 
function ListView:ignoreAnchorPointForPosition() end 
function ListView:setPosition() end 
function ListView:getParent() end 
function ListView:unscheduleUpdate() end 
function ListView:scheduleUpdateWithPriorityLua() end 
function ListView:removeChildByTag() end 
function ListView:convertToNodeSpaceAR() end 
function ListView:convertTouchToNodeSpaceAR() end 
function ListView:convertToWorldSpaceAR() end 
function ListView:setRotation() end 
function ListView:getComponent() end 
function ListView:convertToNodeSpace() end 
---
-- @return @class ListView
--
function ListView:create() end 
function ListView:getScale() end 
function ListView:getPositionY() end 
function ListView:getChildByTag() end 
function ListView:setContentSize() end 
function ListView:description() end 
function ListView:cleanup() end 
function ListView:getRotation() end 
function ListView:nodeToParentTransform() end 
function ListView:stopAction() end 
function ListView:numberOfRunningActions() end 
function ListView:removeAllChildren() end 
function ListView:runAction() end 
function ListView:setUserObject() end 
function ListView:parentToNodeTransform() end 
function ListView:removeChild() end 
function ListView:getAnchorPointInPoints() end 
function ListView:getScaleX() end 
function ListView:transform() end 
function ListView:getActionManager() end 
function ListView:draw() end 
function ListView:setScaleY() end 
function ListView:unregisterScriptHandler() end 
function ListView:setVertexZ() end 
function ListView:setAnchorPoint() end 
function ListView:getShaderProgram() end 
function ListView:stopAllActions() end 
function ListView:setUserData() end 
function ListView:setShaderProgram() end 
function ListView:getActionByTag() end 
function ListView:getGLServerState() end 
function ListView:getOrderOfArrival() end 
function ListView:getPositionX() end 
function ListView:setGLServerState() end 
function ListView:setSkewY() end 
function ListView:setOrderOfArrival() end 
function ListView:nodeToWorldTransform() end 
function ListView:getChildren() end 
function ListView:transformAncestors() end 
function ListView:getGrid() end 
function ListView:isRunning() end 
function ListView:registerScriptHandler() end 
function ListView:getCamera() end 
function ListView:isIgnoreAnchorPointForPosition() end 
function ListView:getUserData() end 
function ListView:setPositionY() end 
function ListView:getZOrder() end 
function ListView:removeNode() end 
function ListView:onTouchBegan() end 
function ListView:addNode() end 
function ListView:setLayoutParameter() end 
function ListView:isFlipX() end 
function ListView:getSizePercent() end 
function ListView:getLeftInParent() end 
function ListView:getPositionPercent() end 
function ListView:onTouchEnded() end 
function ListView:new_local() end 
function ListView:getRightInParent() end 
function ListView:checkChildInfo() end 
function ListView:isEnabled() end 
function ListView:setSizePercent() end 
function ListView:removeFromParentAndCleanup() end 
function ListView:setFlipX() end 
function ListView:getChildrenCount() end 
function ListView:isBright() end 
function ListView:setPositionPercent() end 
function ListView:addChild() end 
function ListView:getBottomInParent() end 
function ListView:setBright() end 
function ListView:getTouchStartPos() end 
function ListView:removeAllChildren() end 
function ListView:setPositionType() end 
function ListView:removeNodeByTag() end 
function ListView:getContentSize() end 
function ListView:clone() end 
function ListView:setFlipY() end 
function ListView:getTouchEndPos() end 
function ListView:setName() end 
function ListView:setPosition() end 
function ListView:setFocused() end 
function ListView:setSizeType() end 
function ListView:hitTest() end 
function ListView:addTouchEventListener() end 
function ListView:getCustomSize() end 
function ListView:isTouchEnabled() end 
function ListView:new() end 
function ListView:removeFromParent() end 
---
-- @return @class ListView
--
function ListView:create() end 
function ListView:delete() end 
function ListView:getChildByTag() end 
function ListView:isFocused() end 
function ListView:getTopInParent() end 
function ListView:isFlipY() end 
function ListView:setColor() end 
function ListView:removeAllChildren() end 
function ListView:updateSizeAndPosition() end 
function ListView:getLayoutParameter() end 
function ListView:getName() end 
function ListView:removeChild() end 
function ListView:onEnter() end 
function ListView:getVirtualRenderer() end 
function ListView:getDescription() end 
function ListView:getChildByName() end 
function ListView:isIgnoreContentAdaptWithSize() end 
function ListView:ignoreContentAdaptWithSize() end 
function ListView:onExit() end 
function ListView:visit() end 
function ListView:getChildren() end 
function ListView:onTouchMoved() end 
function ListView:getLayoutSize() end 
function ListView:getColor() end 
function ListView:getPositionType() end 
function ListView:getTouchMovePos() end 
function ListView:getSize() end 
function ListView:getSizeType() end 
function ListView:setSize() end 
function ListView:getWidgetType() end 
function ListView:getOpacity() end 
function ListView:clippingParentAreaContainPoint() end 
function ListView:setTouchEnabled() end 
function ListView:setEnabled() end 
function ListView:setActionTag() end 
function ListView:getWorldPosition() end 
function ListView:didNotSelectSelf() end 
function ListView:sortAllChildren() end 
function ListView:getNodeByTag() end 
function ListView:onTouchCancelled() end 
function ListView:getNodes() end 
function ListView:removeAllNodes() end 
function ListView:setBrightStyle() end 
function ListView:removeChildByTag() end 
function ListView:getActionTag() end 
function ListView:setOpacity() end 
function ListView:visit() end 
function ListView:onEnter() end 
function ListView:getBackGroundColorOpacity() end 
function ListView:new() end 
function ListView:setBackGroundImageOpacity() end 
function ListView:delete() end 
function ListView:requestDoLayout() end 
function ListView:setBackGroundImage() end 
function ListView:setBackGroundColor() end 
function ListView:removeAllChildren() end 
function ListView:new_local() end 
function ListView:removeChild() end 
function ListView:onExit() end 
function ListView:isBackGroundImageScale9Enabled() end 
function ListView:getDescription() end 
function ListView:sortAllChildren() end 
function ListView:removeAllChildren() end 
function ListView:setBackGroundColorVector() end 
function ListView:setLayoutType() end 
function ListView:getLayoutType() end 
function ListView:getBackGroundColorVector() end 
function ListView:addChild() end 
function ListView:isClippingEnabled() end 
function ListView:getClippingType() end 
function ListView:setBackGroundImageScale9Enabled() end 
function ListView:setBackGroundImageColor() end 
function ListView:removeBackGroundImage() end 
function ListView:setClippingType() end 
function ListView:setClippingEnabled() end 
function ListView:getBackGroundColorType() end 
function ListView:getBackGroundImageTextureSize() end 
function ListView:getBackGroundImageCapInsets() end 
function ListView:getBackGroundImageColor() end 
function ListView:getBackGroundStartColor() end 
function ListView:getBackGroundColor() end 
function ListView:getBackGroundImageOpacity() end 
function ListView:setBackGroundColorType() end 
function ListView:setBackGroundImageCapInsets() end 
function ListView:getBackGroundEndColor() end 
---
-- @return @class ListView
--
function ListView:create() end 
function ListView:setBackGroundColorOpacity() end 
function ListView:hitTest() end 
function ListView:removeNode() end 
function ListView:scrollToRight() end 
function ListView:jumpToLeft() end 
function ListView:scrollToTopLeft() end 
function ListView:setInnerContainerSize() end 
function ListView:setDirection() end 
function ListView:isInertiaScrollEnabled() end 
function ListView:new_local() end 
function ListView:scrollToBottomRight() end 
function ListView:scrollToBottom() end 
function ListView:getDescription() end 
function ListView:getChildrenCount() end 
function ListView:addChild() end 
function ListView:setInertiaScrollEnabled() end 
function ListView:jumpToRight() end 
function ListView:removeAllChildren() end 
function ListView:getNodes() end 
function ListView:removeNodeByTag() end 
function ListView:jumpToTopRight() end 
function ListView:jumpToPercentHorizontal() end 
function ListView:scrollToPercentHorizontal() end 
function ListView:setBounceEnabled() end 
function ListView:getInnerContainerSize() end 
function ListView:new() end 
function ListView:jumpToTopLeft() end 
---
-- @return @class ListView
--
function ListView:create() end 
function ListView:delete() end 
function ListView:getChildByTag() end 
function ListView:scrollToPercentBothDirection() end 
function ListView:scrollToTop() end 
function ListView:isBounceEnabled() end 
function ListView:jumpToBottomLeft() end 
function ListView:removeAllChildren() end 
function ListView:removeChild() end 
function ListView:getChildren() end 
function ListView:jumpToPercentVertical() end 
function ListView:scrollToBottomLeft() end 
function ListView:getLayoutType() end 
function ListView:setLayoutType() end 
function ListView:update() end 
function ListView:jumpToTop() end 
function ListView:getNodeByTag() end 
function ListView:jumpToPercentBothDirection() end 
function ListView:getInnerContainer() end 
function ListView:scrollToPercentVertical() end 
function ListView:jumpToBottom() end 
function ListView:getDirection() end 
function ListView:getChildByName() end 
function ListView:addNode() end 
function ListView:removeAllNodes() end 
function ListView:jumpToBottomRight() end 
function ListView:scrollToTopRight() end 
function ListView:scrollToLeft() end 
function ListView:new() end 
function ListView:setItemsMargin() end 
function ListView:delete() end 
function ListView:getItem() end 
function ListView:setGravity() end 
function ListView:addEventListenerScrollView() end 
function ListView:removeLastItem() end 
function ListView:new_local() end 
function ListView:getDescription() end 
function ListView:insertCustomItem() end 
function ListView:requestRefreshView() end 
function ListView:removeItem() end 
function ListView:getIndex() end 
function ListView:removeAllItems() end 
function ListView:pushBackCustomItem() end 
function ListView:sortAllChildren() end 
function ListView:addEventListenerListView() end 
function ListView:refreshView() end 
function ListView:setDirection() end 
function ListView:getCurSelectedIndex() end 
---
-- @return @class ListView
--
function ListView:create() end 
function ListView:setItemModel() end 
function ListView:pushBackDefaultItem() end 
function ListView:insertDefaultItem() end 
function ListView:getItems() end 
