---@classdef LoadingBar
LoadingBar = {}
function LoadingBar:autorelease() end 
function LoadingBar:retain() end 
function LoadingBar:retainCount() end 
function LoadingBar:isEqual() end 
function LoadingBar:copy() end 
function LoadingBar:release() end 
function LoadingBar:isSingleReference() end 
function LoadingBar:visit() end 
function LoadingBar:getUserObject() end 
function LoadingBar:getSkewY() end 
function LoadingBar:convertTouchToNodeSpace() end 
function LoadingBar:getVertexZ() end 
function LoadingBar:setParent() end 
function LoadingBar:boundingBox() end 
function LoadingBar:setVisible() end 
function LoadingBar:stopActionByTag() end 
function LoadingBar:getScaleY() end 
function LoadingBar:setScaleX() end 
function LoadingBar:reorderChild() end 
function LoadingBar:setPositionX() end 
function LoadingBar:removeFromParentAndCleanup() end 
function LoadingBar:setTag() end 
function LoadingBar:getChildrenCount() end 
function LoadingBar:setScale() end 
function LoadingBar:addChild() end 
function LoadingBar:isVisible() end 
function LoadingBar:setActionManager() end 
function LoadingBar:setScheduler() end 
function LoadingBar:getContentSize() end 
function LoadingBar:getAnchorPoint() end 
function LoadingBar:getTag() end 
function LoadingBar:setGrid() end 
function LoadingBar:convertToWorldSpace() end 
function LoadingBar:setSkewX() end 
function LoadingBar:setZOrder() end 
function LoadingBar:worldToNodeTransform() end 
function LoadingBar:getPosition() end 
function LoadingBar:getSkewX() end 
function LoadingBar:getScheduler() end 
function LoadingBar:ignoreAnchorPointForPosition() end 
function LoadingBar:setPosition() end 
function LoadingBar:getParent() end 
function LoadingBar:unscheduleUpdate() end 
function LoadingBar:scheduleUpdateWithPriorityLua() end 
function LoadingBar:removeChildByTag() end 
function LoadingBar:convertToNodeSpaceAR() end 
function LoadingBar:convertTouchToNodeSpaceAR() end 
function LoadingBar:convertToWorldSpaceAR() end 
function LoadingBar:setRotation() end 
function LoadingBar:getComponent() end 
function LoadingBar:convertToNodeSpace() end 
---
-- @return @class LoadingBar
--
function LoadingBar:create() end 
function LoadingBar:getScale() end 
function LoadingBar:getPositionY() end 
function LoadingBar:getChildByTag() end 
function LoadingBar:setContentSize() end 
function LoadingBar:description() end 
function LoadingBar:cleanup() end 
function LoadingBar:getRotation() end 
function LoadingBar:nodeToParentTransform() end 
function LoadingBar:stopAction() end 
function LoadingBar:numberOfRunningActions() end 
function LoadingBar:removeAllChildren() end 
function LoadingBar:runAction() end 
function LoadingBar:setUserObject() end 
function LoadingBar:parentToNodeTransform() end 
function LoadingBar:removeChild() end 
function LoadingBar:getAnchorPointInPoints() end 
function LoadingBar:getScaleX() end 
function LoadingBar:transform() end 
function LoadingBar:getActionManager() end 
function LoadingBar:draw() end 
function LoadingBar:setScaleY() end 
function LoadingBar:unregisterScriptHandler() end 
function LoadingBar:setVertexZ() end 
function LoadingBar:setAnchorPoint() end 
function LoadingBar:getShaderProgram() end 
function LoadingBar:stopAllActions() end 
function LoadingBar:setUserData() end 
function LoadingBar:setShaderProgram() end 
function LoadingBar:getActionByTag() end 
function LoadingBar:getGLServerState() end 
function LoadingBar:getOrderOfArrival() end 
function LoadingBar:getPositionX() end 
function LoadingBar:setGLServerState() end 
function LoadingBar:setSkewY() end 
function LoadingBar:setOrderOfArrival() end 
function LoadingBar:nodeToWorldTransform() end 
function LoadingBar:getChildren() end 
function LoadingBar:transformAncestors() end 
function LoadingBar:getGrid() end 
function LoadingBar:isRunning() end 
function LoadingBar:registerScriptHandler() end 
function LoadingBar:getCamera() end 
function LoadingBar:isIgnoreAnchorPointForPosition() end 
function LoadingBar:getUserData() end 
function LoadingBar:setPositionY() end 
function LoadingBar:getZOrder() end 
function LoadingBar:removeNode() end 
function LoadingBar:onTouchBegan() end 
function LoadingBar:addNode() end 
function LoadingBar:setLayoutParameter() end 
function LoadingBar:isFlipX() end 
function LoadingBar:getSizePercent() end 
function LoadingBar:getLeftInParent() end 
function LoadingBar:getPositionPercent() end 
function LoadingBar:onTouchEnded() end 
function LoadingBar:new_local() end 
function LoadingBar:getRightInParent() end 
function LoadingBar:checkChildInfo() end 
function LoadingBar:isEnabled() end 
function LoadingBar:setSizePercent() end 
function LoadingBar:removeFromParentAndCleanup() end 
function LoadingBar:setFlipX() end 
function LoadingBar:getChildrenCount() end 
function LoadingBar:isBright() end 
function LoadingBar:setPositionPercent() end 
function LoadingBar:addChild() end 
function LoadingBar:getBottomInParent() end 
function LoadingBar:setBright() end 
function LoadingBar:getTouchStartPos() end 
function LoadingBar:removeAllChildren() end 
function LoadingBar:setPositionType() end 
function LoadingBar:removeNodeByTag() end 
function LoadingBar:getContentSize() end 
function LoadingBar:clone() end 
function LoadingBar:setFlipY() end 
function LoadingBar:getTouchEndPos() end 
function LoadingBar:setName() end 
function LoadingBar:setPosition() end 
function LoadingBar:setFocused() end 
function LoadingBar:setSizeType() end 
function LoadingBar:hitTest() end 
function LoadingBar:addTouchEventListener() end 
function LoadingBar:getCustomSize() end 
function LoadingBar:isTouchEnabled() end 
function LoadingBar:new() end 
function LoadingBar:removeFromParent() end 
---
-- @return @class LoadingBar
--
function LoadingBar:create() end 
function LoadingBar:delete() end 
function LoadingBar:getChildByTag() end 
function LoadingBar:isFocused() end 
function LoadingBar:getTopInParent() end 
function LoadingBar:isFlipY() end 
function LoadingBar:setColor() end 
function LoadingBar:removeAllChildren() end 
function LoadingBar:updateSizeAndPosition() end 
function LoadingBar:getLayoutParameter() end 
function LoadingBar:getName() end 
function LoadingBar:removeChild() end 
function LoadingBar:onEnter() end 
function LoadingBar:getVirtualRenderer() end 
function LoadingBar:getDescription() end 
function LoadingBar:getChildByName() end 
function LoadingBar:isIgnoreContentAdaptWithSize() end 
function LoadingBar:ignoreContentAdaptWithSize() end 
function LoadingBar:onExit() end 
function LoadingBar:visit() end 
function LoadingBar:getChildren() end 
function LoadingBar:onTouchMoved() end 
function LoadingBar:getLayoutSize() end 
function LoadingBar:getColor() end 
function LoadingBar:getPositionType() end 
function LoadingBar:getTouchMovePos() end 
function LoadingBar:getSize() end 
function LoadingBar:getSizeType() end 
function LoadingBar:setSize() end 
function LoadingBar:getWidgetType() end 
function LoadingBar:getOpacity() end 
function LoadingBar:clippingParentAreaContainPoint() end 
function LoadingBar:setTouchEnabled() end 
function LoadingBar:setEnabled() end 
function LoadingBar:setActionTag() end 
function LoadingBar:getWorldPosition() end 
function LoadingBar:didNotSelectSelf() end 
function LoadingBar:sortAllChildren() end 
function LoadingBar:getNodeByTag() end 
function LoadingBar:onTouchCancelled() end 
function LoadingBar:getNodes() end 
function LoadingBar:removeAllNodes() end 
function LoadingBar:setBrightStyle() end 
function LoadingBar:removeChildByTag() end 
function LoadingBar:getActionTag() end 
function LoadingBar:setOpacity() end 
function LoadingBar:new() end 
function LoadingBar:setCapInsets() end 
function LoadingBar:delete() end 
---
-- @return @class LoadingBar
--
function LoadingBar:create() end 
function LoadingBar:getDirection() end 
function LoadingBar:getContentSize() end 
function LoadingBar:getVirtualRenderer() end 
function LoadingBar:ignoreContentAdaptWithSize() end 
function LoadingBar:setScale9Enabled() end 
function LoadingBar:getPercent() end 
function LoadingBar:new_local() end 
function LoadingBar:setPercent() end 
function LoadingBar:loadTexture() end 
function LoadingBar:setDirection() end 
function LoadingBar:getDescription() end 
