---@classdef PageView
PageView = {}
function PageView:autorelease() end 
function PageView:retain() end 
function PageView:retainCount() end 
function PageView:isEqual() end 
function PageView:copy() end 
function PageView:release() end 
function PageView:isSingleReference() end 
function PageView:visit() end 
function PageView:getUserObject() end 
function PageView:getSkewY() end 
function PageView:convertTouchToNodeSpace() end 
function PageView:getVertexZ() end 
function PageView:setParent() end 
function PageView:boundingBox() end 
function PageView:setVisible() end 
function PageView:stopActionByTag() end 
function PageView:getScaleY() end 
function PageView:setScaleX() end 
function PageView:reorderChild() end 
function PageView:setPositionX() end 
function PageView:removeFromParentAndCleanup() end 
function PageView:setTag() end 
function PageView:getChildrenCount() end 
function PageView:setScale() end 
function PageView:addChild() end 
function PageView:isVisible() end 
function PageView:setActionManager() end 
function PageView:setScheduler() end 
function PageView:getContentSize() end 
function PageView:getAnchorPoint() end 
function PageView:getTag() end 
function PageView:setGrid() end 
function PageView:convertToWorldSpace() end 
function PageView:setSkewX() end 
function PageView:setZOrder() end 
function PageView:worldToNodeTransform() end 
function PageView:getPosition() end 
function PageView:getSkewX() end 
function PageView:getScheduler() end 
function PageView:ignoreAnchorPointForPosition() end 
function PageView:setPosition() end 
function PageView:getParent() end 
function PageView:unscheduleUpdate() end 
function PageView:scheduleUpdateWithPriorityLua() end 
function PageView:removeChildByTag() end 
function PageView:convertToNodeSpaceAR() end 
function PageView:convertTouchToNodeSpaceAR() end 
function PageView:convertToWorldSpaceAR() end 
function PageView:setRotation() end 
function PageView:getComponent() end 
function PageView:convertToNodeSpace() end 
---
-- @return @class PageView
--
function PageView:create() end 
function PageView:getScale() end 
function PageView:getPositionY() end 
function PageView:getChildByTag() end 
function PageView:setContentSize() end 
function PageView:description() end 
function PageView:cleanup() end 
function PageView:getRotation() end 
function PageView:nodeToParentTransform() end 
function PageView:stopAction() end 
function PageView:numberOfRunningActions() end 
function PageView:removeAllChildren() end 
function PageView:runAction() end 
function PageView:setUserObject() end 
function PageView:parentToNodeTransform() end 
function PageView:removeChild() end 
function PageView:getAnchorPointInPoints() end 
function PageView:getScaleX() end 
function PageView:transform() end 
function PageView:getActionManager() end 
function PageView:draw() end 
function PageView:setScaleY() end 
function PageView:unregisterScriptHandler() end 
function PageView:setVertexZ() end 
function PageView:setAnchorPoint() end 
function PageView:getShaderProgram() end 
function PageView:stopAllActions() end 
function PageView:setUserData() end 
function PageView:setShaderProgram() end 
function PageView:getActionByTag() end 
function PageView:getGLServerState() end 
function PageView:getOrderOfArrival() end 
function PageView:getPositionX() end 
function PageView:setGLServerState() end 
function PageView:setSkewY() end 
function PageView:setOrderOfArrival() end 
function PageView:nodeToWorldTransform() end 
function PageView:getChildren() end 
function PageView:transformAncestors() end 
function PageView:getGrid() end 
function PageView:isRunning() end 
function PageView:registerScriptHandler() end 
function PageView:getCamera() end 
function PageView:isIgnoreAnchorPointForPosition() end 
function PageView:getUserData() end 
function PageView:setPositionY() end 
function PageView:getZOrder() end 
function PageView:removeNode() end 
function PageView:onTouchBegan() end 
function PageView:addNode() end 
function PageView:setLayoutParameter() end 
function PageView:isFlipX() end 
function PageView:getSizePercent() end 
function PageView:getLeftInParent() end 
function PageView:getPositionPercent() end 
function PageView:onTouchEnded() end 
function PageView:new_local() end 
function PageView:getRightInParent() end 
function PageView:checkChildInfo() end 
function PageView:isEnabled() end 
function PageView:setSizePercent() end 
function PageView:removeFromParentAndCleanup() end 
function PageView:setFlipX() end 
function PageView:getChildrenCount() end 
function PageView:isBright() end 
function PageView:setPositionPercent() end 
function PageView:addChild() end 
function PageView:getBottomInParent() end 
function PageView:setBright() end 
function PageView:getTouchStartPos() end 
function PageView:removeAllChildren() end 
function PageView:setPositionType() end 
function PageView:removeNodeByTag() end 
function PageView:getContentSize() end 
function PageView:clone() end 
function PageView:setFlipY() end 
function PageView:getTouchEndPos() end 
function PageView:setName() end 
function PageView:setPosition() end 
function PageView:setFocused() end 
function PageView:setSizeType() end 
function PageView:hitTest() end 
function PageView:addTouchEventListener() end 
function PageView:getCustomSize() end 
function PageView:isTouchEnabled() end 
function PageView:new() end 
function PageView:removeFromParent() end 
---
-- @return @class PageView
--
function PageView:create() end 
function PageView:delete() end 
function PageView:getChildByTag() end 
function PageView:isFocused() end 
function PageView:getTopInParent() end 
function PageView:isFlipY() end 
function PageView:setColor() end 
function PageView:removeAllChildren() end 
function PageView:updateSizeAndPosition() end 
function PageView:getLayoutParameter() end 
function PageView:getName() end 
function PageView:removeChild() end 
function PageView:onEnter() end 
function PageView:getVirtualRenderer() end 
function PageView:getDescription() end 
function PageView:getChildByName() end 
function PageView:isIgnoreContentAdaptWithSize() end 
function PageView:ignoreContentAdaptWithSize() end 
function PageView:onExit() end 
function PageView:visit() end 
function PageView:getChildren() end 
function PageView:onTouchMoved() end 
function PageView:getLayoutSize() end 
function PageView:getColor() end 
function PageView:getPositionType() end 
function PageView:getTouchMovePos() end 
function PageView:getSize() end 
function PageView:getSizeType() end 
function PageView:setSize() end 
function PageView:getWidgetType() end 
function PageView:getOpacity() end 
function PageView:clippingParentAreaContainPoint() end 
function PageView:setTouchEnabled() end 
function PageView:setEnabled() end 
function PageView:setActionTag() end 
function PageView:getWorldPosition() end 
function PageView:didNotSelectSelf() end 
function PageView:sortAllChildren() end 
function PageView:getNodeByTag() end 
function PageView:onTouchCancelled() end 
function PageView:getNodes() end 
function PageView:removeAllNodes() end 
function PageView:setBrightStyle() end 
function PageView:removeChildByTag() end 
function PageView:getActionTag() end 
function PageView:setOpacity() end 
function PageView:visit() end 
function PageView:onEnter() end 
function PageView:getBackGroundColorOpacity() end 
function PageView:new() end 
function PageView:setBackGroundImageOpacity() end 
function PageView:delete() end 
function PageView:requestDoLayout() end 
function PageView:setBackGroundImage() end 
function PageView:setBackGroundColor() end 
function PageView:removeAllChildren() end 
function PageView:new_local() end 
function PageView:removeChild() end 
function PageView:onExit() end 
function PageView:isBackGroundImageScale9Enabled() end 
function PageView:getDescription() end 
function PageView:sortAllChildren() end 
function PageView:removeAllChildren() end 
function PageView:setBackGroundColorVector() end 
function PageView:setLayoutType() end 
function PageView:getLayoutType() end 
function PageView:getBackGroundColorVector() end 
function PageView:addChild() end 
function PageView:isClippingEnabled() end 
function PageView:getClippingType() end 
function PageView:setBackGroundImageScale9Enabled() end 
function PageView:setBackGroundImageColor() end 
function PageView:removeBackGroundImage() end 
function PageView:setClippingType() end 
function PageView:setClippingEnabled() end 
function PageView:getBackGroundColorType() end 
function PageView:getBackGroundImageTextureSize() end 
function PageView:getBackGroundImageCapInsets() end 
function PageView:getBackGroundImageColor() end 
function PageView:getBackGroundStartColor() end 
function PageView:getBackGroundColor() end 
function PageView:getBackGroundImageOpacity() end 
function PageView:setBackGroundColorType() end 
function PageView:setBackGroundImageCapInsets() end 
function PageView:getBackGroundEndColor() end 
---
-- @return @class PageView
--
function PageView:create() end 
function PageView:setBackGroundColorOpacity() end 
function PageView:hitTest() end 
function PageView:addPage() end 
function PageView:onTouchBegan() end 
function PageView:new() end 
function PageView:addEventListenerPageView() end 
function PageView:delete() end 
function PageView:insertPage() end 
function PageView:onTouchEnded() end 
function PageView:onTouchMoved() end 
function PageView:addWidgetToPage() end 
function PageView:removePage() end 
function PageView:getDescription() end 
function PageView:getCurPageIndex() end 
function PageView:removeAllPages() end 
function PageView:getPage() end 
function PageView:removePageAtIndex() end 
function PageView:setLayoutType() end 
function PageView:getLayoutType() end 
function PageView:update() end 
function PageView:getPages() end 
function PageView:onTouchCancelled() end 
function PageView:scrollToPage() end 
---
-- @return @class PageView
--
function PageView:create() end 
function PageView:new_local() end 
