---@classdef RichText
RichText = {}
function RichText:autorelease() end 
function RichText:retain() end 
function RichText:retainCount() end 
function RichText:isEqual() end 
function RichText:copy() end 
function RichText:release() end 
function RichText:isSingleReference() end 
function RichText:visit() end 
function RichText:getUserObject() end 
function RichText:getSkewY() end 
function RichText:convertTouchToNodeSpace() end 
function RichText:getVertexZ() end 
function RichText:setParent() end 
function RichText:boundingBox() end 
function RichText:setVisible() end 
function RichText:stopActionByTag() end 
function RichText:getScaleY() end 
function RichText:setScaleX() end 
function RichText:reorderChild() end 
function RichText:setPositionX() end 
function RichText:removeFromParentAndCleanup() end 
function RichText:setTag() end 
function RichText:getChildrenCount() end 
function RichText:setScale() end 
function RichText:addChild() end 
function RichText:isVisible() end 
function RichText:setActionManager() end 
function RichText:setScheduler() end 
function RichText:getContentSize() end 
function RichText:getAnchorPoint() end 
function RichText:getTag() end 
function RichText:setGrid() end 
function RichText:convertToWorldSpace() end 
function RichText:setSkewX() end 
function RichText:setZOrder() end 
function RichText:worldToNodeTransform() end 
function RichText:getPosition() end 
function RichText:getSkewX() end 
function RichText:getScheduler() end 
function RichText:ignoreAnchorPointForPosition() end 
function RichText:setPosition() end 
function RichText:getParent() end 
function RichText:unscheduleUpdate() end 
function RichText:scheduleUpdateWithPriorityLua() end 
function RichText:removeChildByTag() end 
function RichText:convertToNodeSpaceAR() end 
function RichText:convertTouchToNodeSpaceAR() end 
function RichText:convertToWorldSpaceAR() end 
function RichText:setRotation() end 
function RichText:getComponent() end 
function RichText:convertToNodeSpace() end 
---
-- @return @class RichText
--
function RichText:create() end 
function RichText:getScale() end 
function RichText:getPositionY() end 
function RichText:getChildByTag() end 
function RichText:setContentSize() end 
function RichText:description() end 
function RichText:cleanup() end 
function RichText:getRotation() end 
function RichText:nodeToParentTransform() end 
function RichText:stopAction() end 
function RichText:numberOfRunningActions() end 
function RichText:removeAllChildren() end 
function RichText:runAction() end 
function RichText:setUserObject() end 
function RichText:parentToNodeTransform() end 
function RichText:removeChild() end 
function RichText:getAnchorPointInPoints() end 
function RichText:getScaleX() end 
function RichText:transform() end 
function RichText:getActionManager() end 
function RichText:draw() end 
function RichText:setScaleY() end 
function RichText:unregisterScriptHandler() end 
function RichText:setVertexZ() end 
function RichText:setAnchorPoint() end 
function RichText:getShaderProgram() end 
function RichText:stopAllActions() end 
function RichText:setUserData() end 
function RichText:setShaderProgram() end 
function RichText:getActionByTag() end 
function RichText:getGLServerState() end 
function RichText:getOrderOfArrival() end 
function RichText:getPositionX() end 
function RichText:setGLServerState() end 
function RichText:setSkewY() end 
function RichText:setOrderOfArrival() end 
function RichText:nodeToWorldTransform() end 
function RichText:getChildren() end 
function RichText:transformAncestors() end 
function RichText:getGrid() end 
function RichText:isRunning() end 
function RichText:registerScriptHandler() end 
function RichText:getCamera() end 
function RichText:isIgnoreAnchorPointForPosition() end 
function RichText:getUserData() end 
function RichText:setPositionY() end 
function RichText:getZOrder() end 
function RichText:removeNode() end 
function RichText:onTouchBegan() end 
function RichText:addNode() end 
function RichText:setLayoutParameter() end 
function RichText:isFlipX() end 
function RichText:getSizePercent() end 
function RichText:getLeftInParent() end 
function RichText:getPositionPercent() end 
function RichText:onTouchEnded() end 
function RichText:new_local() end 
function RichText:getRightInParent() end 
function RichText:checkChildInfo() end 
function RichText:isEnabled() end 
function RichText:setSizePercent() end 
function RichText:removeFromParentAndCleanup() end 
function RichText:setFlipX() end 
function RichText:getChildrenCount() end 
function RichText:isBright() end 
function RichText:setPositionPercent() end 
function RichText:addChild() end 
function RichText:getBottomInParent() end 
function RichText:setBright() end 
function RichText:getTouchStartPos() end 
function RichText:removeAllChildren() end 
function RichText:setPositionType() end 
function RichText:removeNodeByTag() end 
function RichText:getContentSize() end 
function RichText:clone() end 
function RichText:setFlipY() end 
function RichText:getTouchEndPos() end 
function RichText:setName() end 
function RichText:setPosition() end 
function RichText:setFocused() end 
function RichText:setSizeType() end 
function RichText:hitTest() end 
function RichText:addTouchEventListener() end 
function RichText:getCustomSize() end 
function RichText:isTouchEnabled() end 
function RichText:new() end 
function RichText:removeFromParent() end 
---
-- @return @class RichText
--
function RichText:create() end 
function RichText:delete() end 
function RichText:getChildByTag() end 
function RichText:isFocused() end 
function RichText:getTopInParent() end 
function RichText:isFlipY() end 
function RichText:setColor() end 
function RichText:removeAllChildren() end 
function RichText:updateSizeAndPosition() end 
function RichText:getLayoutParameter() end 
function RichText:getName() end 
function RichText:removeChild() end 
function RichText:onEnter() end 
function RichText:getVirtualRenderer() end 
function RichText:getDescription() end 
function RichText:getChildByName() end 
function RichText:isIgnoreContentAdaptWithSize() end 
function RichText:ignoreContentAdaptWithSize() end 
function RichText:onExit() end 
function RichText:visit() end 
function RichText:getChildren() end 
function RichText:onTouchMoved() end 
function RichText:getLayoutSize() end 
function RichText:getColor() end 
function RichText:getPositionType() end 
function RichText:getTouchMovePos() end 
function RichText:getSize() end 
function RichText:getSizeType() end 
function RichText:setSize() end 
function RichText:getWidgetType() end 
function RichText:getOpacity() end 
function RichText:clippingParentAreaContainPoint() end 
function RichText:setTouchEnabled() end 
function RichText:setEnabled() end 
function RichText:setActionTag() end 
function RichText:getWorldPosition() end 
function RichText:didNotSelectSelf() end 
function RichText:sortAllChildren() end 
function RichText:getNodeByTag() end 
function RichText:onTouchCancelled() end 
function RichText:getNodes() end 
function RichText:removeAllNodes() end 
function RichText:setBrightStyle() end 
function RichText:removeChildByTag() end 
function RichText:getActionTag() end 
function RichText:setOpacity() end 
function RichText:new() end 
function RichText:delete() end 
function RichText:ignoreContentAdaptWithSize() end 
function RichText:getContentSize() end 
function RichText:formatText() end 
function RichText:setAnchorPoint() end 
function RichText:setVerticalSpace() end 
function RichText:visit() end 
function RichText:new_local() end 
function RichText:pushBackElement() end 
---
-- @return @class RichText
--
function RichText:create() end 
function RichText:removeElement() end 
function RichText:insertElement() end 
