---@classdef ScrollView
ScrollView = {}
function ScrollView:autorelease() end 
function ScrollView:retain() end 
function ScrollView:retainCount() end 
function ScrollView:isEqual() end 
function ScrollView:copy() end 
function ScrollView:release() end 
function ScrollView:isSingleReference() end 
function ScrollView:visit() end 
function ScrollView:getUserObject() end 
function ScrollView:getSkewY() end 
function ScrollView:convertTouchToNodeSpace() end 
function ScrollView:getVertexZ() end 
function ScrollView:setParent() end 
function ScrollView:boundingBox() end 
function ScrollView:setVisible() end 
function ScrollView:stopActionByTag() end 
function ScrollView:getScaleY() end 
function ScrollView:setScaleX() end 
function ScrollView:reorderChild() end 
function ScrollView:setPositionX() end 
function ScrollView:removeFromParentAndCleanup() end 
function ScrollView:setTag() end 
function ScrollView:getChildrenCount() end 
function ScrollView:setScale() end 
function ScrollView:addChild() end 
function ScrollView:isVisible() end 
function ScrollView:setActionManager() end 
function ScrollView:setScheduler() end 
function ScrollView:getContentSize() end 
function ScrollView:getAnchorPoint() end 
function ScrollView:getTag() end 
function ScrollView:setGrid() end 
function ScrollView:convertToWorldSpace() end 
function ScrollView:setSkewX() end 
function ScrollView:setZOrder() end 
function ScrollView:worldToNodeTransform() end 
function ScrollView:getPosition() end 
function ScrollView:getSkewX() end 
function ScrollView:getScheduler() end 
function ScrollView:ignoreAnchorPointForPosition() end 
function ScrollView:setPosition() end 
function ScrollView:getParent() end 
function ScrollView:unscheduleUpdate() end 
function ScrollView:scheduleUpdateWithPriorityLua() end 
function ScrollView:removeChildByTag() end 
function ScrollView:convertToNodeSpaceAR() end 
function ScrollView:convertTouchToNodeSpaceAR() end 
function ScrollView:convertToWorldSpaceAR() end 
function ScrollView:setRotation() end 
function ScrollView:getComponent() end 
function ScrollView:convertToNodeSpace() end 
---
-- @return @class ScrollView
--
function ScrollView:create() end 
function ScrollView:getScale() end 
function ScrollView:getPositionY() end 
function ScrollView:getChildByTag() end 
function ScrollView:setContentSize() end 
function ScrollView:description() end 
function ScrollView:cleanup() end 
function ScrollView:getRotation() end 
function ScrollView:nodeToParentTransform() end 
function ScrollView:stopAction() end 
function ScrollView:numberOfRunningActions() end 
function ScrollView:removeAllChildren() end 
function ScrollView:runAction() end 
function ScrollView:setUserObject() end 
function ScrollView:parentToNodeTransform() end 
function ScrollView:removeChild() end 
function ScrollView:getAnchorPointInPoints() end 
function ScrollView:getScaleX() end 
function ScrollView:transform() end 
function ScrollView:getActionManager() end 
function ScrollView:draw() end 
function ScrollView:setScaleY() end 
function ScrollView:unregisterScriptHandler() end 
function ScrollView:setVertexZ() end 
function ScrollView:setAnchorPoint() end 
function ScrollView:getShaderProgram() end 
function ScrollView:stopAllActions() end 
function ScrollView:setUserData() end 
function ScrollView:setShaderProgram() end 
function ScrollView:getActionByTag() end 
function ScrollView:getGLServerState() end 
function ScrollView:getOrderOfArrival() end 
function ScrollView:getPositionX() end 
function ScrollView:setGLServerState() end 
function ScrollView:setSkewY() end 
function ScrollView:setOrderOfArrival() end 
function ScrollView:nodeToWorldTransform() end 
function ScrollView:getChildren() end 
function ScrollView:transformAncestors() end 
function ScrollView:getGrid() end 
function ScrollView:isRunning() end 
function ScrollView:registerScriptHandler() end 
function ScrollView:getCamera() end 
function ScrollView:isIgnoreAnchorPointForPosition() end 
function ScrollView:getUserData() end 
function ScrollView:setPositionY() end 
function ScrollView:getZOrder() end 
function ScrollView:removeNode() end 
function ScrollView:onTouchBegan() end 
function ScrollView:addNode() end 
function ScrollView:setLayoutParameter() end 
function ScrollView:isFlipX() end 
function ScrollView:getSizePercent() end 
function ScrollView:getLeftInParent() end 
function ScrollView:getPositionPercent() end 
function ScrollView:onTouchEnded() end 
function ScrollView:new_local() end 
function ScrollView:getRightInParent() end 
function ScrollView:checkChildInfo() end 
function ScrollView:isEnabled() end 
function ScrollView:setSizePercent() end 
function ScrollView:removeFromParentAndCleanup() end 
function ScrollView:setFlipX() end 
function ScrollView:getChildrenCount() end 
function ScrollView:isBright() end 
function ScrollView:setPositionPercent() end 
function ScrollView:addChild() end 
function ScrollView:getBottomInParent() end 
function ScrollView:setBright() end 
function ScrollView:getTouchStartPos() end 
function ScrollView:removeAllChildren() end 
function ScrollView:setPositionType() end 
function ScrollView:removeNodeByTag() end 
function ScrollView:getContentSize() end 
function ScrollView:clone() end 
function ScrollView:setFlipY() end 
function ScrollView:getTouchEndPos() end 
function ScrollView:setName() end 
function ScrollView:setPosition() end 
function ScrollView:setFocused() end 
function ScrollView:setSizeType() end 
function ScrollView:hitTest() end 
function ScrollView:addTouchEventListener() end 
function ScrollView:getCustomSize() end 
function ScrollView:isTouchEnabled() end 
function ScrollView:new() end 
function ScrollView:removeFromParent() end 
---
-- @return @class ScrollView
--
function ScrollView:create() end 
function ScrollView:delete() end 
function ScrollView:getChildByTag() end 
function ScrollView:isFocused() end 
function ScrollView:getTopInParent() end 
function ScrollView:isFlipY() end 
function ScrollView:setColor() end 
function ScrollView:removeAllChildren() end 
function ScrollView:updateSizeAndPosition() end 
function ScrollView:getLayoutParameter() end 
function ScrollView:getName() end 
function ScrollView:removeChild() end 
function ScrollView:onEnter() end 
function ScrollView:getVirtualRenderer() end 
function ScrollView:getDescription() end 
function ScrollView:getChildByName() end 
function ScrollView:isIgnoreContentAdaptWithSize() end 
function ScrollView:ignoreContentAdaptWithSize() end 
function ScrollView:onExit() end 
function ScrollView:visit() end 
function ScrollView:getChildren() end 
function ScrollView:onTouchMoved() end 
function ScrollView:getLayoutSize() end 
function ScrollView:getColor() end 
function ScrollView:getPositionType() end 
function ScrollView:getTouchMovePos() end 
function ScrollView:getSize() end 
function ScrollView:getSizeType() end 
function ScrollView:setSize() end 
function ScrollView:getWidgetType() end 
function ScrollView:getOpacity() end 
function ScrollView:clippingParentAreaContainPoint() end 
function ScrollView:setTouchEnabled() end 
function ScrollView:setEnabled() end 
function ScrollView:setActionTag() end 
function ScrollView:getWorldPosition() end 
function ScrollView:didNotSelectSelf() end 
function ScrollView:sortAllChildren() end 
function ScrollView:getNodeByTag() end 
function ScrollView:onTouchCancelled() end 
function ScrollView:getNodes() end 
function ScrollView:removeAllNodes() end 
function ScrollView:setBrightStyle() end 
function ScrollView:removeChildByTag() end 
function ScrollView:getActionTag() end 
function ScrollView:setOpacity() end 
function ScrollView:visit() end 
function ScrollView:onEnter() end 
function ScrollView:getBackGroundColorOpacity() end 
function ScrollView:new() end 
function ScrollView:setBackGroundImageOpacity() end 
function ScrollView:delete() end 
function ScrollView:requestDoLayout() end 
function ScrollView:setBackGroundImage() end 
function ScrollView:setBackGroundColor() end 
function ScrollView:removeAllChildren() end 
function ScrollView:new_local() end 
function ScrollView:removeChild() end 
function ScrollView:onExit() end 
function ScrollView:isBackGroundImageScale9Enabled() end 
function ScrollView:getDescription() end 
function ScrollView:sortAllChildren() end 
function ScrollView:removeAllChildren() end 
function ScrollView:setBackGroundColorVector() end 
function ScrollView:setLayoutType() end 
function ScrollView:getLayoutType() end 
function ScrollView:getBackGroundColorVector() end 
function ScrollView:addChild() end 
function ScrollView:isClippingEnabled() end 
function ScrollView:getClippingType() end 
function ScrollView:setBackGroundImageScale9Enabled() end 
function ScrollView:setBackGroundImageColor() end 
function ScrollView:removeBackGroundImage() end 
function ScrollView:setClippingType() end 
function ScrollView:setClippingEnabled() end 
function ScrollView:getBackGroundColorType() end 
function ScrollView:getBackGroundImageTextureSize() end 
function ScrollView:getBackGroundImageCapInsets() end 
function ScrollView:getBackGroundImageColor() end 
function ScrollView:getBackGroundStartColor() end 
function ScrollView:getBackGroundColor() end 
function ScrollView:getBackGroundImageOpacity() end 
function ScrollView:setBackGroundColorType() end 
function ScrollView:setBackGroundImageCapInsets() end 
function ScrollView:getBackGroundEndColor() end 
---
-- @return @class ScrollView
--
function ScrollView:create() end 
function ScrollView:setBackGroundColorOpacity() end 
function ScrollView:hitTest() end 
function ScrollView:removeNode() end 
function ScrollView:scrollToRight() end 
function ScrollView:jumpToLeft() end 
function ScrollView:scrollToTopLeft() end 
function ScrollView:setInnerContainerSize() end 
function ScrollView:setDirection() end 
function ScrollView:isInertiaScrollEnabled() end 
function ScrollView:new_local() end 
function ScrollView:scrollToBottomRight() end 
function ScrollView:scrollToBottom() end 
function ScrollView:getDescription() end 
function ScrollView:getChildrenCount() end 
function ScrollView:addChild() end 
function ScrollView:setInertiaScrollEnabled() end 
function ScrollView:jumpToRight() end 
function ScrollView:removeAllChildren() end 
function ScrollView:getNodes() end 
function ScrollView:removeNodeByTag() end 
function ScrollView:jumpToTopRight() end 
function ScrollView:jumpToPercentHorizontal() end 
function ScrollView:scrollToPercentHorizontal() end 
function ScrollView:setBounceEnabled() end 
function ScrollView:getInnerContainerSize() end 
function ScrollView:new() end 
function ScrollView:jumpToTopLeft() end 
---
-- @return @class ScrollView
--
function ScrollView:create() end 
function ScrollView:delete() end 
function ScrollView:getChildByTag() end 
function ScrollView:scrollToPercentBothDirection() end 
function ScrollView:scrollToTop() end 
function ScrollView:isBounceEnabled() end 
function ScrollView:jumpToBottomLeft() end 
function ScrollView:removeAllChildren() end 
function ScrollView:removeChild() end 
function ScrollView:getChildren() end 
function ScrollView:jumpToPercentVertical() end 
function ScrollView:scrollToBottomLeft() end 
function ScrollView:getLayoutType() end 
function ScrollView:setLayoutType() end 
function ScrollView:update() end 
function ScrollView:jumpToTop() end 
function ScrollView:getNodeByTag() end 
function ScrollView:jumpToPercentBothDirection() end 
function ScrollView:getInnerContainer() end 
function ScrollView:scrollToPercentVertical() end 
function ScrollView:jumpToBottom() end 
function ScrollView:getDirection() end 
function ScrollView:getChildByName() end 
function ScrollView:addNode() end 
function ScrollView:removeAllNodes() end 
function ScrollView:jumpToBottomRight() end 
function ScrollView:scrollToTopRight() end 
function ScrollView:scrollToLeft() end 
