---@classdef Slider
Slider = {}
function Slider:autorelease() end 
function Slider:retain() end 
function Slider:retainCount() end 
function Slider:isEqual() end 
function Slider:copy() end 
function Slider:release() end 
function Slider:isSingleReference() end 
function Slider:visit() end 
function Slider:getUserObject() end 
function Slider:getSkewY() end 
function Slider:convertTouchToNodeSpace() end 
function Slider:getVertexZ() end 
function Slider:setParent() end 
function Slider:boundingBox() end 
function Slider:setVisible() end 
function Slider:stopActionByTag() end 
function Slider:getScaleY() end 
function Slider:setScaleX() end 
function Slider:reorderChild() end 
function Slider:setPositionX() end 
function Slider:removeFromParentAndCleanup() end 
function Slider:setTag() end 
function Slider:getChildrenCount() end 
function Slider:setScale() end 
function Slider:addChild() end 
function Slider:isVisible() end 
function Slider:setActionManager() end 
function Slider:setScheduler() end 
function Slider:getContentSize() end 
function Slider:getAnchorPoint() end 
function Slider:getTag() end 
function Slider:setGrid() end 
function Slider:convertToWorldSpace() end 
function Slider:setSkewX() end 
function Slider:setZOrder() end 
function Slider:worldToNodeTransform() end 
function Slider:getPosition() end 
function Slider:getSkewX() end 
function Slider:getScheduler() end 
function Slider:ignoreAnchorPointForPosition() end 
function Slider:setPosition() end 
function Slider:getParent() end 
function Slider:unscheduleUpdate() end 
function Slider:scheduleUpdateWithPriorityLua() end 
function Slider:removeChildByTag() end 
function Slider:convertToNodeSpaceAR() end 
function Slider:convertTouchToNodeSpaceAR() end 
function Slider:convertToWorldSpaceAR() end 
function Slider:setRotation() end 
function Slider:getComponent() end 
function Slider:convertToNodeSpace() end 
---
-- @return @class Slider
--
function Slider:create() end 
function Slider:getScale() end 
function Slider:getPositionY() end 
function Slider:getChildByTag() end 
function Slider:setContentSize() end 
function Slider:description() end 
function Slider:cleanup() end 
function Slider:getRotation() end 
function Slider:nodeToParentTransform() end 
function Slider:stopAction() end 
function Slider:numberOfRunningActions() end 
function Slider:removeAllChildren() end 
function Slider:runAction() end 
function Slider:setUserObject() end 
function Slider:parentToNodeTransform() end 
function Slider:removeChild() end 
function Slider:getAnchorPointInPoints() end 
function Slider:getScaleX() end 
function Slider:transform() end 
function Slider:getActionManager() end 
function Slider:draw() end 
function Slider:setScaleY() end 
function Slider:unregisterScriptHandler() end 
function Slider:setVertexZ() end 
function Slider:setAnchorPoint() end 
function Slider:getShaderProgram() end 
function Slider:stopAllActions() end 
function Slider:setUserData() end 
function Slider:setShaderProgram() end 
function Slider:getActionByTag() end 
function Slider:getGLServerState() end 
function Slider:getOrderOfArrival() end 
function Slider:getPositionX() end 
function Slider:setGLServerState() end 
function Slider:setSkewY() end 
function Slider:setOrderOfArrival() end 
function Slider:nodeToWorldTransform() end 
function Slider:getChildren() end 
function Slider:transformAncestors() end 
function Slider:getGrid() end 
function Slider:isRunning() end 
function Slider:registerScriptHandler() end 
function Slider:getCamera() end 
function Slider:isIgnoreAnchorPointForPosition() end 
function Slider:getUserData() end 
function Slider:setPositionY() end 
function Slider:getZOrder() end 
function Slider:removeNode() end 
function Slider:onTouchBegan() end 
function Slider:addNode() end 
function Slider:setLayoutParameter() end 
function Slider:isFlipX() end 
function Slider:getSizePercent() end 
function Slider:getLeftInParent() end 
function Slider:getPositionPercent() end 
function Slider:onTouchEnded() end 
function Slider:new_local() end 
function Slider:getRightInParent() end 
function Slider:checkChildInfo() end 
function Slider:isEnabled() end 
function Slider:setSizePercent() end 
function Slider:removeFromParentAndCleanup() end 
function Slider:setFlipX() end 
function Slider:getChildrenCount() end 
function Slider:isBright() end 
function Slider:setPositionPercent() end 
function Slider:addChild() end 
function Slider:getBottomInParent() end 
function Slider:setBright() end 
function Slider:getTouchStartPos() end 
function Slider:removeAllChildren() end 
function Slider:setPositionType() end 
function Slider:removeNodeByTag() end 
function Slider:getContentSize() end 
function Slider:clone() end 
function Slider:setFlipY() end 
function Slider:getTouchEndPos() end 
function Slider:setName() end 
function Slider:setPosition() end 
function Slider:setFocused() end 
function Slider:setSizeType() end 
function Slider:hitTest() end 
function Slider:addTouchEventListener() end 
function Slider:getCustomSize() end 
function Slider:isTouchEnabled() end 
function Slider:new() end 
function Slider:removeFromParent() end 
---
-- @return @class Slider
--
function Slider:create() end 
function Slider:delete() end 
function Slider:getChildByTag() end 
function Slider:isFocused() end 
function Slider:getTopInParent() end 
function Slider:isFlipY() end 
function Slider:setColor() end 
function Slider:removeAllChildren() end 
function Slider:updateSizeAndPosition() end 
function Slider:getLayoutParameter() end 
function Slider:getName() end 
function Slider:removeChild() end 
function Slider:onEnter() end 
function Slider:getVirtualRenderer() end 
function Slider:getDescription() end 
function Slider:getChildByName() end 
function Slider:isIgnoreContentAdaptWithSize() end 
function Slider:ignoreContentAdaptWithSize() end 
function Slider:onExit() end 
function Slider:visit() end 
function Slider:getChildren() end 
function Slider:onTouchMoved() end 
function Slider:getLayoutSize() end 
function Slider:getColor() end 
function Slider:getPositionType() end 
function Slider:getTouchMovePos() end 
function Slider:getSize() end 
function Slider:getSizeType() end 
function Slider:setSize() end 
function Slider:getWidgetType() end 
function Slider:getOpacity() end 
function Slider:clippingParentAreaContainPoint() end 
function Slider:setTouchEnabled() end 
function Slider:setEnabled() end 
function Slider:setActionTag() end 
function Slider:getWorldPosition() end 
function Slider:didNotSelectSelf() end 
function Slider:sortAllChildren() end 
function Slider:getNodeByTag() end 
function Slider:onTouchCancelled() end 
function Slider:getNodes() end 
function Slider:removeAllNodes() end 
function Slider:setBrightStyle() end 
function Slider:removeChildByTag() end 
function Slider:getActionTag() end 
function Slider:setOpacity() end 
function Slider:loadBarTexture() end 
function Slider:onTouchBegan() end 
function Slider:new() end 
function Slider:setCapInsets() end 
function Slider:delete() end 
function Slider:setScale9Enabled() end 
function Slider:onTouchEnded() end 
function Slider:setCapInsetProgressBarRebderer() end 
function Slider:loadSlidBallTextureDisabled() end 
function Slider:getCapInsetProgressBarRebderer() end 
function Slider:loadProgressBarTexture() end 
function Slider:getCapInsetBarRenderer() end 
function Slider:getVirtualRenderer() end 
function Slider:loadSlidBallTextureNormal() end 
function Slider:getDescription() end 
function Slider:loadSlidBallTexturePressed() end 
function Slider:addEventListenerSlider() end 
function Slider:setCapInsetsBarRenderer() end 
function Slider:ignoreContentAdaptWithSize() end 
function Slider:getContentSize() end 
---
-- @return @class Slider
--
function Slider:create() end 
function Slider:getPercent() end 
function Slider:onTouchMoved() end 
function Slider:loadSlidBallTextures() end 
function Slider:setPercent() end 
function Slider:onTouchCancelled() end 
function Slider:isScale9Enabled() end 
function Slider:new_local() end 
