---@classdef TextField
TextField = {}
function TextField:autorelease() end 
function TextField:retain() end 
function TextField:retainCount() end 
function TextField:isEqual() end 
function TextField:copy() end 
function TextField:release() end 
function TextField:isSingleReference() end 
function TextField:visit() end 
function TextField:getUserObject() end 
function TextField:getSkewY() end 
function TextField:convertTouchToNodeSpace() end 
function TextField:getVertexZ() end 
function TextField:setParent() end 
function TextField:boundingBox() end 
function TextField:setVisible() end 
function TextField:stopActionByTag() end 
function TextField:getScaleY() end 
function TextField:setScaleX() end 
function TextField:reorderChild() end 
function TextField:setPositionX() end 
function TextField:removeFromParentAndCleanup() end 
function TextField:setTag() end 
function TextField:getChildrenCount() end 
function TextField:setScale() end 
function TextField:addChild() end 
function TextField:isVisible() end 
function TextField:setActionManager() end 
function TextField:setScheduler() end 
function TextField:getContentSize() end 
function TextField:getAnchorPoint() end 
function TextField:getTag() end 
function TextField:setGrid() end 
function TextField:convertToWorldSpace() end 
function TextField:setSkewX() end 
function TextField:setZOrder() end 
function TextField:worldToNodeTransform() end 
function TextField:getPosition() end 
function TextField:getSkewX() end 
function TextField:getScheduler() end 
function TextField:ignoreAnchorPointForPosition() end 
function TextField:setPosition() end 
function TextField:getParent() end 
function TextField:unscheduleUpdate() end 
function TextField:scheduleUpdateWithPriorityLua() end 
function TextField:removeChildByTag() end 
function TextField:convertToNodeSpaceAR() end 
function TextField:convertTouchToNodeSpaceAR() end 
function TextField:convertToWorldSpaceAR() end 
function TextField:setRotation() end 
function TextField:getComponent() end 
function TextField:convertToNodeSpace() end 
---
-- @return @class TextField
--
function TextField:create() end 
function TextField:getScale() end 
function TextField:getPositionY() end 
function TextField:getChildByTag() end 
function TextField:setContentSize() end 
function TextField:description() end 
function TextField:cleanup() end 
function TextField:getRotation() end 
function TextField:nodeToParentTransform() end 
function TextField:stopAction() end 
function TextField:numberOfRunningActions() end 
function TextField:removeAllChildren() end 
function TextField:runAction() end 
function TextField:setUserObject() end 
function TextField:parentToNodeTransform() end 
function TextField:removeChild() end 
function TextField:getAnchorPointInPoints() end 
function TextField:getScaleX() end 
function TextField:transform() end 
function TextField:getActionManager() end 
function TextField:draw() end 
function TextField:setScaleY() end 
function TextField:unregisterScriptHandler() end 
function TextField:setVertexZ() end 
function TextField:setAnchorPoint() end 
function TextField:getShaderProgram() end 
function TextField:stopAllActions() end 
function TextField:setUserData() end 
function TextField:setShaderProgram() end 
function TextField:getActionByTag() end 
function TextField:getGLServerState() end 
function TextField:getOrderOfArrival() end 
function TextField:getPositionX() end 
function TextField:setGLServerState() end 
function TextField:setSkewY() end 
function TextField:setOrderOfArrival() end 
function TextField:nodeToWorldTransform() end 
function TextField:getChildren() end 
function TextField:transformAncestors() end 
function TextField:getGrid() end 
function TextField:isRunning() end 
function TextField:registerScriptHandler() end 
function TextField:getCamera() end 
function TextField:isIgnoreAnchorPointForPosition() end 
function TextField:getUserData() end 
function TextField:setPositionY() end 
function TextField:getZOrder() end 
function TextField:removeNode() end 
function TextField:onTouchBegan() end 
function TextField:addNode() end 
function TextField:setLayoutParameter() end 
function TextField:isFlipX() end 
function TextField:getSizePercent() end 
function TextField:getLeftInParent() end 
function TextField:getPositionPercent() end 
function TextField:onTouchEnded() end 
function TextField:new_local() end 
function TextField:getRightInParent() end 
function TextField:checkChildInfo() end 
function TextField:isEnabled() end 
function TextField:setSizePercent() end 
function TextField:removeFromParentAndCleanup() end 
function TextField:setFlipX() end 
function TextField:getChildrenCount() end 
function TextField:isBright() end 
function TextField:setPositionPercent() end 
function TextField:addChild() end 
function TextField:getBottomInParent() end 
function TextField:setBright() end 
function TextField:getTouchStartPos() end 
function TextField:removeAllChildren() end 
function TextField:setPositionType() end 
function TextField:removeNodeByTag() end 
function TextField:getContentSize() end 
function TextField:clone() end 
function TextField:setFlipY() end 
function TextField:getTouchEndPos() end 
function TextField:setName() end 
function TextField:setPosition() end 
function TextField:setFocused() end 
function TextField:setSizeType() end 
function TextField:hitTest() end 
function TextField:addTouchEventListener() end 
function TextField:getCustomSize() end 
function TextField:isTouchEnabled() end 
function TextField:new() end 
function TextField:removeFromParent() end 
---
-- @return @class TextField
--
function TextField:create() end 
function TextField:delete() end 
function TextField:getChildByTag() end 
function TextField:isFocused() end 
function TextField:getTopInParent() end 
function TextField:isFlipY() end 
function TextField:setColor() end 
function TextField:removeAllChildren() end 
function TextField:updateSizeAndPosition() end 
function TextField:getLayoutParameter() end 
function TextField:getName() end 
function TextField:removeChild() end 
function TextField:onEnter() end 
function TextField:getVirtualRenderer() end 
function TextField:getDescription() end 
function TextField:getChildByName() end 
function TextField:isIgnoreContentAdaptWithSize() end 
function TextField:ignoreContentAdaptWithSize() end 
function TextField:onExit() end 
function TextField:visit() end 
function TextField:getChildren() end 
function TextField:onTouchMoved() end 
function TextField:getLayoutSize() end 
function TextField:getColor() end 
function TextField:getPositionType() end 
function TextField:getTouchMovePos() end 
function TextField:getSize() end 
function TextField:getSizeType() end 
function TextField:setSize() end 
function TextField:getWidgetType() end 
function TextField:getOpacity() end 
function TextField:clippingParentAreaContainPoint() end 
function TextField:setTouchEnabled() end 
function TextField:setEnabled() end 
function TextField:setActionTag() end 
function TextField:getWorldPosition() end 
function TextField:didNotSelectSelf() end 
function TextField:sortAllChildren() end 
function TextField:getNodeByTag() end 
function TextField:onTouchCancelled() end 
function TextField:getNodes() end 
function TextField:removeAllNodes() end 
function TextField:setBrightStyle() end 
function TextField:removeChildByTag() end 
function TextField:getActionTag() end 
function TextField:setOpacity() end 
function TextField:onTouchBegan() end 
function TextField:new() end 
function TextField:attachWithIME() end 
function TextField:delete() end 
function TextField:getFontName() end 
function TextField:addEventListenerTextField() end 
function TextField:update() end 
function TextField:setTouchAreaEnabled() end 
function TextField:setPlaceHolder() end 
function TextField:getStringValue() end 
function TextField:setDeleteBackward() end 
function TextField:setTouchSize() end 
function TextField:new_local() end 
function TextField:setTextHorizontalAlignment() end 
function TextField:setTextAreaSize() end 
function TextField:onEnter() end 
function TextField:getVirtualRenderer() end 
function TextField:getFontSize() end 
function TextField:getDescription() end 
function TextField:getMaxLength() end 
function TextField:setDetachWithIME() end 
function TextField:isPasswordEnabled() end 
function TextField:setAnchorPoint() end 
function TextField:getDeleteBackward() end 
function TextField:setPasswordEnabled() end 
function TextField:setFontName() end 
function TextField:setInsertText() end 
function TextField:getInsertText() end 
function TextField:getDetachWithIME() end 
function TextField:setAttachWithIME() end 
function TextField:setText() end 
function TextField:getAttachWithIME() end 
function TextField:getContentSize() end 
function TextField:setMaxLengthEnabled() end 
function TextField:getPasswordStyleText() end 
function TextField:setMaxLength() end 
function TextField:isMaxLengthEnabled() end 
function TextField:didNotSelectSelf() end 
function TextField:setFontSize() end 
function TextField:getPlaceHolder() end 
---
-- @return @class TextField
--
function TextField:create() end 
function TextField:getTouchSize() end 
function TextField:setTextVerticalAlignment() end 
function TextField:setPasswordStyleText() end 
function TextField:hitTest() end 
