---@classdef TouchGroup
TouchGroup = {}
function TouchGroup:autorelease() end 
function TouchGroup:retain() end 
function TouchGroup:retainCount() end 
function TouchGroup:isEqual() end 
function TouchGroup:copy() end 
function TouchGroup:release() end 
function TouchGroup:isSingleReference() end 
function TouchGroup:visit() end 
function TouchGroup:getUserObject() end 
function TouchGroup:getSkewY() end 
function TouchGroup:convertTouchToNodeSpace() end 
function TouchGroup:getVertexZ() end 
function TouchGroup:setParent() end 
function TouchGroup:boundingBox() end 
function TouchGroup:setVisible() end 
function TouchGroup:stopActionByTag() end 
function TouchGroup:getScaleY() end 
function TouchGroup:setScaleX() end 
function TouchGroup:reorderChild() end 
function TouchGroup:setPositionX() end 
function TouchGroup:removeFromParentAndCleanup() end 
function TouchGroup:setTag() end 
function TouchGroup:getChildrenCount() end 
function TouchGroup:setScale() end 
function TouchGroup:addChild() end 
function TouchGroup:isVisible() end 
function TouchGroup:setActionManager() end 
function TouchGroup:setScheduler() end 
function TouchGroup:getContentSize() end 
function TouchGroup:getAnchorPoint() end 
function TouchGroup:getTag() end 
function TouchGroup:setGrid() end 
function TouchGroup:convertToWorldSpace() end 
function TouchGroup:setSkewX() end 
function TouchGroup:setZOrder() end 
function TouchGroup:worldToNodeTransform() end 
function TouchGroup:getPosition() end 
function TouchGroup:getSkewX() end 
function TouchGroup:getScheduler() end 
function TouchGroup:ignoreAnchorPointForPosition() end 
function TouchGroup:setPosition() end 
function TouchGroup:getParent() end 
function TouchGroup:unscheduleUpdate() end 
function TouchGroup:scheduleUpdateWithPriorityLua() end 
function TouchGroup:removeChildByTag() end 
function TouchGroup:convertToNodeSpaceAR() end 
function TouchGroup:convertTouchToNodeSpaceAR() end 
function TouchGroup:convertToWorldSpaceAR() end 
function TouchGroup:setRotation() end 
function TouchGroup:getComponent() end 
function TouchGroup:convertToNodeSpace() end 
---
-- @return @class TouchGroup
--
function TouchGroup:create() end 
function TouchGroup:getScale() end 
function TouchGroup:getPositionY() end 
function TouchGroup:getChildByTag() end 
function TouchGroup:setContentSize() end 
function TouchGroup:description() end 
function TouchGroup:cleanup() end 
function TouchGroup:getRotation() end 
function TouchGroup:nodeToParentTransform() end 
function TouchGroup:stopAction() end 
function TouchGroup:numberOfRunningActions() end 
function TouchGroup:removeAllChildren() end 
function TouchGroup:runAction() end 
function TouchGroup:setUserObject() end 
function TouchGroup:parentToNodeTransform() end 
function TouchGroup:removeChild() end 
function TouchGroup:getAnchorPointInPoints() end 
function TouchGroup:getScaleX() end 
function TouchGroup:transform() end 
function TouchGroup:getActionManager() end 
function TouchGroup:draw() end 
function TouchGroup:setScaleY() end 
function TouchGroup:unregisterScriptHandler() end 
function TouchGroup:setVertexZ() end 
function TouchGroup:setAnchorPoint() end 
function TouchGroup:getShaderProgram() end 
function TouchGroup:stopAllActions() end 
function TouchGroup:setUserData() end 
function TouchGroup:setShaderProgram() end 
function TouchGroup:getActionByTag() end 
function TouchGroup:getGLServerState() end 
function TouchGroup:getOrderOfArrival() end 
function TouchGroup:getPositionX() end 
function TouchGroup:setGLServerState() end 
function TouchGroup:setSkewY() end 
function TouchGroup:setOrderOfArrival() end 
function TouchGroup:nodeToWorldTransform() end 
function TouchGroup:getChildren() end 
function TouchGroup:transformAncestors() end 
function TouchGroup:getGrid() end 
function TouchGroup:isRunning() end 
function TouchGroup:registerScriptHandler() end 
function TouchGroup:getCamera() end 
function TouchGroup:isIgnoreAnchorPointForPosition() end 
function TouchGroup:getUserData() end 
function TouchGroup:setPositionY() end 
function TouchGroup:getZOrder() end 
function TouchGroup:isTouchEnabled() end 
function TouchGroup:unregisterScriptKeypadHandler() end 
function TouchGroup:registerScriptAccelerateHandler() end 
---
-- @return @class TouchGroup
--
function TouchGroup:create() end 
function TouchGroup:setAccelerometerEnabled() end 
function TouchGroup:registerScriptKeypadHandler() end 
function TouchGroup:setTouchMode() end 
function TouchGroup:isAccelerometerEnabled() end 
function TouchGroup:setTouchEnabled() end 
function TouchGroup:setTouchPriority() end 
function TouchGroup:unregisterScriptAccelerateHandler() end 
function TouchGroup:unregisterScriptTouchHandler() end 
function TouchGroup:setKeypadEnabled() end 
function TouchGroup:registerScriptTouchHandler() end 
function TouchGroup:getTouchPriority() end 
function TouchGroup:isKeypadEnabled() end 
function TouchGroup:getTouchMode() end 
function TouchGroup:onEnter() end 
function TouchGroup:ccTouchMoved() end 
function TouchGroup:new() end 
---
-- @return @class TouchGroup
--
function TouchGroup:create() end 
function TouchGroup:delete() end 
function TouchGroup:getWidgetByName() end 
function TouchGroup:getWidgetByTag() end 
function TouchGroup:ccTouchEnded() end 
function TouchGroup:removeWidget() end 
function TouchGroup:addWidget() end 
function TouchGroup:ccTouchCancelled() end 
function TouchGroup:ccTouchBegan() end 
function TouchGroup:new_local() end 
function TouchGroup:getRootWidget() end 
function TouchGroup:init() end 
function TouchGroup:onEnterTransitionDidFinish() end 
function TouchGroup:clear() end 
function TouchGroup:onExit() end 
