---@classdef Widget
Widget = {}
function Widget:autorelease() end 
function Widget:retain() end 
function Widget:retainCount() end 
function Widget:isEqual() end 
function Widget:copy() end 
function Widget:release() end 
function Widget:isSingleReference() end 
function Widget:visit() end 
function Widget:getUserObject() end 
function Widget:getSkewY() end 
function Widget:convertTouchToNodeSpace() end 
function Widget:getVertexZ() end 
function Widget:setParent() end 
function Widget:boundingBox() end 
function Widget:setVisible() end 
function Widget:stopActionByTag() end 
function Widget:getScaleY() end 
function Widget:setScaleX() end 
function Widget:reorderChild() end 
function Widget:setPositionX() end 
function Widget:removeFromParentAndCleanup() end 
function Widget:setTag() end 
function Widget:getChildrenCount() end 
function Widget:setScale() end 
function Widget:addChild() end 
function Widget:isVisible() end 
function Widget:setActionManager() end 
function Widget:setScheduler() end 
function Widget:getContentSize() end 
function Widget:getAnchorPoint() end 
function Widget:getTag() end 
function Widget:setGrid() end 
function Widget:convertToWorldSpace() end 
function Widget:setSkewX() end 
function Widget:setZOrder() end 
function Widget:worldToNodeTransform() end 
function Widget:getPosition() end 
function Widget:getSkewX() end 
function Widget:getScheduler() end 
function Widget:ignoreAnchorPointForPosition() end 
function Widget:setPosition() end 
function Widget:getParent() end 
function Widget:unscheduleUpdate() end 
function Widget:scheduleUpdateWithPriorityLua() end 
function Widget:removeChildByTag() end 
function Widget:convertToNodeSpaceAR() end 
function Widget:convertTouchToNodeSpaceAR() end 
function Widget:convertToWorldSpaceAR() end 
function Widget:setRotation() end 
function Widget:getComponent() end 
function Widget:convertToNodeSpace() end 
---
-- @return @class Widget
--
function Widget:create() end 
function Widget:getScale() end 
function Widget:getPositionY() end 
function Widget:getChildByTag() end 
function Widget:setContentSize() end 
function Widget:description() end 
function Widget:cleanup() end 
function Widget:getRotation() end 
function Widget:nodeToParentTransform() end 
function Widget:stopAction() end 
function Widget:numberOfRunningActions() end 
function Widget:removeAllChildren() end 
function Widget:runAction() end 
function Widget:setUserObject() end 
function Widget:parentToNodeTransform() end 
function Widget:removeChild() end 
function Widget:getAnchorPointInPoints() end 
function Widget:getScaleX() end 
function Widget:transform() end 
function Widget:getActionManager() end 
function Widget:draw() end 
function Widget:setScaleY() end 
function Widget:unregisterScriptHandler() end 
function Widget:setVertexZ() end 
function Widget:setAnchorPoint() end 
function Widget:getShaderProgram() end 
function Widget:stopAllActions() end 
function Widget:setUserData() end 
function Widget:setShaderProgram() end 
function Widget:getActionByTag() end 
function Widget:getGLServerState() end 
function Widget:getOrderOfArrival() end 
function Widget:getPositionX() end 
function Widget:setGLServerState() end 
function Widget:setSkewY() end 
function Widget:setOrderOfArrival() end 
function Widget:nodeToWorldTransform() end 
function Widget:getChildren() end 
function Widget:transformAncestors() end 
function Widget:getGrid() end 
function Widget:isRunning() end 
function Widget:registerScriptHandler() end 
function Widget:getCamera() end 
function Widget:isIgnoreAnchorPointForPosition() end 
function Widget:getUserData() end 
function Widget:setPositionY() end 
function Widget:getZOrder() end 
function Widget:removeNode() end 
function Widget:onTouchBegan() end 
function Widget:addNode() end 
function Widget:setLayoutParameter() end 
function Widget:isFlipX() end 
function Widget:getSizePercent() end 
function Widget:getLeftInParent() end 
function Widget:getPositionPercent() end 
function Widget:onTouchEnded() end 
function Widget:new_local() end 
function Widget:getRightInParent() end 
function Widget:checkChildInfo() end 
function Widget:isEnabled() end 
function Widget:setSizePercent() end 
function Widget:removeFromParentAndCleanup() end 
function Widget:setFlipX() end 
function Widget:getChildrenCount() end 
function Widget:isBright() end 
function Widget:setPositionPercent() end 
function Widget:addChild() end 
function Widget:getBottomInParent() end 
function Widget:setBright() end 
function Widget:getTouchStartPos() end 
function Widget:removeAllChildren() end 
function Widget:setPositionType() end 
function Widget:removeNodeByTag() end 
function Widget:getContentSize() end 
function Widget:clone() end 
function Widget:setFlipY() end 
function Widget:getTouchEndPos() end 
function Widget:setName() end 
function Widget:setPosition() end 
function Widget:setFocused() end 
function Widget:setSizeType() end 
function Widget:hitTest() end 
function Widget:addTouchEventListener() end 
function Widget:getCustomSize() end 
function Widget:isTouchEnabled() end 
function Widget:new() end 
function Widget:removeFromParent() end 
---
-- @return @class Widget
--
function Widget:create() end 
function Widget:delete() end 
function Widget:getChildByTag() end 
function Widget:isFocused() end 
function Widget:getTopInParent() end 
function Widget:isFlipY() end 
function Widget:setColor() end 
function Widget:removeAllChildren() end 
function Widget:updateSizeAndPosition() end 
function Widget:getLayoutParameter() end 
function Widget:getName() end 
function Widget:removeChild() end 
function Widget:onEnter() end 
function Widget:getVirtualRenderer() end 
function Widget:getDescription() end 
function Widget:getChildByName() end 
function Widget:isIgnoreContentAdaptWithSize() end 
function Widget:ignoreContentAdaptWithSize() end 
function Widget:onExit() end 
function Widget:visit() end 
function Widget:getChildren() end 
function Widget:onTouchMoved() end 
function Widget:getLayoutSize() end 
function Widget:getColor() end 
function Widget:getPositionType() end 
function Widget:getTouchMovePos() end 
function Widget:getSize() end 
function Widget:getSizeType() end 
function Widget:setSize() end 
function Widget:getWidgetType() end 
function Widget:getOpacity() end 
function Widget:clippingParentAreaContainPoint() end 
function Widget:setTouchEnabled() end 
function Widget:setEnabled() end 
function Widget:setActionTag() end 
function Widget:getWorldPosition() end 
function Widget:didNotSelectSelf() end 
function Widget:sortAllChildren() end 
function Widget:getNodeByTag() end 
function Widget:onTouchCancelled() end 
function Widget:getNodes() end 
function Widget:removeAllNodes() end 
function Widget:setBrightStyle() end 
function Widget:removeChildByTag() end 
function Widget:getActionTag() end 
function Widget:setOpacity() end 
